import { AppMode, CommandType, CircuitComponent, CommandBlock } from '../../types';
import { LucideIcon, Zap, Swords, Crosshair, Eye, Shield } from 'lucide-react';

export const actionTemplates: {
    id: string,
    mode: AppMode,
    name: string,
    description: string,
    icon: LucideIcon,
    color: string,
    commands: CommandBlock[],
    circuitComponents?: CircuitComponent[]
}[] = [
        {
            id: 'tpl_action_hackslash',
            mode: AppMode.GAME,
            name: 'Hack & Slash',
            description: 'Slashing combo action with wave-based enemies!',
            icon: Zap,
            color: 'bg-gradient-to-r from-red-500 to-orange-500',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '⚔️' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'combo', value: 0 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'wave', value: 1 } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '👾' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '💀' } },
                { id: 'e3', type: CommandType.SPAWN_ENEMY, params: { text: '👺' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -6 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 6 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -6 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 6 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'at1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'at2', type: CommandType.SHOOT, params: { text: '⚔️' } },
                { id: 'at3', type: CommandType.CHANGE_VAR, params: { varName: 'combo', value: 1 } },
                { id: 'at4', type: CommandType.PLAY_SOUND, params: { text: 'laser' } },
                { id: 'at5', type: CommandType.END_IF, params: {} },
                { id: 'kb1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '👾' } },
                { id: 'kb2', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
                { id: 'kb3', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'kb4', type: CommandType.SPAWN_PARTICLES, params: { value: 5 } },
                { id: 'kb5', type: CommandType.END_IF, params: {} },
                { id: 'wc1', type: CommandType.IF, params: { condition: 'GREATER' } },
                { id: 'wc2', type: CommandType.WIN_GAME, params: {} },
                { id: 'wc3', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
                { id: 'wc4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_action_beatemup',
            mode: AppMode.GAME,
            name: 'Beat Em Up',
            description: 'Side-scrolling brawler with combos!',
            icon: Zap,
            color: 'bg-gradient-to-r from-pink-500 to-rose-500',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🥊' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'combo', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'special', value: 100 } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '👺' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '💀' } },
                { id: 'e3', type: CommandType.SPAWN_ENEMY, params: { text: '👹' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -5 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 5 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'at1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'at2', type: CommandType.SHOOT, params: { text: '👊' } },
                { id: 'at3', type: CommandType.CHANGE_VAR, params: { varName: 'combo', value: 1 } },
                { id: 'at4', type: CommandType.PLAY_SOUND, params: { text: 'attack' } },
                { id: 'at5', type: CommandType.END_IF, params: {} },
                { id: 'sp1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 88 } },
                { id: 'sp2', type: CommandType.SHOOT, params: { text: '💥' } },
                { id: 'sp3', type: CommandType.CHANGE_VAR, params: { varName: 'special', value: -50 } },
                { id: 'sp4', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'sp5', type: CommandType.SPAWN_PARTICLES, params: { value: 15 } },
                { id: 'sp6', type: CommandType.END_IF, params: {} },
                { id: 'kb1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '👺' } },
                { id: 'kb2', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 15 } },
                { id: 'kb3', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'kb4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_action_arena',
            mode: AppMode.GAME,
            name: 'Arena Fighter',
            description: 'Survive waves in a circular arena!',
            icon: Zap,
            color: 'bg-gradient-to-r from-amber-500 to-orange-600',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🗡️' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'wave', value: 1 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'kills', value: 0 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'health', value: 100 } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '👾' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '💀' } },
                { id: 'e3', type: CommandType.SPAWN_ENEMY, params: { text: '👺' } },
                { id: 'e4', type: CommandType.SPAWN_ENEMY, params: { text: '👻' } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '❤️' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -5 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 5 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -5 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 5 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'at1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'at2', type: CommandType.SHOOT, params: { text: '🗡️' } },
                { id: 'at3', type: CommandType.PLAY_SOUND, params: { text: 'laser' } },
                { id: 'at4', type: CommandType.END_IF, params: {} },
                { id: 'hp1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '❤️' } },
                { id: 'hp2', type: CommandType.CHANGE_VAR, params: { varName: 'health', value: 25 } },
                { id: 'hp3', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'hp4', type: CommandType.END_IF, params: {} },
                { id: 'go1', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'health', value: 0 } },
                { id: 'go2', type: CommandType.GAME_OVER, params: {} },
                { id: 'go3', type: CommandType.PLAY_SOUND, params: { text: 'death' } },
                { id: 'go4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_action_twinstick',
            mode: AppMode.GAME,
            name: 'Twin Stick Shooter',
            description: 'Move with WASD, aim and shoot with mouse!',
            icon: Zap,
            color: 'bg-gradient-to-r from-cyan-500 to-blue-500',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🤖' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'health', value: 100 } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '👾' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '💀' } },
                { id: 'e3', type: CommandType.SPAWN_ENEMY, params: { text: '🤖' } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '❤️' } },
                { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '⚡' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 65 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -6 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 68 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 6 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 87 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -6 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 83 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 6 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'sh1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'sh2', type: CommandType.SHOOT, params: { text: '🔥' } },
                { id: 'sh3', type: CommandType.PLAY_SOUND, params: { text: 'laser' } },
                { id: 'sh4', type: CommandType.END_IF, params: {} },
                { id: 'kb1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '👾' } },
                { id: 'kb2', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
                { id: 'kb3', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'kb4', type: CommandType.END_IF, params: {} },
                { id: 'hp1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '❤️' } },
                { id: 'hp2', type: CommandType.CHANGE_VAR, params: { varName: 'health', value: 25 } },
                { id: 'hp3', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'hp4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_action_bullet hell',
            mode: AppMode.GAME,
            name: 'Bullet Hell',
            description: 'Dodge thousands of projectiles!',
            icon: Zap,
            color: 'bg-gradient-to-r from-purple-500 to-pink-500',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'space' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '✈️' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'health', value: 1 } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '🔴' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '🟠' } },
                { id: 'e3', type: CommandType.SPAWN_ENEMY, params: { text: '🟡' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -8 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 8 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -8 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 8 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'sh1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'sh2', type: CommandType.SHOOT, params: { text: '💚' } },
                { id: 'sh3', type: CommandType.PLAY_SOUND, params: { text: 'laser' } },
                { id: 'sh4', type: CommandType.END_IF, params: {} },
                { id: 'go1', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'health', value: 0 } },
                { id: 'go2', type: CommandType.GAME_OVER, params: {} },
                { id: 'go3', type: CommandType.PLAY_SOUND, params: { text: 'death' } },
                { id: 'go4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_action_survival',
            mode: AppMode.GAME,
            name: 'Survival Action',
            description: 'Survive endless waves of enemies!',
            icon: Zap,
            color: 'bg-gradient-to-r from-emerald-500 to-teal-500',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🧍' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'wave', value: 1 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'health', value: 100 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'ammo', value: 50 } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '🧟' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '🧟' } },
                { id: 'e3', type: CommandType.SPAWN_ENEMY, params: { text: '🧟' } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '📦' } },
                { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '❤️' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -4 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 4 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -4 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 4 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'sh1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'sh2', type: CommandType.SHOOT, params: { text: '🔥' } },
                { id: 'sh3', type: CommandType.CHANGE_VAR, params: { varName: 'ammo', value: -1 } },
                { id: 'sh4', type: CommandType.PLAY_SOUND, params: { text: 'laser' } },
                { id: 'sh5', type: CommandType.END_IF, params: {} },
                { id: 'am1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '📦' } },
                { id: 'am2', type: CommandType.CHANGE_VAR, params: { varName: 'ammo', value: 10 } },
                { id: 'am3', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'am4', type: CommandType.END_IF, params: {} },
                { id: 'hp1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '❤️' } },
                { id: 'hp2', type: CommandType.CHANGE_VAR, params: { varName: 'health', value: 25 } },
                { id: 'hp3', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'hp4', type: CommandType.END_IF, params: {} },
                { id: 'go1', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'health', value: 0 } },
                { id: 'go2', type: CommandType.GAME_OVER, params: {} },
                { id: 'go3', type: CommandType.PLAY_SOUND, params: { text: 'death' } },
                { id: 'go4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_action_bossrush',
            mode: AppMode.GAME,
            name: 'Boss Rush',
            description: 'Fight boss after boss with no rest!',
            icon: Zap,
            color: 'bg-gradient-to-r from-red-600 to-red-800',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '⚔️' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'boss_count', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'health', value: 100 } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '🐲' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -6 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 6 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -6 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 6 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'at1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'at2', type: CommandType.SHOOT, params: { text: '🔥' } },
                { id: 'at3', type: CommandType.PLAY_SOUND, params: { text: 'laser' } },
                { id: 'at4', type: CommandType.END_IF, params: {} },
                { id: 'bs1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🐲' } },
                { id: 'bs2', type: CommandType.CHANGE_VAR, params: { varName: 'boss_count', value: 1 } },
                { id: 'bs3', type: CommandType.SAY, params: { text: 'BOSS DEFEATED!' } },
                { id: 'bs4', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
                { id: 'bs5', type: CommandType.SPAWN_PARTICLES, params: { value: 20 } },
                { id: 'bs6', type: CommandType.SPAWN_ENEMY, params: { text: '👹' } },
                { id: 'bs7', type: CommandType.END_IF, params: {} },
                { id: 'go1', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'health', value: 0 } },
                { id: 'go2', type: CommandType.GAME_OVER, params: {} },
                { id: 'go3', type: CommandType.PLAY_SOUND, params: { text: 'death' } },
                { id: 'go4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_action_ninja',
            mode: AppMode.GAME,
            name: 'Ninja Action',
            description: 'Wall jump and shuriken throwing ninja!',
            icon: Zap,
            color: 'bg-gradient-to-r from-slate-700 to-slate-900',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🥷' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'stealth', value: 100 } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '💂' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '💂' } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '⭐' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -8 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 8 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.JUMP, params: { value: 15 } },
                { id: 'mv9', type: CommandType.PLAY_SOUND, params: { text: 'jump' } },
                { id: 'mv10', type: CommandType.END_IF, params: {} },
                { id: 'sh1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'sh2', type: CommandType.SHOOT, params: { text: '🌟' } },
                { id: 'sh3', type: CommandType.PLAY_SOUND, params: { text: 'laser' } },
                { id: 'sh4', type: CommandType.END_IF, params: {} },
                { id: 'kb1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '💂' } },
                { id: 'kb2', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 20 } },
                { id: 'kb3', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'kb4', type: CommandType.SPAWN_PARTICLES, params: { value: 8 } },
                { id: 'kb5', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_action_samurai',
            mode: AppMode.GAME,
            name: 'Samurai Combat',
            description: 'Precise sword strikes and parries!',
            icon: Zap,
            color: 'bg-gradient-to-r from-red-500 to-red-700',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '⚔️' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'parry_meter', value: 100 } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '🥷' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '🥷' } },
                { id: 'e3', type: CommandType.SPAWN_ENEMY, params: { text: '💀' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -5 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 5 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'at1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'at2', type: CommandType.SHOOT, params: { text: '⚔️' } },
                { id: 'at3', type: CommandType.PLAY_SOUND, params: { text: 'attack' } },
                { id: 'at4', type: CommandType.END_IF, params: {} },
                { id: 'pr1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 88 } },
                { id: 'pr2', type: CommandType.CHANGE_VAR, params: { varName: 'parry_meter', value: -20 } },
                { id: 'pr3', type: CommandType.SAY, params: { text: '🛡️ PARRY!' } },
                { id: 'pr4', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'pr5', type: CommandType.END_IF, params: {} },
                { id: 'kb1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🥷' } },
                { id: 'kb2', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 25 } },
                { id: 'kb3', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'kb4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_action_mech',
            mode: AppMode.GAME,
            name: 'Mech Combat',
            description: 'Pilot a giant robot with heavy weapons!',
            icon: Zap,
            color: 'bg-gradient-to-r from-blue-600 to-indigo-700',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🤖' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'health', value: 200 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'ammo', value: 50 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: ' tanks' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: ' helicopters' } },
                { id: 'e3', type: CommandType.SPAWN_ENEMY, params: { text: ' robots' } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '📦' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -3 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 3 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -3 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 3 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'sh1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'sh2', type: CommandType.SHOOT, params: { text: '🚀' } },
                { id: 'sh3', type: CommandType.CHANGE_VAR, params: { varName: 'ammo', value: -1 } },
                { id: 'sh4', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'sh5', type: CommandType.END_IF, params: {} },
                { id: 'am1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '📦' } },
                { id: 'am2', type: CommandType.CHANGE_VAR, params: { varName: 'ammo', value: 10 } },
                { id: 'am3', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'am4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_rhythm_dance',
            mode: AppMode.GAME,
            name: '💃 Dance Dance Revolution',
            description: 'Hit the beats in time with arrow keys!',
            icon: Zap,
            color: 'bg-gradient-to-r from-pink-500 to-fuchsia-500',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '💃' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'combo', value: 0 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'health', value: 100 } },
                { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'dance' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'ar1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'ar2', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
                { id: 'ar3', type: CommandType.CHANGE_VAR, params: { varName: 'combo', value: 1 } },
                { id: 'ar4', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: 'ar5', type: CommandType.SAY, params: { text: '← PERFECT!' } },
                { id: 'ar6', type: CommandType.END_IF, params: {} },
                { id: 'ar7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'ar8', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
                { id: 'ar9', type: CommandType.CHANGE_VAR, params: { varName: 'combo', value: 1 } },
                { id: 'ar10', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: 'ar11', type: CommandType.SAY, params: { text: '→ PERFECT!' } },
                { id: 'ar12', type: CommandType.END_IF, params: {} },
                { id: 'ar13', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'ar14', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
                { id: 'ar15', type: CommandType.CHANGE_VAR, params: { varName: 'combo', value: 1 } },
                { id: 'ar16', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: 'ar17', type: CommandType.SAY, params: { text: '↑ PERFECT!' } },
                { id: 'ar18', type: CommandType.END_IF, params: {} },
                { id: 'ar19', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'ar20', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
                { id: 'ar21', type: CommandType.CHANGE_VAR, params: { varName: 'combo', value: 1 } },
                { id: 'ar22', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: 'ar23', type: CommandType.SAY, params: { text: '↓ PERFECT!' } },
                { id: 'ar24', type: CommandType.END_IF, params: {} },
                { id: 'wc1', type: CommandType.IF, params: { condition: 'GREATER' } },
                { id: 'wc2', type: CommandType.WIN_GAME, params: {} },
                { id: 'wc3', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
                { id: 'wc4', type: CommandType.END_IF, params: {} },
                { id: 'go1', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'health', value: 0 } },
                { id: 'go2', type: CommandType.GAME_OVER, params: {} },
                { id: 'go3', type: CommandType.PLAY_SOUND, params: { text: 'death' } },
                { id: 'go4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_rhythm_guitar',
            mode: AppMode.GAME,
            name: '🎸 Guitar Hero',
            description: 'Strum the strings in time with the music!',
            icon: Zap,
            color: 'bg-gradient-to-r from-red-500 to-orange-500',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🎸' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'streak', value: 0 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'health', value: 100 } },
                { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'rock' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'nt1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'nt2', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 15 } },
                { id: 'nt3', type: CommandType.CHANGE_VAR, params: { varName: 'streak', value: 1 } },
                { id: 'nt4', type: CommandType.PLAY_SOUND, params: { text: 'attack' } },
                { id: 'nt5', type: CommandType.SAY, params: { text: '🔥 ROCK!' } },
                { id: 'nt6', type: CommandType.END_IF, params: {} },
                { id: 'nt7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 88 } },
                { id: 'nt8', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 20 } },
                { id: 'nt9', type: CommandType.CHANGE_VAR, params: { varName: 'streak', value: 2 } },
                { id: 'nt10', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'nt11', type: CommandType.SAY, params: { text: '⭐ STAR POWER!' } },
                { id: 'nt12', type: CommandType.END_IF, params: {} },
                { id: 'wc1', type: CommandType.IF, params: { condition: 'GREATER' } },
                { id: 'wc2', type: CommandType.WIN_GAME, params: {} },
                { id: 'wc3', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
                { id: 'wc4', type: CommandType.END_IF, params: {} },
                { id: 'go1', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'health', value: 0 } },
                { id: 'go2', type: CommandType.GAME_OVER, params: {} },
                { id: 'go3', type: CommandType.PLAY_SOUND, params: { text: 'death' } },
                { id: 'go4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_rhythm_piano',
            mode: AppMode.GAME,
            name: '🎹 Piano Tiles',
            description: 'Tap the black tiles as they scroll down!',
            icon: Zap,
            color: 'bg-gradient-to-r from-slate-700 to-slate-900',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🎹' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'speed', value: 1 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'health', value: 100 } },
                { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'piano' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'tl1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'tl2', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
                { id: 'tl3', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: 'tl4', type: CommandType.SAY, params: { text: '🎵 Do!' } },
                { id: 'tl5', type: CommandType.END_IF, params: {} },
                { id: 'tl6', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'tl7', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
                { id: 'tl8', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: 'tl9', type: CommandType.SAY, params: { text: '🎵 Re!' } },
                { id: 'tl10', type: CommandType.END_IF, params: {} },
                { id: 'tl11', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'tl12', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
                { id: 'tl13', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: 'tl14', type: CommandType.SAY, params: { text: '🎵 Mi!' } },
                { id: 'tl15', type: CommandType.END_IF, params: {} },
                { id: 'tl16', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'tl17', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
                { id: 'tl18', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: 'tl19', type: CommandType.SAY, params: { text: '🎵 Fa!' } },
                { id: 'tl20', type: CommandType.END_IF, params: {} },
                { id: 'wc1', type: CommandType.IF, params: { condition: 'GREATER' } },
                { id: 'wc2', type: CommandType.WIN_GAME, params: {} },
                { id: 'wc3', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
                { id: 'wc4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_rhythm_beat',
            mode: AppMode.GAME,
            name: '🥽 Beat Saber',
            description: 'Slice through beats with your sabers!',
            icon: Zap,
            color: 'bg-gradient-to-r from-cyan-500 to-blue-600',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'space' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '⚔️' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'combo', value: 0 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'health', value: 100 } },
                { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'electronic' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'sl1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'sl2', type: CommandType.SHOOT, params: { text: '🔴' } },
                { id: 'sl3', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 15 } },
                { id: 'sl4', type: CommandType.CHANGE_VAR, params: { varName: 'combo', value: 1 } },
                { id: 'sl5', type: CommandType.PLAY_SOUND, params: { text: 'attack' } },
                { id: 'sl6', type: CommandType.END_IF, params: {} },
                { id: 'sl7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'sl8', type: CommandType.SHOOT, params: { text: '🔵' } },
                { id: 'sl9', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 15 } },
                { id: 'sl10', type: CommandType.CHANGE_VAR, params: { varName: 'combo', value: 1 } },
                { id: 'sl11', type: CommandType.PLAY_SOUND, params: { text: 'attack' } },
                { id: 'sl12', type: CommandType.END_IF, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv2', type: CommandType.MOVE_Y, params: { value: -8 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv5', type: CommandType.MOVE_Y, params: { value: 8 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'wc1', type: CommandType.IF, params: { condition: 'GREATER' } },
                { id: 'wc2', type: CommandType.WIN_GAME, params: {} },
                { id: 'wc3', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
                { id: 'wc4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_rhythm_dj',
            mode: AppMode.GAME,
            name: '🎧 DJ Simulator',
            description: 'Mix beats and drop the bass!',
            icon: Zap,
            color: 'bg-gradient-to-r from-violet-500 to-purple-600',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🎧' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'bpm', value: 120 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'crowd', value: 50 } },
                { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'electronic' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'dj1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'dj2', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
                { id: 'dj3', type: CommandType.CHANGE_VAR, params: { varName: 'crowd', value: 5 } },
                { id: 'dj4', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'dj5', type: CommandType.SAY, params: { text: '🎵 DROP!' } },
                { id: 'dj6', type: CommandType.END_IF, params: {} },
                { id: 'dj7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 88 } },
                { id: 'dj8', type: CommandType.CHANGE_VAR, params: { varName: 'bpm', value: 10 } },
                { id: 'dj9', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 20 } },
                { id: 'dj10', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'dj11', type: CommandType.SAY, params: { text: '🔥 BASS DROP!' } },
                { id: 'dj12', type: CommandType.SPAWN_PARTICLES, params: { value: 10 } },
                { id: 'dj13', type: CommandType.END_IF, params: {} },
                { id: 'wc1', type: CommandType.IF, params: { condition: 'GREATER' } },
                { id: 'wc2', type: CommandType.WIN_GAME, params: {} },
                { id: 'wc3', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
                { id: 'wc4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_rhythm_drum',
            mode: AppMode.GAME,
            name: '🪘 Drum Simulator',
            description: 'Play the drums with different beats!',
            icon: Zap,
            color: 'bg-gradient-to-r from-amber-500 to-orange-600',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🪘' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'rhythm', value: 0 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'energy', value: 100 } },
                { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'drums' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'dm1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'dm2', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 5 } },
                { id: 'dm3', type: CommandType.PLAY_SOUND, params: { text: 'attack' } },
                { id: 'dm4', type: CommandType.SAY, params: { text: '🪘 Kick!' } },
                { id: 'dm5', type: CommandType.END_IF, params: {} },
                { id: 'dm6', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'dm7', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 5 } },
                { id: 'dm8', type: CommandType.PLAY_SOUND, params: { text: 'hit' } },
                { id: 'dm9', type: CommandType.SAY, params: { text: '🪘 Snare!' } },
                { id: 'dm10', type: CommandType.END_IF, params: {} },
                { id: 'dm11', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'dm12', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 5 } },
                { id: 'dm13', type: CommandType.PLAY_SOUND, params: { text: 'punch' } },
                { id: 'dm14', type: CommandType.SAY, params: { text: '🪘 Hi-Hat!' } },
                { id: 'dm15', type: CommandType.END_IF, params: {} },
                { id: 'dm16', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'dm17', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 5 } },
                { id: 'dm18', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'dm19', type: CommandType.SAY, params: { text: '🪘 Crash!' } },
                { id: 'dm20', type: CommandType.END_IF, params: {} },
                { id: 'wc1', type: CommandType.IF, params: { condition: 'GREATER' } },
                { id: 'wc2', type: CommandType.WIN_GAME, params: {} },
                { id: 'wc3', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
                { id: 'wc4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_military_tactical',
            mode: AppMode.GAME,
            name: '🎖️ Tactical Combat',
            description: 'Lead your squad through enemy territory!',
            icon: Zap,
            color: 'bg-gradient-to-r from-green-700 to-green-900',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'forest' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🎖️' } },
                { id: 's3', type: CommandType.SET_WEATHER, params: { text: 'fog' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'ammo', value: 30 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'health', value: 100 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'enemies_down', value: 0 } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '💂' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '💂' } },
                { id: 'e3', type: CommandType.SPAWN_ENEMY, params: { text: '💂' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -4 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 4 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -4 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 4 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'sh1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'sh2', type: CommandType.SHOOT, params: { text: '🔫' } },
                { id: 'sh3', type: CommandType.CHANGE_VAR, params: { varName: 'ammo', value: -1 } },
                { id: 'sh4', type: CommandType.PLAY_SOUND, params: { text: 'laser' } },
                { id: 'sh5', type: CommandType.END_IF, params: {} },
                { id: 'kb1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '💂' } },
                { id: 'kb2', type: CommandType.CHANGE_VAR, params: { varName: 'enemies_down', value: 1 } },
                { id: 'kb3', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'kb4', type: CommandType.SPAWN_PARTICLES, params: { value: 5 } },
                { id: 'kb5', type: CommandType.END_IF, params: {} },
                { id: 'go1', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'health', value: 0 } },
                { id: 'go2', type: CommandType.GAME_OVER, params: {} },
                { id: 'go3', type: CommandType.PLAY_SOUND, params: { text: 'death' } },
                { id: 'go4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_military_base',
            mode: AppMode.GAME,
            name: '🏰 Base Defense',
            description: 'Defend your base from waves of enemies!',
            icon: Zap,
            color: 'bg-gradient-to-r from-amber-600 to-orange-700',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🏰' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'wave', value: 1 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'kills', value: 0 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'health', value: 100 } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '🧟' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '🧟' } },
                { id: 'e3', type: CommandType.SPAWN_ENEMY, params: { text: '🧟' } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '📦' } },
                { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '❤️' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'sh1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'sh2', type: CommandType.SHOOT, params: { text: '🔫' } },
                { id: 'sh3', type: CommandType.PLAY_SOUND, params: { text: 'laser' } },
                { id: 'sh4', type: CommandType.END_IF, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -5 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 5 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'kb1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🧟' } },
                { id: 'kb2', type: CommandType.CHANGE_VAR, params: { varName: 'kills', value: 1 } },
                { id: 'kb3', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'kb4', type: CommandType.END_IF, params: {} },
                { id: 'ws1', type: CommandType.IF, params: { condition: 'GREATER' } },
                { id: 'ws2', type: CommandType.CHANGE_VAR, params: { varName: 'wave', value: 1 } },
                { id: 'ws3', type: CommandType.SET_VAR, params: { varName: 'kills', value: 0 } },
                { id: 'ws4', type: CommandType.SAY, params: { text: '🌊 WAVE ' } },
                { id: 'ws5', type: CommandType.SPAWN_ENEMY, params: { text: '🧟' } },
                { id: 'ws6', type: CommandType.SPAWN_ENEMY, params: { text: '🧟' } },
                { id: 'ws7', type: CommandType.SPAWN_ENEMY, params: { text: '🧟' } },
                { id: 'ws8', type: CommandType.END_IF, params: {} },
                { id: 'hp1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '❤️' } },
                { id: 'hp2', type: CommandType.CHANGE_VAR, params: { varName: 'health', value: 25 } },
                { id: 'hp3', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'hp4', type: CommandType.END_IF, params: {} },
                { id: 'go1', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'health', value: 0 } },
                { id: 'go2', type: CommandType.GAME_OVER, params: {} },
                { id: 'go3', type: CommandType.PLAY_SOUND, params: { text: 'death' } },
                { id: 'go4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_military_tank',
            mode: AppMode.GAME,
            name: '🔫 Tank Warfare',
            description: 'Pilot a tank and destroy enemy forces!',
            icon: Zap,
            color: 'bg-gradient-to-r from-slate-600 to-slate-800',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🔫' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'health', value: 200 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'ammo', value: 50 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '💣' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '💣' } },
                { id: 'e3', type: CommandType.SPAWN_ENEMY, params: { text: '💣' } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '📦' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -3 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 3 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -3 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 3 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'sh1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'sh2', type: CommandType.SHOOT, params: { text: '💣' } },
                { id: 'sh3', type: CommandType.CHANGE_VAR, params: { varName: 'ammo', value: -1 } },
                { id: 'sh4', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'sh5', type: CommandType.SPAWN_PARTICLES, params: { value: 8 } },
                { id: 'sh6', type: CommandType.END_IF, params: {} },
                { id: 'kb1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '💣' } },
                { id: 'kb2', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
                { id: 'kb3', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'kb4', type: CommandType.END_IF, params: {} },
                { id: 'am1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '📦' } },
                { id: 'am2', type: CommandType.CHANGE_VAR, params: { varName: 'ammo', value: 10 } },
                { id: 'am3', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'am4', type: CommandType.END_IF, params: {} },
                { id: 'go1', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'health', value: 0 } },
                { id: 'go2', type: CommandType.GAME_OVER, params: {} },
                { id: 'go3', type: CommandType.PLAY_SOUND, params: { text: 'death' } },
                { id: 'go4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_military_naval',
            mode: AppMode.GAME,
            name: '🚢 Naval Warfare',
            description: 'Command your fleet across the ocean!',
            icon: Zap,
            color: 'bg-gradient-to-r from-blue-600 to-blue-800',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🚢' } },
                { id: 's3', type: CommandType.SET_WEATHER, params: { text: 'rain' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'health', value: 200 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'ammo', value: 40 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '⛵' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '⛵' } },
                { id: 'e3', type: CommandType.SPAWN_ENEMY, params: { text: '🚢' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -3 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 3 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -3 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 3 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'sh1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'sh2', type: CommandType.SHOOT, params: { text: '💣' } },
                { id: 'sh3', type: CommandType.CHANGE_VAR, params: { varName: 'ammo', value: -1 } },
                { id: 'sh4', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'sh5', type: CommandType.SPAWN_PARTICLES, params: { value: 8 } },
                { id: 'sh6', type: CommandType.END_IF, params: {} },
                { id: 'kb1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '⛵' } },
                { id: 'kb2', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
                { id: 'kb3', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'kb4', type: CommandType.END_IF, params: {} },
                { id: 'go1', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'health', value: 0 } },
                { id: 'go2', type: CommandType.GAME_OVER, params: {} },
                { id: 'go3', type: CommandType.PLAY_SOUND, params: { text: 'death' } },
                { id: 'go4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_military_air',
            mode: AppMode.GAME,
            name: '✈️ Air Combat',
            description: 'Dogfight enemy planes in the sky!',
            icon: Zap,
            color: 'bg-gradient-to-r from-sky-500 to-sky-700',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'space' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '✈️' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'health', value: 100 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'missiles', value: 20 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '✈️' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '✈️' } },
                { id: 'e3', type: CommandType.SPAWN_ENEMY, params: { text: '🚀' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -6 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 6 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -6 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 6 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'sh1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'sh2', type: CommandType.SHOOT, params: { text: '🚀' } },
                { id: 'sh3', type: CommandType.CHANGE_VAR, params: { varName: 'missiles', value: -1 } },
                { id: 'sh4', type: CommandType.PLAY_SOUND, params: { text: 'laser' } },
                { id: 'sh5', type: CommandType.END_IF, params: {} },
                { id: 'kb1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '✈️' } },
                { id: 'kb2', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 15 } },
                { id: 'kb3', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'kb4', type: CommandType.SPAWN_PARTICLES, params: { value: 10 } },
                { id: 'kb5', type: CommandType.END_IF, params: {} },
                { id: 'go1', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'health', value: 0 } },
                { id: 'go2', type: CommandType.GAME_OVER, params: {} },
                { id: 'go3', type: CommandType.PLAY_SOUND, params: { text: 'death' } },
                { id: 'go4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_military_special',
            mode: AppMode.GAME,
            name: '🎖️ Special Forces',
            description: 'Covert ops behind enemy lines!',
            icon: Zap,
            color: 'bg-gradient-to-r from-slate-800 to-black',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🎖️' } },
                { id: 's3', type: CommandType.SET_WEATHER, params: { text: 'fog' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'stealth', value: 100 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'ammo', value: 20 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '💂' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '💂' } },
                { id: 'e3', type: CommandType.SPAWN_ENEMY, params: { text: '💂' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -5 } },
                { id: 'mv3', type: CommandType.CHANGE_VAR, params: { varName: 'stealth', value: -1 } },
                { id: 'mv4', type: CommandType.END_IF, params: {} },
                { id: 'mv5', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv6', type: CommandType.MOVE_X, params: { value: 5 } },
                { id: 'mv7', type: CommandType.CHANGE_VAR, params: { varName: 'stealth', value: -1 } },
                { id: 'mv8', type: CommandType.END_IF, params: {} },
                { id: 'mv9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv10', type: CommandType.MOVE_Y, params: { value: -5 } },
                { id: 'mv11', type: CommandType.END_IF, params: {} },
                { id: 'mv12', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv13', type: CommandType.MOVE_Y, params: { value: 5 } },
                { id: 'mv14', type: CommandType.END_IF, params: {} },
                { id: 'sh1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'sh2', type: CommandType.SHOOT, params: { text: '🗡️' } },
                { id: 'sh3', type: CommandType.CHANGE_VAR, params: { varName: 'ammo', value: -1 } },
                { id: 'sh4', type: CommandType.CHANGE_VAR, params: { varName: 'stealth', value: -10 } },
                { id: 'sh5', type: CommandType.PLAY_SOUND, params: { text: 'attack' } },
                { id: 'sh6', type: CommandType.END_IF, params: {} },
                { id: 'kb1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '💂' } },
                { id: 'kb2', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 20 } },
                { id: 'kb3', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'kb4', type: CommandType.END_IF, params: {} },
                { id: 'go1', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'health', value: 0 } },
                { id: 'go2', type: CommandType.GAME_OVER, params: {} },
                { id: 'go3', type: CommandType.PLAY_SOUND, params: { text: 'death' } },
                { id: 'go4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        { id: 'tpl_action_hack_slash', mode: AppMode.GAME, name: 'Hack & Slash Warrior', description: 'Intense melee combat with combos, dodges, and special moves!', icon: Swords, color: 'bg-gradient-to-r from-red-500 to-orange-600', commands: [
            { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'stone_floor' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '⚔️' } }, { id: 'c3', type: CommandType.SET_GRAVITY, params: { condition: 'true' } }, { id: 'c4', type: CommandType.SET_VAR, params: { varName: 'combo', value: 0 } }, { id: 'c5', type: CommandType.SET_VAR, params: { varName: 'health', value: 100 } }, { id: 'c6', type: CommandType.SPAWN_ENEMY, params: { text: '👾' } }, { id: 'c7', type: CommandType.SPAWN_ENEMY, params: { text: '🧟' } }, { id: 'c8', type: CommandType.FOREVER, params: {} }, { id: 'c9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } }, { id: 'c10', type: CommandType.MOVE_X, params: { value: -5 } }, { id: 'c11', type: CommandType.END_IF, params: {} }, { id: 'c12', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } }, { id: 'c13', type: CommandType.MOVE_X, params: { value: 5 } }, { id: 'c14', type: CommandType.END_IF, params: {} }, { id: 'c15', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } }, { id: 'c16', type: CommandType.JUMP, params: { value: 12 } }, { id: 'c17', type: CommandType.END_IF, params: {} }, { id: 'c18', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c19', type: CommandType.SWING_WEAPON, params: { text: '⚔️', value: 15 } }, { id: 'c20', type: CommandType.PLAY_SOUND, params: { text: 'attack' } }, { id: 'c21', type: CommandType.SHAKE_SCREEN, params: { value: 0.3 } }, { id: 'c22', type: CommandType.END_IF, params: {} }, { id: 'c23', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 33 } }, { id: 'c24', type: CommandType.COMBO_ATTACK, params: { value: 3 } }, { id: 'c25', type: CommandType.CHANGE_VAR, params: { varName: 'combo', value: 1 } }, { id: 'c26', type: CommandType.END_IF, params: {} }, { id: 'c27', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } }, { id: 'c28', type: CommandType.DODGE_ROLL, params: { value: 8 } }, { id: 'c29', type: CommandType.END_IF, params: {} }, { id: 'c30', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 35 } }, { id: 'c31', type: CommandType.BLOCK_ATTACK, params: {} }, { id: 'c32', type: CommandType.END_IF, params: {} }, { id: 'c33', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_action_beat_em_up', mode: AppMode.GAME, name: 'Street Beat Em Up', description: 'Classic side-scrolling brawler with combos!', icon: Swords, color: 'bg-gradient-to-r from-pink-500 to-red-600', commands: [
            { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'metal_floor' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🥊' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'enemies_beaten', value: 0 } }, { id: 'c4', type: CommandType.SPAWN_ENEMY, params: { text: '👾' } }, { id: 'c5', type: CommandType.SPAWN_ENEMY, params: { text: '👺' } }, { id: 'c6', type: CommandType.FOREVER, params: {} }, { id: 'c7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } }, { id: 'c8', type: CommandType.MOVE_X, params: { value: -6 } }, { id: 'c9', type: CommandType.END_IF, params: {} }, { id: 'c10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } }, { id: 'c11', type: CommandType.MOVE_X, params: { value: 6 } }, { id: 'c12', type: CommandType.END_IF, params: {} }, { id: 'c13', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c14', type: CommandType.COMBO_ATTACK, params: { value: 5 } }, { id: 'c15', type: CommandType.PLAY_SOUND, params: { text: 'punch' } }, { id: 'c16', type: CommandType.CHANGE_VAR, params: { varName: 'enemies_beaten', value: 1 } }, { id: 'c17', type: CommandType.END_IF, params: {} }, { id: 'c18', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_action_arena_fighter', mode: AppMode.GAME, name: 'Arena Fighter', description: 'Fight waves of enemies in an arena!', icon: Swords, color: 'bg-gradient-to-r from-amber-500 to-red-600', commands: [
            { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'arena_floor' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🤺' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'wave', value: 1 } }, { id: 'c4', type: CommandType.SET_VAR, params: { varName: 'kills', value: 0 } }, { id: 'c5', type: CommandType.SPAWN_ENEMY, params: { text: '👾' } }, { id: 'c6', type: CommandType.SPAWN_ENEMY, params: { text: '👾' } }, { id: 'c7', type: CommandType.FOREVER, params: {} }, { id: 'c8', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c9', type: CommandType.SWING_WEAPON, params: { text: '⚔️', value: 12 } }, { id: 'c10', type: CommandType.CHANGE_VAR, params: { varName: 'kills', value: 1 } }, { id: 'c11', type: CommandType.PLAY_SOUND, params: { text: 'attack' } }, { id: 'c12', type: CommandType.END_IF, params: {} }, { id: 'c13', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } }, { id: 'c14', type: CommandType.DODGE_ROLL, params: { value: 10 } }, { id: 'c15', type: CommandType.END_IF, params: {} }, { id: 'c16', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_action_twin_stick', mode: AppMode.GAME, name: 'Twin Stick Shooter', description: 'Move and shoot in all directions!', icon: Crosshair, color: 'bg-gradient-to-r from-cyan-500 to-blue-600', commands: [
            { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'metal_floor' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🤖' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } }, { id: 'c4', type: CommandType.SPAWN_ENEMY, params: { text: '👾' } }, { id: 'c5', type: CommandType.SPAWN_ENEMY, params: { text: '🦇' } }, { id: 'c6', type: CommandType.FOREVER, params: {} }, { id: 'c7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } }, { id: 'c8', type: CommandType.MOVE_X, params: { value: -5 } }, { id: 'c9', type: CommandType.END_IF, params: {} }, { id: 'c10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } }, { id: 'c11', type: CommandType.MOVE_X, params: { value: 5 } }, { id: 'c12', type: CommandType.END_IF, params: {} }, { id: 'c13', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } }, { id: 'c14', type: CommandType.MOVE_Y, params: { value: -5 } }, { id: 'c15', type: CommandType.END_IF, params: {} }, { id: 'c16', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } }, { id: 'c17', type: CommandType.MOVE_Y, params: { value: 5 } }, { id: 'c18', type: CommandType.END_IF, params: {} }, { id: 'c19', type: CommandType.SHOOT, params: { text: '🔥' } }, { id: 'c20', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 1 } }, { id: 'c21', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_action_bullet_hell', mode: AppMode.GAME, name: 'Bullet Hell', description: 'Dodge hundreds of projectiles!', icon: Crosshair, color: 'bg-gradient-to-r from-purple-500 to-pink-600', commands: [
            { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'space' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '✈️' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'survival_time', value: 0 } }, { id: 'c4', type: CommandType.SPAWN_ENEMY, params: { text: '💀' } }, { id: 'c5', type: CommandType.FOREVER, params: {} }, { id: 'c6', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } }, { id: 'c7', type: CommandType.MOVE_X, params: { value: -8 } }, { id: 'c8', type: CommandType.END_IF, params: {} }, { id: 'c9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } }, { id: 'c10', type: CommandType.MOVE_X, params: { value: 8 } }, { id: 'c11', type: CommandType.END_IF, params: {} }, { id: 'c12', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } }, { id: 'c13', type: CommandType.MOVE_Y, params: { value: -8 } }, { id: 'c14', type: CommandType.END_IF, params: {} }, { id: 'c15', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } }, { id: 'c16', type: CommandType.MOVE_Y, params: { value: 8 } }, { id: 'c17', type: CommandType.END_IF, params: {} }, { id: 'c18', type: CommandType.CHANGE_VAR, params: { varName: 'survival_time', value: 1 } }, { id: 'c19', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_action_survival_action', mode: AppMode.GAME, name: 'Survival Action', description: 'Survive waves of enemies with limited resources!', icon: Swords, color: 'bg-gradient-to-r from-emerald-500 to-teal-600', commands: [
            { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'stone_floor' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🛡️' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'health', value: 100 } }, { id: 'c4', type: CommandType.SET_VAR, params: { varName: 'wave', value: 1 } }, { id: 'c5', type: CommandType.SET_VAR, params: { varName: 'ammo', value: 10 } }, { id: 'c6', type: CommandType.SPAWN_ENEMY, params: { text: '🧟' } }, { id: 'c7', type: CommandType.FOREVER, params: {} }, { id: 'c8', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c9', type: CommandType.SHOOT, params: { text: '🔫' } }, { id: 'c10', type: CommandType.CHANGE_VAR, params: { varName: 'ammo', value: -1 } }, { id: 'c11', type: CommandType.END_IF, params: {} }, { id: 'c12', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 33 } }, { id: 'c13', type: CommandType.BLOCK_ATTACK, params: {} }, { id: 'c14', type: CommandType.END_IF, params: {} }, { id: 'c15', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_action_boss_rush', mode: AppMode.GAME, name: 'Boss Rush', description: 'Defeat epic bosses one after another!', icon: Swords, color: 'bg-gradient-to-r from-red-600 to-purple-700', commands: [
            { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'arena_floor' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '⚔️' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'bosses_defeated', value: 0 } }, { id: 'c4', type: CommandType.SPAWN_BOSS, params: { text: 'Dragon', value: 200 } }, { id: 'c5', type: CommandType.FOREVER, params: {} }, { id: 'c6', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c7', type: CommandType.SWING_WEAPON, params: { text: '⚔️', value: 20 } }, { id: 'c8', type: CommandType.PLAY_SOUND, params: { text: 'attack' } }, { id: 'c9', type: CommandType.END_IF, params: {} }, { id: 'c10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } }, { id: 'c11', type: CommandType.SPECIAL_MOVE, params: { text: 'ult', value: 50 } }, { id: 'c12', type: CommandType.SHAKE_SCREEN, params: { value: 1 } }, { id: 'c13', type: CommandType.END_IF, params: {} }, { id: 'c14', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_action_racing', mode: AppMode.GAME, name: 'Racing Rush', description: 'High-speed racing with boost and drift!', icon: Zap, color: 'bg-gradient-to-r from-red-500 to-yellow-500', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'track' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🏎️' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'speed', value: 0 } }, { id: 'c4', type: CommandType.SET_VAR, params: { varName: 'lap', value: 1 } }, { id: 'c5', type: CommandType.FOREVER, params: {} }, { id: 'c6', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } }, { id: 'c7', type: CommandType.MOVE_X, params: { value: 8 } }, { id: 'c8', type: CommandType.CHANGE_VAR, params: { varName: 'speed', value: 1 } }, { id: 'c9', type: CommandType.END_IF, params: {} }, { id: 'c10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } }, { id: 'c11', type: CommandType.MOVE_X, params: { value: 15 } }, { id: 'c12', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } }, { id: 'c13', type: CommandType.END_IF, params: {} }, { id: 'c14', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_action_parkour', mode: AppMode.GAME, name: 'Parkour Runner', description: 'Wall runs, double jumps, and grapple hooks!', icon: Zap, color: 'bg-gradient-to-r from-cyan-500 to-blue-600', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'metal_floor' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🏃' } }, { id: 'c3', type: CommandType.SET_GRAVITY, params: { condition: 'true' } }, { id: 'c4', type: CommandType.DOUBLE_JUMP, params: { condition: 'true' } }, { id: 'c5', type: CommandType.SET_VAR, params: { varName: 'distance', value: 0 } }, { id: 'c6', type: CommandType.FOREVER, params: {} }, { id: 'c7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } }, { id: 'c8', type: CommandType.MOVE_X, params: { value: -6 } }, { id: 'c9', type: CommandType.END_IF, params: {} }, { id: 'c10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } }, { id: 'c11', type: CommandType.MOVE_X, params: { value: 6 } }, { id: 'c12', type: CommandType.END_IF, params: {} }, { id: 'c13', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } }, { id: 'c14', type: CommandType.JUMP, params: { value: 18 } }, { id: 'c15', type: CommandType.END_IF, params: {} }, { id: 'c16', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } }, { id: 'c17', type: CommandType.GRAPPLE, params: { value: 100 } }, { id: 'c18', type: CommandType.END_IF, params: {} }, { id: 'c19', type: CommandType.CHANGE_VAR, params: { varName: 'distance', value: 1 } }, { id: 'c20', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_action_sword_art', mode: AppMode.GAME, name: 'Sword Art Online', description: 'Anime-style sword combat with skills!', icon: Swords, color: 'bg-gradient-to-r from-red-500 to-pink-500', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'grass' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '⚔️' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'level', value: 1 } }, { id: 'c4', type: CommandType.SET_VAR, params: { varName: 'xp', value: 0 } }, { id: 'c5', type: CommandType.SPAWN_ENEMY, params: { text: '💀' } }, { id: 'c6', type: CommandType.FOREVER, params: {} }, { id: 'c7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c8', type: CommandType.SWING_WEAPON, params: { text: '⚔️', value: 15 } }, { id: 'c9', type: CommandType.CHANGE_VAR, params: { varName: 'xp', value: 10 } }, { id: 'c10', type: CommandType.PLAY_SOUND, params: { text: 'attack' } }, { id: 'c11', type: CommandType.END_IF, params: {} }, { id: 'c12', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } }, { id: 'c13', type: CommandType.SPECIAL_MOVE, params: { text: 'starburst', value: 50 } }, { id: 'c14', type: CommandType.SCREEN_SHAKE, params: { value: 1 } }, { id: 'c15', type: CommandType.END_IF, params: {} }, { id: 'c16', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_action_stealth', mode: AppMode.GAME, name: 'Stealth Mission', description: 'Infiltrate undetected!', icon: Eye, color: 'bg-gradient-to-r from-slate-700 to-slate-900', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'metal_floor' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🥷' } }, { id: 'c3', type: CommandType.SET_OPACITY, params: { value: 30 } }, { id: 'c4', type: CommandType.SET_VAR, params: { varName: 'stealth', value: 100 } }, { id: 'c5', type: CommandType.SPAWN_ENEMY, params: { text: '💀' } }, { id: 'c6', type: CommandType.FOREVER, params: {} }, { id: 'c7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } }, { id: 'c8', type: CommandType.MOVE_X, params: { value: -3 } }, { id: 'c9', type: CommandType.END_IF, params: {} }, { id: 'c10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } }, { id: 'c11', type: CommandType.MOVE_X, params: { value: 3 } }, { id: 'c12', type: CommandType.END_IF, params: {} }, { id: 'c13', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c14', type: CommandType.SHOOT, params: { text: '⭐' } }, { id: 'c15', type: CommandType.SET_OPACITY, params: { value: 100 } }, { id: 'c16', type: CommandType.END_IF, params: {} }, { id: 'c17', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_action_tower_defense', mode: AppMode.GAME, name: 'Tower Defense', description: 'Build towers to defend against waves!', icon: Shield, color: 'bg-gradient-to-r from-emerald-500 to-teal-600', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'grass' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🏰' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'gold', value: 100 } }, { id: 'c4', type: CommandType.SET_VAR, params: { varName: 'wave', value: 1 } }, { id: 'c5', type: CommandType.SPAWN_ENEMY, params: { text: '💀' } }, { id: 'c6', type: CommandType.FOREVER, params: {} }, { id: 'c7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c8', type: CommandType.BUILD, params: { text: 'tower', value: 25 } }, { id: 'c9', type: CommandType.CHANGE_VAR, params: { varName: 'gold', value: -25 } }, { id: 'c10', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } }, { id: 'c11', type: CommandType.END_IF, params: {} }, { id: 'c12', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_action_roguelike', mode: AppMode.GAME, name: 'Roguelike Dungeon', description: 'Random dungeon crawl with permadeath!', icon: Swords, color: 'bg-gradient-to-r from-violet-600 to-purple-800', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'stone_floor' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🧙' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'floor', value: 1 } }, { id: 'c4', type: CommandType.SET_VAR, params: { varName: 'health', value: 50 } }, { id: 'c5', type: CommandType.SPAWN_ENEMY, params: { text: '💀' } }, { id: 'c6', type: CommandType.SPAWN_ITEM, params: { text: '🧪' } }, { id: 'c7', type: CommandType.FOREVER, params: {} }, { id: 'c8', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c9', type: CommandType.SWING_WEAPON, params: { text: '🔥', value: 12 } }, { id: 'c10', type: CommandType.PLAY_SOUND, params: { text: 'attack' } }, { id: 'c11', type: CommandType.END_IF, params: {} }, { id: 'c12', type: CommandType.END_FOREVER, params: {} }
        ]},
];
