import { AppMode, CommandType, CircuitComponent, CommandBlock } from '../../types';
import { LucideIcon, Zap, MessageSquare, User, Eye, MapPin, Globe, Sparkles, Ghost } from 'lucide-react';

export const adventureTemplates: {
    id: string,
    mode: AppMode,
    name: string,
    description: string,
    icon: LucideIcon,
    color: string,
    commands: CommandBlock[],
    circuitComponents?: CircuitComponent[]
}[] = [
        {
            id: 'tpl_game_quest',
            mode: AppMode.GAME,
            name: 'AI Quest RPG',
            description: 'Talk to an NPC to start your adventure!',
            icon: MessageSquare,
            color: 'bg-indigo-600',
            commands: [
                { id: '1', type: CommandType.SET_SCENE, params: { text: 'forest' } },
                { id: '2', type: CommandType.NPC_TALK, params: { text: 'Wizard', message: 'The forest is dangerous! Take this fireball!' } },
                { id: '3', type: CommandType.SPAWN_PARTICLES, params: { text: 'sparkle', color: '#fbbf24' } },
                { id: '4', type: CommandType.SET_VAR, params: { varName: 'has_spell', value: 1 } }
            ]
        },
        {
            id: 'tpl_game_rpg',
            mode: AppMode.GAME,
            name: 'RPG Adventure',
            description: 'A top-down RPG with enemies, items, and dialogue!',
            icon: User,
            color: 'bg-amber-600',
            commands: [
                { id: '1', type: CommandType.SET_SCENE, params: { text: 'forest' } },
                { id: '2', type: CommandType.SET_EMOJI, params: { text: '🧙' } },
                { id: '3', type: CommandType.SAY, params: { text: 'Welcome, adventurer!' } },
                { id: '4', type: CommandType.SET_VAR, params: { varName: 'health', value: 100 } },
                { id: '5', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: '6', type: CommandType.FOREVER, params: {} },
                { id: '7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: '8', type: CommandType.MOVE_Y, params: { value: -5 } },
                { id: '9', type: CommandType.END_IF, params: {} },
                { id: '10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: '11', type: CommandType.MOVE_Y, params: { value: 5 } },
                { id: '12', type: CommandType.END_IF, params: {} },
                { id: '13', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: '14', type: CommandType.MOVE_X, params: { value: -5 } },
                { id: '15', type: CommandType.END_IF, params: {} },
                { id: '16', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: '17', type: CommandType.MOVE_X, params: { value: 5 } },
                { id: '18', type: CommandType.END_IF, params: {} },
                { id: '19', type: CommandType.SHOOT, params: { text: '⚡' } },
                { id: '20', type: CommandType.SPAWN_ENEMY, params: { text: '👾' } },
                { id: '21', type: CommandType.ADD_TO_INVENTORY, params: { text: 'Health Potion', value: 1 } },
                { id: '22', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_adventure_pointclick',
            mode: AppMode.GAME,
            name: 'Point & Click',
            description: 'Click to explore and solve puzzles!',
            icon: Zap,
            color: 'bg-gradient-to-r from-amber-500 to-yellow-500',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🔍' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'items_found', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'puzzles_solved', value: 0 } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '🔑' } },
                { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '🗝️' } },
                { id: 'p3', type: CommandType.SPAWN_ITEM, params: { text: '💎' } },
                { id: 'p4', type: CommandType.SPAWN_ITEM, params: { text: '📜' } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '🔒' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '🔒' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -4 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 4 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -4 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 4 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'in1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🔑' } },
                { id: 'in2', type: CommandType.CHANGE_VAR, params: { varName: 'items_found', value: 1 } },
                { id: 'in3', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: 'in4', type: CommandType.SAY, params: { text: '🔑 Found a key!' } },
                { id: 'in5', type: CommandType.END_IF, params: {} },
                { id: 'lk1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🔒' } },
                { id: 'lk2', type: CommandType.IF, params: { condition: 'GREATER' } },
                { id: 'lk3', type: CommandType.CHANGE_VAR, params: { varName: 'puzzles_solved', value: 1 } },
                { id: 'lk4', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'lk5', type: CommandType.SAY, params: { text: '🔓 Door unlocked!' } },
                { id: 'lk6', type: CommandType.END_IF, params: {} },
                { id: 'lk7', type: CommandType.END_IF, params: {} },
                { id: 'wc1', type: CommandType.IF, params: { condition: 'GREATER' } },
                { id: 'wc2', type: CommandType.WIN_GAME, params: {} },
                { id: 'wc3', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
                { id: 'wc4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_adventure_exploration',
            mode: AppMode.GAME,
            name: 'Exploration',
            description: 'Explore a vast world and discover secrets!',
            icon: Zap,
            color: 'bg-gradient-to-r from-emerald-500 to-green-600',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'forest' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🧭' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'treasures', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'map_revealed', value: 0 } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '💎' } },
                { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '💎' } },
                { id: 'p3', type: CommandType.SPAWN_ITEM, params: { text: '💎' } },
                { id: 'p4', type: CommandType.SPAWN_ITEM, params: { text: '🗺️' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -4 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 4 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -4 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 4 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'tr1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '💎' } },
                { id: 'tr2', type: CommandType.CHANGE_VAR, params: { varName: 'treasures', value: 1 } },
                { id: 'tr3', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: 'tr4', type: CommandType.SAY, params: { text: '💎 Treasure found!' } },
                { id: 'tr5', type: CommandType.END_IF, params: {} },
                { id: 'mp1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🗺️' } },
                { id: 'mp2', type: CommandType.SET_VAR, params: { varName: 'map_revealed', value: 1 } },
                { id: 'mp3', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'mp4', type: CommandType.SAY, params: { text: '🗺️ Map revealed!' } },
                { id: 'mp5', type: CommandType.END_IF, params: {} },
                { id: 'wc1', type: CommandType.IF, params: { condition: 'GREATER' } },
                { id: 'wc2', type: CommandType.WIN_GAME, params: {} },
                { id: 'wc3', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
                { id: 'wc4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_adventure_story',
            mode: AppMode.GAME,
            name: 'Story Adventure',
            description: 'A branching narrative with choices!',
            icon: Zap,
            color: 'bg-gradient-to-r from-violet-500 to-purple-600',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '📖' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'choices_made', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'ending', value: 0 } },
                { id: 'c1', type: CommandType.SAY, params: { text: 'You wake up in a mysterious forest...' } },
                { id: 'c2', type: CommandType.WAIT, params: { value: 3 } },
                { id: 'c3', type: CommandType.SAY, params: { text: 'A fork in the road appears.' } },
                { id: 'c4', type: CommandType.WAIT, params: { value: 2 } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '📜' } },
                { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '📜' } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '🚪' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -4 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 4 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -4 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 4 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'ch1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '📜' } },
                { id: 'ch2', type: CommandType.CHANGE_VAR, params: { varName: 'choices_made', value: 1 } },
                { id: 'ch3', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: 'ch4', type: CommandType.SAY, params: { text: '📜 You found a scroll!' } },
                { id: 'ch5', type: CommandType.END_IF, params: {} },
                { id: 'en1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🚪' } },
                { id: 'en2', type: CommandType.SET_VAR, params: { varName: 'ending', value: 1 } },
                { id: 'en3', type: CommandType.WIN_GAME, params: {} },
                { id: 'en4', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
                { id: 'en5', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_adventure_openworld',
            mode: AppMode.GAME,
            name: 'Open World Adventure',
            description: 'Free-roam a massive world with quests!',
            icon: Zap,
            color: 'bg-gradient-to-r from-sky-500 to-blue-600',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'forest' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🧑‍🌾' } },
                { id: 's3', type: CommandType.SET_WEATHER, params: { text: 'rain' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'quests_done', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'gold', value: 0 } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '🪙' } },
                { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '🪙' } },
                { id: 'p3', type: CommandType.SPAWN_ITEM, params: { text: '🪙' } },
                { id: 'p4', type: CommandType.SPAWN_ITEM, params: { text: '❤️' } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '🧙' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '🧝' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -4 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 4 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -4 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 4 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'gd1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🪙' } },
                { id: 'gd2', type: CommandType.CHANGE_VAR, params: { varName: 'gold', value: 1 } },
                { id: 'gd3', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: 'gd4', type: CommandType.END_IF, params: {} },
                { id: 'qt1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🧙' } },
                { id: 'qt2', type: CommandType.CHANGE_VAR, params: { varName: 'quests_done', value: 1 } },
                { id: 'qt3', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'qt4', type: CommandType.SAY, params: { text: '📜 Quest complete!' } },
                { id: 'qt5', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_adventure_fantasy',
            mode: AppMode.GAME,
            name: 'Fantasy Adventure',
            description: 'Medieval fantasy with magic and dragons!',
            icon: Zap,
            color: 'bg-gradient-to-r from-purple-500 to-pink-500',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'forest' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🧙' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'mana', value: 100 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '🐉' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '👻' } },
                { id: 'e3', type: CommandType.SPAWN_ENEMY, params: { text: '🧟' } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '🧪' } },
                { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '❤️' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -4 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 4 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -4 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 4 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'ca1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'ca2', type: CommandType.SHOOT, params: { text: '✨' } },
                { id: 'ca3', type: CommandType.CHANGE_VAR, params: { varName: 'mana', value: -10 } },
                { id: 'ca4', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'ca5', type: CommandType.END_IF, params: {} },
                { id: 'mp1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🧪' } },
                { id: 'mp2', type: CommandType.CHANGE_VAR, params: { varName: 'mana', value: 25 } },
                { id: 'mp3', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'mp4', type: CommandType.END_IF, params: {} },
                { id: 'kb1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🐉' } },
                { id: 'kb2', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 50 } },
                { id: 'kb3', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'kb4', type: CommandType.SPAWN_PARTICLES, params: { value: 10 } },
                { id: 'kb5', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_adventure_pirate',
            mode: AppMode.GAME,
            name: 'Pirate Adventure',
            description: 'Sail the seas and find treasure!',
            icon: Zap,
            color: 'bg-gradient-to-r from-amber-600 to-orange-700',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🏴‍☠️' } },
                { id: 's3', type: CommandType.SET_WEATHER, params: { text: 'rain' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'gold', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'treasure_map', value: 0 } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '🪙' } },
                { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '🪙' } },
                { id: 'p3', type: CommandType.SPAWN_ITEM, params: { text: '🗺️' } },
                { id: 'p4', type: CommandType.SPAWN_ITEM, params: { text: '💎' } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '🦈' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '🐙' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -4 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 4 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -4 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 4 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'gd1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🪙' } },
                { id: 'gd2', type: CommandType.CHANGE_VAR, params: { varName: 'gold', value: 1 } },
                { id: 'gd3', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: 'gd4', type: CommandType.END_IF, params: {} },
                { id: 'mp1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🗺️' } },
                { id: 'mp2', type: CommandType.SET_VAR, params: { varName: 'treasure_map', value: 1 } },
                { id: 'mp3', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'mp4', type: CommandType.SAY, params: { text: '🗺️ Treasure map found!' } },
                { id: 'mp5', type: CommandType.END_IF, params: {} },
                { id: 'tr1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '💎' } },
                { id: 'tr2', type: CommandType.CHANGE_VAR, params: { varName: 'gold', value: 10 } },
                { id: 'tr3', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: 'tr4', type: CommandType.SAY, params: { text: '💎 TREASURE!' } },
                { id: 'tr5', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_adventure_treasure',
            mode: AppMode.GAME,
            name: 'Treasure Hunt',
            description: 'Find all the hidden treasures!',
            icon: Zap,
            color: 'bg-gradient-to-r from-yellow-500 to-amber-500',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🗺️' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'treasures', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'hints', value: 3 } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '💎' } },
                { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '💎' } },
                { id: 'p3', type: CommandType.SPAWN_ITEM, params: { text: '💎' } },
                { id: 'p4', type: CommandType.SPAWN_ITEM, params: { text: '💎' } },
                { id: 'p5', type: CommandType.SPAWN_ITEM, params: { text: '💎' } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '陷阱' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '陷阱' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -4 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 4 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -4 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 4 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'tr1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '💎' } },
                { id: 'tr2', type: CommandType.CHANGE_VAR, params: { varName: 'treasures', value: 1 } },
                { id: 'tr3', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: 'tr4', type: CommandType.SAY, params: { text: '💎 Treasure found!' } },
                { id: 'tr5', type: CommandType.END_IF, params: {} },
                { id: 'wc1', type: CommandType.IF, params: { condition: 'GREATER' } },
                { id: 'wc2', type: CommandType.WIN_GAME, params: {} },
                { id: 'wc3', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
                { id: 'wc4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_adventure_detective',
            mode: AppMode.GAME,
            name: 'Detective Adventure',
            description: 'Solve mysteries by finding clues!',
            icon: Zap,
            color: 'bg-gradient-to-r from-slate-600 to-slate-800',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🕵️' } },
                { id: 's3', type: CommandType.SET_WEATHER, params: { text: 'fog' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'clues_found', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'suspects', value: 0 } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '🔍' } },
                { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '🔍' } },
                { id: 'p3', type: CommandType.SPAWN_ITEM, params: { text: '🔍' } },
                { id: 'p4', type: CommandType.SPAWN_ITEM, params: { text: '📋' } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '👤' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '👤' } },
                { id: 'e3', type: CommandType.SPAWN_ENEMY, params: { text: '👤' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -3 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 3 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -3 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 3 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'cl1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🔍' } },
                { id: 'cl2', type: CommandType.CHANGE_VAR, params: { varName: 'clues_found', value: 1 } },
                { id: 'cl3', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: 'cl4', type: CommandType.SAY, params: { text: '🔍 Clue found!' } },
                { id: 'cl5', type: CommandType.END_IF, params: {} },
                { id: 'su1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '👤' } },
                { id: 'su2', type: CommandType.CHANGE_VAR, params: { varName: 'suspects', value: 1 } },
                { id: 'su3', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'su4', type: CommandType.SAY, params: { text: '👤 Suspect identified!' } },
                { id: 'su5', type: CommandType.END_IF, params: {} },
                { id: 'wc1', type: CommandType.IF, params: { condition: 'GREATER' } },
                { id: 'wc2', type: CommandType.WIN_GAME, params: {} },
                { id: 'wc3', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
                { id: 'wc4', type: CommandType.SAY, params: { text: '🎉 Case solved!' } },
                { id: 'wc5', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_space_exploration',
            mode: AppMode.GAME,
            name: '🌌 Space Exploration',
            description: 'Explore the infinite universe!',
            icon: Zap,
            color: 'bg-gradient-to-r from-indigo-600 to-purple-700',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'space' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🚀' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'planets_found', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'fuel', value: 100 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '🪐' } },
                { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '🌍' } },
                { id: 'p3', type: CommandType.SPAWN_ITEM, params: { text: '⛽' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -5 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 5 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -5 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 5 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'pl1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🪐' } },
                { id: 'pl2', type: CommandType.CHANGE_VAR, params: { varName: 'planets_found', value: 1 } },
                { id: 'pl3', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 50 } },
                { id: 'pl4', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: 'pl5', type: CommandType.SAY, params: { text: '🪐 Planet discovered!' } },
                { id: 'pl6', type: CommandType.END_IF, params: {} },
                { id: 'fu1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '⛽' } },
                { id: 'fu2', type: CommandType.CHANGE_VAR, params: { varName: 'fuel', value: 25 } },
                { id: 'fu3', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'fu4', type: CommandType.END_IF, params: {} },
                { id: 'wc1', type: CommandType.IF, params: { condition: 'GREATER' } },
                { id: 'wc2', type: CommandType.WIN_GAME, params: {} },
                { id: 'wc3', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
                { id: 'wc4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_space_colony',
            mode: AppMode.GAME,
            name: '🏠 Colony Builder',
            description: 'Build and manage a space colony!',
            icon: Zap,
            color: 'bg-gradient-to-r from-emerald-500 to-teal-600',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'space' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🏠' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'resources', value: 50 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'population', value: 10 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'happiness', value: 100 } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '🪨' } },
                { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '🪨' } },
                { id: 'p3', type: CommandType.SPAWN_ITEM, params: { text: '🪙' } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '☄️' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -4 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 4 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -4 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 4 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'rs1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🪨' } },
                { id: 'rs2', type: CommandType.CHANGE_VAR, params: { varName: 'resources', value: 10 } },
                { id: 'rs3', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: 'rs4', type: CommandType.END_IF, params: {} },
                { id: 'go1', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'health', value: 0 } },
                { id: 'go2', type: CommandType.GAME_OVER, params: {} },
                { id: 'go3', type: CommandType.PLAY_SOUND, params: { text: 'death' } },
                { id: 'go4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_space_rts',
            mode: AppMode.GAME,
            name: '⚔️ Space RTS',
            description: 'Command your fleet in real-time strategy!',
            icon: Zap,
            color: 'bg-gradient-to-r from-red-500 to-red-700',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'space' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '⚔️' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'credits', value: 100 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'ships', value: 5 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '🛸' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '🛸' } },
                { id: 'e3', type: CommandType.SPAWN_ENEMY, params: { text: '🛸' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -5 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 5 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -5 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 5 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'sh1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'sh2', type: CommandType.SHOOT, params: { text: '🚀' } },
                { id: 'sh3', type: CommandType.PLAY_SOUND, params: { text: 'laser' } },
                { id: 'sh4', type: CommandType.END_IF, params: {} },
                { id: 'kb1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🛸' } },
                { id: 'kb2', type: CommandType.CHANGE_VAR, params: { varName: 'credits', value: 20 } },
                { id: 'kb3', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
                { id: 'kb4', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'kb5', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_space_survival',
            mode: AppMode.GAME,
            name: '🌌 Space Survival',
            description: 'Survive in the cold void of space!',
            icon: Zap,
            color: 'bg-gradient-to-r from-slate-700 to-slate-900',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'space' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🚀' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'oxygen', value: 100 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'health', value: 100 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '☄️' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '☄️' } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '💨' } },
                { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '❤️' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -5 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 5 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -5 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 5 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'ox1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '💨' } },
                { id: 'ox2', type: CommandType.CHANGE_VAR, params: { varName: 'oxygen', value: 25 } },
                { id: 'ox3', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'ox4', type: CommandType.END_IF, params: {} },
                { id: 'hp1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '❤️' } },
                { id: 'hp2', type: CommandType.CHANGE_VAR, params: { varName: 'health', value: 25 } },
                { id: 'hp3', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'hp4', type: CommandType.END_IF, params: {} },
                { id: 'go1', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'health', value: 0 } },
                { id: 'go2', type: CommandType.GAME_OVER, params: {} },
                { id: 'go3', type: CommandType.PLAY_SOUND, params: { text: 'death' } },
                { id: 'go4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_space_trading',
            mode: AppMode.GAME,
            name: '💰 Galaxy Trading',
            description: 'Trade goods across the galaxy!',
            icon: Zap,
            color: 'bg-gradient-to-r from-yellow-500 to-amber-600',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'space' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🚀' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'credits', value: 100 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'cargo', value: 0 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'trades', value: 0 } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '📦' } },
                { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '📦' } },
                { id: 'p3', type: CommandType.SPAWN_ITEM, params: { text: '💰' } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '🏴‍☠️' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -4 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 4 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -4 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 4 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'cp1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '📦' } },
                { id: 'cp2', type: CommandType.CHANGE_VAR, params: { varName: 'cargo', value: 1 } },
                { id: 'cp3', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: 'cp4', type: CommandType.SAY, params: { text: '📦 Cargo picked up!' } },
                { id: 'cp5', type: CommandType.END_IF, params: {} },
                { id: 'tr1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '💰' } },
                { id: 'tr2', type: CommandType.CHANGE_VAR, params: { varName: 'credits', value: 50 } },
                { id: 'tr3', type: CommandType.CHANGE_VAR, params: { varName: 'trades', value: 1 } },
                { id: 'tr4', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: 'tr5', type: CommandType.SAY, params: { text: '💰 Trade complete!' } },
                { id: 'tr6', type: CommandType.END_IF, params: {} },
                { id: 'wc1', type: CommandType.IF, params: { condition: 'GREATER' } },
                { id: 'wc2', type: CommandType.WIN_GAME, params: {} },
                { id: 'wc3', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
                { id: 'wc4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_scifi_cyberpunk',
            mode: AppMode.GAME,
            name: '🌃 Cyberpunk',
            description: 'Neon-lit cyberpunk action adventure!',
            icon: Zap,
            color: 'bg-gradient-to-r from-cyan-400 to-pink-500',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🤖' } },
                { id: 's3', type: CommandType.SET_WEATHER, params: { text: 'rain' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'health', value: 100 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'credits', value: 0 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'hacks', value: 10 } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '🤖' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '🦾' } },
                { id: 'e3', type: CommandType.SPAWN_ENEMY, params: { text: '🦿' } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '💰' } },
                { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '💰' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -5 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 5 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -5 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 5 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'sh1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'sh2', type: CommandType.SHOOT, params: { text: '⚡' } },
                { id: 'sh3', type: CommandType.CHANGE_VAR, params: { varName: 'hacks', value: -1 } },
                { id: 'sh4', type: CommandType.PLAY_SOUND, params: { text: 'laser' } },
                { id: 'sh5', type: CommandType.END_IF, params: {} },
                { id: 'kb1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🤖' } },
                { id: 'kb2', type: CommandType.CHANGE_VAR, params: { varName: 'credits', value: 10 } },
                { id: 'kb3', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'kb4', type: CommandType.END_IF, params: {} },
                { id: 'mn1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '💰' } },
                { id: 'mn2', type: CommandType.CHANGE_VAR, params: { varName: 'credits', value: 25 } },
                { id: 'mn3', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: 'mn4', type: CommandType.END_IF, params: {} },
                { id: 'go1', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'health', value: 0 } },
                { id: 'go2', type: CommandType.GAME_OVER, params: {} },
                { id: 'go3', type: CommandType.PLAY_SOUND, params: { text: 'death' } },
                { id: 'go4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_scifi_alien',
            mode: AppMode.GAME,
            name: '👽 Alien Invasion',
            description: 'Defend Earth from alien invaders!',
            icon: Zap,
            color: 'bg-gradient-to-r from-green-500 to-green-700',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'space' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🛸' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'health', value: 100 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'wave', value: 1 } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '👽' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '👽' } },
                { id: 'e3', type: CommandType.SPAWN_ENEMY, params: { text: '👾' } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '❤️' } },
                { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '⚡' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -6 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 6 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -6 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 6 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'sh1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'sh2', type: CommandType.SHOOT, params: { text: '🚀' } },
                { id: 'sh3', type: CommandType.PLAY_SOUND, params: { text: 'laser' } },
                { id: 'sh4', type: CommandType.END_IF, params: {} },
                { id: 'kb1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '👽' } },
                { id: 'kb2', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 15 } },
                { id: 'kb3', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'kb4', type: CommandType.SPAWN_PARTICLES, params: { value: 8 } },
                { id: 'kb5', type: CommandType.END_IF, params: {} },
                { id: 'hp1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '❤️' } },
                { id: 'hp2', type: CommandType.CHANGE_VAR, params: { varName: 'health', value: 25 } },
                { id: 'hp3', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'hp4', type: CommandType.END_IF, params: {} },
                { id: 'ws1', type: CommandType.IF, params: { condition: 'GREATER' } },
                { id: 'ws2', type: CommandType.CHANGE_VAR, params: { varName: 'wave', value: 1 } },
                { id: 'ws3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'ws4', type: CommandType.SAY, params: { text: '🌊 WAVE ' } },
                { id: 'ws5', type: CommandType.SPAWN_ENEMY, params: { text: '👽' } },
                { id: 'ws6', type: CommandType.SPAWN_ENEMY, params: { text: '👽' } },
                { id: 'ws7', type: CommandType.SPAWN_ENEMY, params: { text: '👾' } },
                { id: 'ws8', type: CommandType.END_IF, params: {} },
                { id: 'go1', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'health', value: 0 } },
                { id: 'go2', type: CommandType.GAME_OVER, params: {} },
                { id: 'go3', type: CommandType.PLAY_SOUND, params: { text: 'death' } },
                { id: 'go4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_scifi_time',
            mode: AppMode.GAME,
            name: '⏰ Time Travel',
            description: 'Travel through time and change history!',
            icon: Zap,
            color: 'bg-gradient-to-r from-violet-500 to-indigo-600',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '⏰' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'time_energy', value: 100 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'paradoxes', value: 0 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '⏳' } },
                { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '⏳' } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '🦴' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '🦴' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -5 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 5 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -5 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 5 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'sh1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'sh2', type: CommandType.SHOOT, params: { text: '⏳' } },
                { id: 'sh3', type: CommandType.CHANGE_VAR, params: { varName: 'time_energy', value: -10 } },
                { id: 'sh4', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'sh5', type: CommandType.SAY, params: { text: '⏰ TIME WARP!' } },
                { id: 'sh6', type: CommandType.END_IF, params: {} },
                { id: 'tp1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '⏳' } },
                { id: 'tp2', type: CommandType.CHANGE_VAR, params: { varName: 'time_energy', value: 25 } },
                { id: 'tp3', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'tp4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_scifi_robot',
            mode: AppMode.GAME,
            name: '🤖 Robot Wars',
            description: 'Battle robots in the arena!',
            icon: Zap,
            color: 'bg-gradient-to-r from-slate-500 to-slate-700',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🤖' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'health', value: 150 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'energy', value: 100 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '🤖' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '🦾' } },
                { id: 'e3', type: CommandType.SPAWN_ENEMY, params: { text: '🦿' } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '🔋' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -4 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 4 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -4 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 4 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'sh1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'sh2', type: CommandType.SHOOT, params: { text: '⚡' } },
                { id: 'sh3', type: CommandType.CHANGE_VAR, params: { varName: 'energy', value: -10 } },
                { id: 'sh4', type: CommandType.PLAY_SOUND, params: { text: 'laser' } },
                { id: 'sh5', type: CommandType.END_IF, params: {} },
                { id: 'kb1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🤖' } },
                { id: 'kb2', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 20 } },
                { id: 'kb3', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'kb4', type: CommandType.SPAWN_PARTICLES, params: { value: 10 } },
                { id: 'kb5', type: CommandType.END_IF, params: {} },
                { id: 'en1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🔋' } },
                { id: 'en2', type: CommandType.CHANGE_VAR, params: { varName: 'energy', value: 25 } },
                { id: 'en3', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'en4', type: CommandType.END_IF, params: {} },
                { id: 'go1', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'health', value: 0 } },
                { id: 'go2', type: CommandType.GAME_OVER, params: {} },
                { id: 'go3', type: CommandType.PLAY_SOUND, params: { text: 'death' } },
                { id: 'go4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_scifi_mech',
            mode: AppMode.GAME,
            name: '🦾 Mech Combat',
            description: 'Pilot a giant mech in futuristic warfare!',
            icon: Zap,
            color: 'bg-gradient-to-r from-blue-500 to-cyan-600',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🦾' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'health', value: 300 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'energy', value: 100 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '🤖' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '🤖' } },
                { id: 'e3', type: CommandType.SPAWN_ENEMY, params: { text: '🤖' } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '🔋' } },
                { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '❤️' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -3 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 3 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -3 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 3 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'sh1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'sh2', type: CommandType.SHOOT, params: { text: '🚀' } },
                { id: 'sh3', type: CommandType.CHANGE_VAR, params: { varName: 'energy', value: -5 } },
                { id: 'sh4', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'sh5', type: CommandType.SPAWN_PARTICLES, params: { value: 10 } },
                { id: 'sh6', type: CommandType.END_IF, params: {} },
                { id: 'kb1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🤖' } },
                { id: 'kb2', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 25 } },
                { id: 'kb3', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'kb4', type: CommandType.END_IF, params: {} },
                { id: 'en1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🔋' } },
                { id: 'en2', type: CommandType.CHANGE_VAR, params: { varName: 'energy', value: 30 } },
                { id: 'en3', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'en4', type: CommandType.END_IF, params: {} },
                { id: 'hp1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '❤️' } },
                { id: 'hp2', type: CommandType.CHANGE_VAR, params: { varName: 'health', value: 50 } },
                { id: 'hp3', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'hp4', type: CommandType.END_IF, params: {} },
                { id: 'go1', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'health', value: 0 } },
                { id: 'go2', type: CommandType.GAME_OVER, params: {} },
                { id: 'go3', type: CommandType.PLAY_SOUND, params: { text: 'death' } },
                { id: 'go4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        { id: 'tpl_adventure_point_click', mode: AppMode.GAME, name: 'Point & Click Mystery', description: 'Solve puzzles by clicking and examining the world!', icon: Eye, color: 'bg-gradient-to-r from-indigo-500 to-purple-600', commands: [
            { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'stone_floor' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🔍' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'clues_found', value: 0 } }, { id: 'c4', type: CommandType.SET_VAR, params: { varName: 'puzzles_solved', value: 0 } }, { id: 'c5', type: CommandType.ADD_QUEST, params: { text: 'Find the Lost Treasure' } }, { id: 'c6', type: CommandType.FOREVER, params: {} }, { id: 'c7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } }, { id: 'c8', type: CommandType.MOVE_X, params: { value: -3 } }, { id: 'c9', type: CommandType.END_IF, params: {} }, { id: 'c10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } }, { id: 'c11', type: CommandType.MOVE_X, params: { value: 3 } }, { id: 'c12', type: CommandType.END_IF, params: {} }, { id: 'c13', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c14', type: CommandType.EXAMINE, params: { text: 'nearby' } }, { id: 'c15', type: CommandType.CHANGE_VAR, params: { varName: 'clues_found', value: 1 } }, { id: 'c16', type: CommandType.END_IF, params: {} }, { id: 'c17', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 33 } }, { id: 'c18', type: CommandType.TRIGGER_PUZZLE, params: { text: 'lock' } }, { id: 'c19', type: CommandType.END_IF, params: {} }, { id: 'c20', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_adventure_open_world', mode: AppMode.GAME, name: 'Open World Adventure', description: 'Explore a vast world with quests and secrets!', icon: Globe, color: 'bg-gradient-to-r from-green-500 to-emerald-600', commands: [
            { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'grass' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🌍' } }, { id: 'c3', type: CommandType.SET_CAMERA, params: { condition: 'true' } }, { id: 'c4', type: CommandType.SET_VAR, params: { varName: 'quests_complete', value: 0 } }, { id: 'c5', type: CommandType.ADD_QUEST, params: { text: 'Main Quest' } }, { id: 'c6', type: CommandType.FOREVER, params: {} }, { id: 'c7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } }, { id: 'c8', type: CommandType.MOVE_X, params: { value: -5 } }, { id: 'c9', type: CommandType.END_IF, params: {} }, { id: 'c10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } }, { id: 'c11', type: CommandType.MOVE_X, params: { value: 5 } }, { id: 'c12', type: CommandType.END_IF, params: {} }, { id: 'c13', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } }, { id: 'c14', type: CommandType.MOVE_Y, params: { value: -5 } }, { id: 'c15', type: CommandType.END_IF, params: {} }, { id: 'c16', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } }, { id: 'c17', type: CommandType.MOVE_Y, params: { value: 5 } }, { id: 'c18', type: CommandType.END_IF, params: {} }, { id: 'c19', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_adventure_ghost_hunter', mode: AppMode.GAME, name: 'Ghost Hunter', description: 'Track and capture ghosts in haunted locations!', icon: Ghost, color: 'bg-gradient-to-r from-slate-600 to-purple-700', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'stone_floor' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '👻' } }, { id: 'c3', type: CommandType.SET_WEATHER, params: { text: 'rain' } }, { id: 'c4', type: CommandType.SET_VAR, params: { varName: 'ghosts_caught', value: 0 } }, { id: 'c5', type: CommandType.SPAWN_ENEMY, params: { text: '👻' } }, { id: 'c6', type: CommandType.SPAWN_ENEMY, params: { text: '👻' } }, { id: 'c7', type: CommandType.FOREVER, params: {} }, { id: 'c8', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c9', type: CommandType.SHOOT, params: { text: '✨' } }, { id: 'c10', type: CommandType.CHANGE_VAR, params: { varName: 'ghosts_caught', value: 1 } }, { id: 'c11', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } }, { id: 'c12', type: CommandType.END_IF, params: {} }, { id: 'c13', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_adventure_caving', mode: AppMode.GAME, name: 'Deep Caving', description: 'Explore underground caves with a torch!', icon: MapPin, color: 'bg-gradient-to-r from-stone-600 to-stone-800', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'stone_floor' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '⛏️' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'gems', value: 0 } }, { id: 'c4', type: CommandType.SPAWN_ITEM, params: { text: '💎' } }, { id: 'c5', type: CommandType.FOREVER, params: {} }, { id: 'c6', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c7', type: CommandType.GATHER, params: { text: 'gem', value: 1 } }, { id: 'c8', type: CommandType.CHANGE_VAR, params: { varName: 'gems', value: 1 } }, { id: 'c9', type: CommandType.PLAY_SOUND, params: { text: 'coin' } }, { id: 'c10', type: CommandType.END_IF, params: {} }, { id: 'c11', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 33 } }, { id: 'c12', type: CommandType.PLACE_TORCH, params: {} }, { id: 'c13', type: CommandType.END_IF, params: {} }, { id: 'c14', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_adventure_pixel_quest', mode: AppMode.GAME, name: 'Pixel Art Quest', description: 'A charming pixel art adventure!', icon: Sparkles, color: 'bg-gradient-to-r from-pink-400 to-purple-500', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'grass' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🧑‍🎨' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'paintings', value: 0 } }, { id: 'c4', type: CommandType.ADD_QUEST, params: { text: 'Collect all paintings' } }, { id: 'c5', type: CommandType.SPAWN_ITEM, params: { text: '🎨' } }, { id: 'c6', type: CommandType.SPAWN_ITEM, params: { text: '🎨' } }, { id: 'c7', type: CommandType.FOREVER, params: {} }, { id: 'c8', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c9', type: CommandType.EXAMINE, params: { text: 'painting' } }, { id: 'c10', type: CommandType.CHANGE_VAR, params: { varName: 'paintings', value: 1 } }, { id: 'c11', type: CommandType.PLAY_SOUND, params: { text: 'coin' } }, { id: 'c12', type: CommandType.END_IF, params: {} }, { id: 'c13', type: CommandType.END_FOREVER, params: {} }
        ]},
];
