import { AppMode, CommandType, CommandBlock } from '../../types';
import { Swords, Shield, Music, Pencil, Grid3x3 } from 'lucide-react';

export const arcadeTemplates: {
    id: string;
    mode: AppMode;
    name: string;
    description: string;
    icon: typeof Swords;
    color: string;
    commands: CommandBlock[];
}[] = [
    {
        id: 'tpl_arcade_fighter',
        mode: AppMode.GAME,
        name: 'Fighting Arena',
        description: '1v1 combat with combos, blocks, and special moves!',
        icon: Swords,
        color: 'bg-gradient-to-r from-red-600 to-orange-500',
        commands: [
            { id: 'fa1', type: CommandType.SET_SCENE, params: { text: 'dark' } },
            { id: 'fa2', type: CommandType.SET_EMOJI, params: { text: '🥊' } },
            { id: 'fa3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
            { id: 'fa4', type: CommandType.SET_VAR, params: { varName: 'combo', value: 0 } },
            { id: 'fa5', type: CommandType.SET_VAR, params: { varName: 'health', value: 100 } },
            { id: 'fa6', type: CommandType.SPAWN_ENEMY, params: { text: '🥊' } },
            { id: 'fa7', type: CommandType.SPAWN_ENEMY, params: { text: '🤛' } },
            { id: 'fa8', type: CommandType.FOREVER, params: {} },
            { id: 'fa9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'fa10', type: CommandType.MOVE_X, params: { value: -5 } },
            { id: 'fa11', type: CommandType.END_IF, params: {} },
            { id: 'fa12', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'fa13', type: CommandType.MOVE_X, params: { value: 5 } },
            { id: 'fa14', type: CommandType.END_IF, params: {} },
            { id: 'fa15', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'fa16', type: CommandType.SWING_WEAPON, params: { text: '👊', value: 15 } },
            { id: 'fa17', type: CommandType.CHANGE_VAR, params: { varName: 'combo', value: 1 } },
            { id: 'fa18', type: CommandType.PLAY_SOUND, params: { text: 'attack' } },
            { id: 'fa19', type: CommandType.END_IF, params: {} },
            { id: 'fa20', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 33 } },
            { id: 'fa21', type: CommandType.COMBO_ATTACK, params: { value: 3 } },
            { id: 'fa22', type: CommandType.CHANGE_VAR, params: { varName: 'combo', value: 3 } },
            { id: 'fa23', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
            { id: 'fa24', type: CommandType.END_IF, params: {} },
            { id: 'fa25', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } },
            { id: 'fa26', type: CommandType.BLOCK_ATTACK, params: {} },
            { id: 'fa27', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
            { id: 'fa28', type: CommandType.END_IF, params: {} },
            { id: 'fa29', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'combo', value: 10 } },
            { id: 'fa30', type: CommandType.SPECIAL_MOVE, params: {} },
            { id: 'fa31', type: CommandType.SCREEN_SHAKE, params: { value: 0.5 } },
            { id: 'fa32', type: CommandType.CHANGE_VAR, params: { varName: 'combo', value: -10 } },
            { id: 'fa33', type: CommandType.END_IF, params: {} },
            { id: 'fa34', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'score', value: 200 } },
            { id: 'fa35', type: CommandType.WIN_GAME, params: {} },
            { id: 'fa36', type: CommandType.END_IF, params: {} },
            { id: 'fa37', type: CommandType.END_FOREVER, params: {} },
        ],
    },
    {
        id: 'tpl_arcade_tower_defense',
        mode: AppMode.GAME,
        name: 'Tower Defense',
        description: 'Defend against waves of enemies with strategic placement!',
        icon: Shield,
        color: 'bg-gradient-to-r from-green-600 to-emerald-500',
        commands: [
            { id: 'td1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 'td2', type: CommandType.SET_EMOJI, params: { text: '🏰' } },
            { id: 'td3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
            { id: 'td4', type: CommandType.SET_VAR, params: { varName: 'health', value: 100 } },
            { id: 'td5', type: CommandType.SET_VAR, params: { varName: 'wave', value: 1 } },
            { id: 'td6', type: CommandType.SPAWN_ENEMY, params: { text: '👾' } },
            { id: 'td7', type: CommandType.SPAWN_ENEMY, params: { text: '👾' } },
            { id: 'td8', type: CommandType.SPAWN_ENEMY, params: { text: '👾' } },
            { id: 'td9', type: CommandType.FOREVER, params: {} },
            { id: 'td10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'td11', type: CommandType.MOVE_X, params: { value: -3 } },
            { id: 'td12', type: CommandType.END_IF, params: {} },
            { id: 'td13', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'td14', type: CommandType.MOVE_X, params: { value: 3 } },
            { id: 'td15', type: CommandType.END_IF, params: {} },
            { id: 'td16', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'td17', type: CommandType.SPAWN_ITEM, params: { text: '🗼' } },
            { id: 'td18', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 5 } },
            { id: 'td19', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'td20', type: CommandType.END_IF, params: {} },
            { id: 'td21', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 33 } },
            { id: 'td22', type: CommandType.SPAWN_PARTICLES, params: { value: 10 } },
            { id: 'td23', type: CommandType.CHANGE_VAR, params: { varName: 'wave', value: 1 } },
            { id: 'td24', type: CommandType.SPAWN_ENEMY, params: { text: '👺' } },
            { id: 'td25', type: CommandType.SPAWN_ENEMY, params: { text: '💀' } },
            { id: 'td26', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
            { id: 'td27', type: CommandType.END_IF, params: {} },
            { id: 'td28', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'score', value: 300 } },
            { id: 'td29', type: CommandType.WIN_GAME, params: {} },
            { id: 'td30', type: CommandType.END_IF, params: {} },
            { id: 'td31', type: CommandType.END_FOREVER, params: {} },
        ],
    },
    {
        id: 'tpl_arcade_rhythm',
        mode: AppMode.GAME,
        name: 'Rhythm Beats',
        description: 'Hit notes on the beat to score points!',
        icon: Music,
        color: 'bg-gradient-to-r from-purple-600 to-pink-500',
        commands: [
            { id: 'rb1', type: CommandType.SET_SCENE, params: { text: 'space' } },
            { id: 'rb2', type: CommandType.SET_EMOJI, params: { text: '🎵' } },
            { id: 'rb3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
            { id: 'rb4', type: CommandType.SET_VAR, params: { varName: 'streak', value: 0 } },
            { id: 'rb5', type: CommandType.SPAWN_ITEM, params: { text: '🎶' } },
            { id: 'rb6', type: CommandType.SPAWN_ITEM, params: { text: '🎵' } },
            { id: 'rb7', type: CommandType.SPAWN_ITEM, params: { text: '🎸' } },
            { id: 'rb8', type: CommandType.FOREVER, params: {} },
            { id: 'rb9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'rb10', type: CommandType.MOVE_X, params: { value: -8 } },
            { id: 'rb11', type: CommandType.PLAY_SOUND, params: { text: 'laser' } },
            { id: 'rb12', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
            { id: 'rb13', type: CommandType.CHANGE_VAR, params: { varName: 'streak', value: 1 } },
            { id: 'rb14', type: CommandType.END_IF, params: {} },
            { id: 'rb15', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'rb16', type: CommandType.MOVE_X, params: { value: 8 } },
            { id: 'rb17', type: CommandType.PLAY_SOUND, params: { text: 'laser' } },
            { id: 'rb18', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
            { id: 'rb19', type: CommandType.CHANGE_VAR, params: { varName: 'streak', value: 1 } },
            { id: 'rb20', type: CommandType.END_IF, params: {} },
            { id: 'rb21', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'rb22', type: CommandType.SPAWN_PARTICLES, params: { value: 5 } },
            { id: 'rb23', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
            { id: 'rb24', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 25 } },
            { id: 'rb25', type: CommandType.END_IF, params: {} },
            { id: 'rb26', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'streak', value: 5 } },
            { id: 'rb27', type: CommandType.SPECIAL_MOVE, params: {} },
            { id: 'rb28', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 50 } },
            { id: 'rb29', type: CommandType.CHANGE_VAR, params: { varName: 'streak', value: -5 } },
            { id: 'rb30', type: CommandType.END_IF, params: {} },
            { id: 'rb31', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'score', value: 500 } },
            { id: 'rb32', type: CommandType.WIN_GAME, params: {} },
            { id: 'rb33', type: CommandType.END_IF, params: {} },
            { id: 'rb34', type: CommandType.END_FOREVER, params: {} },
        ],
    },
    {
        id: 'tpl_arcade_drawing',
        mode: AppMode.GAME,
        name: 'Drawing Challenge',
        description: 'Draw shapes and patterns — score based on creativity!',
        icon: Pencil,
        color: 'bg-gradient-to-r from-yellow-500 to-amber-500',
        commands: [
            { id: 'dc1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 'dc2', type: CommandType.SET_EMOJI, params: { text: '✏️' } },
            { id: 'dc3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
            { id: 'dc4', type: CommandType.SET_VAR, params: { varName: 'shapes', value: 0 } },
            { id: 'dc5', type: CommandType.FOREVER, params: {} },
            { id: 'dc6', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'dc7', type: CommandType.MOVE_X, params: { value: -5 } },
            { id: 'dc8', type: CommandType.SPAWN_PARTICLES, params: { value: 2 } },
            { id: 'dc9', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 1 } },
            { id: 'dc10', type: CommandType.END_IF, params: {} },
            { id: 'dc11', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'dc12', type: CommandType.MOVE_X, params: { value: 5 } },
            { id: 'dc13', type: CommandType.SPAWN_PARTICLES, params: { value: 2 } },
            { id: 'dc14', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 1 } },
            { id: 'dc15', type: CommandType.END_IF, params: {} },
            { id: 'dc16', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
            { id: 'dc17', type: CommandType.MOVE_Y, params: { value: -5 } },
            { id: 'dc18', type: CommandType.SPAWN_PARTICLES, params: { value: 2 } },
            { id: 'dc19', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 1 } },
            { id: 'dc20', type: CommandType.END_IF, params: {} },
            { id: 'dc21', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
            { id: 'dc22', type: CommandType.MOVE_Y, params: { value: 5 } },
            { id: 'dc23', type: CommandType.SPAWN_PARTICLES, params: { value: 2 } },
            { id: 'dc24', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 1 } },
            { id: 'dc25', type: CommandType.END_IF, params: {} },
            { id: 'dc26', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'dc27', type: CommandType.SPAWN_ITEM, params: { text: '⭐' } },
            { id: 'dc28', type: CommandType.CHANGE_VAR, params: { varName: 'shapes', value: 1 } },
            { id: 'dc29', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
            { id: 'dc30', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'dc31', type: CommandType.END_IF, params: {} },
            { id: 'dc32', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'shapes', value: 10 } },
            { id: 'dc33', type: CommandType.WIN_GAME, params: {} },
            { id: 'dc34', type: CommandType.END_IF, params: {} },
            { id: 'dc35', type: CommandType.END_FOREVER, params: {} },
        ],
    },
    {
        id: 'tpl_arcade_music_maker',
        mode: AppMode.GAME,
        name: 'Music Maker',
        description: 'Compose beats with a grid sequencer — make music!',
        icon: Grid3x3,
        color: 'bg-gradient-to-r from-cyan-500 to-blue-600',
        commands: [
            { id: 'mm1', type: CommandType.SET_SCENE, params: { text: 'space' } },
            { id: 'mm2', type: CommandType.SET_EMOJI, params: { text: '🎤' } },
            { id: 'mm3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
            { id: 'mm4', type: CommandType.SET_VAR, params: { varName: 'beat', value: 0 } },
            { id: 'mm5', type: CommandType.SET_VAR, params: { varName: 'bpm', value: 120 } },
            { id: 'mm6', type: CommandType.FOREVER, params: {} },
            { id: 'mm7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'mm8', type: CommandType.PLAY_SOUND, params: { text: 'laser' } },
            { id: 'mm9', type: CommandType.SPAWN_PARTICLES, params: { value: 3 } },
            { id: 'mm10', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 5 } },
            { id: 'mm11', type: CommandType.CHANGE_VAR, params: { varName: 'beat', value: 1 } },
            { id: 'mm12', type: CommandType.END_IF, params: {} },
            { id: 'mm13', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'mm14', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
            { id: 'mm15', type: CommandType.SPAWN_PARTICLES, params: { value: 3 } },
            { id: 'mm16', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 5 } },
            { id: 'mm17', type: CommandType.CHANGE_VAR, params: { varName: 'beat', value: 1 } },
            { id: 'mm18', type: CommandType.END_IF, params: {} },
            { id: 'mm19', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'mm20', type: CommandType.PLAY_SOUND, params: { text: 'attack' } },
            { id: 'mm21', type: CommandType.SPAWN_PARTICLES, params: { value: 3 } },
            { id: 'mm22', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 5 } },
            { id: 'mm23', type: CommandType.CHANGE_VAR, params: { varName: 'beat', value: 1 } },
            { id: 'mm24', type: CommandType.END_IF, params: {} },
            { id: 'mm25', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 33 } },
            { id: 'mm26', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
            { id: 'mm27', type: CommandType.SPAWN_PARTICLES, params: { value: 3 } },
            { id: 'mm28', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 5 } },
            { id: 'mm29', type: CommandType.CHANGE_VAR, params: { varName: 'beat', value: 1 } },
            { id: 'mm30', type: CommandType.END_IF, params: {} },
            { id: 'mm31', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } },
            { id: 'mm32', type: CommandType.PLAY_SOUND, params: { text: 'dash' } },
            { id: 'mm33', type: CommandType.SPAWN_PARTICLES, params: { value: 3 } },
            { id: 'mm34', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 5 } },
            { id: 'mm35', type: CommandType.CHANGE_VAR, params: { varName: 'beat', value: 1 } },
            { id: 'mm36', type: CommandType.END_IF, params: {} },
            { id: 'mm37', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'beat', value: 8 } },
            { id: 'mm38', type: CommandType.SCREEN_SHAKE, params: { value: 0.3 } },
            { id: 'mm39', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 20 } },
            { id: 'mm40', type: CommandType.CHANGE_VAR, params: { varName: 'beat', value: -8 } },
            { id: 'mm41', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
            { id: 'mm42', type: CommandType.END_IF, params: {} },
            { id: 'mm43', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'score', value: 200 } },
            { id: 'mm44', type: CommandType.WIN_GAME, params: {} },
            { id: 'mm45', type: CommandType.END_IF, params: {} },
            { id: 'mm46', type: CommandType.END_FOREVER, params: {} },
        ],
    },
];
