import { AppMode, CommandType, CircuitComponent, CommandBlock } from '../../types';
import { LucideIcon, Swords, Bot, Ship, Skull, SwordsIcon, Rocket, Flame, ShieldCheck, Bug, User } from 'lucide-react';

export const battleTemplates: {
    id: string,
    mode: AppMode,
    name: string,
    description: string,
    icon: LucideIcon,
    color: string,
    commands: CommandBlock[],
    circuitComponents?: CircuitComponent[]
}[] = [
        {
            id: 'tpl_battle_shadow_fight',
            mode: AppMode.GAME,
            name: 'Shadow Fight',
            description: 'Dark-themed fighting game with shadow warriors!',
            icon: Swords,
            color: 'bg-gradient-to-r from-gray-800 to-purple-900',
            commands: [
                { id: 'sf1', type: CommandType.SET_SCENE, params: { text: 'dark' } },
                { id: 'sf2', type: CommandType.SET_EMOJI, params: { text: '🥷' } },
                { id: 'sf3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'sf4', type: CommandType.SET_VAR, params: { varName: 'shadowEnergy', value: 0 } },
                { id: 'sf5', type: CommandType.SPAWN_ENEMY, params: { text: '👤' } },
                { id: 'sf6', type: CommandType.SPAWN_ENEMY, params: { text: '🧛' } },
                { id: 'sf7', type: CommandType.FOREVER, params: {} },
                { id: 'sf8', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'sf9', type: CommandType.MOVE_X, params: { value: -5 } },
                { id: 'sf10', type: CommandType.END_IF, params: {} },
                { id: 'sf11', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'sf12', type: CommandType.MOVE_X, params: { value: 5 } },
                { id: 'sf13', type: CommandType.END_IF, params: {} },
                { id: 'sf14', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'sf15', type: CommandType.SWING_WEAPON, params: { text: '🗡️', value: 15 } },
                { id: 'sf16', type: CommandType.PLAY_SOUND, params: { text: 'attack' } },
                { id: 'sf17', type: CommandType.CHANGE_VAR, params: { varName: 'shadowEnergy', value: 1 } },
                { id: 'sf18', type: CommandType.END_IF, params: {} },
                { id: 'sf19', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 33 } },
                { id: 'sf20', type: CommandType.DODGE_ROLL, params: { value: 6 } },
                { id: 'sf21', type: CommandType.PLAY_SOUND, params: { text: 'dash' } },
                { id: 'sf22', type: CommandType.END_IF, params: {} },
                { id: 'sf23', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '👤' } },
                { id: 'sf24', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
                { id: 'sf25', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'sf26', type: CommandType.END_IF, params: {} },
                { id: 'win_shadow', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'score', value: 100 } },
                { id: 'win_shadow2', type: CommandType.WIN_GAME, params: {} },
                { id: 'win_shadow3', type: CommandType.END_IF, params: {} },
                { id: 'sf27', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_battle_robot_wars',
            mode: AppMode.GAME,
            name: 'Robot Wars',
            description: 'Mech combat arena — build and destroy!',
            icon: Bot,
            color: 'bg-gradient-to-r from-blue-600 to-cyan-500',
            commands: [
                { id: 'rw1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 'rw2', type: CommandType.SET_EMOJI, params: { text: '🤖' } },
                { id: 'rw3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'rw4', type: CommandType.SET_VAR, params: { varName: 'armor', value: 100 } },
                { id: 'rw5', type: CommandType.SPAWN_ENEMY, params: { text: '🦾' } },
                { id: 'rw6', type: CommandType.SPAWN_ENEMY, params: { text: '🦿' } },
                { id: 'rw7', type: CommandType.FOREVER, params: {} },
                { id: 'rw8', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'rw9', type: CommandType.MOVE_X, params: { value: -4 } },
                { id: 'rw10', type: CommandType.END_IF, params: {} },
                { id: 'rw11', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'rw12', type: CommandType.MOVE_X, params: { value: 4 } },
                { id: 'rw13', type: CommandType.END_IF, params: {} },
                { id: 'rw14', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'rw15', type: CommandType.MOVE_Y, params: { value: -4 } },
                { id: 'rw16', type: CommandType.END_IF, params: {} },
                { id: 'rw17', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'rw18', type: CommandType.MOVE_Y, params: { value: 4 } },
                { id: 'rw19', type: CommandType.END_IF, params: {} },
                { id: 'rw20', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'rw21', type: CommandType.SHOOT, params: { text: '🤖' } },
                { id: 'rw22', type: CommandType.PLAY_SOUND, params: { text: 'laser' } },
                { id: 'rw23', type: CommandType.END_IF, params: {} },
                { id: 'rw24', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🦾' } },
                { id: 'rw25', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
                { id: 'rw26', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'rw27', type: CommandType.END_IF, params: {} },
                { id: 'win_robot', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'score', value: 100 } },
                { id: 'win_robot2', type: CommandType.WIN_GAME, params: {} },
                { id: 'win_robot3', type: CommandType.END_IF, params: {} },
                { id: 'lose_robot', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'armor', value: 0 } },
                { id: 'lose_robot2', type: CommandType.GAME_OVER, params: {} },
                { id: 'lose_robot3', type: CommandType.END_IF, params: {} },
                { id: 'rw28', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_battle_pirate_ship',
            mode: AppMode.GAME,
            name: 'Pirate Ship',
            description: 'Naval combat on the high seas!',
            icon: Ship,
            color: 'bg-gradient-to-r from-amber-700 to-yellow-600',
            commands: [
                { id: 'ps1', type: CommandType.SET_SCENE, params: { text: 'water' } },
                { id: 'ps2', type: CommandType.SET_EMOJI, params: { text: '🏴‍☠️' } },
                { id: 'ps3', type: CommandType.SET_WEATHER, params: { text: 'rain' } },
                { id: 'ps4', type: CommandType.SET_VAR, params: { varName: 'gold', value: 0 } },
                { id: 'ps5', type: CommandType.SPAWN_ENEMY, params: { text: '🚢' } },
                { id: 'ps6', type: CommandType.SPAWN_ITEM, params: { text: '🪙' } },
                { id: 'ps7', type: CommandType.FOREVER, params: {} },
                { id: 'ps8', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'ps9', type: CommandType.MOVE_X, params: { value: -5 } },
                { id: 'ps10', type: CommandType.END_IF, params: {} },
                { id: 'ps11', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'ps12', type: CommandType.MOVE_X, params: { value: 5 } },
                { id: 'ps13', type: CommandType.END_IF, params: {} },
                { id: 'ps14', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'ps15', type: CommandType.SHOOT, params: { text: '💣' } },
                { id: 'ps16', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'ps17', type: CommandType.END_IF, params: {} },
                { id: 'ps18', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🚢' } },
                { id: 'ps19', type: CommandType.CHANGE_VAR, params: { varName: 'gold', value: 50 } },
                { id: 'ps20', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: 'ps21', type: CommandType.END_IF, params: {} },
                { id: 'win_pirate', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'gold', value: 500 } },
                { id: 'win_pirate2', type: CommandType.WIN_GAME, params: {} },
                { id: 'win_pirate3', type: CommandType.END_IF, params: {} },
                { id: 'ps22', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_battle_zombie_apocalypse',
            mode: AppMode.GAME,
            name: 'Zombie Apocalypse',
            description: 'Survive endless zombie waves!',
            icon: Skull,
            color: 'bg-gradient-to-r from-green-800 to-red-900',
            commands: [
                { id: 'za1', type: CommandType.SET_SCENE, params: { text: 'dark' } },
                { id: 'za2', type: CommandType.SET_EMOJI, params: { text: '🧟' } },
                { id: 'za3', type: CommandType.SET_WEATHER, params: { text: 'rain' } },
                { id: 'za4', type: CommandType.SET_VAR, params: { varName: 'wave', value: 1 } },
                { id: 'za5', type: CommandType.SET_VAR, params: { varName: 'kills', value: 0 } },
                { id: 'za6', type: CommandType.SPAWN_ENEMY, params: { text: '🧟' } },
                { id: 'za7', type: CommandType.SPAWN_ENEMY, params: { text: '🧟' } },
                { id: 'za8', type: CommandType.SPAWN_ENEMY, params: { text: '🧟' } },
                { id: 'za9', type: CommandType.FOREVER, params: {} },
                { id: 'za10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'za11', type: CommandType.MOVE_X, params: { value: -5 } },
                { id: 'za12', type: CommandType.END_IF, params: {} },
                { id: 'za13', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'za14', type: CommandType.MOVE_X, params: { value: 5 } },
                { id: 'za15', type: CommandType.END_IF, params: {} },
                { id: 'za16', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'za17', type: CommandType.SHOOT, params: { text: '🔫' } },
                { id: 'za18', type: CommandType.PLAY_SOUND, params: { text: 'shoot' } },
                { id: 'za19', type: CommandType.CHANGE_VAR, params: { varName: 'kills', value: 1 } },
                { id: 'za20', type: CommandType.END_IF, params: {} },
                { id: 'za21', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🧟' } },
                { id: 'za22', type: CommandType.CHANGE_VAR, params: { varName: 'wave', value: 1 } },
                { id: 'za23', type: CommandType.SCREEN_SHAKE, params: { value: 0.2 } },
                { id: 'za24', type: CommandType.PLAY_SOUND, params: { text: 'hurt' } },
                { id: 'za25', type: CommandType.END_IF, params: {} },
                { id: 'win_zombie_apoc', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'kills', value: 50 } },
                { id: 'win_zombie_apoc2', type: CommandType.WIN_GAME, params: {} },
                { id: 'win_zombie_apoc3', type: CommandType.END_IF, params: {} },
                { id: 'za26', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_battle_ninja_stealth',
            mode: AppMode.GAME,
            name: 'Ninja Stealth',
            description: 'Sneak through levels undetected!',
            icon: User,
            color: 'bg-gradient-to-r from-gray-900 to-indigo-900',
            commands: [
                { id: 'ns1', type: CommandType.SET_SCENE, params: { text: 'dark' } },
                { id: 'ns2', type: CommandType.SET_EMOJI, params: { text: '🥷' } },
                { id: 'ns3', type: CommandType.SET_VAR, params: { varName: 'stealth', value: 100 } },
                { id: 'ns4', type: CommandType.SET_VAR, params: { varName: 'kills', value: 0 } },
                { id: 'ns5', type: CommandType.SPAWN_ENEMY, params: { text: '👁️' } },
                { id: 'ns6', type: CommandType.SPAWN_ENEMY, params: { text: '👁️' } },
                { id: 'ns7', type: CommandType.FOREVER, params: {} },
                { id: 'ns8', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'ns9', type: CommandType.MOVE_X, params: { value: -3 } },
                { id: 'ns10', type: CommandType.END_IF, params: {} },
                { id: 'ns11', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'ns12', type: CommandType.MOVE_X, params: { value: 3 } },
                { id: 'ns13', type: CommandType.END_IF, params: {} },
                { id: 'ns14', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'ns15', type: CommandType.SWING_WEAPON, params: { text: '🗡️', value: 20 } },
                { id: 'ns16', type: CommandType.CHANGE_VAR, params: { varName: 'stealth', value: -20 } },
                { id: 'ns17', type: CommandType.PLAY_SOUND, params: { text: 'swish' } },
                { id: 'ns18', type: CommandType.END_IF, params: {} },
                { id: 'ns19', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 33 } },
                { id: 'ns20', type: CommandType.DODGE_ROLL, params: { value: 8 } },
                { id: 'ns21', type: CommandType.PLAY_SOUND, params: { text: 'dash' } },
                { id: 'ns22', type: CommandType.END_IF, params: {} },
                { id: 'ns23', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '👁️' } },
                { id: 'ns24', type: CommandType.CHANGE_VAR, params: { varName: 'stealth', value: -30 } },
                { id: 'ns25', type: CommandType.PLAY_SOUND, params: { text: 'hurt' } },
                { id: 'ns26', type: CommandType.END_IF, params: {} },
                { id: 'win_ninja', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'kills', value: 20 } },
                { id: 'win_ninja2', type: CommandType.WIN_GAME, params: {} },
                { id: 'win_ninja3', type: CommandType.END_IF, params: {} },
                { id: 'lose_ninja', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'stealth', value: 0 } },
                { id: 'lose_ninja2', type: CommandType.GAME_OVER, params: {} },
                { id: 'lose_ninja3', type: CommandType.END_IF, params: {} },
                { id: 'ns27', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_battle_samurai_duel',
            mode: AppMode.GAME,
            name: 'Samurai Duel',
            description: '1v1 sword fights to the death!',
            icon: SwordsIcon,
            color: 'bg-gradient-to-r from-red-600 to-yellow-500',
            commands: [
                { id: 'sd1', type: CommandType.SET_SCENE, params: { text: 'grass' } },
                { id: 'sd2', type: CommandType.SET_EMOJI, params: { text: '⚔️' } },
                { id: 'sd3', type: CommandType.SET_VAR, params: { varName: 'wins', value: 0 } },
                { id: 'sd4', type: CommandType.SET_VAR, params: { varName: 'health', value: 100 } },
                { id: 'sd5', type: CommandType.SPAWN_ENEMY, params: { text: '🥷' } },
                { id: 'sd6', type: CommandType.FOREVER, params: {} },
                { id: 'sd7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'sd8', type: CommandType.MOVE_X, params: { value: -4 } },
                { id: 'sd9', type: CommandType.END_IF, params: {} },
                { id: 'sd10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'sd11', type: CommandType.MOVE_X, params: { value: 4 } },
                { id: 'sd12', type: CommandType.END_IF, params: {} },
                { id: 'sd13', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'sd14', type: CommandType.SWING_WEAPON, params: { text: '⚔️', value: 25 } },
                { id: 'sd15', type: CommandType.PLAY_SOUND, params: { text: 'attack' } },
                { id: 'sd16', type: CommandType.SCREEN_SHAKE, params: { value: 0.15 } },
                { id: 'sd17', type: CommandType.END_IF, params: {} },
                { id: 'sd18', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 33 } },
                { id: 'sd19', type: CommandType.BLOCK_ATTACK, params: {} },
                { id: 'sd20', type: CommandType.PLAY_SOUND, params: { text: 'crack' } },
                { id: 'sd21', type: CommandType.END_IF, params: {} },
                { id: 'sd22', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🥷' } },
                { id: 'sd23', type: CommandType.CHANGE_VAR, params: { varName: 'wins', value: 1 } },
                { id: 'sd24', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
                { id: 'sd25', type: CommandType.END_IF, params: {} },
                { id: 'win_samurai', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'wins', value: 5 } },
                { id: 'win_samurai2', type: CommandType.WIN_GAME, params: {} },
                { id: 'win_samurai3', type: CommandType.END_IF, params: {} },
                { id: 'lose_samurai', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'health', value: 0 } },
                { id: 'lose_samurai2', type: CommandType.GAME_OVER, params: {} },
                { id: 'lose_samurai3', type: CommandType.END_IF, params: {} },
                { id: 'sd26', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_battle_alien_invasion',
            mode: AppMode.GAME,
            name: 'Alien Invasion',
            description: 'Defend Earth from alien invaders!',
            icon: Rocket,
            color: 'bg-gradient-to-r from-green-500 to-teal-600',
            commands: [
                { id: 'ai1', type: CommandType.SET_SCENE, params: { text: 'space' } },
                { id: 'ai2', type: CommandType.SET_EMOJI, params: { text: '🛸' } },
                { id: 'ai3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'ai4', type: CommandType.SET_VAR, params: { varName: 'wave', value: 1 } },
                { id: 'ai5', type: CommandType.SPAWN_ENEMY, params: { text: '👽' } },
                { id: 'ai6', type: CommandType.SPAWN_ENEMY, params: { text: '👽' } },
                { id: 'ai7', type: CommandType.SPAWN_ENEMY, params: { text: '👾' } },
                { id: 'ai8', type: CommandType.FOREVER, params: {} },
                { id: 'ai9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'ai10', type: CommandType.MOVE_X, params: { value: -5 } },
                { id: 'ai11', type: CommandType.END_IF, params: {} },
                { id: 'ai12', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'ai13', type: CommandType.MOVE_X, params: { value: 5 } },
                { id: 'ai14', type: CommandType.END_IF, params: {} },
                { id: 'ai15', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'ai16', type: CommandType.MOVE_Y, params: { value: -5 } },
                { id: 'ai17', type: CommandType.END_IF, params: {} },
                { id: 'ai18', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'ai19', type: CommandType.MOVE_Y, params: { value: 5 } },
                { id: 'ai20', type: CommandType.END_IF, params: {} },
                { id: 'ai21', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'ai22', type: CommandType.SHOOT, params: { text: '🚀' } },
                { id: 'ai23', type: CommandType.PLAY_SOUND, params: { text: 'laser' } },
                { id: 'ai24', type: CommandType.END_IF, params: {} },
                { id: 'ai25', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '👽' } },
                { id: 'ai26', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 15 } },
                { id: 'ai27', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'ai28', type: CommandType.END_IF, params: {} },
                { id: 'win_alien', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'score', value: 200 } },
                { id: 'win_alien2', type: CommandType.WIN_GAME, params: {} },
                { id: 'win_alien3', type: CommandType.END_IF, params: {} },
                { id: 'ai29', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_battle_dragon_rider',
            mode: AppMode.GAME,
            name: 'Dragon Rider',
            description: 'Fly your dragon and defeat enemies!',
            icon: Flame,
            color: 'bg-gradient-to-r from-orange-500 to-red-600',
            commands: [
                { id: 'dr1', type: CommandType.SET_SCENE, params: { text: 'space' } },
                { id: 'dr2', type: CommandType.SET_EMOJI, params: { text: '🐉' } },
                { id: 'dr3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'dr4', type: CommandType.SET_VAR, params: { varName: 'mana', value: 100 } },
                { id: 'dr5', type: CommandType.SPAWN_ENEMY, params: { text: '🗡️' } },
                { id: 'dr6', type: CommandType.SPAWN_ENEMY, params: { text: '🛡️' } },
                { id: 'dr7', type: CommandType.FOREVER, params: {} },
                { id: 'dr8', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'dr9', type: CommandType.MOVE_X, params: { value: -6 } },
                { id: 'dr10', type: CommandType.END_IF, params: {} },
                { id: 'dr11', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'dr12', type: CommandType.MOVE_X, params: { value: 6 } },
                { id: 'dr13', type: CommandType.END_IF, params: {} },
                { id: 'dr14', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'dr15', type: CommandType.MOVE_Y, params: { value: -6 } },
                { id: 'dr16', type: CommandType.END_IF, params: {} },
                { id: 'dr17', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'dr18', type: CommandType.MOVE_Y, params: { value: 6 } },
                { id: 'dr19', type: CommandType.END_IF, params: {} },
                { id: 'dr20', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'dr21', type: CommandType.SHOOT, params: { text: '🔥' } },
                { id: 'dr22', type: CommandType.CHANGE_VAR, params: { varName: 'mana', value: -5 } },
                { id: 'dr23', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'dr24', type: CommandType.END_IF, params: {} },
                { id: 'dr25', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 33 } },
                { id: 'dr26', type: CommandType.SPECIAL_MOVE, params: {} },
                { id: 'dr27', type: CommandType.CHANGE_VAR, params: { varName: 'mana', value: -20 } },
                { id: 'dr28', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'dr29', type: CommandType.END_IF, params: {} },
                { id: 'dr30', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🗡️' } },
                { id: 'dr31', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 20 } },
                { id: 'dr32', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: 'dr33', type: CommandType.END_IF, params: {} },
                { id: 'win_dragon', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'score', value: 200 } },
                { id: 'win_dragon2', type: CommandType.WIN_GAME, params: {} },
                { id: 'win_dragon3', type: CommandType.END_IF, params: {} },
                { id: 'warn_dragon', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'mana', value: 0 } },
                { id: 'warn_dragon2', type: CommandType.SAY, params: { text: 'Out of mana!' } },
                { id: 'warn_dragon3', type: CommandType.END_IF, params: {} },
                { id: 'dr34', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_battle_wizard_tower',
            mode: AppMode.GAME,
            name: 'Wizard Tower',
            description: 'Defend your tower with magical spells!',
            icon: ShieldCheck,
            color: 'bg-gradient-to-r from-purple-600 to-pink-500',
            commands: [
                { id: 'wt1', type: CommandType.SET_SCENE, params: { text: 'dark' } },
                { id: 'wt2', type: CommandType.SET_EMOJI, params: { text: '🧙' } },
                { id: 'wt3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'wt4', type: CommandType.SET_VAR, params: { varName: 'mana', value: 100 } },
                { id: 'wt5', type: CommandType.SPAWN_ENEMY, params: { text: '💀' } },
                { id: 'wt6', type: CommandType.SPAWN_ENEMY, params: { text: '🦇' } },
                { id: 'wt7', type: CommandType.SPAWN_ENEMY, params: { text: '👻' } },
                { id: 'wt8', type: CommandType.FOREVER, params: {} },
                { id: 'wt9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'wt10', type: CommandType.MOVE_X, params: { value: -4 } },
                { id: 'wt11', type: CommandType.END_IF, params: {} },
                { id: 'wt12', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'wt13', type: CommandType.MOVE_X, params: { value: 4 } },
                { id: 'wt14', type: CommandType.END_IF, params: {} },
                { id: 'wt15', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'wt16', type: CommandType.SHOOT, params: { text: '✨' } },
                { id: 'wt17', type: CommandType.CHANGE_VAR, params: { varName: 'mana', value: -5 } },
                { id: 'wt18', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'wt19', type: CommandType.END_IF, params: {} },
                { id: 'wt20', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 33 } },
                { id: 'wt21', type: CommandType.BLOCK_ATTACK, params: {} },
                { id: 'wt22', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'wt23', type: CommandType.END_IF, params: {} },
                { id: 'wt24', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '💀' } },
                { id: 'wt25', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
                { id: 'wt26', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'wt27', type: CommandType.END_IF, params: {} },
                { id: 'win_wizard', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'score', value: 100 } },
                { id: 'win_wizard2', type: CommandType.WIN_GAME, params: {} },
                { id: 'win_wizard3', type: CommandType.END_IF, params: {} },
                { id: 'warn_wizard', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'mana', value: 0 } },
                { id: 'warn_wizard2', type: CommandType.SAY, params: { text: 'No mana!' } },
                { id: 'warn_wizard3', type: CommandType.END_IF, params: {} },
                { id: 'wt28', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_battle_vampire_hunter',
            mode: AppMode.GAME,
            name: 'Vampire Hunter',
            description: 'Hunt vampires under the moonlight!',
            icon: Bug,
            color: 'bg-gradient-to-r from-red-900 to-gray-800',
            commands: [
                { id: 'vh1', type: CommandType.SET_SCENE, params: { text: 'dark' } },
                { id: 'vh2', type: CommandType.SET_EMOJI, params: { text: '🧛' } },
                { id: 'vh3', type: CommandType.SET_WEATHER, params: { text: 'rain' } },
                { id: 'vh4', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'vh5', type: CommandType.SET_VAR, params: { varName: 'ammo', value: 30 } },
                { id: 'vh6', type: CommandType.SPAWN_ENEMY, params: { text: '🧛' } },
                { id: 'vh7', type: CommandType.SPAWN_ENEMY, params: { text: '🦇' } },
                { id: 'vh8', type: CommandType.SPAWN_ENEMY, params: { text: '🧛' } },
                { id: 'vh9', type: CommandType.FOREVER, params: {} },
                { id: 'vh10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'vh11', type: CommandType.MOVE_X, params: { value: -5 } },
                { id: 'vh12', type: CommandType.END_IF, params: {} },
                { id: 'vh13', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'vh14', type: CommandType.MOVE_X, params: { value: 5 } },
                { id: 'vh15', type: CommandType.END_IF, params: {} },
                { id: 'vh16', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'vh17', type: CommandType.SHOOT, params: { text: '🔫' } },
                { id: 'vh18', type: CommandType.CHANGE_VAR, params: { varName: 'ammo', value: -1 } },
                { id: 'vh19', type: CommandType.PLAY_SOUND, params: { text: 'shoot' } },
                { id: 'vh20', type: CommandType.END_IF, params: {} },
                { id: 'vh21', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 33 } },
                { id: 'vh22', type: CommandType.SWING_WEAPON, params: { text: '🗡️', value: 15 } },
                { id: 'vh23', type: CommandType.PLAY_SOUND, params: { text: 'attack' } },
                { id: 'vh24', type: CommandType.END_IF, params: {} },
                { id: 'vh25', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🧛' } },
                { id: 'vh26', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 25 } },
                { id: 'vh27', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'vh28', type: CommandType.END_IF, params: {} },
                { id: 'win_vampire', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'score', value: 200 } },
                { id: 'win_vampire2', type: CommandType.WIN_GAME, params: {} },
                { id: 'win_vampire3', type: CommandType.END_IF, params: {} },
                { id: 'warn_vampire', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'ammo', value: 0 } },
                { id: 'warn_vampire2', type: CommandType.SAY, params: { text: 'Out of ammo!' } },
                { id: 'warn_vampire3', type: CommandType.END_IF, params: {} },
                { id: 'vh29', type: CommandType.END_FOREVER, params: {} }
            ]
        },
    ];
