import { AppMode, CommandType, CircuitComponent, CommandBlock } from '../../types';
import {
    LucideIcon, Swords, Shield, Music, Type, PenTool, Piano, BookOpen,
    HelpCircle, Layers, Dices, Circle, Compass, Ghost, ArrowDown,
    Zap, Box, Target, Sun, Wheat, Landmark
} from 'lucide-react';

export const classicTemplates: {
    id: string,
    mode: AppMode,
    name: string,
    description: string,
    icon: LucideIcon,
    color: string,
    commands: CommandBlock[],
    circuitComponents?: CircuitComponent[]
}[] = [
    {
        id: 'tpl_classic_fighting',
        mode: AppMode.GAME,
        name: 'Fighting Game',
        description: '1v1 arena with health bars, special moves, and combo system',
        icon: Swords,
        color: 'bg-gradient-to-r from-red-600 to-red-800',
        commands: [
            { id: 'f1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 'f2', type: CommandType.SET_EMOJI, params: { text: '🥊' } },
            { id: 'f3', type: CommandType.SET_VAR, params: { varName: 'player_hp', value: 100 } },
            { id: 'f4', type: CommandType.SET_VAR, params: { varName: 'enemy_hp', value: 100 } },
            { id: 'f5', type: CommandType.SET_VAR, params: { varName: 'combo', value: 0 } },
            { id: 'f6', type: CommandType.SET_VAR, params: { varName: 'special', value: 0 } },
            { id: 'f7', type: CommandType.SPAWN_ENEMY, params: { text: '👹' } },
            { id: 'f8', type: CommandType.PLAY_SOUND, params: { text: 'fight' } },
            { id: 'f9', type: CommandType.FOREVER, params: {} },
            { id: 'f10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'f11', type: CommandType.MOVE_X, params: { value: -5 } },
            { id: 'f12', type: CommandType.END_IF, params: {} },
            { id: 'f13', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'f14', type: CommandType.MOVE_X, params: { value: 5 } },
            { id: 'f15', type: CommandType.END_IF, params: {} },
            { id: 'f16', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'f17', type: CommandType.SHOOT, params: { text: '👊' } },
            { id: 'f18', type: CommandType.CHANGE_VAR, params: { varName: 'combo', value: 1 } },
            { id: 'f19', type: CommandType.CHANGE_VAR, params: { varName: 'special', value: 10 } },
            { id: 'f20', type: CommandType.PLAY_SOUND, params: { text: 'punch' } },
            { id: 'f21', type: CommandType.END_IF, params: {} },
            { id: 'f22', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
            { id: 'f23', type: CommandType.SHOOT, params: { text: '🥊' } },
            { id: 'f24', type: CommandType.SCREEN_SHAKE, params: { value: 5 } },
            { id: 'f25', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
            { id: 'f26', type: CommandType.END_IF, params: {} },
            { id: 'f27', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 33 } },
            { id: 'f28', type: CommandType.SHOOT, params: { text: '💥' } },
            { id: 'f29', type: CommandType.CHANGE_VAR, params: { varName: 'special', value: -50 } },
            { id: 'f30', type: CommandType.SPAWN_PARTICLES, params: { value: 10 } },
            { id: 'f31', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
            { id: 'f32', type: CommandType.END_IF, params: {} },
            { id: 'f33', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '👹' } },
            { id: 'f34', type: CommandType.CHANGE_VAR, params: { varName: 'player_hp', value: -10 } },
            { id: 'f35', type: CommandType.PLAY_SOUND, params: { text: 'hurt' } },
            { id: 'f36', type: CommandType.END_IF, params: {} },
            { id: 'f37', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'enemy_hp', value: 0 } },
            { id: 'f38', type: CommandType.WIN_GAME, params: {} },
            { id: 'f39', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
            { id: 'f40', type: CommandType.END_IF, params: {} },
            { id: 'lose_fighting', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'player_hp', value: 0 } },
            { id: 'lose_fighting2', type: CommandType.GAME_OVER, params: {} },
            { id: 'lose_fighting3', type: CommandType.END_IF, params: {} },
            { id: 'f41', type: CommandType.END_FOREVER, params: {} },
        ]
    },
    {
        id: 'tpl_classic_tower_defense',
        mode: AppMode.GAME,
        name: 'Tower Defense',
        description: 'Place towers, enemies follow paths, waves increase in difficulty',
        icon: Shield,
        color: 'bg-gradient-to-r from-green-600 to-emerald-700',
        commands: [
            { id: 't1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 't2', type: CommandType.SET_EMOJI, params: { text: '🏰' } },
            { id: 't3', type: CommandType.SET_VAR, params: { varName: 'gold', value: 100 } },
            { id: 't4', type: CommandType.SET_VAR, params: { varName: 'wave', value: 1 } },
            { id: 't5', type: CommandType.SET_VAR, params: { varName: 'enemies_left', value: 10 } },
            { id: 't6', type: CommandType.START_WAVE, params: {} },
            { id: 't7', type: CommandType.SPAWN_WAVE_ENEMIES, params: { value: 10 } },
            { id: 't8', type: CommandType.PLAY_SOUND, params: { text: 'alarm' } },
            { id: 't9', type: CommandType.FOREVER, params: {} },
            { id: 't10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 't11', type: CommandType.SHOOT, params: { text: '🗼' } },
            { id: 't12', type: CommandType.PLAY_SOUND, params: { text: 'build' } },
            { id: 't13', type: CommandType.END_IF, params: {} },
            { id: 't14', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '👾' } },
            { id: 't15', type: CommandType.CHANGE_VAR, params: { varName: 'enemies_left', value: -1 } },
            { id: 't16', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
            { id: 't17', type: CommandType.END_IF, params: {} },
            { id: 't18', type: CommandType.IF, params: { condition: 'GREATER' } },
            { id: 't19', type: CommandType.NEXT_WAVE, params: {} },
            { id: 't20', type: CommandType.CHANGE_VAR, params: { varName: 'wave', value: 1 } },
            { id: 't21', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
            { id: 't22', type: CommandType.END_IF, params: {} },
            { id: 'win_td', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'enemies_left', value: 0 } },
            { id: 'win_td2', type: CommandType.WIN_GAME, params: {} },
            { id: 'win_td3', type: CommandType.END_IF, params: {} },
            { id: 't23', type: CommandType.END_FOREVER, params: {} },
        ]
    },
    {
        id: 'tpl_classic_rhythm',
        mode: AppMode.GAME,
        name: 'Rhythm Game',
        description: 'Hit notes on beat, score based on timing accuracy',
        icon: Music,
        color: 'bg-gradient-to-r from-pink-500 to-fuchsia-600',
        commands: [
            { id: 'r1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 'r2', type: CommandType.SET_EMOJI, params: { text: '🎵' } },
            { id: 'r3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
            { id: 'r4', type: CommandType.SET_VAR, params: { varName: 'streak', value: 0 } },
            { id: 'r5', type: CommandType.SET_VAR, params: { varName: 'misses', value: 0 } },
            { id: 'r6', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'beat' } },
            { id: 'r7', type: CommandType.SPAWN_ENEMY, params: { text: '🎵' } },
            { id: 'r8', type: CommandType.FOREVER, params: {} },
            { id: 'r9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'r10', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
            { id: 'r11', type: CommandType.CHANGE_VAR, params: { varName: 'streak', value: 1 } },
            { id: 'r12', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'r13', type: CommandType.SPAWN_PARTICLES, params: { value: 5 } },
            { id: 'r14', type: CommandType.END_IF, params: {} },
            { id: 'r15', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } },
            { id: 'r16', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 15 } },
            { id: 'r17', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
            { id: 'r18', type: CommandType.SPAWN_PARTICLES, params: { value: 8 } },
            { id: 'r19', type: CommandType.END_IF, params: {} },
            { id: 'r20', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'r21', type: CommandType.CHANGE_VAR, params: { varName: 'misses', value: 1 } },
            { id: 'r22', type: CommandType.CHANGE_VAR, params: { varName: 'streak', value: -3 } },
            { id: 'r23', type: CommandType.PLAY_SOUND, params: { text: 'hurt' } },
            { id: 'r24', type: CommandType.END_IF, params: {} },
            { id: 'win_rhythm', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'score', value: 500 } },
            { id: 'win_rhythm2', type: CommandType.WIN_GAME, params: {} },
            { id: 'win_rhythm3', type: CommandType.END_IF, params: {} },
            { id: 'lose_rhythm', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'misses', value: 10 } },
            { id: 'lose_rhythm2', type: CommandType.GAME_OVER, params: {} },
            { id: 'lose_rhythm3', type: CommandType.END_IF, params: {} },
            { id: 'r25', type: CommandType.END_FOREVER, params: {} },
        ]
    },
    {
        id: 'tpl_classic_word',
        mode: AppMode.GAME,
        name: 'Word Game',
        description: 'Type words fast, score based on speed and accuracy',
        icon: Type,
        color: 'bg-gradient-to-r from-blue-500 to-cyan-600',
        commands: [
            { id: 'w1', type: CommandType.SET_TITLE, params: { text: 'Word Rush' } },
            { id: 'w2', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 'w3', type: CommandType.SET_EMOJI, params: { text: '📝' } },
            { id: 'w4', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
            { id: 'w5', type: CommandType.SET_VAR, params: { varName: 'words_typed', value: 0 } },
            { id: 'w6', type: CommandType.SET_VAR, params: { varName: 'timer', value: 60 } },
            { id: 'w7', type: CommandType.SAY, params: { text: 'Type words to score!' } },
            { id: 'w8', type: CommandType.FOREVER, params: {} },
            { id: 'w9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'w10', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 5 } },
            { id: 'w11', type: CommandType.CHANGE_VAR, params: { varName: 'words_typed', value: 1 } },
            { id: 'w12', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'w13', type: CommandType.END_IF, params: {} },
            { id: 'w14', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } },
            { id: 'w15', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
            { id: 'w16', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
            { id: 'w17', type: CommandType.END_IF, params: {} },
            { id: 'win_word', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'words_typed', value: 20 } },
            { id: 'win_word2', type: CommandType.WIN_GAME, params: {} },
            { id: 'win_word3', type: CommandType.END_IF, params: {} },
            { id: 'lose_word', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'timer', value: 0 } },
            { id: 'lose_word2', type: CommandType.GAME_OVER, params: {} },
            { id: 'lose_word3', type: CommandType.END_IF, params: {} },
            { id: 'w18', type: CommandType.END_FOREVER, params: {} },
        ]
    },
    {
        id: 'tpl_classic_drawing',
        mode: AppMode.GAME,
        name: 'Drawing Game',
        description: 'Draw shapes and patterns, AI scores your creativity',
        icon: PenTool,
        color: 'bg-gradient-to-r from-yellow-500 to-amber-600',
        commands: [
            { id: 'd1', type: CommandType.SET_TITLE, params: { text: 'Art Studio' } },
            { id: 'd2', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 'd3', type: CommandType.SET_EMOJI, params: { text: '🎨' } },
            { id: 'd4', type: CommandType.SET_VAR, params: { varName: 'creativity', value: 0 } },
            { id: 'd5', type: CommandType.SET_VAR, params: { varName: 'shapes_drawn', value: 0 } },
            { id: 'd6', type: CommandType.ADD_DRAWING_CANVAS, params: {} },
            { id: 'd7', type: CommandType.SAY, params: { text: 'Draw something amazing!' } },
            { id: 'd8', type: CommandType.FOREVER, params: {} },
            { id: 'd9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'd10', type: CommandType.FILL_COLOR, params: { color: '#ff6b6b' } },
            { id: 'd11', type: CommandType.CHANGE_VAR, params: { varName: 'shapes_drawn', value: 1 } },
            { id: 'd12', type: CommandType.PLAY_SOUND, params: { text: 'click' } },
            { id: 'd13', type: CommandType.END_IF, params: {} },
            { id: 'd14', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } },
            { id: 'd15', type: CommandType.FILL_COLOR, params: { color: '#4ecdc4' } },
            { id: 'd16', type: CommandType.CHANGE_VAR, params: { varName: 'creativity', value: 5 } },
            { id: 'd17', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
            { id: 'd18', type: CommandType.END_IF, params: {} },
            { id: 'win_drawing', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'shapes_drawn', value: 10 } },
            { id: 'win_drawing2', type: CommandType.WIN_GAME, params: {} },
            { id: 'win_drawing3', type: CommandType.END_IF, params: {} },
            { id: 'd19', type: CommandType.END_FOREVER, params: {} },
        ]
    },
    {
        id: 'tpl_classic_music_maker',
        mode: AppMode.GAME,
        name: 'Music Maker',
        description: 'Compose beats with a grid sequencer, layer tracks and effects',
        icon: Piano,
        color: 'bg-gradient-to-r from-purple-500 to-indigo-600',
        commands: [
            { id: 'm1', type: CommandType.SET_TITLE, params: { text: 'Beat Maker' } },
            { id: 'm2', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 'm3', type: CommandType.SET_EMOJI, params: { text: '🎹' } },
            { id: 'm4', type: CommandType.SET_VAR, params: { varName: 'bpm', value: 120 } },
            { id: 'm5', type: CommandType.SET_VAR, params: { varName: 'track', value: 1 } },
            { id: 'm6', type: CommandType.SET_VAR, params: { varName: 'pattern', value: 0 } },
            { id: 'm7', type: CommandType.PLAY_SOUND, params: { text: 'kick' } },
            { id: 'm8', type: CommandType.SAY, params: { text: 'Make some beats!' } },
            { id: 'm9', type: CommandType.FOREVER, params: {} },
            { id: 'm10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'm11', type: CommandType.PLAY_SOUND, params: { text: 'kick' } },
            { id: 'm12', type: CommandType.CHANGE_VAR, params: { varName: 'pattern', value: 1 } },
            { id: 'm13', type: CommandType.END_IF, params: {} },
            { id: 'm14', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } },
            { id: 'm15', type: CommandType.PLAY_SOUND, params: { text: 'snare' } },
            { id: 'm16', type: CommandType.CHANGE_VAR, params: { varName: 'pattern', value: 1 } },
            { id: 'm17', type: CommandType.END_IF, params: {} },
            { id: 'm18', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'm19', type: CommandType.PLAY_SOUND, params: { text: 'hihat' } },
            { id: 'm20', type: CommandType.CHANGE_VAR, params: { varName: 'pattern', value: 1 } },
            { id: 'm21', type: CommandType.END_IF, params: {} },
            { id: 'm22', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'm23', type: CommandType.PLAY_SOUND, params: { text: 'bass' } },
            { id: 'm24', type: CommandType.CHANGE_VAR, params: { varName: 'pattern', value: 1 } },
            { id: 'm25', type: CommandType.END_IF, params: {} },
            { id: 'win_music', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'pattern', value: 16 } },
            { id: 'win_music2', type: CommandType.WIN_GAME, params: {} },
            { id: 'win_music3', type: CommandType.END_IF, params: {} },
            { id: 'm26', type: CommandType.END_FOREVER, params: {} },
        ]
    },
    {
        id: 'tpl_classic_story',
        mode: AppMode.GAME,
        name: 'Story Writer',
        description: 'Interactive fiction with branching choices and multiple endings',
        icon: BookOpen,
        color: 'bg-gradient-to-r from-emerald-500 to-teal-600',
        commands: [
            { id: 's1', type: CommandType.SET_TITLE, params: { text: 'The Quest' } },
            { id: 's2', type: CommandType.TRIGGER_CUTSCENE, params: { text: 'intro' } },
            { id: 's3', type: CommandType.SAY, params: { text: 'You wake up in a mysterious forest...' } },
            { id: 's4', type: CommandType.WAIT, params: { value: 2 } },
            { id: 's5', type: CommandType.CREATE_DIALOGUE, params: { text: 'What do you do?' } },
            { id: 's6', type: CommandType.ADD_BUTTON, params: { text: 'Go left', message: 'left' } },
            { id: 's7', type: CommandType.ADD_BUTTON, params: { text: 'Go right', message: 'right' } },
            { id: 's8', type: CommandType.SET_VAR, params: { varName: 'choices', value: 0 } },
            { id: 's9', type: CommandType.SET_VAR, params: { varName: 'trust', value: 50 } },
            { id: 's10', type: CommandType.PLAY_SOUND, params: { text: 'ambient' } },
            { id: 's11', type: CommandType.FOREVER, params: {} },
            { id: 's12', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 's13', type: CommandType.SAY, params: { text: 'You found a treasure!' } },
            { id: 's14', type: CommandType.CHANGE_VAR, params: { varName: 'choices', value: 1 } },
            { id: 's15', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 's16', type: CommandType.END_IF, params: {} },
            { id: 's17', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } },
            { id: 's18', type: CommandType.SAY, params: { text: 'A wild creature appears!' } },
            { id: 's19', type: CommandType.CHANGE_VAR, params: { varName: 'trust', value: -10 } },
            { id: 's20', type: CommandType.PLAY_SOUND, params: { text: 'hurt' } },
            { id: 's21', type: CommandType.END_IF, params: {} },
            { id: 'win_story', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'choices', value: 5 } },
            { id: 'win_story2', type: CommandType.WIN_GAME, params: {} },
            { id: 'win_story3', type: CommandType.END_IF, params: {} },
            { id: 'lose_story', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'trust', value: 0 } },
            { id: 'lose_story2', type: CommandType.GAME_OVER, params: {} },
            { id: 'lose_story3', type: CommandType.END_IF, params: {} },
            { id: 's22', type: CommandType.END_FOREVER, params: {} },
        ]
    },
    {
        id: 'tpl_classic_quiz',
        mode: AppMode.GAME,
        name: 'Quiz Game',
        description: 'Multiple choice questions, track score and streaks',
        icon: HelpCircle,
        color: 'bg-gradient-to-r from-orange-500 to-red-500',
        commands: [
            { id: 'q1', type: CommandType.SET_TITLE, params: { text: 'Quiz Master' } },
            { id: 'q2', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 'q3', type: CommandType.SET_EMOJI, params: { text: '❓' } },
            { id: 'q4', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
            { id: 'q5', type: CommandType.SET_VAR, params: { varName: 'streak', value: 0 } },
            { id: 'q6', type: CommandType.SET_VAR, params: { varName: 'question', value: 1 } },
            { id: 'q7', type: CommandType.SAY, params: { text: 'Q1: What is 2+2?' } },
            { id: 'q8', type: CommandType.FOREVER, params: {} },
            { id: 'q9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'q10', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
            { id: 'q11', type: CommandType.CHANGE_VAR, params: { varName: 'streak', value: 1 } },
            { id: 'q12', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
            { id: 'q13', type: CommandType.SAY, params: { text: 'Correct!' } },
            { id: 'q14', type: CommandType.SPAWN_PARTICLES, params: { value: 5 } },
            { id: 'q15', type: CommandType.END_IF, params: {} },
            { id: 'q16', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } },
            { id: 'q17', type: CommandType.CHANGE_VAR, params: { varName: 'streak', value: -1 } },
            { id: 'q18', type: CommandType.PLAY_SOUND, params: { text: 'hurt' } },
            { id: 'q19', type: CommandType.SAY, params: { text: 'Wrong!' } },
            { id: 'q20', type: CommandType.END_IF, params: {} },
            { id: 'win_quiz', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'question', value: 10 } },
            { id: 'win_quiz2', type: CommandType.WIN_GAME, params: {} },
            { id: 'win_quiz3', type: CommandType.END_IF, params: {} },
            { id: 'lose_quiz', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'streak', value: -3 } },
            { id: 'lose_quiz2', type: CommandType.GAME_OVER, params: {} },
            { id: 'lose_quiz3', type: CommandType.END_IF, params: {} },
            { id: 'q21', type: CommandType.END_FOREVER, params: {} },
        ]
    },
    {
        id: 'tpl_classic_card',
        mode: AppMode.GAME,
        name: 'Card Game',
        description: 'Play cards, match pairs, strategic deck building',
        icon: Layers,
        color: 'bg-gradient-to-r from-red-500 to-pink-600',
        commands: [
            { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🃏' } },
            { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
            { id: 'c4', type: CommandType.SET_VAR, params: { varName: 'pairs', value: 0 } },
            { id: 'c5', type: CommandType.SET_VAR, params: { varName: 'attempts', value: 0 } },
            { id: 'c6', type: CommandType.SAY, params: { text: 'Match the pairs!' } },
            { id: 'c7', type: CommandType.FOREVER, params: {} },
            { id: 'c8', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'c9', type: CommandType.FLIP_CARD, params: {} },
            { id: 'c10', type: CommandType.CHANGE_VAR, params: { varName: 'attempts', value: 1 } },
            { id: 'c11', type: CommandType.PLAY_SOUND, params: { text: 'click' } },
            { id: 'c12', type: CommandType.END_IF, params: {} },
            { id: 'c13', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } },
            { id: 'c14', type: CommandType.FLIP_CARD, params: {} },
            { id: 'c15', type: CommandType.CHECK_MATCH, params: {} },
            { id: 'c16', type: CommandType.CHANGE_VAR, params: { varName: 'pairs', value: 1 } },
            { id: 'c17', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 20 } },
            { id: 'c18', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
            { id: 'c19', type: CommandType.END_IF, params: {} },
            { id: 'win_card', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'pairs', value: 6 } },
            { id: 'win_card2', type: CommandType.WIN_GAME, params: {} },
            { id: 'win_card3', type: CommandType.END_IF, params: {} },
            { id: 'c20', type: CommandType.END_FOREVER, params: {} },
        ]
    },
    {
        id: 'tpl_classic_dice',
        mode: AppMode.GAME,
        name: 'Dice Game',
        description: 'Roll dice, score combinations, risk vs reward',
        icon: Dices,
        color: 'bg-gradient-to-r from-indigo-500 to-blue-600',
        commands: [
            { id: 'dc1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 'dc2', type: CommandType.SET_EMOJI, params: { text: '🎲' } },
            { id: 'dc3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
            { id: 'dc4', type: CommandType.SET_VAR, params: { varName: 'rolls', value: 3 } },
            { id: 'dc5', type: CommandType.SET_VAR, params: { varName: 'bank', value: 0 } },
            { id: 'dc6', type: CommandType.SAY, params: { text: 'Roll the dice!' } },
            { id: 'dc7', type: CommandType.FOREVER, params: {} },
            { id: 'dc8', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'dc9', type: CommandType.CALC_RANDOM, params: { varName: 'die1', value: 1, value2: 6 } },
            { id: 'dc10', type: CommandType.CALC_RANDOM, params: { varName: 'die2', value: 1, value2: 6 } },
            { id: 'dc11', type: CommandType.PLAY_SOUND, params: { text: 'click' } },
            { id: 'dc12', type: CommandType.CHANGE_VAR, params: { varName: 'rolls', value: -1 } },
            { id: 'dc13', type: CommandType.END_IF, params: {} },
            { id: 'dc14', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } },
            { id: 'dc15', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
            { id: 'dc16', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'dc17', type: CommandType.SPAWN_PARTICLES, params: { value: 5 } },
            { id: 'dc18', type: CommandType.END_IF, params: {} },
            { id: 'lose_dice', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'rolls', value: 0 } },
            { id: 'lose_dice2', type: CommandType.GAME_OVER, params: {} },
            { id: 'lose_dice3', type: CommandType.SAY, params: { text: 'No rolls left!' } },
            { id: 'lose_dice4', type: CommandType.END_IF, params: {} },
            { id: 'dc19', type: CommandType.END_FOREVER, params: {} },
        ]
    },
    {
        id: 'tpl_classic_marble',
        mode: AppMode.GAME,
        name: 'Marble Run',
        description: 'Guide marbles through obstacles, collect gems, reach the goal',
        icon: Circle,
        color: 'bg-gradient-to-r from-cyan-500 to-blue-500',
        commands: [
            { id: 'mr1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 'mr2', type: CommandType.SET_EMOJI, params: { text: '🔵' } },
            { id: 'mr3', type: CommandType.SET_VAR, params: { varName: 'gems', value: 0 } },
            { id: 'mr4', type: CommandType.SET_VAR, params: { varName: 'lives', value: 3 } },
            { id: 'mr5', type: CommandType.SET_GRAVITY, params: { condition: 'true' } },
            { id: 'mr6', type: CommandType.BOUNCE_ON_EDGE, params: {} },
            { id: 'mr7', type: CommandType.SPAWN_ITEM, params: { text: '💎' } },
            { id: 'mr8', type: CommandType.SPAWN_ENEMY, params: { text: '🪨' } },
            { id: 'mr9', type: CommandType.FOREVER, params: {} },
            { id: 'mr10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'mr11', type: CommandType.MOVE_X, params: { value: -5 } },
            { id: 'mr12', type: CommandType.END_IF, params: {} },
            { id: 'mr13', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'mr14', type: CommandType.MOVE_X, params: { value: 5 } },
            { id: 'mr15', type: CommandType.END_IF, params: {} },
            { id: 'mr16', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'mr17', type: CommandType.JUMP, params: { value: 10 } },
            { id: 'mr18', type: CommandType.PLAY_SOUND, params: { text: 'jump' } },
            { id: 'mr19', type: CommandType.END_IF, params: {} },
            { id: 'mr20', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '💎' } },
            { id: 'mr21', type: CommandType.CHANGE_VAR, params: { varName: 'gems', value: 1 } },
            { id: 'mr22', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'mr23', type: CommandType.END_IF, params: {} },
            { id: 'win_marble', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'gems', value: 10 } },
            { id: 'win_marble2', type: CommandType.WIN_GAME, params: {} },
            { id: 'win_marble3', type: CommandType.END_IF, params: {} },
            { id: 'lose_marble', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'lives', value: 0 } },
            { id: 'lose_marble2', type: CommandType.GAME_OVER, params: {} },
            { id: 'lose_marble3', type: CommandType.END_IF, params: {} },
            { id: 'mr24', type: CommandType.END_FOREVER, params: {} },
        ]
    },
    {
        id: 'tpl_classic_zelda',
        mode: AppMode.GAME,
        name: 'Zelda Clone',
        description: 'Top-down adventure with items, dungeons, and combat',
        icon: Compass,
        color: 'bg-gradient-to-r from-green-500 to-green-700',
        commands: [
            { id: 'z1', type: CommandType.TRIGGER_CUTSCENE, params: { text: 'intro' } },
            { id: 'z2', type: CommandType.SAY, params: { text: 'The Legend Begins...' } },
            { id: 'z3', type: CommandType.WAIT, params: { value: 2 } },
            { id: 'z4', type: CommandType.FADE_IN, params: { value: 1 } },
            { id: 'z5', type: CommandType.SET_SCENE, params: { text: 'grass' } },
            { id: 'z6', type: CommandType.SET_EMOJI, params: { text: '🧑' } },
            { id: 'z7', type: CommandType.SET_VAR, params: { varName: 'health', value: 100 } },
            { id: 'z8', type: CommandType.SET_VAR, params: { varName: 'rupees', value: 0 } },
            { id: 'z9', type: CommandType.ADD_TO_INVENTORY, params: { text: 'Sword' } },
            { id: 'z10', type: CommandType.SET_CAMERA, params: { condition: 'true' } },
            { id: 'z11', type: CommandType.FOREVER, params: {} },
            { id: 'z12', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'z13', type: CommandType.MOVE_X, params: { value: -4 } },
            { id: 'z14', type: CommandType.END_IF, params: {} },
            { id: 'z15', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'z16', type: CommandType.MOVE_X, params: { value: 4 } },
            { id: 'z17', type: CommandType.END_IF, params: {} },
            { id: 'z18', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
            { id: 'z19', type: CommandType.MOVE_Y, params: { value: -4 } },
            { id: 'z20', type: CommandType.END_IF, params: {} },
            { id: 'z21', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
            { id: 'z22', type: CommandType.MOVE_Y, params: { value: 4 } },
            { id: 'z23', type: CommandType.END_IF, params: {} },
            { id: 'z24', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'z25', type: CommandType.SHOOT, params: { text: '⚔️' } },
            { id: 'z26', type: CommandType.PLAY_SOUND, params: { text: 'sword' } },
            { id: 'z27', type: CommandType.END_IF, params: {} },
            { id: 'z28', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '💎' } },
            { id: 'z29', type: CommandType.CHANGE_VAR, params: { varName: 'rupees', value: 1 } },
            { id: 'z30', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'z31', type: CommandType.END_IF, params: {} },
            { id: 'win_zelda', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'rupees', value: 20 } },
            { id: 'win_zelda2', type: CommandType.WIN_GAME, params: {} },
            { id: 'win_zelda3', type: CommandType.END_IF, params: {} },
            { id: 'z32', type: CommandType.END_FOREVER, params: {} },
        ]
    },
    {
        id: 'tpl_classic_pacman',
        mode: AppMode.GAME,
        name: 'Pacman Clone',
        description: 'Eat dots, avoid ghosts, collect power pellets',
        icon: Ghost,
        color: 'bg-gradient-to-r from-yellow-400 to-yellow-600',
        commands: [
            { id: 'p1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 'p2', type: CommandType.SET_EMOJI, params: { text: '👻' } },
            { id: 'p3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
            { id: 'p4', type: CommandType.SET_VAR, params: { varName: 'lives', value: 3 } },
            { id: 'p5', type: CommandType.SPAWN_ENEMY, params: { text: '👻' } },
            { id: 'p6', type: CommandType.SPAWN_ENEMY, params: { text: '👾' } },
            { id: 'p7', type: CommandType.SPAWN_ITEM, params: { text: '🟡' } },
            { id: 'p8', type: CommandType.FOREVER, params: {} },
            { id: 'p9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'p10', type: CommandType.MOVE_X, params: { value: -5 } },
            { id: 'p11', type: CommandType.END_IF, params: {} },
            { id: 'p12', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'p13', type: CommandType.MOVE_X, params: { value: 5 } },
            { id: 'p14', type: CommandType.END_IF, params: {} },
            { id: 'p15', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
            { id: 'p16', type: CommandType.MOVE_Y, params: { value: -5 } },
            { id: 'p17', type: CommandType.END_IF, params: {} },
            { id: 'p18', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
            { id: 'p19', type: CommandType.MOVE_Y, params: { value: 5 } },
            { id: 'p20', type: CommandType.END_IF, params: {} },
            { id: 'p21', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🟡' } },
            { id: 'p22', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
            { id: 'p23', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'p24', type: CommandType.END_IF, params: {} },
            { id: 'p25', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '👻' } },
            { id: 'p26', type: CommandType.CHANGE_VAR, params: { varName: 'lives', value: -1 } },
            { id: 'p27', type: CommandType.PLAY_SOUND, params: { text: 'death' } },
            { id: 'p28', type: CommandType.END_IF, params: {} },
            { id: 'lose_pacman', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'lives', value: 0 } },
            { id: 'lose_pacman2', type: CommandType.GAME_OVER, params: {} },
            { id: 'lose_pacman3', type: CommandType.END_IF, params: {} },
            { id: 'p29', type: CommandType.END_FOREVER, params: {} },
        ]
    },
    {
        id: 'tpl_classic_snake',
        mode: AppMode.GAME,
        name: 'Snake Clone',
        description: 'Grow longer by eating food, avoid hitting walls and yourself',
        icon: ArrowDown,
        color: 'bg-gradient-to-r from-lime-500 to-green-600',
        commands: [
            { id: 'sn1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 'sn2', type: CommandType.SET_EMOJI, params: { text: '🐍' } },
            { id: 'sn3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
            { id: 'sn4', type: CommandType.SET_VAR, params: { varName: 'length', value: 3 } },
            { id: 'sn5', type: CommandType.SPAWN_ITEM, params: { text: '🍎' } },
            { id: 'sn6', type: CommandType.BOUNCE_ON_EDGE, params: {} },
            { id: 'sn7', type: CommandType.FOREVER, params: {} },
            { id: 'sn8', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'sn9', type: CommandType.MOVE_X, params: { value: -5 } },
            { id: 'sn10', type: CommandType.PLAY_SOUND, params: { text: 'click' } },
            { id: 'sn11', type: CommandType.END_IF, params: {} },
            { id: 'sn12', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'sn13', type: CommandType.MOVE_X, params: { value: 5 } },
            { id: 'sn14', type: CommandType.PLAY_SOUND, params: { text: 'click' } },
            { id: 'sn15', type: CommandType.END_IF, params: {} },
            { id: 'sn16', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
            { id: 'sn17', type: CommandType.MOVE_Y, params: { value: -5 } },
            { id: 'sn18', type: CommandType.PLAY_SOUND, params: { text: 'click' } },
            { id: 'sn19', type: CommandType.END_IF, params: {} },
            { id: 'sn20', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
            { id: 'sn21', type: CommandType.MOVE_Y, params: { value: 5 } },
            { id: 'sn22', type: CommandType.PLAY_SOUND, params: { text: 'click' } },
            { id: 'sn23', type: CommandType.END_IF, params: {} },
            { id: 'sn24', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🍎' } },
            { id: 'sn25', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
            { id: 'sn26', type: CommandType.CHANGE_VAR, params: { varName: 'length', value: 1 } },
            { id: 'sn27', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'sn28', type: CommandType.SPAWN_PARTICLES, params: { value: 3 } },
            { id: 'sn29', type: CommandType.END_IF, params: {} },
            { id: 'lose_snake', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'length', value: 0 } },
            { id: 'lose_snake2', type: CommandType.GAME_OVER, params: {} },
            { id: 'lose_snake3', type: CommandType.END_IF, params: {} },
            { id: 'sn30', type: CommandType.END_FOREVER, params: {} },
        ]
    },
    {
        id: 'tpl_classic_breakout',
        mode: AppMode.GAME,
        name: 'Breakout Clone',
        description: 'Break bricks with a bouncing ball, clear all levels',
        icon: Zap,
        color: 'bg-gradient-to-r from-orange-500 to-red-600',
        commands: [
            { id: 'b1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 'b2', type: CommandType.SET_EMOJI, params: { text: '🟩' } },
            { id: 'b3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
            { id: 'b4', type: CommandType.SET_VAR, params: { varName: 'bricks', value: 20 } },
            { id: 'b5', type: CommandType.SET_GRAVITY, params: { condition: 'false' } },
            { id: 'b6', type: CommandType.SPAWN_PARTICLES, params: { value: 10 } },
            { id: 'b7', type: CommandType.FOREVER, params: {} },
            { id: 'b8', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'b9', type: CommandType.MOVE_X, params: { value: -8 } },
            { id: 'b10', type: CommandType.END_IF, params: {} },
            { id: 'b11', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'b12', type: CommandType.MOVE_X, params: { value: 8 } },
            { id: 'b13', type: CommandType.END_IF, params: {} },
            { id: 'b14', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'b15', type: CommandType.SHOOT, params: { text: '🔴' } },
            { id: 'b16', type: CommandType.PLAY_SOUND, params: { text: 'launch' } },
            { id: 'b17', type: CommandType.END_IF, params: {} },
            { id: 'b18', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🟩' } },
            { id: 'b19', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
            { id: 'b20', type: CommandType.CHANGE_VAR, params: { varName: 'bricks', value: -1 } },
            { id: 'b21', type: CommandType.PLAY_SOUND, params: { text: 'break' } },
            { id: 'b22', type: CommandType.SPAWN_PARTICLES, params: { value: 5 } },
            { id: 'b23', type: CommandType.END_IF, params: {} },
            { id: 'win_breakout', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'bricks', value: 0 } },
            { id: 'win_breakout2', type: CommandType.WIN_GAME, params: {} },
            { id: 'win_breakout3', type: CommandType.END_IF, params: {} },
            { id: 'b24', type: CommandType.END_FOREVER, params: {} },
        ]
    },
    {
        id: 'tpl_classic_flappy',
        mode: AppMode.GAME,
        name: 'Flappy Bird Clone',
        description: 'Tap to fly, avoid pipes, beat your high score',
        icon: Target,
        color: 'bg-gradient-to-r from-sky-400 to-blue-500',
        commands: [
            { id: 'fb1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 'fb2', type: CommandType.SET_EMOJI, params: { text: '🐦' } },
            { id: 'fb3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
            { id: 'fb4', type: CommandType.SET_VAR, params: { varName: 'best', value: 0 } },
            { id: 'fb5', type: CommandType.SET_GRAVITY, params: { condition: 'true' } },
            { id: 'fb6', type: CommandType.SPAWN_ENEMY, params: { text: '🟢' } },
            { id: 'fb7', type: CommandType.SPAWN_ENEMY, params: { text: '🟢' } },
            { id: 'fb8', type: CommandType.FOREVER, params: {} },
            { id: 'fb9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'fb10', type: CommandType.JUMP, params: { value: 8 } },
            { id: 'fb11', type: CommandType.PLAY_SOUND, params: { text: 'flap' } },
            { id: 'fb12', type: CommandType.SPAWN_PARTICLES, params: { value: 2 } },
            { id: 'fb13', type: CommandType.END_IF, params: {} },
            { id: 'fb14', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🟢' } },
            { id: 'fb15', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 1 } },
            { id: 'fb16', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'fb17', type: CommandType.END_IF, params: {} },
            { id: 'win_flappy', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'score', value: 20 } },
            { id: 'win_flappy2', type: CommandType.WIN_GAME, params: {} },
            { id: 'win_flappy3', type: CommandType.END_IF, params: {} },
            { id: 'fb18', type: CommandType.END_FOREVER, params: {} },
        ]
    },
    {
        id: 'tpl_classic_match3_deluxe',
        mode: AppMode.GAME,
        name: 'Match-3 Deluxe',
        description: 'Advanced gem matching with power-ups, cascades, and combo multipliers',
        icon: Zap,
        color: 'bg-gradient-to-r from-fuchsia-500 to-purple-600',
        commands: [
            { id: 'm3d1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 'm3d2', type: CommandType.SET_EMOJI, params: { text: '💎' } },
            { id: 'm3d3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
            { id: 'm3d4', type: CommandType.SET_VAR, params: { varName: 'moves', value: 30 } },
            { id: 'm3d5', type: CommandType.SET_VAR, params: { varName: 'combo', value: 1 } },
            { id: 'm3d6', type: CommandType.SET_VAR, params: { varName: 'power', value: 0 } },
            { id: 'm3d7', type: CommandType.SAY, params: { text: 'Match 3 or more!' } },
            { id: 'm3d8', type: CommandType.FOREVER, params: {} },
            { id: 'm3d9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'm3d10', type: CommandType.SWAP_TILES, params: {} },
            { id: 'm3d11', type: CommandType.CHECK_MATCH, params: {} },
            { id: 'm3d12', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
            { id: 'm3d13', type: CommandType.CHANGE_VAR, params: { varName: 'moves', value: -1 } },
            { id: 'm3d14', type: CommandType.CHANGE_VAR, params: { varName: 'combo', value: 1 } },
            { id: 'm3d15', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'm3d16', type: CommandType.SPAWN_PARTICLES, params: { value: 8 } },
            { id: 'm3d17', type: CommandType.END_IF, params: {} },
            { id: 'm3d18', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } },
            { id: 'm3d19', type: CommandType.SHOOT, params: { text: '✨' } },
            { id: 'm3d20', type: CommandType.CHANGE_VAR, params: { varName: 'power', value: 1 } },
            { id: 'm3d21', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
            { id: 'm3d22', type: CommandType.SPAWN_PARTICLES, params: { value: 15 } },
            { id: 'm3d23', type: CommandType.END_IF, params: {} },
            { id: 'win_match3', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'score', value: 500 } },
            { id: 'win_match3_2', type: CommandType.WIN_GAME, params: {} },
            { id: 'win_match3_3', type: CommandType.END_IF, params: {} },
            { id: 'lose_match3', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'moves', value: 0 } },
            { id: 'lose_match3_2', type: CommandType.GAME_OVER, params: {} },
            { id: 'lose_match3_3', type: CommandType.END_IF, params: {} },
            { id: 'm3d24', type: CommandType.END_FOREVER, params: {} },
        ]
    },
    {
        id: 'tpl_classic_physics',
        mode: AppMode.GAME,
        name: 'Physics Sandbox',
        description: 'Drop objects, watch them interact with realistic physics',
        icon: Box,
        color: 'bg-gradient-to-r from-slate-500 to-gray-600',
        commands: [
            { id: 'ph1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 'ph2', type: CommandType.SET_EMOJI, params: { text: '🟦' } },
            { id: 'ph3', type: CommandType.SET_GRAVITY, params: { condition: 'true' } },
            { id: 'ph4', type: CommandType.SET_PHYSICS_TYPE, params: { text: 'dynamic' } },
            { id: 'ph5', type: CommandType.SET_VAR, params: { varName: 'objects', value: 0 } },
            { id: 'ph6', type: CommandType.SAY, params: { text: 'Drop objects!' } },
            { id: 'ph7', type: CommandType.FOREVER, params: {} },
            { id: 'ph8', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'ph9', type: CommandType.CREATE_CLONE, params: {} },
            { id: 'ph10', type: CommandType.CHANGE_VAR, params: { varName: 'objects', value: 1 } },
            { id: 'ph11', type: CommandType.PLAY_SOUND, params: { text: 'drop' } },
            { id: 'ph12', type: CommandType.END_IF, params: {} },
            { id: 'ph13', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } },
            { id: 'ph14', type: CommandType.APPLY_FORCE, params: { value: 10 } },
            { id: 'ph15', type: CommandType.PLAY_SOUND, params: { text: 'launch' } },
            { id: 'ph16', type: CommandType.END_IF, params: {} },
            { id: 'ph17', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'ph18', type: CommandType.MOVE_X, params: { value: -5 } },
            { id: 'ph19', type: CommandType.END_IF, params: {} },
            { id: 'ph20', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'ph21', type: CommandType.MOVE_X, params: { value: 5 } },
            { id: 'ph22', type: CommandType.END_IF, params: {} },
            { id: 'ph23', type: CommandType.END_FOREVER, params: {} },
        ]
    },
    {
        id: 'tpl_classic_city',
        mode: AppMode.GAME,
        name: 'City Builder',
        description: 'Place buildings, manage resources, grow your city',
        icon: Landmark,
        color: 'bg-gradient-to-r from-stone-500 to-stone-700',
        commands: [
            { id: 'cb1', type: CommandType.SET_TITLE, params: { text: 'My City' } },
            { id: 'cb2', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 'cb3', type: CommandType.SET_EMOJI, params: { text: '🏠' } },
            { id: 'cb4', type: CommandType.SET_VAR, params: { varName: 'gold', value: 500 } },
            { id: 'cb5', type: CommandType.SET_VAR, params: { varName: 'population', value: 0 } },
            { id: 'cb6', type: CommandType.SET_VAR, params: { varName: 'buildings', value: 0 } },
            { id: 'cb7', type: CommandType.SAY, params: { text: 'Build your dream city!' } },
            { id: 'cb8', type: CommandType.FOREVER, params: {} },
            { id: 'cb9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'cb10', type: CommandType.BUILD, params: { text: 'house' } },
            { id: 'cb11', type: CommandType.CHANGE_VAR, params: { varName: 'gold', value: -50 } },
            { id: 'cb12', type: CommandType.CHANGE_VAR, params: { varName: 'population', value: 4 } },
            { id: 'cb13', type: CommandType.CHANGE_VAR, params: { varName: 'buildings', value: 1 } },
            { id: 'cb14', type: CommandType.PLAY_SOUND, params: { text: 'build' } },
            { id: 'cb15', type: CommandType.SPAWN_PARTICLES, params: { value: 5 } },
            { id: 'cb16', type: CommandType.END_IF, params: {} },
            { id: 'cb17', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } },
            { id: 'cb18', type: CommandType.BUILD, params: { text: 'farm' } },
            { id: 'cb19', type: CommandType.CHANGE_VAR, params: { varName: 'gold', value: -30 } },
            { id: 'cb20', type: CommandType.CHANGE_VAR, params: { varName: 'population', value: 2 } },
            { id: 'cb21', type: CommandType.PLAY_SOUND, params: { text: 'build' } },
            { id: 'cb22', type: CommandType.END_IF, params: {} },
            { id: 'cb23', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'cb24', type: CommandType.BUILD, params: { text: 'shop' } },
            { id: 'cb25', type: CommandType.CHANGE_VAR, params: { varName: 'gold', value: -80 } },
            { id: 'cb26', type: CommandType.CHANGE_VAR, params: { varName: 'population', value: 6 } },
            { id: 'cb27', type: CommandType.PLAY_SOUND, params: { text: 'build' } },
            { id: 'cb28', type: CommandType.END_IF, params: {} },
            { id: 'cb29', type: CommandType.IF, params: { condition: 'GREATER' } },
            { id: 'cb30', type: CommandType.CHANGE_VAR, params: { varName: 'gold', value: 10 } },
            { id: 'cb31', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'cb32', type: CommandType.END_IF, params: {} },
            { id: 'win_city', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'population', value: 100 } },
            { id: 'win_city2', type: CommandType.WIN_GAME, params: {} },
            { id: 'win_city3', type: CommandType.END_IF, params: {} },
            { id: 'cb33', type: CommandType.END_FOREVER, params: {} },
        ]
    },
    {
        id: 'tpl_classic_farm',
        mode: AppMode.GAME,
        name: 'Farm Simulator',
        description: 'Plant crops, water them, harvest and sell for profit',
        icon: Wheat,
        color: 'bg-gradient-to-r from-amber-500 to-yellow-600',
        commands: [
            { id: 'fs1', type: CommandType.SET_TITLE, params: { text: 'My Farm' } },
            { id: 'fs2', type: CommandType.SET_SCENE, params: { text: 'grass' } },
            { id: 'fs3', type: CommandType.SET_EMOJI, params: { text: '🧑‍🌾' } },
            { id: 'fs4', type: CommandType.SET_VAR, params: { varName: 'gold', value: 100 } },
            { id: 'fs5', type: CommandType.SET_VAR, params: { varName: 'crops', value: 0 } },
            { id: 'fs6', type: CommandType.SET_VAR, params: { varName: 'water', value: 10 } },
            { id: 'fs7', type: CommandType.SAY, params: { text: 'Welcome to the farm!' } },
            { id: 'fs8', type: CommandType.PLAY_SOUND, params: { text: 'ambient' } },
            { id: 'fs9', type: CommandType.FOREVER, params: {} },
            { id: 'fs10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'fs11', type: CommandType.SHOOT, params: { text: '🌱' } },
            { id: 'fs12', type: CommandType.CHANGE_VAR, params: { varName: 'crops', value: 1 } },
            { id: 'fs13', type: CommandType.PLAY_SOUND, params: { text: 'plant' } },
            { id: 'fs14', type: CommandType.END_IF, params: {} },
            { id: 'fs15', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } },
            { id: 'fs16', type: CommandType.CHANGE_VAR, params: { varName: 'water', value: -1 } },
            { id: 'fs17', type: CommandType.PLAY_SOUND, params: { text: 'splash' } },
            { id: 'fs18', type: CommandType.END_IF, params: {} },
            { id: 'fs19', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'fs20', type: CommandType.SHOOT, params: { text: '🌾' } },
            { id: 'fs21', type: CommandType.CHANGE_VAR, params: { varName: 'gold', value: 20 } },
            { id: 'fs22', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'fs23', type: CommandType.SPAWN_PARTICLES, params: { value: 5 } },
            { id: 'fs24', type: CommandType.END_IF, params: {} },
            { id: 'fs25', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'fs26', type: CommandType.SHOOT, params: { text: '🌽' } },
            { id: 'fs27', type: CommandType.CHANGE_VAR, params: { varName: 'crops', value: 1 } },
            { id: 'fs28', type: CommandType.PLAY_SOUND, params: { text: 'plant' } },
            { id: 'fs29', type: CommandType.END_IF, params: {} },
            { id: 'win_farm', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'gold', value: 1000 } },
            { id: 'win_farm2', type: CommandType.WIN_GAME, params: {} },
            { id: 'win_farm3', type: CommandType.END_IF, params: {} },
            { id: 'fs30', type: CommandType.END_FOREVER, params: {} },
        ]
    },
];
