import { AppMode, CommandType, CircuitComponent, CommandBlock } from '../../types';
import { LucideIcon, Skull, Rocket, Building2, Wheat, CreditCard } from 'lucide-react';

export const cycle9Templates: {
    id: string,
    mode: AppMode,
    name: string,
    description: string,
    icon: LucideIcon,
    color: string,
    commands: CommandBlock[],
    circuitComponents?: CircuitComponent[]
}[] = [
    {
        id: 'tpl_zombie_waves',
        mode: AppMode.GAME,
        name: 'Zombie Wave Defense',
        description: 'Defend against increasingly difficult zombie waves!',
        icon: Skull,
        color: 'bg-gradient-to-r from-green-800 to-red-900',
        commands: [
            { id: 'zw1', type: CommandType.SET_SCENE, params: { text: 'grass' } },
            { id: 'zw2', type: CommandType.SET_EMOJI, params: { text: '🧟' } },
            { id: 'zw3', type: CommandType.SET_VAR, params: { varName: 'wave', value: 1 } },
            { id: 'zw4', type: CommandType.SET_VAR, params: { varName: 'kills', value: 0 } },
            { id: 'zw5', type: CommandType.SET_VAR, params: { varName: 'health', value: 100 } },
            { id: 'zw6', type: CommandType.SET_WEATHER, params: { text: 'rain' } },
            { id: 'zw7', type: CommandType.SPAWN_ENEMY, params: { text: '🧟' } },
            { id: 'zw8', type: CommandType.FOREVER, params: {} },
            { id: 'zw9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'zw10', type: CommandType.SHOOT, params: { text: '🔫' } },
            { id: 'zw11', type: CommandType.PLAY_SOUND, params: { text: 'shoot' } },
            { id: 'zw12', type: CommandType.CHANGE_VAR, params: { varName: 'kills', value: 1 } },
            { id: 'zw13', type: CommandType.END_IF, params: {} },
            { id: 'zw14', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 33 } },
            { id: 'zw15', type: CommandType.BUILD, params: { text: 'wall', value: 2 } },
            { id: 'zw16', type: CommandType.END_IF, params: {} },
            { id: 'zw17', type: CommandType.IF, params: { condition: 'IS_GREATER', varName: 'kills', value: 10 } },
            { id: 'zw18', type: CommandType.CHANGE_VAR, params: { varName: 'wave', value: 1 } },
            { id: 'zw19', type: CommandType.SET_VAR, params: { varName: 'kills', value: 0 } },
            { id: 'zw20', type: CommandType.SPAWN_ENEMY, params: { text: '🧟' } },
            { id: 'zw21', type: CommandType.SPAWN_ENEMY, params: { text: '🧟' } },
            { id: 'zw22', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
            { id: 'zw23', type: CommandType.SAY, params: { text: 'Wave 2!' } },
            { id: 'zw24', type: CommandType.END_IF, params: {} },
            { id: 'zw25', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'health', value: 0 } },
            { id: 'zw26', type: CommandType.GAME_OVER, params: {} },
            { id: 'zw27', type: CommandType.END_IF, params: {} },
            { id: 'zw28', type: CommandType.END_FOREVER, params: {} }
        ]
    },
    {
        id: 'tpl_space_explorer',
        mode: AppMode.GAME,
        name: 'Space Explorer',
        description: 'Explore planets, discover resources, and travel the galaxy!',
        icon: Rocket,
        color: 'bg-gradient-to-r from-indigo-600 to-blue-800',
        commands: [
            { id: 'se1', type: CommandType.SET_SCENE, params: { text: 'space' } },
            { id: 'se2', type: CommandType.SET_EMOJI, params: { text: '🚀' } },
            { id: 'se3', type: CommandType.SET_VAR, params: { varName: 'fuel', value: 100 } },
            { id: 'se4', type: CommandType.SET_VAR, params: { varName: 'planets', value: 0 } },
            { id: 'se5', type: CommandType.SET_VAR, params: { varName: 'resources', value: 0 } },
            { id: 'se6', type: CommandType.FOREVER, params: {} },
            { id: 'se7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'se8', type: CommandType.MOVE_X, params: { value: -5 } },
            { id: 'se9', type: CommandType.CHANGE_VAR, params: { varName: 'fuel', value: -1 } },
            { id: 'se10', type: CommandType.END_IF, params: {} },
            { id: 'se11', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'se12', type: CommandType.MOVE_X, params: { value: 5 } },
            { id: 'se13', type: CommandType.CHANGE_VAR, params: { varName: 'fuel', value: -1 } },
            { id: 'se14', type: CommandType.END_IF, params: {} },
            { id: 'se15', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'se16', type: CommandType.JUMP, params: { value: 12 } },
            { id: 'se17', type: CommandType.END_IF, params: {} },
            { id: 'se18', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 33 } },
            { id: 'se19', type: CommandType.GATHER, params: { text: 'crystal', value: 1 } },
            { id: 'se20', type: CommandType.CHANGE_VAR, params: { varName: 'resources', value: 5 } },
            { id: 'se21', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'se22', type: CommandType.END_IF, params: {} },
            { id: 'se23', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🪐' } },
            { id: 'se24', type: CommandType.CHANGE_VAR, params: { varName: 'planets', value: 1 } },
            { id: 'se25', type: CommandType.CHANGE_VAR, params: { varName: 'fuel', value: 20 } },
            { id: 'se26', type: CommandType.SAY, params: { text: 'New planet discovered!' } },
            { id: 'se27', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
            { id: 'se28', type: CommandType.END_IF, params: {} },
            { id: 'win_space', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'planets', value: 5 } },
            { id: 'win_space2', type: CommandType.WIN_GAME, params: {} },
            { id: 'win_space3', type: CommandType.SAY, params: { text: 'Galaxy explored!' } },
            { id: 'win_space4', type: CommandType.END_IF, params: {} },
            { id: 'lose_space', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'fuel', value: 0 } },
            { id: 'lose_space2', type: CommandType.GAME_OVER, params: {} },
            { id: 'lose_space3', type: CommandType.SAY, params: { text: 'Out of fuel!' } },
            { id: 'lose_space4', type: CommandType.END_IF, params: {} },
            { id: 'se29', type: CommandType.END_FOREVER, params: {} }
        ]
    },
    {
        id: 'tpl_city_builder',
        mode: AppMode.GAME,
        name: 'City Builder',
        description: 'Manage resources, build structures, and grow your city!',
        icon: Building2,
        color: 'bg-gradient-to-r from-gray-600 to-blue-700',
        commands: [
            { id: 'cb1', type: CommandType.SET_SCENE, params: { text: 'grass' } },
            { id: 'cb2', type: CommandType.SET_EMOJI, params: { text: '🏗️' } },
            { id: 'cb3', type: CommandType.SET_VAR, params: { varName: 'money', value: 500 } },
            { id: 'cb4', type: CommandType.SET_VAR, params: { varName: 'population', value: 10 } },
            { id: 'cb5', type: CommandType.SET_VAR, params: { varName: 'happiness', value: 50 } },
            { id: 'cb6', type: CommandType.SET_VAR, params: { varName: 'buildings', value: 0 } },
            { id: 'cb7', type: CommandType.FOREVER, params: {} },
            { id: 'cb8', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'cb9', type: CommandType.BUILD, params: { text: 'house', value: 50 } },
            { id: 'cb10', type: CommandType.CHANGE_VAR, params: { varName: 'population', value: 5 } },
            { id: 'cb11', type: CommandType.CHANGE_VAR, params: { varName: 'buildings', value: 1 } },
            { id: 'cb12', type: CommandType.PLAY_SOUND, params: { text: 'build' } },
            { id: 'cb13', type: CommandType.END_IF, params: {} },
            { id: 'cb14', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 33 } },
            { id: 'cb15', type: CommandType.BUILD, params: { text: 'factory', value: 100 } },
            { id: 'cb16', type: CommandType.CHANGE_VAR, params: { varName: 'money', value: 50 } },
            { id: 'cb17', type: CommandType.CHANGE_VAR, params: { varName: 'happiness', value: -5 } },
            { id: 'cb18', type: CommandType.END_IF, params: {} },
            { id: 'cb19', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } },
            { id: 'cb20', type: CommandType.BUILD, params: { text: 'park', value: 30 } },
            { id: 'cb21', type: CommandType.CHANGE_VAR, params: { varName: 'happiness', value: 10 } },
            { id: 'cb22', type: CommandType.END_IF, params: {} },
            { id: 'cb23', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 35 } },
            { id: 'cb24', type: CommandType.GATHER, params: { text: 'tax', value: 1 } },
            { id: 'cb25', type: CommandType.CHANGE_VAR, params: { varName: 'money', value: 10 } },
            { id: 'cb26', type: CommandType.END_IF, params: {} },
            { id: 'win_city', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'population', value: 100 } },
            { id: 'win_city2', type: CommandType.WIN_GAME, params: {} },
            { id: 'win_city3', type: CommandType.SAY, params: { text: 'Metropolis achieved!' } },
            { id: 'win_city4', type: CommandType.END_IF, params: {} },
            { id: 'cb27', type: CommandType.END_FOREVER, params: {} }
        ]
    },
    {
        id: 'tpl_farm_sim',
        mode: AppMode.GAME,
        name: 'Farm Simulator',
        description: 'Plant crops, harvest, and build your dream farm!',
        icon: Wheat,
        color: 'bg-gradient-to-r from-green-500 to-yellow-600',
        commands: [
            { id: 'fs1', type: CommandType.SET_SCENE, params: { text: 'grass' } },
            { id: 'fs2', type: CommandType.SET_EMOJI, params: { text: '👨‍🌾' } },
            { id: 'fs3', type: CommandType.SET_VAR, params: { varName: 'gold', value: 100 } },
            { id: 'fs4', type: CommandType.SET_VAR, params: { varName: 'crops', value: 0 } },
            { id: 'fs5', type: CommandType.SET_VAR, params: { varName: 'water', value: 50 } },
            { id: 'fs6', type: CommandType.SET_VAR, params: { varName: 'season', value: 1 } },
            { id: 'fs7', type: CommandType.FOREVER, params: {} },
            { id: 'fs8', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'fs9', type: CommandType.BUILD, params: { text: '🌱' } },
            { id: 'fs10', type: CommandType.CHANGE_VAR, params: { varName: 'crops', value: 1 } },
            { id: 'fs11', type: CommandType.CHANGE_VAR, params: { varName: 'water', value: -5 } },
            { id: 'fs12', type: CommandType.PLAY_SOUND, params: { text: 'plant' } },
            { id: 'fs13', type: CommandType.END_IF, params: {} },
            { id: 'fs14', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 33 } },
            { id: 'fs15', type: CommandType.GATHER, params: { text: 'wheat', value: 1 } },
            { id: 'fs16', type: CommandType.CHANGE_VAR, params: { varName: 'crops', value: -1 } },
            { id: 'fs17', type: CommandType.CHANGE_VAR, params: { varName: 'gold', value: 10 } },
            { id: 'fs18', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'fs19', type: CommandType.END_IF, params: {} },
            { id: 'fs20', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } },
            { id: 'fs21', type: CommandType.DRINK, params: { value: 10 } },
            { id: 'fs22', type: CommandType.CHANGE_VAR, params: { varName: 'water', value: 15 } },
            { id: 'fs23', type: CommandType.END_IF, params: {} },
            { id: 'fs24', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 35 } },
            { id: 'fs25', type: CommandType.BUILD, params: { text: 'barn', value: 50 } },
            { id: 'fs26', type: CommandType.CHANGE_VAR, params: { varName: 'season', value: 1 } },
            { id: 'fs27', type: CommandType.SAY, params: { text: 'New season!' } },
            { id: 'fs28', type: CommandType.END_IF, params: {} },
            { id: 'win_farm', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'gold', value: 500 } },
            { id: 'win_farm2', type: CommandType.WIN_GAME, params: {} },
            { id: 'win_farm3', type: CommandType.SAY, params: { text: 'Master Farmer!' } },
            { id: 'win_farm4', type: CommandType.END_IF, params: {} },
            { id: 'fs29', type: CommandType.END_FOREVER, params: {} }
        ]
    },
    {
        id: 'tpl_card_battle',
        mode: AppMode.GAME,
        name: 'Card Battle',
        description: 'Play cards strategically to defeat opponents!',
        icon: CreditCard,
        color: 'bg-gradient-to-r from-purple-600 to-pink-700',
        commands: [
            { id: 'cd1', type: CommandType.SET_SCENE, params: { text: 'dark' } },
            { id: 'cd2', type: CommandType.SET_EMOJI, params: { text: '🃏' } },
            { id: 'cd3', type: CommandType.SET_VAR, params: { varName: 'mana', value: 10 } },
            { id: 'cd4', type: CommandType.SET_VAR, params: { varName: 'health', value: 30 } },
            { id: 'cd5', type: CommandType.SET_VAR, params: { varName: 'enemyHealth', value: 30 } },
            { id: 'cd6', type: CommandType.SET_VAR, params: { varName: 'cardsPlayed', value: 0 } },
            { id: 'cd7', type: CommandType.FOREVER, params: {} },
            { id: 'cd8', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'cd9', type: CommandType.SHOOT, params: { text: '🔥' } },
            { id: 'cd10', type: CommandType.CHANGE_VAR, params: { varName: 'enemyHealth', value: -5 } },
            { id: 'cd11', type: CommandType.CHANGE_VAR, params: { varName: 'mana', value: -2 } },
            { id: 'cd12', type: CommandType.CHANGE_VAR, params: { varName: 'cardsPlayed', value: 1 } },
            { id: 'cd13', type: CommandType.PLAY_SOUND, params: { text: 'attack' } },
            { id: 'cd14', type: CommandType.END_IF, params: {} },
            { id: 'cd15', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 33 } },
            { id: 'cd16', type: CommandType.SHOOT, params: { text: '❄️' } },
            { id: 'cd17', type: CommandType.CHANGE_VAR, params: { varName: 'enemyHealth', value: -8 } },
            { id: 'cd18', type: CommandType.CHANGE_VAR, params: { varName: 'mana', value: -3 } },
            { id: 'cd19', type: CommandType.CHANGE_VAR, params: { varName: 'cardsPlayed', value: 1 } },
            { id: 'cd20', type: CommandType.PLAY_SOUND, params: { text: 'freeze' } },
            { id: 'cd21', type: CommandType.END_IF, params: {} },
            { id: 'cd22', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } },
            { id: 'cd23', type: CommandType.CHANGE_VAR, params: { varName: 'health', value: 5 } },
            { id: 'cd24', type: CommandType.CHANGE_VAR, params: { varName: 'mana', value: -4 } },
            { id: 'cd25', type: CommandType.CHANGE_VAR, params: { varName: 'cardsPlayed', value: 1 } },
            { id: 'cd26', type: CommandType.PLAY_SOUND, params: { text: 'heal' } },
            { id: 'cd27', type: CommandType.END_IF, params: {} },
            { id: 'cd28', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 35 } },
            { id: 'cd29', type: CommandType.CHANGE_VAR, params: { varName: 'mana', value: 5 } },
            { id: 'cd30', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
            { id: 'cd31', type: CommandType.END_IF, params: {} },
            { id: 'cd32', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'enemyHealth', value: 0 } },
            { id: 'cd33', type: CommandType.WIN_GAME, params: {} },
            { id: 'cd34', type: CommandType.SAY, params: { text: 'Victory!' } },
            { id: 'cd35', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
            { id: 'cd36', type: CommandType.END_IF, params: {} },
            { id: 'cd37', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'health', value: 0 } },
            { id: 'cd38', type: CommandType.GAME_OVER, params: {} },
            { id: 'cd39', type: CommandType.SAY, params: { text: 'Defeated!' } },
            { id: 'cd40', type: CommandType.END_IF, params: {} },
            { id: 'cd41', type: CommandType.END_FOREVER, params: {} }
        ]
    }
];