import { AppMode, CommandType, CircuitComponent, CommandBlock } from '../../types';
import { LucideIcon, Shield, Swords, UtensilsCrossed, Wheat, Building2, EyeOff, Skull, Gamepad2, Dices, Music, FlaskConical, Landmark, BookOpen, HelpCircle, Paintbrush } from 'lucide-react';

export const genreTemplates: {
    id: string,
    mode: AppMode,
    name: string,
    description: string,
    icon: LucideIcon,
    color: string,
    commands: CommandBlock[],
    circuitComponents?: CircuitComponent[]
}[] = [
    {
        id: 'tpl_genre_towerdefense',
        mode: AppMode.GAME,
        name: 'Tower Defense',
        description: 'Build towers to defend against waves of enemies!',
        icon: Shield,
        color: 'bg-gradient-to-r from-stone-600 to-stone-800',
        commands: [
            { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🏰' } },
            { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'gold', value: 100 } },
            { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'wave', value: 1 } },
            { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'lives', value: 20 } },
            { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '👾' } },
            { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '👺' } },
            { id: 'e3', type: CommandType.SPAWN_ENEMY, params: { text: '💀' } },
            { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'battle' } },
            { id: 'f1', type: CommandType.FOREVER, params: {} },
            { id: 'p1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '🗼' } },
            { id: 'p3', type: CommandType.CHANGE_VAR, params: { varName: 'gold', value: -25 } },
            { id: 'p4', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'p5', type: CommandType.END_IF, params: {} },
            { id: 'k1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '👾' } },
            { id: 'k2', type: CommandType.CHANGE_VAR, params: { varName: 'gold', value: 10 } },
            { id: 'k3', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
            { id: 'k4', type: CommandType.END_IF, params: {} },
            { id: 'g1', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'lives', value: 0 } },
            { id: 'g2', type: CommandType.GAME_OVER, params: {} },
            { id: 'g3', type: CommandType.PLAY_SOUND, params: { text: 'death' } },
            { id: 'g4', type: CommandType.END_IF, params: {} },
            { id: 'f2', type: CommandType.END_FOREVER, params: {} }
        ]
    },
    {
        id: 'tpl_genre_cardbattle',
        mode: AppMode.GAME,
        name: 'Card Battle',
        description: 'Collect cards and battle opponents in strategic duels!',
        icon: Swords,
        color: 'bg-gradient-to-r from-red-600 to-purple-700',
        commands: [
            { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🃏' } },
            { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'health', value: 30 } },
            { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'mana', value: 3 } },
            { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'cards', value: 5 } },
            { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '🧙' } },
            { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'battle' } },
            { id: 'f1', type: CommandType.FOREVER, params: {} },
            { id: 'pl1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'pl2', type: CommandType.SHOOT, params: { text: '🔥' } },
            { id: 'pl3', type: CommandType.CHANGE_VAR, params: { varName: 'mana', value: -1 } },
            { id: 'pl4', type: CommandType.PLAY_SOUND, params: { text: 'attack' } },
            { id: 'pl5', type: CommandType.SAY, params: { text: 'Fireball!' } },
            { id: 'pl6', type: CommandType.END_IF, params: {} },
            { id: 'pl7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 88 } },
            { id: 'pl8', type: CommandType.CHANGE_VAR, params: { varName: 'health', value: 5 } },
            { id: 'pl9', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
            { id: 'pl10', type: CommandType.SAY, params: { text: 'Heal!' } },
            { id: 'pl11', type: CommandType.END_IF, params: {} },
            { id: 'k1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🧙' } },
            { id: 'k2', type: CommandType.CHANGE_VAR, params: { varName: 'cards', value: 1 } },
            { id: 'k3', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'k4', type: CommandType.SAY, params: { text: 'Card captured!' } },
            { id: 'k5', type: CommandType.END_IF, params: {} },
            { id: 'f2', type: CommandType.END_FOREVER, params: {} }
        ]
    },
    {
        id: 'tpl_genre_cooking',
        mode: AppMode.GAME,
        name: 'Kitchen Chaos',
        description: 'Cook dishes quickly before customers leave!',
        icon: UtensilsCrossed,
        color: 'bg-gradient-to-r from-orange-500 to-red-500',
        commands: [
            { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 's2', type: CommandType.SET_EMOJI, params: { text: '👨‍🍳' } },
            { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
            { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'orders', value: 0 } },
            { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'time', value: 60 } },
            { id: 't1', type: CommandType.SET_TIMER, params: { value: 60 } },
            { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '🍔' } },
            { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '🍕' } },
            { id: 'p3', type: CommandType.SPAWN_ITEM, params: { text: '🍣' } },
            { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'upbeat' } },
            { id: 'f1', type: CommandType.FOREVER, params: {} },
            { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'mv2', type: CommandType.MOVE_X, params: { value: -5 } },
            { id: 'mv3', type: CommandType.END_IF, params: {} },
            { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'mv5', type: CommandType.MOVE_X, params: { value: 5 } },
            { id: 'mv6', type: CommandType.END_IF, params: {} },
            { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
            { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -5 } },
            { id: 'mv9', type: CommandType.END_IF, params: {} },
            { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
            { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 5 } },
            { id: 'mv12', type: CommandType.END_IF, params: {} },
            { id: 'co1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🍔' } },
            { id: 'co2', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
            { id: 'co3', type: CommandType.CHANGE_VAR, params: { varName: 'orders', value: 1 } },
            { id: 'co4', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'co5', type: CommandType.SAY, params: { text: 'Order up!' } },
            { id: 'co6', type: CommandType.END_IF, params: {} },
            { id: 'f2', type: CommandType.END_FOREVER, params: {} }
        ]
    },
    {
        id: 'tpl_genre_farming',
        mode: AppMode.GAME,
        name: 'Farm Life',
        description: 'Grow crops, raise animals, and build your farm!',
        icon: Wheat,
        color: 'bg-gradient-to-r from-yellow-500 to-green-500',
        commands: [
            { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grass' } },
            { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🧑‍🌾' } },
            { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'money', value: 50 } },
            { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'crops', value: 0 } },
            { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'animals', value: 0 } },
            { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '🌱' } },
            { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '🐔' } },
            { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'peaceful' } },
            { id: 'f1', type: CommandType.FOREVER, params: {} },
            { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'mv2', type: CommandType.MOVE_X, params: { value: -4 } },
            { id: 'mv3', type: CommandType.END_IF, params: {} },
            { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'mv5', type: CommandType.MOVE_X, params: { value: 4 } },
            { id: 'mv6', type: CommandType.END_IF, params: {} },
            { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
            { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -4 } },
            { id: 'mv9', type: CommandType.END_IF, params: {} },
            { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
            { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 4 } },
            { id: 'mv12', type: CommandType.END_IF, params: {} },
            { id: 'pl1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'pl2', type: CommandType.CHANGE_VAR, params: { varName: 'crops', value: 1 } },
            { id: 'pl3', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'pl4', type: CommandType.SAY, params: { text: 'Planted!' } },
            { id: 'pl5', type: CommandType.END_IF, params: {} },
            { id: 'hv1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🌱' } },
            { id: 'hv2', type: CommandType.CHANGE_VAR, params: { varName: 'money', value: 5 } },
            { id: 'hv3', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
            { id: 'hv4', type: CommandType.END_IF, params: {} },
            { id: 'f2', type: CommandType.END_FOREVER, params: {} }
        ]
    },
    {
        id: 'tpl_genre_citybuilder',
        mode: AppMode.GAME,
        name: 'City Builder',
        description: 'Build and manage a thriving city!',
        icon: Building2,
        color: 'bg-gradient-to-r from-slate-500 to-blue-600',
        commands: [
            { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🏗️' } },
            { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'money', value: 500 } },
            { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'population', value: 0 } },
            { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'happiness', value: 50 } },
            { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '🏠' } },
            { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '🏢' } },
            { id: 'p3', type: CommandType.SPAWN_ITEM, params: { text: '🏭' } },
            { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'ambient' } },
            { id: 'f1', type: CommandType.FOREVER, params: {} },
            { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'mv2', type: CommandType.MOVE_X, params: { value: -5 } },
            { id: 'mv3', type: CommandType.END_IF, params: {} },
            { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'mv5', type: CommandType.MOVE_X, params: { value: 5 } },
            { id: 'mv6', type: CommandType.END_IF, params: {} },
            { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
            { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -5 } },
            { id: 'mv9', type: CommandType.END_IF, params: {} },
            { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
            { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 5 } },
            { id: 'mv12', type: CommandType.END_IF, params: {} },
            { id: 'bl1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'bl2', type: CommandType.CHANGE_VAR, params: { varName: 'money', value: -100 } },
            { id: 'bl3', type: CommandType.CHANGE_VAR, params: { varName: 'population', value: 10 } },
            { id: 'bl4', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'bl5', type: CommandType.SAY, params: { text: 'Building!' } },
            { id: 'bl6', type: CommandType.END_IF, params: {} },
            { id: 'f2', type: CommandType.END_FOREVER, params: {} }
        ]
    },
    {
        id: 'tpl_genre_stealth',
        mode: AppMode.GAME,
        name: 'Shadow Agent',
        description: 'Sneak past guards and complete covert missions!',
        icon: EyeOff,
        color: 'bg-gradient-to-r from-gray-700 to-gray-900',
        commands: [
            { id: 's1', type: CommandType.SET_SCENE, params: { text: 'stone_floor' } },
            { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🕵️' } },
            { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'stealth', value: 100 } },
            { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'alerts', value: 0 } },
            { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'objectives', value: 0 } },
            { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '💂' } },
            { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '💂' } },
            { id: 'e3', type: CommandType.SPAWN_ENEMY, params: { text: '🐕' } },
            { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '🔑' } },
            { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'stealth' } },
            { id: 'f1', type: CommandType.FOREVER, params: {} },
            { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'mv2', type: CommandType.MOVE_X, params: { value: -3 } },
            { id: 'mv3', type: CommandType.END_IF, params: {} },
            { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'mv5', type: CommandType.MOVE_X, params: { value: 3 } },
            { id: 'mv6', type: CommandType.END_IF, params: {} },
            { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
            { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -3 } },
            { id: 'mv9', type: CommandType.END_IF, params: {} },
            { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
            { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 3 } },
            { id: 'mv12', type: CommandType.END_IF, params: {} },
            { id: 'd1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '💂' } },
            { id: 'd2', type: CommandType.CHANGE_VAR, params: { varName: 'stealth', value: -25 } },
            { id: 'd3', type: CommandType.CHANGE_VAR, params: { varName: 'alerts', value: 1 } },
            { id: 'd4', type: CommandType.PLAY_SOUND, params: { text: 'alert' } },
            { id: 'd5', type: CommandType.SAY, params: { text: 'Spotted!' } },
            { id: 'd6', type: CommandType.END_IF, params: {} },
            { id: 'k1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🔑' } },
            { id: 'k2', type: CommandType.CHANGE_VAR, params: { varName: 'objectives', value: 1 } },
            { id: 'k3', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'k4', type: CommandType.END_IF, params: {} },
            { id: 'f2', type: CommandType.END_FOREVER, params: {} }
        ]
    },
    {
        id: 'tpl_genre_horror',
        mode: AppMode.GAME,
        name: 'Night Terrors',
        description: 'Survive the night while avoiding monsters in the dark!',
        icon: Skull,
        color: 'bg-gradient-to-r from-red-900 to-black',
        commands: [
            { id: 's1', type: CommandType.SET_SCENE, params: { text: 'dark' } },
            { id: 's2', type: CommandType.SET_EMOJI, params: { text: '😱' } },
            { id: 's3', type: CommandType.SET_WEATHER, params: { text: 'fog' } },
            { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'sanity', value: 100 } },
            { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'time', value: 0 } },
            { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'lights', value: 3 } },
            { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '👻' } },
            { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '🧟' } },
            { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'horror' } },
            { id: 'f1', type: CommandType.FOREVER, params: {} },
            { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'mv2', type: CommandType.MOVE_X, params: { value: -4 } },
            { id: 'mv3', type: CommandType.END_IF, params: {} },
            { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'mv5', type: CommandType.MOVE_X, params: { value: 4 } },
            { id: 'mv6', type: CommandType.END_IF, params: {} },
            { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
            { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -4 } },
            { id: 'mv9', type: CommandType.END_IF, params: {} },
            { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
            { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 4 } },
            { id: 'mv12', type: CommandType.END_IF, params: {} },
            { id: 'fl1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'fl2', type: CommandType.CHANGE_VAR, params: { varName: 'lights', value: -1 } },
            { id: 'fl3', type: CommandType.PLAY_SOUND, params: { text: 'flashlight' } },
            { id: 'fl4', type: CommandType.SAY, params: { text: '⚡ Flashlight!' } },
            { id: 'fl5', type: CommandType.END_IF, params: {} },
            { id: 'd1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '👻' } },
            { id: 'd2', type: CommandType.CHANGE_VAR, params: { varName: 'sanity', value: -20 } },
            { id: 'd3', type: CommandType.PLAY_SOUND, params: { text: 'scream' } },
            { id: 'd4', type: CommandType.END_IF, params: {} },
            { id: 'f2', type: CommandType.END_FOREVER, params: {} }
        ]
    },
    {
        id: 'tpl_genre_platformer2',
        mode: AppMode.GAME,
        name: 'Pixel Runner',
        description: 'Run, jump, and collect gems in a retro platformer!',
        icon: Gamepad2,
        color: 'bg-gradient-to-r from-indigo-500 to-purple-500',
        commands: [
            { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grass' } },
            { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🏃' } },
            { id: 's3', type: CommandType.SET_GRAVITY, params: { condition: 'true' } },
            { id: 's4', type: CommandType.BOUNCE_ON_EDGE, params: {} },
            { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
            { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'lives', value: 3 } },
            { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'gems', value: 0 } },
            { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '💎' } },
            { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '💎' } },
            { id: 'p3', type: CommandType.SPAWN_ITEM, params: { text: '⭐' } },
            { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'platformer' } },
            { id: 'f1', type: CommandType.FOREVER, params: {} },
            { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'mv2', type: CommandType.MOVE_X, params: { value: -5 } },
            { id: 'mv3', type: CommandType.END_IF, params: {} },
            { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'mv5', type: CommandType.MOVE_X, params: { value: 5 } },
            { id: 'mv6', type: CommandType.END_IF, params: {} },
            { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
            { id: 'mv8', type: CommandType.JUMP, params: { value: 12 } },
            { id: 'mv9', type: CommandType.PLAY_SOUND, params: { text: 'jump' } },
            { id: 'mv10', type: CommandType.END_IF, params: {} },
            { id: 'g1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '💎' } },
            { id: 'g2', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
            { id: 'g3', type: CommandType.CHANGE_VAR, params: { varName: 'gems', value: 1 } },
            { id: 'g4', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'g5', type: CommandType.END_IF, params: {} },
            { id: 'f2', type: CommandType.END_FOREVER, params: {} }
        ]
    },
    {
        id: 'tpl_genre_roguelike',
        mode: AppMode.GAME,
        name: 'Dungeon Explorer',
        description: 'Explore randomly generated dungeons and grow stronger!',
        icon: Dices,
        color: 'bg-gradient-to-r from-amber-700 to-orange-800',
        commands: [
            { id: 's1', type: CommandType.SET_SCENE, params: { text: 'stone_floor' } },
            { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🗡️' } },
            { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'hp', value: 100 } },
            { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'attack', value: 10 } },
            { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'floor', value: 1 } },
            { id: 'v4', type: CommandType.SET_VAR, params: { varName: 'gold', value: 0 } },
            { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '🐲' } },
            { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '💀' } },
            { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '❤️' } },
            { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '⚔️' } },
            { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'dungeon' } },
            { id: 'f1', type: CommandType.FOREVER, params: {} },
            { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'mv2', type: CommandType.MOVE_X, params: { value: -5 } },
            { id: 'mv3', type: CommandType.END_IF, params: {} },
            { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'mv5', type: CommandType.MOVE_X, params: { value: 5 } },
            { id: 'mv6', type: CommandType.END_IF, params: {} },
            { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
            { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -5 } },
            { id: 'mv9', type: CommandType.END_IF, params: {} },
            { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
            { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 5 } },
            { id: 'mv12', type: CommandType.END_IF, params: {} },
            { id: 'at1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'at2', type: CommandType.SHOOT, params: { text: '⚔️' } },
            { id: 'at3', type: CommandType.PLAY_SOUND, params: { text: 'attack' } },
            { id: 'at4', type: CommandType.END_IF, params: {} },
            { id: 'k1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🐲' } },
            { id: 'k2', type: CommandType.CHANGE_VAR, params: { varName: 'gold', value: 20 } },
            { id: 'k3', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
            { id: 'k4', type: CommandType.END_IF, params: {} },
            { id: 'h1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '❤️' } },
            { id: 'h2', type: CommandType.CHANGE_VAR, params: { varName: 'hp', value: 25 } },
            { id: 'h3', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
            { id: 'h4', type: CommandType.END_IF, params: {} },
            { id: 'f2', type: CommandType.END_FOREVER, params: {} }
        ]
    },
    {
        id: 'tpl_genre_rhythm2',
        mode: AppMode.GAME,
        name: 'Rhythm Rush',
        description: 'Keep the beat and hit notes as they flow down!',
        icon: Music,
        color: 'bg-gradient-to-r from-pink-500 to-violet-500',
        commands: [
            { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🎵' } },
            { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
            { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'combo', value: 0 } },
            { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'multiplier', value: 1 } },
            { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'electronic' } },
            { id: 'f1', type: CommandType.FOREVER, params: {} },
            { id: 'n1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'n2', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
            { id: 'n3', type: CommandType.CHANGE_VAR, params: { varName: 'combo', value: 1 } },
            { id: 'n4', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'n5', type: CommandType.SAY, params: { text: '♪' } },
            { id: 'n6', type: CommandType.END_IF, params: {} },
            { id: 'n7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
            { id: 'n8', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
            { id: 'n9', type: CommandType.CHANGE_VAR, params: { varName: 'combo', value: 1 } },
            { id: 'n10', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'n11', type: CommandType.SAY, params: { text: '♫' } },
            { id: 'n12', type: CommandType.END_IF, params: {} },
            { id: 'n13', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'n14', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
            { id: 'n15', type: CommandType.CHANGE_VAR, params: { varName: 'combo', value: 1 } },
            { id: 'n16', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'n17', type: CommandType.SAY, params: { text: '♬' } },
            { id: 'n18', type: CommandType.END_IF, params: {} },
            { id: 'n19', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
            { id: 'n20', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
            { id: 'n21', type: CommandType.CHANGE_VAR, params: { varName: 'combo', value: 1 } },
            { id: 'n22', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'n23', type: CommandType.SAY, params: { text: '♭' } },
            { id: 'n24', type: CommandType.END_IF, params: {} },
            { id: 'f2', type: CommandType.END_FOREVER, params: {} }
        ]
    },
    {
        id: 'tpl_genre_potion',
        mode: AppMode.GAME,
        name: 'Potion Crafter',
        description: 'Mix ingredients to brew magical potions!',
        icon: FlaskConical,
        color: 'bg-gradient-to-r from-emerald-500 to-teal-600',
        commands: [
            { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🧪' } },
            { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
            { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'ingredients', value: 0 } },
            { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'potions', value: 0 } },
            { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '🍄' } },
            { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '🌸' } },
            { id: 'p3', type: CommandType.SPAWN_ITEM, params: { text: '🍄' } },
            { id: 'p4', type: CommandType.SPAWN_ITEM, params: { text: '🌟' } },
            { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'magical' } },
            { id: 'f1', type: CommandType.FOREVER, params: {} },
            { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'mv2', type: CommandType.MOVE_X, params: { value: -5 } },
            { id: 'mv3', type: CommandType.END_IF, params: {} },
            { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'mv5', type: CommandType.MOVE_X, params: { value: 5 } },
            { id: 'mv6', type: CommandType.END_IF, params: {} },
            { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
            { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -5 } },
            { id: 'mv9', type: CommandType.END_IF, params: {} },
            { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
            { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 5 } },
            { id: 'mv12', type: CommandType.END_IF, params: {} },
            { id: 'br1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🍄' } },
            { id: 'br2', type: CommandType.CHANGE_VAR, params: { varName: 'ingredients', value: 1 } },
            { id: 'br3', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'br4', type: CommandType.SAY, params: { text: 'Gathered!' } },
            { id: 'br5', type: CommandType.END_IF, params: {} },
            { id: 'mk1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'mk2', type: CommandType.CHANGE_VAR, params: { varName: 'potions', value: 1 } },
            { id: 'mk3', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 25 } },
            { id: 'mk4', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
            { id: 'mk5', type: CommandType.SAY, params: { text: 'Brewed!' } },
            { id: 'mk6', type: CommandType.END_IF, params: {} },
            { id: 'f2', type: CommandType.END_FOREVER, params: {} }
        ]
    },
    {
        id: 'tpl_genre_kingdom',
        mode: AppMode.GAME,
        name: 'Kingdom Quest',
        description: 'Rule a kingdom, hire knights, and repel invaders!',
        icon: Landmark,
        color: 'bg-gradient-to-r from-yellow-600 to-amber-700',
        commands: [
            { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grass' } },
            { id: 's2', type: CommandType.SET_EMOJI, params: { text: '👑' } },
            { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'gold', value: 200 } },
            { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'knights', value: 0 } },
            { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'reputation', value: 50 } },
            { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '🗡️' } },
            { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '🏴‍☠️' } },
            { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '💰' } },
            { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'medieval' } },
            { id: 'f1', type: CommandType.FOREVER, params: {} },
            { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'mv2', type: CommandType.MOVE_X, params: { value: -4 } },
            { id: 'mv3', type: CommandType.END_IF, params: {} },
            { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'mv5', type: CommandType.MOVE_X, params: { value: 4 } },
            { id: 'mv6', type: CommandType.END_IF, params: {} },
            { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
            { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -4 } },
            { id: 'mv9', type: CommandType.END_IF, params: {} },
            { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
            { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 4 } },
            { id: 'mv12', type: CommandType.END_IF, params: {} },
            { id: 'hr1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'hr2', type: CommandType.CHANGE_VAR, params: { varName: 'knights', value: 1 } },
            { id: 'hr3', type: CommandType.CHANGE_VAR, params: { varName: 'gold', value: -50 } },
            { id: 'hr4', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'hr5', type: CommandType.SAY, params: { text: 'Knight recruited!' } },
            { id: 'hr6', type: CommandType.END_IF, params: {} },
            { id: 'tr1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '💰' } },
            { id: 'tr2', type: CommandType.CHANGE_VAR, params: { varName: 'gold', value: 25 } },
            { id: 'tr3', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'tr4', type: CommandType.END_IF, params: {} },
            { id: 'f2', type: CommandType.END_FOREVER, params: {} }
        ]
    },
    {
        id: 'tpl_genre_word',
        mode: AppMode.GAME,
        name: 'Word Wizard',
        description: 'Form words from falling letters to score points!',
        icon: BookOpen,
        color: 'bg-gradient-to-r from-teal-500 to-cyan-600',
        commands: [
            { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 's2', type: CommandType.SET_EMOJI, params: { text: '📝' } },
            { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
            { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'words', value: 0 } },
            { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'level', value: 1 } },
            { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'peaceful' } },
            { id: 'f1', type: CommandType.FOREVER, params: {} },
            { id: 'l1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'l2', type: CommandType.SHOOT, params: { text: 'A' } },
            { id: 'l3', type: CommandType.PLAY_SOUND, params: { text: 'click' } },
            { id: 'l4', type: CommandType.END_IF, params: {} },
            { id: 'l5', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
            { id: 'l6', type: CommandType.SHOOT, params: { text: 'E' } },
            { id: 'l7', type: CommandType.PLAY_SOUND, params: { text: 'click' } },
            { id: 'l8', type: CommandType.END_IF, params: {} },
            { id: 'l9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'l10', type: CommandType.SHOOT, params: { text: 'I' } },
            { id: 'l11', type: CommandType.PLAY_SOUND, params: { text: 'click' } },
            { id: 'l12', type: CommandType.END_IF, params: {} },
            { id: 'l13', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
            { id: 'l14', type: CommandType.SHOOT, params: { text: 'O' } },
            { id: 'l15', type: CommandType.PLAY_SOUND, params: { text: 'click' } },
            { id: 'l16', type: CommandType.END_IF, params: {} },
            { id: 'ck1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'ck2', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 50 } },
            { id: 'ck3', type: CommandType.CHANGE_VAR, params: { varName: 'words', value: 1 } },
            { id: 'ck4', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
            { id: 'ck5', type: CommandType.SAY, params: { text: 'Word found!' } },
            { id: 'ck6', type: CommandType.END_IF, params: {} },
            { id: 'f2', type: CommandType.END_FOREVER, params: {} }
        ]
    },
    {
        id: 'tpl_genre_trivia',
        mode: AppMode.GAME,
        name: 'Quiz Champion',
        description: 'Answer trivia questions and climb the leaderboard!',
        icon: HelpCircle,
        color: 'bg-gradient-to-r from-blue-500 to-indigo-600',
        commands: [
            { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 's2', type: CommandType.SET_EMOJI, params: { text: '❓' } },
            { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
            { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'streak', value: 0 } },
            { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'questions', value: 0 } },
            { id: 'v4', type: CommandType.SET_VAR, params: { varName: 'timer', value: 10 } },
            { id: 't1', type: CommandType.SET_TIMER, params: { value: 10 } },
            { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'thinking' } },
            { id: 'f1', type: CommandType.FOREVER, params: {} },
            { id: 'a1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'a2', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
            { id: 'a3', type: CommandType.CHANGE_VAR, params: { varName: 'streak', value: 1 } },
            { id: 'a4', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'a5', type: CommandType.SAY, params: { text: '✅ Correct!' } },
            { id: 'a6', type: CommandType.END_IF, params: {} },
            { id: 'a7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
            { id: 'a8', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
            { id: 'a9', type: CommandType.CHANGE_VAR, params: { varName: 'streak', value: 1 } },
            { id: 'a10', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'a11', type: CommandType.SAY, params: { text: '✅ Correct!' } },
            { id: 'a12', type: CommandType.END_IF, params: {} },
            { id: 'a13', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'a14', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
            { id: 'a15', type: CommandType.CHANGE_VAR, params: { varName: 'streak', value: 1 } },
            { id: 'a16', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'a17', type: CommandType.SAY, params: { text: '✅ Correct!' } },
            { id: 'a18', type: CommandType.END_IF, params: {} },
            { id: 'a19', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
            { id: 'a20', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
            { id: 'a21', type: CommandType.CHANGE_VAR, params: { varName: 'streak', value: 1 } },
            { id: 'a22', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'a23', type: CommandType.SAY, params: { text: '✅ Correct!' } },
            { id: 'a24', type: CommandType.END_IF, params: {} },
            { id: 'f2', type: CommandType.END_FOREVER, params: {} }
        ]
    },
    {
        id: 'tpl_genre_sandbox',
        mode: AppMode.GAME,
        name: 'Pixel World',
        description: 'Place and break blocks in a creative sandbox!',
        icon: Paintbrush,
        color: 'bg-gradient-to-r from-violet-500 to-fuchsia-500',
        commands: [
            { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🎨' } },
            { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'blocks', value: 0 } },
            { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'mode', value: 0 } },
            { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '🟥' } },
            { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '🟦' } },
            { id: 'p3', type: CommandType.SPAWN_ITEM, params: { text: '🟩' } },
            { id: 'p4', type: CommandType.SPAWN_ITEM, params: { text: '🟨' } },
            { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'ambient' } },
            { id: 'f1', type: CommandType.FOREVER, params: {} },
            { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'mv2', type: CommandType.MOVE_X, params: { value: -4 } },
            { id: 'mv3', type: CommandType.END_IF, params: {} },
            { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'mv5', type: CommandType.MOVE_X, params: { value: 4 } },
            { id: 'mv6', type: CommandType.END_IF, params: {} },
            { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
            { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -4 } },
            { id: 'mv9', type: CommandType.END_IF, params: {} },
            { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
            { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 4 } },
            { id: 'mv12', type: CommandType.END_IF, params: {} },
            { id: 'pl1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'pl2', type: CommandType.CHANGE_VAR, params: { varName: 'blocks', value: 1 } },
            { id: 'pl3', type: CommandType.FILL_COLOR, params: { color: '#8b5cf6' } },
            { id: 'pl4', type: CommandType.PLAY_SOUND, params: { text: 'click' } },
            { id: 'pl5', type: CommandType.SAY, params: { text: 'Placed!' } },
            { id: 'pl6', type: CommandType.END_IF, params: {} },
            { id: 'br1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 88 } },
            { id: 'br2', type: CommandType.FILL_COLOR, params: { color: '#000000' } },
            { id: 'br3', type: CommandType.PLAY_SOUND, params: { text: 'click' } },
            { id: 'br4', type: CommandType.SAY, params: { text: 'Erased!' } },
            { id: 'br5', type: CommandType.END_IF, params: {} },
            { id: 'f2', type: CommandType.END_FOREVER, params: {} }
        ]
    },
];
