import { AppMode, CommandType, CommandBlock } from '../../types';
import { LucideIcon, Box, Castle, Ghost, Clock, MapPin } from 'lucide-react';

export const minecraftTemplates: {
    id: string,
    mode: AppMode,
    name: string,
    description: string,
    icon: LucideIcon,
    color: string,
    commands: CommandBlock[]
}[] = [
    {
        id: 'tpl_mc_first_world',
        mode: AppMode.MINECRAFT,
        name: 'My First World',
        description: 'Basic terrain with grass, trees, and a starting platform',
        icon: Box,
        color: 'bg-gradient-to-r from-green-500 to-emerald-600',
        commands: [
            { id: 'mc1', type: CommandType.MC_SET_WEATHER, params: { weather: 'clear' } },
            { id: 'mc2', type: CommandType.MC_SET_TIME, params: { time: 'day' } },
            { id: 'mc3', type: CommandType.MC_FILL_AREA, params: { x: -5, y: 62, z: -5, x2: 5, y2: 62, z2: 5, blockType: 'dirt' } },
            { id: 'mc4', type: CommandType.MC_FILL_AREA, params: { x: -5, y: 63, z: -5, x2: 5, y2: 63, z2: 5, blockType: 'grass' } },
            { id: 'mc5', type: CommandType.MC_SET_BLOCK, params: { x: 0, y: 64, z: 0, blockType: 'wood' } },
            { id: 'mc6', type: CommandType.MC_SET_BLOCK, params: { x: 0, y: 65, z: 0, blockType: 'wood' } },
            { id: 'mc7', type: CommandType.MC_SET_BLOCK, params: { x: 0, y: 66, z: 0, blockType: 'wood' } },
            { id: 'mc8', type: CommandType.MC_FILL_AREA, params: { x: -2, y: 67, z: -2, x2: 2, y2: 67, z2: 2, blockType: 'grass' } },
            { id: 'mc9', type: CommandType.MC_SHOW_MESSAGE, params: { text: 'Welcome to your first world!' } },
            { id: 'mc10', type: CommandType.MC_TELEPORT, params: { x: 0, y: 64, z: 3 } },
        ]
    },
    {
        id: 'tpl_mc_castle',
        mode: AppMode.MINECRAFT,
        name: 'Castle Builder',
        description: 'Build a grand castle with towers and walls',
        icon: Castle,
        color: 'bg-gradient-to-r from-stone-500 to-gray-700',
        commands: [
            { id: 'mc1', type: CommandType.MC_SET_WEATHER, params: { weather: 'clear' } },
            { id: 'mc2', type: CommandType.MC_SET_TIME, params: { time: 'noon' } },
            { id: 'mc3', type: CommandType.MC_CREATE_STRUCTURE, params: { x: 0, y: 64, z: 0, structure: 'castle' } },
            { id: 'mc4', type: CommandType.MC_CREATE_STRUCTURE, params: { x: 20, y: 64, z: 0, structure: 'tower' } },
            { id: 'mc5', type: CommandType.MC_CREATE_STRUCTURE, params: { x: -20, y: 64, z: 0, structure: 'tower' } },
            { id: 'mc6', type: CommandType.MC_FILL_AREA, params: { x: -4, y: 64, z: -1, x2: 4, y2: 64, z2: -1, blockType: 'cobblestone' } },
            { id: 'mc7', type: CommandType.MC_SPAWN_ENTITY, params: { x: 0, y: 65, z: 5, entityType: 'villager' } },
            { id: 'mc8', type: CommandType.MC_SPAWN_ENTITY, params: { x: 3, y: 65, z: 5, entityType: 'villager' } },
            { id: 'mc9', type: CommandType.MC_SHOW_MESSAGE, params: { text: 'Your castle is ready!' } },
        ]
    },
    {
        id: 'tpl_mc_mob_arena',
        mode: AppMode.MINECRAFT,
        name: 'Mob Arena',
        description: 'Spawn different mobs and battle them',
        icon: Ghost,
        color: 'bg-gradient-to-r from-red-500 to-red-700',
        commands: [
            { id: 'mc1', type: CommandType.MC_SET_WEATHER, params: { weather: 'thunder' } },
            { id: 'mc2', type: CommandType.MC_SET_TIME, params: { time: 'night' } },
            { id: 'mc3', type: CommandType.MC_FILL_AREA, params: { x: -10, y: 62, z: -10, x2: 10, y2: 62, z2: 10, blockType: 'stone' } },
            { id: 'mc4', type: CommandType.MC_FILL_AREA, params: { x: -10, y: 66, z: -10, x2: 10, y2: 66, z2: 10, blockType: 'glass' } },
            { id: 'mc5', type: CommandType.MC_SPAWN_ENTITY, params: { x: -5, y: 64, z: -5, entityType: 'zombie' } },
            { id: 'mc6', type: CommandType.MC_SPAWN_ENTITY, params: { x: 5, y: 64, z: -5, entityType: 'skeleton' } },
            { id: 'mc7', type: CommandType.MC_SPAWN_ENTITY, params: { x: 0, y: 64, z: 5, entityType: 'creeper' } },
            { id: 'mc8', type: CommandType.MC_SPAWN_ENTITY, params: { x: -5, y: 64, z: 5, entityType: 'spider' } },
            { id: 'mc9', type: CommandType.MC_GIVE_ITEM, params: { item: 'diamond_sword', amount: 1 } },
            { id: 'mc10', type: CommandType.MC_GIVE_ITEM, params: { item: 'shield', amount: 1 } },
            { id: 'mc11', type: CommandType.MC_SHOW_MESSAGE, params: { text: 'Fight! Mobs have been spawned!' } },
            { id: 'mc12', type: CommandType.MC_PLAY_SOUND, params: { sound: 'ambient.cave' } },
        ]
    },
    {
        id: 'tpl_mc_day_night',
        mode: AppMode.MINECRAFT,
        name: 'Day/Night Cycle',
        description: 'Create a day and night cycle with weather effects',
        icon: Clock,
        color: 'bg-gradient-to-r from-blue-400 to-indigo-600',
        commands: [
            { id: 'mc1', type: CommandType.MC_SET_TIME, params: { time: 'dawn' } },
            { id: 'mc2', type: CommandType.MC_SET_WEATHER, params: { weather: 'clear' } },
            { id: 'mc3', type: CommandType.MC_SHOW_MESSAGE, params: { text: 'The sun rises...' } },
            { id: 'mc4', type: CommandType.MC_SET_TIME, params: { time: 'noon' } },
            { id: 'mc5', type: CommandType.MC_SHOW_MESSAGE, params: { text: 'Midday! The world is bright.' } },
            { id: 'mc6', type: CommandType.MC_SET_WEATHER, params: { weather: 'rain' } },
            { id: 'mc7', type: CommandType.MC_PLAY_SOUND, params: { sound: 'weather.rain' } },
            { id: 'mc8', type: CommandType.MC_SHOW_MESSAGE, params: { text: 'Rain starts to fall...' } },
            { id: 'mc9', type: CommandType.MC_SET_TIME, params: { time: 'dusk' } },
            { id: 'mc10', type: CommandType.MC_SET_WEATHER, params: { weather: 'clear' } },
            { id: 'mc11', type: CommandType.MC_SHOW_MESSAGE, params: { text: 'Sunset paints the sky orange.' } },
            { id: 'mc12', type: CommandType.MC_SET_TIME, params: { time: 'night' } },
            { id: 'mc13', type: CommandType.MC_SET_WEATHER, params: { weather: 'thunder' } },
            { id: 'mc14', type: CommandType.MC_SHOW_MESSAGE, params: { text: 'A thunderstorm approaches!' } },
            { id: 'mc15', type: CommandType.MC_PLAY_SOUND, params: { sound: 'ambient.weather.thunder' } },
        ]
    },
    {
        id: 'tpl_mc_treasure',
        mode: AppMode.MINECRAFT,
        name: 'Treasure Hunt',
        description: 'Place treasure chests and teleport players to find them',
        icon: MapPin,
        color: 'bg-gradient-to-r from-yellow-500 to-amber-600',
        commands: [
            { id: 'mc1', type: CommandType.MC_SET_TIME, params: { time: 'day' } },
            { id: 'mc2', type: CommandType.MC_SET_WEATHER, params: { weather: 'clear' } },
            { id: 'mc3', type: CommandType.MC_SHOW_MESSAGE, params: { text: 'Find the treasure chests!' } },
            { id: 'mc4', type: CommandType.MC_CREATE_STRUCTURE, params: { x: 0, y: 64, z: 0, structure: 'farm' } },
            { id: 'mc5', type: CommandType.MC_SET_BLOCK, params: { x: 10, y: 64, z: 10, blockType: 'chest' } },
            { id: 'mc6', type: CommandType.MC_GIVE_ITEM, params: { item: 'diamond', amount: 5 } },
            { id: 'mc7', type: CommandType.MC_SET_BLOCK, params: { x: -10, y: 64, z: 10, blockType: 'chest' } },
            { id: 'mc8', type: CommandType.MC_GIVE_ITEM, params: { item: 'gold_ingot', amount: 10 } },
            { id: 'mc9', type: CommandType.MC_SET_BLOCK, params: { x: 10, y: 64, z: -10, blockType: 'chest' } },
            { id: 'mc10', type: CommandType.MC_GIVE_ITEM, params: { item: 'emerald', amount: 3 } },
            { id: 'mc11', type: CommandType.MC_TELEPORT, params: { x: 0, y: 70, z: 0 } },
            { id: 'mc12', type: CommandType.MC_PLAY_SOUND, params: { sound: 'note.pling' } },
        ]
    },
];
