import { AppMode, CommandType, CommandBlock } from '../../types';
import {
    LucideIcon, Eye, ChefHat, PawPrint, Brain, Dumbbell, Puzzle, Music,
    Paintbrush, Keyboard, Dices
} from 'lucide-react';

export const phase3Templates: {
    id: string,
    mode: AppMode,
    name: string,
    description: string,
    icon: LucideIcon,
    color: string,
    commands: CommandBlock[]
}[] = [
    {
        id: 'tpl_p3_stealth',
        mode: AppMode.GAME,
        name: 'Stealth Mission',
        description: 'Sneak past guards, avoid detection, reach the objective',
        icon: Eye,
        color: 'bg-gradient-to-r from-slate-700 to-gray-900',
        commands: [
            { id: 'st1', type: CommandType.SET_SCENE, params: { text: 'night' } },
            { id: 'st2', type: CommandType.SET_EMOJI, params: { text: '🥷' } },
            { id: 'st3', type: CommandType.SET_VAR, params: { varName: 'detection', value: 0 } },
            { id: 'st4', type: CommandType.SET_VAR, params: { varName: 'stealth_score', value: 0 } },
            { id: 'st5', type: CommandType.SET_VAR, params: { varName: 'guards_evaded', value: 0 } },
            { id: 'st6', type: CommandType.SET_OPACITY, params: { value: 50 } },
            { id: 'st7', type: CommandType.SPAWN_ENEMY, params: { text: '👮' } },
            { id: 'st8', type: CommandType.SPAWN_ENEMY, params: { text: '🔦' } },
            { id: 'st9', type: CommandType.FOREVER, params: {} },
            { id: 'st10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'st11', type: CommandType.MOVE_X, params: { value: -3 } },
            { id: 'st12', type: CommandType.END_IF, params: {} },
            { id: 'st13', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'st14', type: CommandType.MOVE_X, params: { value: 3 } },
            { id: 'st15', type: CommandType.END_IF, params: {} },
            { id: 'st16', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
            { id: 'st17', type: CommandType.MOVE_Y, params: { value: -3 } },
            { id: 'st18', type: CommandType.END_IF, params: {} },
            { id: 'st19', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
            { id: 'st20', type: CommandType.MOVE_Y, params: { value: 3 } },
            { id: 'st21', type: CommandType.END_IF, params: {} },
            { id: 'st22', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '👮' } },
            { id: 'st23', type: CommandType.CHANGE_VAR, params: { varName: 'detection', value: 25 } },
            { id: 'st24', type: CommandType.PLAY_SOUND, params: { text: 'alert' } },
            { id: 'st25', type: CommandType.SCREEN_SHAKE, params: { value: 3 } },
            { id: 'st26', type: CommandType.END_IF, params: {} },
            { id: 'st27', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'st28', type: CommandType.HIDE, params: {} },
            { id: 'st29', type: CommandType.PLAY_SOUND, params: { text: 'stealth' } },
            { id: 'st30', type: CommandType.CHANGE_VAR, params: { varName: 'stealth_score', value: 5 } },
            { id: 'st31', type: CommandType.END_IF, params: {} },
            { id: 'st32', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } },
            { id: 'st33', type: CommandType.SHOW, params: {} },
            { id: 'st34', type: CommandType.CHANGE_VAR, params: { varName: 'guards_evaded', value: 1 } },
            { id: 'st35', type: CommandType.END_IF, params: {} },
            { id: 'win_stealth', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'guards_evaded', value: 5 } },
            { id: 'win_stealth2', type: CommandType.WIN_GAME, params: {} },
            { id: 'win_stealth3', type: CommandType.END_IF, params: {} },
            { id: 'lose_stealth', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'detection', value: 100 } },
            { id: 'lose_stealth2', type: CommandType.GAME_OVER, params: {} },
            { id: 'lose_stealth3', type: CommandType.END_IF, params: {} },
            { id: 'st36', type: CommandType.END_FOREVER, params: {} },
        ]
    },
    {
        id: 'tpl_p3_cooking',
        mode: AppMode.GAME,
        name: 'Kitchen Chaos',
        description: 'Cook dishes by mixing ingredients, serve before time runs out',
        icon: ChefHat,
        color: 'bg-gradient-to-r from-orange-500 to-red-600',
        commands: [
            { id: 'ck1', type: CommandType.SET_TITLE, params: { text: 'Kitchen Chaos' } },
            { id: 'ck2', type: CommandType.SET_SCENE, params: { text: 'kitchen' } },
            { id: 'ck3', type: CommandType.SET_EMOJI, params: { text: '👨‍🍳' } },
            { id: 'ck4', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
            { id: 'ck5', type: CommandType.SET_VAR, params: { varName: 'timer', value: 60 } },
            { id: 'ck6', type: CommandType.SET_VAR, params: { varName: 'dishes', value: 0 } },
            { id: 'ck7', type: CommandType.SET_VAR, params: { varName: 'combo', value: 1 } },
            { id: 'ck8', type: CommandType.SPAWN_ITEM, params: { text: '🍅' } },
            { id: 'ck9', type: CommandType.SPAWN_ITEM, params: { text: '🧀' } },
            { id: 'ck10', type: CommandType.SPAWN_ITEM, params: { text: '🍝' } },
            { id: 'ck11', type: CommandType.FOREVER, params: {} },
            { id: 'ck12', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'ck13', type: CommandType.PLAY_SOUND, params: { text: 'sizzle' } },
            { id: 'ck14', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
            { id: 'ck15', type: CommandType.SPAWN_PARTICLES, params: { value: 5 } },
            { id: 'ck16', type: CommandType.END_IF, params: {} },
            { id: 'ck17', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } },
            { id: 'ck18', type: CommandType.CRAFT_ITEM, params: {} },
            { id: 'ck19', type: CommandType.CHANGE_VAR, params: { varName: 'dishes', value: 1 } },
            { id: 'ck20', type: CommandType.CHANGE_VAR, params: { varName: 'combo', value: 1 } },
            { id: 'ck21', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'ck22', type: CommandType.END_IF, params: {} },
            { id: 'ck23', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'ck24', type: CommandType.PLAY_SOUND, params: { text: 'chop' } },
            { id: 'ck25', type: CommandType.SPAWN_PARTICLES, params: { value: 3 } },
            { id: 'ck26', type: CommandType.END_IF, params: {} },
            { id: 'ck27', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'ck28', type: CommandType.PLAY_SOUND, params: { text: 'boil' } },
            { id: 'ck29', type: CommandType.END_IF, params: {} },
            { id: 'win_cooking', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'dishes', value: 10 } },
            { id: 'win_cooking2', type: CommandType.WIN_GAME, params: {} },
            { id: 'win_cooking3', type: CommandType.END_IF, params: {} },
            { id: 'lose_cooking', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'timer', value: 0 } },
            { id: 'lose_cooking2', type: CommandType.GAME_OVER, params: {} },
            { id: 'lose_cooking3', type: CommandType.END_IF, params: {} },
            { id: 'ck30', type: CommandType.END_FOREVER, params: {} },
        ]
    },
    {
        id: 'tpl_p3_pet',
        mode: AppMode.GAME,
        name: 'Virtual Pet',
        description: 'Feed, play with, and care for your digital companion',
        icon: PawPrint,
        color: 'bg-gradient-to-r from-pink-500 to-rose-600',
        commands: [
            { id: 'pt1', type: CommandType.SET_TITLE, params: { text: 'My Pet' } },
            { id: 'pt2', type: CommandType.SET_SCENE, params: { text: 'garden' } },
            { id: 'pt3', type: CommandType.SET_EMOJI, params: { text: '🐕' } },
            { id: 'pt4', type: CommandType.SET_VAR, params: { varName: 'hunger', value: 50 } },
            { id: 'pt5', type: CommandType.SET_VAR, params: { varName: 'happiness', value: 50 } },
            { id: 'pt6', type: CommandType.SET_VAR, params: { varName: 'energy', value: 100 } },
            { id: 'pt7', type: CommandType.SET_VAR, params: { varName: 'level', value: 1 } },
            { id: 'pt8', type: CommandType.SET_VAR, params: { varName: 'xp', value: 0 } },
            { id: 'pt9', type: CommandType.SAY, params: { text: 'Your pet needs care!' } },
            { id: 'pt10', type: CommandType.FOREVER, params: {} },
            { id: 'pt11', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'pt12', type: CommandType.CHANGE_VAR, params: { varName: 'hunger', value: -20 } },
            { id: 'pt13', type: CommandType.CHANGE_VAR, params: { varName: 'happiness', value: 5 } },
            { id: 'pt14', type: CommandType.PLAY_SOUND, params: { text: 'nom' } },
            { id: 'pt15', type: CommandType.SAY, params: { text: 'Yummy!' } },
            { id: 'pt16', type: CommandType.END_IF, params: {} },
            { id: 'pt17', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } },
            { id: 'pt18', type: CommandType.CHANGE_VAR, params: { varName: 'happiness', value: 20 } },
            { id: 'pt19', type: CommandType.CHANGE_VAR, params: { varName: 'energy', value: -10 } },
            { id: 'pt20', type: CommandType.PLAY_SOUND, params: { text: 'happy' } },
            { id: 'pt21', type: CommandType.SAY, params: { text: 'So fun!' } },
            { id: 'pt22', type: CommandType.SPAWN_PARTICLES, params: { value: 5 } },
            { id: 'pt23', type: CommandType.END_IF, params: {} },
            { id: 'pt24', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'pt25', type: CommandType.CHANGE_VAR, params: { varName: 'energy', value: 30 } },
            { id: 'pt26', type: CommandType.PLAY_SOUND, params: { text: 'sleep' } },
            { id: 'pt27', type: CommandType.SAY, params: { text: 'Zzz...' } },
            { id: 'pt28', type: CommandType.END_IF, params: {} },
            { id: 'pt29', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'pt30', type: CommandType.CHANGE_VAR, params: { varName: 'xp', value: 10 } },
            { id: 'pt31', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'pt32', type: CommandType.END_IF, params: {} },
            { id: 'pt33', type: CommandType.IF, params: { condition: 'GREATER', varName: 'xp', value: 100 } },
            { id: 'pt34', type: CommandType.CHANGE_VAR, params: { varName: 'level', value: 1 } },
            { id: 'pt35', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
            { id: 'pt36', type: CommandType.SAY, params: { text: 'Level Up!' } },
            { id: 'pt37', type: CommandType.SPAWN_PARTICLES, params: { value: 10 } },
            { id: 'pt38', type: CommandType.END_IF, params: {} },
            { id: 'lose_pet', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'hunger', value: 100 } },
            { id: 'lose_pet2', type: CommandType.SAY, params: { text: 'Your pet is too hungry!' } },
            { id: 'lose_pet3', type: CommandType.END_IF, params: {} },
            { id: 'pt39', type: CommandType.END_FOREVER, params: {} },
        ]
    },
    {
        id: 'tpl_p3_memory',
        mode: AppMode.GAME,
        name: 'Memory Matrix',
        description: 'Remember and reproduce increasingly complex patterns',
        icon: Brain,
        color: 'bg-gradient-to-r from-violet-500 to-purple-700',
        commands: [
            { id: 'mm1', type: CommandType.SET_TITLE, params: { text: 'Memory Matrix' } },
            { id: 'mm2', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 'mm3', type: CommandType.SET_EMOJI, params: { text: '🧠' } },
            { id: 'mm4', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
            { id: 'mm5', type: CommandType.SET_VAR, params: { varName: 'level', value: 1 } },
            { id: 'mm6', type: CommandType.SET_VAR, params: { varName: 'lives', value: 3 } },
            { id: 'mm7', type: CommandType.SET_VAR, params: { varName: 'streak', value: 0 } },
            { id: 'mm8', type: CommandType.SAY, params: { text: 'Watch the pattern!' } },
            { id: 'mm9', type: CommandType.PLAY_SOUND, params: { text: 'attention' } },
            { id: 'mm10', type: CommandType.FOREVER, params: {} },
            { id: 'mm11', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'mm12', type: CommandType.PLAY_SOUND, params: { text: 'click' } },
            { id: 'mm13', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
            { id: 'mm14', type: CommandType.CHANGE_VAR, params: { varName: 'streak', value: 1 } },
            { id: 'mm15', type: CommandType.SPAWN_PARTICLES, params: { value: 3 } },
            { id: 'mm16', type: CommandType.END_IF, params: {} },
            { id: 'mm17', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } },
            { id: 'mm18', type: CommandType.PLAY_SOUND, params: { text: 'click' } },
            { id: 'mm19', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
            { id: 'mm20', type: CommandType.CHANGE_VAR, params: { varName: 'streak', value: 1 } },
            { id: 'mm21', type: CommandType.SPAWN_PARTICLES, params: { value: 3 } },
            { id: 'mm22', type: CommandType.END_IF, params: {} },
            { id: 'mm23', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'mm24', type: CommandType.PLAY_SOUND, params: { text: 'click' } },
            { id: 'mm25', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
            { id: 'mm26', type: CommandType.CHANGE_VAR, params: { varName: 'streak', value: 1 } },
            { id: 'mm27', type: CommandType.SPAWN_PARTICLES, params: { value: 3 } },
            { id: 'mm28', type: CommandType.END_IF, params: {} },
            { id: 'mm29', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'mm30', type: CommandType.PLAY_SOUND, params: { text: 'click' } },
            { id: 'mm31', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
            { id: 'mm32', type: CommandType.CHANGE_VAR, params: { varName: 'streak', value: 1 } },
            { id: 'mm33', type: CommandType.SPAWN_PARTICLES, params: { value: 3 } },
            { id: 'mm34', type: CommandType.END_IF, params: {} },
            { id: 'win_memory', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'score', value: 500 } },
            { id: 'win_memory2', type: CommandType.WIN_GAME, params: {} },
            { id: 'win_memory3', type: CommandType.END_IF, params: {} },
            { id: 'lose_memory', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'lives', value: 0 } },
            { id: 'lose_memory2', type: CommandType.GAME_OVER, params: {} },
            { id: 'lose_memory3', type: CommandType.END_IF, params: {} },
            { id: 'mm35', type: CommandType.END_FOREVER, params: {} },
        ]
    },
    {
        id: 'tpl_p3_strength',
        mode: AppMode.GAME,
        name: 'Strength Challenge',
        description: 'Train your character, compete in strength contests',
        icon: Dumbbell,
        color: 'bg-gradient-to-r from-red-600 to-orange-600',
        commands: [
            { id: 'str1', type: CommandType.SET_TITLE, params: { text: 'Strength Challenge' } },
            { id: 'str2', type: CommandType.SET_SCENE, params: { text: 'gym' } },
            { id: 'str3', type: CommandType.SET_EMOJI, params: { text: '💪' } },
            { id: 'str4', type: CommandType.SET_VAR, params: { varName: 'strength', value: 10 } },
            { id: 'str5', type: CommandType.SET_VAR, params: { varName: 'endurance', value: 10 } },
            { id: 'str6', type: CommandType.SET_VAR, params: { varName: 'wins', value: 0 } },
            { id: 'str7', type: CommandType.SET_VAR, params: { varName: 'training', value: 0 } },
            { id: 'str8', type: CommandType.SPAWN_ENEMY, params: { text: '🏋️' } },
            { id: 'str9', type: CommandType.FOREVER, params: {} },
            { id: 'str10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'str11', type: CommandType.CHANGE_VAR, params: { varName: 'strength', value: 2 } },
            { id: 'str12', type: CommandType.CHANGE_VAR, params: { varName: 'training', value: 1 } },
            { id: 'str13', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
            { id: 'str14', type: CommandType.SPAWN_PARTICLES, params: { value: 5 } },
            { id: 'str15', type: CommandType.END_IF, params: {} },
            { id: 'str16', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } },
            { id: 'str17', type: CommandType.CHANGE_VAR, params: { varName: 'endurance', value: 2 } },
            { id: 'str18', type: CommandType.PLAY_SOUND, params: { text: 'run' } },
            { id: 'str19', type: CommandType.END_IF, params: {} },
            { id: 'str20', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'str21', type: CommandType.SHOOT, params: { text: '💪' } },
            { id: 'str22', type: CommandType.CHANGE_VAR, params: { varName: 'wins', value: 1 } },
            { id: 'str23', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
            { id: 'str24', type: CommandType.SCREEN_SHAKE, params: { value: 5 } },
            { id: 'str25', type: CommandType.END_IF, params: {} },
            { id: 'str26', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'str27', type: CommandType.SPAWN_ENEMY, params: { text: '🏆' } },
            { id: 'str28', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'str29', type: CommandType.END_IF, params: {} },
            { id: 'win_strength', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'wins', value: 10 } },
            { id: 'win_strength2', type: CommandType.WIN_GAME, params: {} },
            { id: 'win_strength3', type: CommandType.END_IF, params: {} },
            { id: 'str30', type: CommandType.END_FOREVER, params: {} },
        ]
    },
    {
        id: 'tpl_p3_pattern',
        mode: AppMode.GAME,
        name: 'Pattern Puzzle',
        description: 'Complete visual patterns by finding the missing pieces',
        icon: Puzzle,
        color: 'bg-gradient-to-r from-teal-500 to-cyan-600',
        commands: [
            { id: 'pp1', type: CommandType.SET_TITLE, params: { text: 'Pattern Puzzle' } },
            { id: 'pp2', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 'pp3', type: CommandType.SET_EMOJI, params: { text: '🧩' } },
            { id: 'pp4', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
            { id: 'pp5', type: CommandType.SET_VAR, params: { varName: 'patterns_solved', value: 0 } },
            { id: 'pp6', type: CommandType.SET_VAR, params: { varName: 'hints', value: 3 } },
            { id: 'pp7', type: CommandType.SAY, params: { text: 'Find the pattern!' } },
            { id: 'pp8', type: CommandType.FOREVER, params: {} },
            { id: 'pp9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'pp10', type: CommandType.SWAP_TILES, params: {} },
            { id: 'pp11', type: CommandType.PLAY_SOUND, params: { text: 'click' } },
            { id: 'pp12', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 15 } },
            { id: 'pp13', type: CommandType.END_IF, params: {} },
            { id: 'pp14', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } },
            { id: 'pp15', type: CommandType.CHECK_MATCH, params: {} },
            { id: 'pp16', type: CommandType.CHANGE_VAR, params: { varName: 'patterns_solved', value: 1 } },
            { id: 'pp17', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
            { id: 'pp18', type: CommandType.SPAWN_PARTICLES, params: { value: 8 } },
            { id: 'pp19', type: CommandType.END_IF, params: {} },
            { id: 'pp20', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'pp21', type: CommandType.CHANGE_VAR, params: { varName: 'hints', value: -1 } },
            { id: 'pp22', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
            { id: 'pp23', type: CommandType.SAY, params: { text: 'Hint used!' } },
            { id: 'pp24', type: CommandType.END_IF, params: {} },
            { id: 'pp25', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'pp26', type: CommandType.ROTATE_BLOCK, params: {} },
            { id: 'pp27', type: CommandType.PLAY_SOUND, params: { text: 'rotate' } },
            { id: 'pp28', type: CommandType.END_IF, params: {} },
            { id: 'win_pattern', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'patterns_solved', value: 10 } },
            { id: 'win_pattern2', type: CommandType.WIN_GAME, params: {} },
            { id: 'win_pattern3', type: CommandType.END_IF, params: {} },
            { id: 'pp29', type: CommandType.END_FOREVER, params: {} },
        ]
    },
    {
        id: 'tpl_p3_dj',
        mode: AppMode.GAME,
        name: 'DJ Mixer',
        description: 'Mix tracks, scratch records, create live beats',
        icon: Music,
        color: 'bg-gradient-to-r from-fuchsia-500 to-pink-600',
        commands: [
            { id: 'dj1', type: CommandType.SET_TITLE, params: { text: 'DJ Mixer' } },
            { id: 'dj2', type: CommandType.SET_SCENE, params: { text: 'club' } },
            { id: 'dj3', type: CommandType.SET_EMOJI, params: { text: '🎧' } },
            { id: 'dj4', type: CommandType.SET_VAR, params: { varName: 'energy', value: 0 } },
            { id: 'dj5', type: CommandType.SET_VAR, params: { varName: 'crowd', value: 50 } },
            { id: 'dj6', type: CommandType.SET_VAR, params: { varName: 'combo', value: 1 } },
            { id: 'dj7', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'beat' } },
            { id: 'dj8', type: CommandType.FOREVER, params: {} },
            { id: 'dj9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'dj10', type: CommandType.PLAY_SOUND, params: { text: 'kick' } },
            { id: 'dj11', type: CommandType.CHANGE_VAR, params: { varName: 'energy', value: 5 } },
            { id: 'dj12', type: CommandType.CHANGE_VAR, params: { varName: 'crowd', value: 2 } },
            { id: 'dj13', type: CommandType.SPAWN_PARTICLES, params: { value: 3 } },
            { id: 'dj14', type: CommandType.END_IF, params: {} },
            { id: 'dj15', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } },
            { id: 'dj16', type: CommandType.PLAY_SOUND, params: { text: 'snare' } },
            { id: 'dj17', type: CommandType.CHANGE_VAR, params: { varName: 'energy', value: 5 } },
            { id: 'dj18', type: CommandType.CHANGE_VAR, params: { varName: 'crowd', value: 3 } },
            { id: 'dj19', type: CommandType.END_IF, params: {} },
            { id: 'dj20', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'dj21', type: CommandType.PLAY_SOUND, params: { text: 'scratch' } },
            { id: 'dj22', type: CommandType.CHANGE_VAR, params: { varName: 'energy', value: 10 } },
            { id: 'dj23', type: CommandType.CHANGE_VAR, params: { varName: 'combo', value: 1 } },
            { id: 'dj24', type: CommandType.SPAWN_PARTICLES, params: { value: 8 } },
            { id: 'dj25', type: CommandType.END_IF, params: {} },
            { id: 'dj26', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'dj27', type: CommandType.PLAY_SOUND, params: { text: 'drop' } },
            { id: 'dj28', type: CommandType.CHANGE_VAR, params: { varName: 'energy', value: 20 } },
            { id: 'dj29', type: CommandType.CHANGE_VAR, params: { varName: 'crowd', value: 10 } },
            { id: 'dj30', type: CommandType.SCREEN_SHAKE, params: { value: 3 } },
            { id: 'dj31', type: CommandType.END_IF, params: {} },
            { id: 'win_dj', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'crowd', value: 100 } },
            { id: 'win_dj2', type: CommandType.WIN_GAME, params: {} },
            { id: 'win_dj3', type: CommandType.END_IF, params: {} },
            { id: 'dj32', type: CommandType.END_FOREVER, params: {} },
        ]
    },
    {
        id: 'tpl_p3_paint',
        mode: AppMode.GAME,
        name: 'Pixel Painter',
        description: 'Create pixel art masterpieces with a limited palette',
        icon: Paintbrush,
        color: 'bg-gradient-to-r from-amber-500 to-yellow-600',
        commands: [
            { id: 'pn1', type: CommandType.SET_TITLE, params: { text: 'Pixel Painter' } },
            { id: 'pn2', type: CommandType.SET_SCENE, params: { text: 'canvas' } },
            { id: 'pn3', type: CommandType.SET_EMOJI, params: { text: '🎨' } },
            { id: 'pn4', type: CommandType.SET_VAR, params: { varName: 'pixels', value: 0 } },
            { id: 'pn5', type: CommandType.SET_VAR, params: { varName: 'colors_used', value: 0 } },
            { id: 'pn6', type: CommandType.SET_VAR, params: { varName: 'creativity', value: 0 } },
            { id: 'pn7', type: CommandType.ADD_DRAWING_CANVAS, params: {} },
            { id: 'pn8', type: CommandType.SAY, params: { text: 'Paint your masterpiece!' } },
            { id: 'pn9', type: CommandType.FOREVER, params: {} },
            { id: 'pn10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'pn11', type: CommandType.FILL_COLOR, params: { color: '#ff6b6b' } },
            { id: 'pn12', type: CommandType.CHANGE_VAR, params: { varName: 'pixels', value: 1 } },
            { id: 'pn13', type: CommandType.PLAY_SOUND, params: { text: 'paint' } },
            { id: 'pn14', type: CommandType.END_IF, params: {} },
            { id: 'pn15', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } },
            { id: 'pn16', type: CommandType.FILL_COLOR, params: { color: '#4ecdc4' } },
            { id: 'pn17', type: CommandType.CHANGE_VAR, params: { varName: 'pixels', value: 1 } },
            { id: 'pn18', type: CommandType.PLAY_SOUND, params: { text: 'paint' } },
            { id: 'pn19', type: CommandType.END_IF, params: {} },
            { id: 'pn20', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'pn21', type: CommandType.FILL_COLOR, params: { color: '#45b7d1' } },
            { id: 'pn22', type: CommandType.CHANGE_VAR, params: { varName: 'pixels', value: 1 } },
            { id: 'pn23', type: CommandType.PLAY_SOUND, params: { text: 'paint' } },
            { id: 'pn24', type: CommandType.END_IF, params: {} },
            { id: 'pn25', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'pn26', type: CommandType.FILL_COLOR, params: { color: '#96ceb4' } },
            { id: 'pn27', type: CommandType.CHANGE_VAR, params: { varName: 'pixels', value: 1 } },
            { id: 'pn28', type: CommandType.PLAY_SOUND, params: { text: 'paint' } },
            { id: 'pn29', type: CommandType.END_IF, params: {} },
            { id: 'win_paint', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'pixels', value: 50 } },
            { id: 'win_paint2', type: CommandType.WIN_GAME, params: {} },
            { id: 'win_paint3', type: CommandType.END_IF, params: {} },
            { id: 'pn30', type: CommandType.END_FOREVER, params: {} },
        ]
    },
    {
        id: 'tpl_p3_typing',
        mode: AppMode.GAME,
        name: 'Speed Typer',
        description: 'Type words as fast as you can, compete for high scores',
        icon: Keyboard,
        color: 'bg-gradient-to-r from-emerald-500 to-green-600',
        commands: [
            { id: 'ty1', type: CommandType.SET_TITLE, params: { text: 'Speed Typer' } },
            { id: 'ty2', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 'ty3', type: CommandType.SET_EMOJI, params: { text: '⌨️' } },
            { id: 'ty4', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
            { id: 'ty5', type: CommandType.SET_VAR, params: { varName: 'wpm', value: 0 } },
            { id: 'ty6', type: CommandType.SET_VAR, params: { varName: 'accuracy', value: 100 } },
            { id: 'ty7', type: CommandType.SET_VAR, params: { varName: 'words_typed', value: 0 } },
            { id: 'ty8', type: CommandType.SAY, params: { text: 'Type the words!' } },
            { id: 'ty9', type: CommandType.FOREVER, params: {} },
            { id: 'ty10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'ty11', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
            { id: 'ty12', type: CommandType.CHANGE_VAR, params: { varName: 'wpm', value: 1 } },
            { id: 'ty13', type: CommandType.CHANGE_VAR, params: { varName: 'words_typed', value: 1 } },
            { id: 'ty14', type: CommandType.PLAY_SOUND, params: { text: 'click' } },
            { id: 'ty15', type: CommandType.SPAWN_PARTICLES, params: { value: 3 } },
            { id: 'ty16', type: CommandType.END_IF, params: {} },
            { id: 'ty17', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } },
            { id: 'ty18', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 25 } },
            { id: 'ty19', type: CommandType.CHANGE_VAR, params: { varName: 'wpm', value: 2 } },
            { id: 'ty20', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
            { id: 'ty21', type: CommandType.SPAWN_PARTICLES, params: { value: 8 } },
            { id: 'ty22', type: CommandType.END_IF, params: {} },
            { id: 'ty23', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'ty24', type: CommandType.CHANGE_VAR, params: { varName: 'accuracy', value: -5 } },
            { id: 'ty25', type: CommandType.PLAY_SOUND, params: { text: 'hurt' } },
            { id: 'ty26', type: CommandType.END_IF, params: {} },
            { id: 'ty27', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'ty28', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 50 } },
            { id: 'ty29', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
            { id: 'ty30', type: CommandType.SPAWN_PARTICLES, params: { value: 10 } },
            { id: 'ty31', type: CommandType.END_IF, params: {} },
            { id: 'win_typing', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'words_typed', value: 20 } },
            { id: 'win_typing2', type: CommandType.WIN_GAME, params: {} },
            { id: 'win_typing3', type: CommandType.END_IF, params: {} },
            { id: 'ty32', type: CommandType.END_FOREVER, params: {} },
        ]
    },
    {
        id: 'tpl_p3_lucky',
        mode: AppMode.GAME,
        name: 'Lucky Spinner',
        description: 'Spin the wheel, win prizes, build your collection',
        icon: Dices,
        color: 'bg-gradient-to-r from-rose-500 to-pink-600',
        commands: [
            { id: 'ls1', type: CommandType.SET_TITLE, params: { text: 'Lucky Spinner' } },
            { id: 'ls2', type: CommandType.SET_SCENE, params: { text: 'grid' } },
            { id: 'ls3', type: CommandType.SET_EMOJI, params: { text: '🎰' } },
            { id: 'ls4', type: CommandType.SET_VAR, params: { varName: 'coins', value: 100 } },
            { id: 'ls5', type: CommandType.SET_VAR, params: { varName: 'prizes', value: 0 } },
            { id: 'ls6', type: CommandType.SET_VAR, params: { varName: 'streak', value: 0 } },
            { id: 'ls7', type: CommandType.SET_VAR, params: { varName: 'spins', value: 10 } },
            { id: 'ls8', type: CommandType.SAY, params: { text: 'Spin to win!' } },
            { id: 'ls9', type: CommandType.FOREVER, params: {} },
            { id: 'ls10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
            { id: 'ls11', type: CommandType.CALC_RANDOM, params: { varName: 'result', value: 1, value2: 6 } },
            { id: 'ls12', type: CommandType.CHANGE_VAR, params: { varName: 'spins', value: -1 } },
            { id: 'ls13', type: CommandType.PLAY_SOUND, params: { text: 'spin' } },
            { id: 'ls14', type: CommandType.SCREEN_SHAKE, params: { value: 3 } },
            { id: 'ls15', type: CommandType.END_IF, params: {} },
            { id: 'ls16', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } },
            { id: 'ls17', type: CommandType.CHANGE_VAR, params: { varName: 'coins', value: 50 } },
            { id: 'ls18', type: CommandType.CHANGE_VAR, params: { varName: 'prizes', value: 1 } },
            { id: 'ls19', type: CommandType.CHANGE_VAR, params: { varName: 'streak', value: 1 } },
            { id: 'ls20', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
            { id: 'ls21', type: CommandType.SPAWN_PARTICLES, params: { value: 8 } },
            { id: 'ls22', type: CommandType.END_IF, params: {} },
            { id: 'ls23', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
            { id: 'ls24', type: CommandType.CHANGE_VAR, params: { varName: 'coins', value: 25 } },
            { id: 'ls25', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
            { id: 'ls26', type: CommandType.END_IF, params: {} },
            { id: 'ls27', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
            { id: 'ls28', type: CommandType.CHANGE_VAR, params: { varName: 'spins', value: 3 } },
            { id: 'ls29', type: CommandType.PLAY_SOUND, params: { text: 'bonus' } },
            { id: 'ls30', type: CommandType.SAY, params: { text: '+3 Spins!' } },
            { id: 'ls31', type: CommandType.END_IF, params: {} },
            { id: 'win_lucky', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'prizes', value: 10 } },
            { id: 'win_lucky2', type: CommandType.WIN_GAME, params: {} },
            { id: 'win_lucky3', type: CommandType.END_IF, params: {} },
            { id: 'lose_lucky', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'spins', value: 0 } },
            { id: 'lose_lucky2', type: CommandType.GAME_OVER, params: {} },
            { id: 'lose_lucky3', type: CommandType.END_IF, params: {} },
            { id: 'ls32', type: CommandType.END_FOREVER, params: {} },
        ]
    }
];
