import { AppMode, CommandType, CircuitComponent, CommandBlock } from '../../types';
import { LucideIcon, Zap, Lock, Box, Eye, Sparkles, RotateCw, Flag, Grid, Link, List, Compass, ArrowBigUp, AlertTriangle } from 'lucide-react';

export const puzzleTemplates: {
    id: string,
    mode: AppMode,
    name: string,
    description: string,
    icon: LucideIcon,
    color: string,
    commands: CommandBlock[],
    circuitComponents?: CircuitComponent[]
}[] = [
        {
            id: 'tpl_game_puzzle',
            mode: AppMode.GAME,
            name: 'Puzzle Match',
            description: 'Match colors and clear the board!',
            icon: Zap,
            color: 'bg-pink-600',
            commands: [
                { id: '1', type: CommandType.SET_TITLE, params: { text: 'Color Match' } },
                { id: '2', type: CommandType.SET_BACKGROUND, params: { color: '#1e293b' } },
                { id: '3', type: CommandType.SET_VAR, params: { varName: 'moves', value: 0 } },
                { id: '4', type: CommandType.SET_VAR, params: { varName: 'matched', value: 0 } },
                { id: '5', type: CommandType.SAY, params: { text: 'Match the colors!' } },
                { id: '6', type: CommandType.FOREVER, params: {} },
                { id: '7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: '8', type: CommandType.CHANGE_VAR, params: { varName: 'moves', value: 1 } },
                { id: '9', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: '10', type: CommandType.END_IF, params: {} },
                { id: 'win_puzzle_match', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'matched', value: 10 } },
                { id: 'win_puzzle_match2', type: CommandType.WIN_GAME, params: {} },
                { id: 'win_puzzle_match3', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
                { id: 'win_puzzle_match4', type: CommandType.END_IF, params: {} },
                { id: 'lose_puzzle_match', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'moves', value: 0 } },
                { id: 'lose_puzzle_match2', type: CommandType.GAME_OVER, params: {} },
                { id: 'lose_puzzle_match3', type: CommandType.SAY, params: { text: 'No moves left!' } },
                { id: 'lose_puzzle_match4', type: CommandType.END_IF, params: {} },
                { id: '11', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        { id: 'tpl_puzzle_match3', mode: AppMode.GAME, name: 'Gem Crusher', description: 'Match 3 or more gems to score!', icon: Sparkles, color: 'bg-gradient-to-r from-purple-500 to-pink-600', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'grid' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '💎' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } }, { id: 'c4', type: CommandType.SET_VAR, params: { varName: 'moves', value: 30 } }, { id: 'c5', type: CommandType.FOREVER, params: {} }, { id: 'c6', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c7', type: CommandType.SWAP_TILES, params: {} }, { id: 'c8', type: CommandType.CHECK_MATCH, params: {} }, { id: 'c9', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } }, { id: 'c10', type: CommandType.CHANGE_VAR, params: { varName: 'moves', value: -1 } }, { id: 'c11', type: CommandType.PLAY_SOUND, params: { text: 'coin' } }, { id: 'c12', type: CommandType.END_IF, params: {} }, { id: 'win_gem', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'score', value: 300 } }, { id: 'win_gem2', type: CommandType.WIN_GAME, params: {} }, { id: 'win_gem3', type: CommandType.END_IF, params: {} }, { id: 'lose_gem', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'moves', value: 0 } }, { id: 'lose_gem2', type: CommandType.GAME_OVER, params: {} }, { id: 'lose_gem3', type: CommandType.END_IF, params: {} }, { id: 'c13', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_puzzle_sliding', mode: AppMode.GAME, name: 'Sliding Puzzle', description: 'Slide tiles to complete the picture!', icon: Grid, color: 'bg-gradient-to-r from-blue-500 to-indigo-600', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'grid' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🧩' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'moves', value: 0 } }, { id: 'c4', type: CommandType.FOREVER, params: {} }, { id: 'c5', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } }, { id: 'c6', type: CommandType.SLIDE_PUZZLE, params: { text: 'left' } }, { id: 'c7', type: CommandType.CHANGE_VAR, params: { varName: 'moves', value: 1 } }, { id: 'c8', type: CommandType.PLAY_SOUND, params: { text: 'click' } }, { id: 'c9', type: CommandType.END_IF, params: {} }, { id: 'c10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } }, { id: 'c11', type: CommandType.SLIDE_PUZZLE, params: { text: 'right' } }, { id: 'c12', type: CommandType.CHANGE_VAR, params: { varName: 'moves', value: 1 } }, { id: 'c13', type: CommandType.PLAY_SOUND, params: { text: 'click' } }, { id: 'c14', type: CommandType.END_IF, params: {} }, { id: 'c15', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } }, { id: 'c16', type: CommandType.SLIDE_PUZZLE, params: { text: 'up' } }, { id: 'c17', type: CommandType.CHANGE_VAR, params: { varName: 'moves', value: 1 } }, { id: 'c18', type: CommandType.PLAY_SOUND, params: { text: 'click' } }, { id: 'c19', type: CommandType.END_IF, params: {} }, { id: 'c20', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } }, { id: 'c21', type: CommandType.SLIDE_PUZZLE, params: { text: 'down' } }, { id: 'c22', type: CommandType.CHANGE_VAR, params: { varName: 'moves', value: 1 } }, { id: 'c23', type: CommandType.PLAY_SOUND, params: { text: 'click' } }, { id: 'c24', type: CommandType.END_IF, params: {} }, { id: 'lose_slide', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'moves', value: 0 } }, { id: 'lose_slide2', type: CommandType.GAME_OVER, params: {} }, { id: 'lose_slide3', type: CommandType.END_IF, params: {} }, { id: 'c25', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_puzzle_connect', mode: AppMode.GAME, name: 'Connect Dots', description: 'Connect matching colored dots!', icon: Link, color: 'bg-gradient-to-r from-cyan-500 to-blue-600', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'grid' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🔗' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'pairs', value: 0 } }, { id: 'c4', type: CommandType.FOREVER, params: {} }, { id: 'c5', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c6', type: CommandType.CONNECT_DOTS, params: { value: 2 } }, { id: 'c7', type: CommandType.CHANGE_VAR, params: { varName: 'pairs', value: 1 } }, { id: 'c8', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } }, { id: 'c9', type: CommandType.END_IF, params: {} }, { id: 'win_connect', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'pairs', value: 5 } }, { id: 'win_connect2', type: CommandType.WIN_GAME, params: {} }, { id: 'win_connect3', type: CommandType.END_IF, params: {} }, { id: 'c10', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_puzzle_memory', mode: AppMode.GAME, name: 'Memory Match', description: 'Flip cards and find matching pairs!', icon: Eye, color: 'bg-gradient-to-r from-amber-500 to-orange-600', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'grid' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🧠' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'matches', value: 0 } }, { id: 'c4', type: CommandType.SET_VAR, params: { varName: 'attempts', value: 0 } }, { id: 'c5', type: CommandType.FOREVER, params: {} }, { id: 'c6', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c7', type: CommandType.FLIP_CARD, params: {} }, { id: 'c8', type: CommandType.CHANGE_VAR, params: { varName: 'attempts', value: 1 } }, { id: 'c9', type: CommandType.PLAY_SOUND, params: { text: 'click' } }, { id: 'c10', type: CommandType.END_IF, params: {} }, { id: 'win_memory', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'matches', value: 8 } }, { id: 'win_memory2', type: CommandType.WIN_GAME, params: {} }, { id: 'win_memory3', type: CommandType.END_IF, params: {} }, { id: 'c11', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_puzzle_sudoku', mode: AppMode.GAME, name: 'Number Logic', description: 'Fill the grid with the right numbers!', icon: Grid, color: 'bg-gradient-to-r from-emerald-500 to-teal-600', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'grid' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🔢' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'correct', value: 0 } }, { id: 'c4', type: CommandType.FOREVER, params: {} }, { id: 'c5', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c6', type: CommandType.FILL_COLOR, params: { color: '#22c55e' } }, { id: 'c7', type: CommandType.PLAY_SOUND, params: { text: 'coin' } }, { id: 'c8', type: CommandType.END_IF, params: {} }, { id: 'win_sudoku', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'correct', value: 9 } }, { id: 'win_sudoku2', type: CommandType.WIN_GAME, params: {} }, { id: 'win_sudoku3', type: CommandType.END_IF, params: {} }, { id: 'c9', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_puzzle_sort', mode: AppMode.GAME, name: 'Color Sort', description: 'Sort colored liquids into tubes!', icon: List, color: 'bg-gradient-to-r from-rose-500 to-pink-600', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'grid' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🧪' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'sorted', value: 0 } }, { id: 'c4', type: CommandType.FOREVER, params: {} }, { id: 'c5', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c6', type: CommandType.SORT_ITEMS, params: { text: 'color' } }, { id: 'c7', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } }, { id: 'c8', type: CommandType.END_IF, params: {} }, { id: 'win_sort', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'sorted', value: 5 } }, { id: 'win_sort2', type: CommandType.WIN_GAME, params: {} }, { id: 'win_sort3', type: CommandType.END_IF, params: {} }, { id: 'c9', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_puzzle_tetris', mode: AppMode.GAME, name: 'Block Drop', description: 'Classic falling block puzzle!', icon: Box, color: 'bg-gradient-to-r from-indigo-500 to-violet-600', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'grid' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🟦' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'lines', value: 0 } }, { id: 'c4', type: CommandType.SET_VAR, params: { varName: 'level', value: 1 } }, { id: 'c5', type: CommandType.FOREVER, params: {} }, { id: 'c6', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } }, { id: 'c7', type: CommandType.MOVE_X, params: { value: -40 } }, { id: 'c8', type: CommandType.PLAY_SOUND, params: { text: 'click' } }, { id: 'c9', type: CommandType.END_IF, params: {} }, { id: 'c10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } }, { id: 'c11', type: CommandType.MOVE_X, params: { value: 40 } }, { id: 'c12', type: CommandType.PLAY_SOUND, params: { text: 'click' } }, { id: 'c13', type: CommandType.END_IF, params: {} }, { id: 'c14', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } }, { id: 'c15', type: CommandType.ROTATE_BLOCK, params: { value: 90 } }, { id: 'c16', type: CommandType.PLAY_SOUND, params: { text: 'click' } }, { id: 'c17', type: CommandType.END_IF, params: {} }, { id: 'c18', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } }, { id: 'c19', type: CommandType.MOVE_Y, params: { value: 40 } }, { id: 'c20', type: CommandType.END_IF, params: {} }, { id: 'win_tetris', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'lines', value: 20 } }, { id: 'win_tetris2', type: CommandType.WIN_GAME, params: {} }, { id: 'win_tetris3', type: CommandType.END_IF, params: {} }, { id: 'c21', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_puzzle_maze', mode: AppMode.GAME, name: 'Maze Runner', description: 'Navigate through the maze!', icon: Compass, color: 'bg-gradient-to-r from-stone-600 to-stone-800', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'stone_floor' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🏃' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'time', value: 0 } }, { id: 'c4', type: CommandType.FOREVER, params: {} }, { id: 'c5', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } }, { id: 'c6', type: CommandType.MOVE_X, params: { value: -5 } }, { id: 'c7', type: CommandType.END_IF, params: {} }, { id: 'c8', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } }, { id: 'c9', type: CommandType.MOVE_X, params: { value: 5 } }, { id: 'c10', type: CommandType.END_IF, params: {} }, { id: 'c11', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } }, { id: 'c12', type: CommandType.MOVE_Y, params: { value: -5 } }, { id: 'c13', type: CommandType.END_IF, params: {} }, { id: 'c14', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } }, { id: 'c15', type: CommandType.MOVE_Y, params: { value: 5 } }, { id: 'c16', type: CommandType.END_IF, params: {} }, { id: 'c17', type: CommandType.CHANGE_VAR, params: { varName: 'time', value: 1 } }, { id: 'lose_maze', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'time', value: 600 } }, { id: 'lose_maze2', type: CommandType.GAME_OVER, params: {} }, { id: 'lose_maze3', type: CommandType.SAY, params: { text: 'Time up!' } }, { id: 'lose_maze4', type: CommandType.END_IF, params: {} }, { id: 'c18', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_puzzle_pattern', mode: AppMode.GAME, name: 'Pattern Master', description: 'Unlock the door with the right pattern!', icon: Lock, color: 'bg-gradient-to-r from-amber-600 to-yellow-600', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'stone_floor' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🔐' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'attempts', value: 0 } }, { id: 'c4', type: CommandType.FOREVER, params: {} }, { id: 'c5', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c6', type: CommandType.UNLOCK_PATTERN, params: { text: '1234' } }, { id: 'c7', type: CommandType.CHANGE_VAR, params: { varName: 'attempts', value: 1 } }, { id: 'c8', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } }, { id: 'c9', type: CommandType.END_IF, params: {} }, { id: 'lose_pattern', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'attempts', value: 5 } }, { id: 'lose_pattern2', type: CommandType.GAME_OVER, params: {} }, { id: 'lose_pattern3', type: CommandType.SAY, params: { text: 'Too many attempts!' } }, { id: 'lose_pattern4', type: CommandType.END_IF, params: {} }, { id: 'c10', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_puzzle_mahjong', mode: AppMode.GAME, name: 'Mahjong Tiles', description: 'Match identical tiles to clear the board!', icon: Grid, color: 'bg-gradient-to-r from-emerald-600 to-teal-700', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'grid' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🀄' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'matches', value: 0 } }, { id: 'c4', type: CommandType.FOREVER, params: {} }, { id: 'c5', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c6', type: CommandType.SWAP_TILES, params: {} }, { id: 'c7', type: CommandType.CHECK_MATCH, params: {} }, { id: 'c8', type: CommandType.CHANGE_VAR, params: { varName: 'matches', value: 1 } }, { id: 'c9', type: CommandType.PLAY_SOUND, params: { text: 'coin' } }, { id: 'c10', type: CommandType.END_IF, params: {} }, { id: 'win_mahjong', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'matches', value: 10 } }, { id: 'win_mahjong2', type: CommandType.WIN_GAME, params: {} }, { id: 'win_mahjong3', type: CommandType.END_IF, params: {} }, { id: 'c11', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_puzzle_pipe', mode: AppMode.GAME, name: 'Pipe Connect', description: 'Rotate pipes to connect water flow!', icon: RotateCw, color: 'bg-gradient-to-r from-blue-500 to-cyan-600', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'grid' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🔧' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'pipes_connected', value: 0 } }, { id: 'c4', type: CommandType.FOREVER, params: {} }, { id: 'c5', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c6', type: CommandType.ROTATE_BLOCK, params: { value: 90 } }, { id: 'c7', type: CommandType.PLAY_SOUND, params: { text: 'click' } }, { id: 'c8', type: CommandType.END_IF, params: {} }, { id: 'win_pipe', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'pipes_connected', value: 8 } }, { id: 'win_pipe2', type: CommandType.WIN_GAME, params: {} }, { id: 'win_pipe3', type: CommandType.END_IF, params: {} }, { id: 'c9', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_puzzle_platformer_puzzle', mode: AppMode.GAME, name: 'Gravity Puzzle', description: 'Rotate gravity to solve puzzles!', icon: ArrowBigUp, color: 'bg-gradient-to-r from-violet-500 to-purple-700', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'stone_floor' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🟣' } }, { id: 'c3', type: CommandType.SET_GRAVITY, params: { condition: 'true' } }, { id: 'c4', type: CommandType.SET_VAR, params: { varName: 'gravity_dir', value: 1 } }, { id: 'c5', type: CommandType.FOREVER, params: {} }, { id: 'c6', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c7', type: CommandType.CHANGE_VAR, params: { varName: 'gravity_dir', value: 1 } }, { id: 'c8', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } }, { id: 'c9', type: CommandType.END_IF, params: {} }, { id: 'c10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } }, { id: 'c11', type: CommandType.MOVE_X, params: { value: -5 } }, { id: 'c12', type: CommandType.END_IF, params: {} }, { id: 'c13', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } }, { id: 'c14', type: CommandType.MOVE_X, params: { value: 5 } }, { id: 'c15', type: CommandType.END_IF, params: {} }, { id: 'win_gravity', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'gravity_dir', value: 4 } }, { id: 'win_gravity2', type: CommandType.WIN_GAME, params: {} }, { id: 'win_gravity3', type: CommandType.END_IF, params: {} }, { id: 'c16', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_puzzle_minesweeper', mode: AppMode.GAME, name: 'Mine Sweeper', description: 'Flag all mines without detonating them!', icon: AlertTriangle, color: 'bg-gradient-to-r from-slate-600 to-slate-800', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'grid' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '💣' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'flags_placed', value: 0 } }, { id: 'c4', type: CommandType.SET_VAR, params: { varName: 'mines', value: 10 } }, { id: 'c5', type: CommandType.FOREVER, params: {} }, { id: 'c6', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c7', type: CommandType.EXAMINE, params: { text: 'cell' } }, { id: 'c8', type: CommandType.PLAY_SOUND, params: { text: 'click' } }, { id: 'c9', type: CommandType.END_IF, params: {} }, { id: 'c10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 33 } }, { id: 'c11', type: CommandType.CHANGE_VAR, params: { varName: 'flags_placed', value: 1 } }, { id: 'c12', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } }, { id: 'c13', type: CommandType.END_IF, params: {} }, { id: 'win_minesweeper', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'flags_placed', value: 10 } }, { id: 'win_minesweeper2', type: CommandType.WIN_GAME, params: {} }, { id: 'win_minesweeper3', type: CommandType.END_IF, params: {} }, { id: 'c14', type: CommandType.END_FOREVER, params: {} }
        ]},
];
