import { AppMode, CommandType, CircuitComponent, CommandBlock } from '../../types';
import { LucideIcon, Zap, RotateCcw } from 'lucide-react';

export const racingTemplates: {
    id: string,
    mode: AppMode,
    name: string,
    description: string,
    icon: LucideIcon,
    color: string,
    commands: CommandBlock[],
    circuitComponents?: CircuitComponent[]
}[] = [
        {
            id: 'tpl_racing_kart',
            mode: AppMode.GAME,
            name: 'Kart Racing',
            description: 'Mario Kart-style racing with power-ups and drifting!',
            icon: Zap,
            color: 'bg-gradient-to-r from-yellow-500 to-orange-500',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🏎️' } },
                { id: 's3', type: CommandType.SET_WEATHER, params: { text: 'none' } },
                { id: 's4', type: CommandType.BOUNCE_ON_EDGE, params: {} },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'speed', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'lap', value: 1 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'position', value: 1 } },
                { id: 'v4', type: CommandType.SET_VAR, params: { varName: 'boost', value: 0 } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '⚡' } },
                { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '⭐' } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '🚙' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '🚗' } },
                { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'race' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv2', type: CommandType.MOVE_Y, params: { value: -10 } },
                { id: 'mv3', type: CommandType.CHANGE_VAR, params: { varName: 'speed', value: 1 } },
                { id: 'mv4', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'mv5', type: CommandType.END_IF, params: {} },
                { id: 'mv6', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv7', type: CommandType.MOVE_Y, params: { value: 10 } },
                { id: 'mv8', type: CommandType.END_IF, params: {} },
                { id: 'mv9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv10', type: CommandType.MOVE_X, params: { value: -8 } },
                { id: 'mv11', type: CommandType.END_IF, params: {} },
                { id: 'mv12', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv13', type: CommandType.MOVE_X, params: { value: 8 } },
                { id: 'mv14', type: CommandType.END_IF, params: {} },
                { id: 'dr1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'dr2', type: CommandType.CHANGE_VAR, params: { varName: 'boost', value: 5 } },
                { id: 'dr3', type: CommandType.PLAY_SOUND, params: { text: 'laser' } },
                { id: 'dr4', type: CommandType.END_IF, params: {} },
                { id: 'pw1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '⚡' } },
                { id: 'pw2', type: CommandType.CHANGE_VAR, params: { varName: 'speed', value: 10 } },
                { id: 'pw3', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'pw4', type: CommandType.SAY, params: { text: '⚡ BOOST!' } },
                { id: 'pw5', type: CommandType.END_IF, params: {} },
                { id: 'st1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🏁' } },
                { id: 'st2', type: CommandType.CHANGE_VAR, params: { varName: 'lap', value: 1 } },
                { id: 'st3', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: 'st4', type: CommandType.SAY, params: { text: '🏁 LAP ' } },
                { id: 'st5', type: CommandType.END_IF, params: {} },
                { id: 'wc1', type: CommandType.IF, params: { condition: 'GREATER' } },
                { id: 'wc2', type: CommandType.WIN_GAME, params: {} },
                { id: 'wc3', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
                { id: 'wc4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_racing_formula',
            mode: AppMode.GAME,
            name: 'Formula Racing',
            description: 'High-speed F1 racing with slipstreaming!',
            icon: Zap,
            color: 'bg-gradient-to-r from-red-500 to-red-700',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🏎️' } },
                { id: 's3', type: CommandType.SET_WEATHER, params: { text: 'none' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'speed', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'lap', value: 1 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'top_speed', value: 15 } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '🏎️' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '🏎️' } },
                { id: 'e3', type: CommandType.SPAWN_ENEMY, params: { text: '🏎️' } },
                { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'race' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv2', type: CommandType.MOVE_Y, params: { value: -12 } },
                { id: 'mv3', type: CommandType.CHANGE_VAR, params: { varName: 'speed', value: 2 } },
                { id: 'mv4', type: CommandType.END_IF, params: {} },
                { id: 'mv5', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv6', type: CommandType.MOVE_Y, params: { value: 8 } },
                { id: 'mv7', type: CommandType.CHANGE_VAR, params: { varName: 'speed', value: -1 } },
                { id: 'mv8', type: CommandType.END_IF, params: {} },
                { id: 'mv9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv10', type: CommandType.MOVE_X, params: { value: -10 } },
                { id: 'mv11', type: CommandType.END_IF, params: {} },
                { id: 'mv12', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv13', type: CommandType.MOVE_X, params: { value: 10 } },
                { id: 'mv14', type: CommandType.END_IF, params: {} },
                { id: 'dr1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'dr2', type: CommandType.CHANGE_VAR, params: { varName: 'speed', value: 5 } },
                { id: 'dr3', type: CommandType.PLAY_SOUND, params: { text: 'laser' } },
                { id: 'dr4', type: CommandType.SAY, params: { text: '🔥 NITRO!' } },
                { id: 'dr5', type: CommandType.END_IF, params: {} },
                { id: 'st1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🏁' } },
                { id: 'st2', type: CommandType.CHANGE_VAR, params: { varName: 'lap', value: 1 } },
                { id: 'st3', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: 'st4', type: CommandType.END_IF, params: {} },
                { id: 'wc1', type: CommandType.IF, params: { condition: 'GREATER' } },
                { id: 'wc2', type: CommandType.WIN_GAME, params: {} },
                { id: 'wc3', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
                { id: 'wc4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_racing_street',
            mode: AppMode.GAME,
            name: 'Street Racing',
            description: 'Night street racing with traffic dodging!',
            icon: Zap,
            color: 'bg-gradient-to-r from-purple-500 to-indigo-600',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🚗' } },
                { id: 's3', type: CommandType.SET_WEATHER, params: { text: 'none' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'speed', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'distance', value: 0 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'dodged', value: 0 } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '🚗' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '🚙' } },
                { id: 'e3', type: CommandType.SPAWN_ENEMY, params: { text: '🚕' } },
                { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'race' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -8 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 8 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.MOVE_Y, params: { value: -5 } },
                { id: 'mv8', type: CommandType.CHANGE_VAR, params: { varName: 'distance', value: 1 } },
                { id: 'ed1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🚗' } },
                { id: 'ed2', type: CommandType.CHANGE_VAR, params: { varName: 'speed', value: -20 } },
                { id: 'ed3', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'ed4', type: CommandType.SPAWN_PARTICLES, params: { value: 10 } },
                { id: 'ed5', type: CommandType.END_IF, params: {} },
                { id: 'sp1', type: CommandType.SPAWN_ITEM, params: { text: '⚡' } },
                { id: 'sp2', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '⚡' } },
                { id: 'sp3', type: CommandType.CHANGE_VAR, params: { varName: 'speed', value: 10 } },
                { id: 'sp4', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'sp5', type: CommandType.END_IF, params: {} },
                { id: 'wc1', type: CommandType.IF, params: { condition: 'GREATER', varName: 'distance', value: 500 } },
                { id: 'wc2', type: CommandType.WIN_GAME, params: {} },
                { id: 'wc3', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
                { id: 'wc4', type: CommandType.END_IF, params: {} },
                { id: 'go1', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'speed', value: 0 } },
                { id: 'go2', type: CommandType.GAME_OVER, params: {} },
                { id: 'go3', type: CommandType.PLAY_SOUND, params: { text: 'death' } },
                { id: 'go4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_racing_drift',
            mode: AppMode.GAME,
            name: 'Drift Racing',
            description: 'Drift around corners for points!',
            icon: Zap,
            color: 'bg-gradient-to-r from-cyan-500 to-blue-500',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🏎️' } },
                { id: 's3', type: CommandType.SET_WEATHER, params: { text: 'none' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'drift_score', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'is_drifting', value: 0 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'combo', value: 0 } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '🏁' } },
                { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '🏁' } },
                { id: 'p3', type: CommandType.SPAWN_ITEM, params: { text: '🏁' } },
                { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'race' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -6 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 6 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.MOVE_Y, params: { value: -3 } },
                { id: 'dr1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'dr2', type: CommandType.SET_VAR, params: { varName: 'is_drifting', value: 1 } },
                { id: 'dr3', type: CommandType.CHANGE_VAR, params: { varName: 'drift_score', value: 5 } },
                { id: 'dr4', type: CommandType.PLAY_SOUND, params: { text: 'laser' } },
                { id: 'dr5', type: CommandType.END_IF, params: {} },
                { id: 'st1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🏁' } },
                { id: 'st2', type: CommandType.CHANGE_VAR, params: { varName: 'drift_score', value: 50 } },
                { id: 'st3', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: 'st4', type: CommandType.SAY, params: { text: '🔥 DRIFT BONUS!' } },
                { id: 'st5', type: CommandType.END_IF, params: {} },
                { id: 'wc1', type: CommandType.IF, params: { condition: 'GREATER' } },
                { id: 'wc2', type: CommandType.WIN_GAME, params: {} },
                { id: 'wc3', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
                { id: 'wc4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_racing_bike',
            mode: AppMode.GAME,
            name: 'Bike Racing',
            description: 'Motorcycle racing with wheelies and stunts!',
            icon: Zap,
            color: 'bg-gradient-to-r from-orange-500 to-red-500',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🏍️' } },
                { id: 's3', type: CommandType.SET_WEATHER, params: { text: 'none' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'speed', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'stunts', value: 0 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'airtime', value: 0 } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '⚡' } },
                { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '⭐' } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '🏍️' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '🏍️' } },
                { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'race' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv2', type: CommandType.MOVE_Y, params: { value: -10 } },
                { id: 'mv3', type: CommandType.CHANGE_VAR, params: { varName: 'speed', value: 2 } },
                { id: 'mv4', type: CommandType.END_IF, params: {} },
                { id: 'mv5', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv6', type: CommandType.MOVE_X, params: { value: -6 } },
                { id: 'mv7', type: CommandType.END_IF, params: {} },
                { id: 'mv8', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv9', type: CommandType.MOVE_X, params: { value: 6 } },
                { id: 'mv10', type: CommandType.END_IF, params: {} },
                { id: 'st1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'st2', type: CommandType.CHANGE_VAR, params: { varName: 'stunts', value: 1 } },
                { id: 'st3', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'st4', type: CommandType.SAY, params: { text: ' wheelie!' } },
                { id: 'st5', type: CommandType.END_IF, params: {} },
                { id: 'wc1', type: CommandType.IF, params: { condition: 'GREATER' } },
                { id: 'wc2', type: CommandType.WIN_GAME, params: {} },
                { id: 'wc3', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
                { id: 'wc4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_racing_boat',
            mode: AppMode.GAME,
            name: 'Boat Racing',
            description: 'Speed boat racing with waves and buoys!',
            icon: Zap,
            color: 'bg-gradient-to-r from-blue-500 to-cyan-500',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🚤' } },
                { id: 's3', type: CommandType.SET_WEATHER, params: { text: 'rain' } },
                { id: 's4', type: CommandType.SET_WEATHER, params: { text: 'water' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'speed', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'checkpoint', value: 0 } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '🚩' } },
                { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '🚩' } },
                { id: 'p3', type: CommandType.SPAWN_ITEM, params: { text: '🚩' } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '⛵' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '🚢' } },
                { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'race' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv2', type: CommandType.MOVE_Y, params: { value: -8 } },
                { id: 'mv3', type: CommandType.CHANGE_VAR, params: { varName: 'speed', value: 1 } },
                { id: 'mv4', type: CommandType.END_IF, params: {} },
                { id: 'mv5', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv6', type: CommandType.MOVE_X, params: { value: -6 } },
                { id: 'mv7', type: CommandType.END_IF, params: {} },
                { id: 'mv8', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv9', type: CommandType.MOVE_X, params: { value: 6 } },
                { id: 'mv10', type: CommandType.END_IF, params: {} },
                { id: 'cp1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🚩' } },
                { id: 'cp2', type: CommandType.CHANGE_VAR, params: { varName: 'checkpoint', value: 1 } },
                { id: 'cp3', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: 'cp4', type: CommandType.SAY, params: { text: '🚩 Checkpoint!' } },
                { id: 'cp5', type: CommandType.END_IF, params: {} },
                { id: 'wc1', type: CommandType.IF, params: { condition: 'GREATER' } },
                { id: 'wc2', type: CommandType.WIN_GAME, params: {} },
                { id: 'wc3', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
                { id: 'wc4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_racing_plane',
            mode: AppMode.GAME,
            name: 'Plane Racing',
            description: 'Aerial racing through clouds and rings!',
            icon: Zap,
            color: 'bg-gradient-to-r from-sky-400 to-blue-600',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '✈️' } },
                { id: 's3', type: CommandType.SET_WEATHER, params: { text: 'none' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'speed', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'rings', value: 0 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'altitude', value: 50 } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '⭕' } },
                { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '⭕' } },
                { id: 'p3', type: CommandType.SPAWN_ITEM, params: { text: '⭕' } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '🦅' } },
                { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'race' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv2', type: CommandType.MOVE_Y, params: { value: -8 } },
                { id: 'mv3', type: CommandType.CHANGE_VAR, params: { varName: 'altitude', value: 1 } },
                { id: 'mv4', type: CommandType.END_IF, params: {} },
                { id: 'mv5', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv6', type: CommandType.MOVE_Y, params: { value: 8 } },
                { id: 'mv7', type: CommandType.CHANGE_VAR, params: { varName: 'altitude', value: -1 } },
                { id: 'mv8', type: CommandType.END_IF, params: {} },
                { id: 'mv9', type: CommandType.MOVE_X, params: { value: 5 } },
                { id: 'rg1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '⭕' } },
                { id: 'rg2', type: CommandType.CHANGE_VAR, params: { varName: 'rings', value: 1 } },
                { id: 'rg3', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: 'rg4', type: CommandType.SAY, params: { text: '⭕ Ring!' } },
                { id: 'rg5', type: CommandType.END_IF, params: {} },
                { id: 'wc1', type: CommandType.IF, params: { condition: 'GREATER' } },
                { id: 'wc2', type: CommandType.WIN_GAME, params: {} },
                { id: 'wc3', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
                { id: 'wc4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_racing_space',
            mode: AppMode.GAME,
            name: 'Space Racing',
            description: 'Race through asteroid fields in your spaceship!',
            icon: Zap,
            color: 'bg-gradient-to-r from-indigo-500 to-purple-600',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'space' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🚀' } },
                { id: 's3', type: CommandType.SET_WEATHER, params: { text: 'none' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'speed', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'dodged', value: 0 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'health', value: 100 } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '☄️' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '🪨' } },
                { id: 'e3', type: CommandType.SPAWN_ENEMY, params: { text: '☄️' } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '⚡' } },
                { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '❤️' } },
                { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'race' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -8 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 8 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv8', type: CommandType.MOVE_Y, params: { value: -8 } },
                { id: 'mv9', type: CommandType.END_IF, params: {} },
                { id: 'mv10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } },
                { id: 'mv11', type: CommandType.MOVE_Y, params: { value: 8 } },
                { id: 'mv12', type: CommandType.END_IF, params: {} },
                { id: 'ed1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '☄️' } },
                { id: 'ed2', type: CommandType.CHANGE_VAR, params: { varName: 'health', value: -20 } },
                { id: 'ed3', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'ed4', type: CommandType.SPAWN_PARTICLES, params: { value: 8 } },
                { id: 'ed5', type: CommandType.END_IF, params: {} },
                { id: 'hp1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '❤️' } },
                { id: 'hp2', type: CommandType.CHANGE_VAR, params: { varName: 'health', value: 25 } },
                { id: 'hp3', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'hp4', type: CommandType.END_IF, params: {} },
                { id: 'go1', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'health', value: 0 } },
                { id: 'go2', type: CommandType.GAME_OVER, params: {} },
                { id: 'go3', type: CommandType.PLAY_SOUND, params: { text: 'death' } },
                { id: 'go4', type: CommandType.END_IF, params: {} },
                { id: 'wc1', type: CommandType.IF, params: { condition: 'GREATER', varName: 'dodged', value: 100 } },
                { id: 'wc2', type: CommandType.WIN_GAME, params: {} },
                { id: 'wc3', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
                { id: 'wc4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_racing_monster',
            mode: AppMode.GAME,
            name: 'Monster Truck',
            description: 'Crush cars and jump over obstacles!',
            icon: Zap,
            color: 'bg-gradient-to-r from-red-600 to-orange-600',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🏎️' } },
                { id: 's3', type: CommandType.SET_WEATHER, params: { text: 'none' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'crushed', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'jumps', value: 0 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'score', value: 0 } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '🚗' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '🚙' } },
                { id: 'e3', type: CommandType.SPAWN_ENEMY, params: { text: '🚕' } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '⭐' } },
                { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'race' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -6 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 6 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.MOVE_Y, params: { value: -3 } },
                { id: 'jp1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: 'jp2', type: CommandType.JUMP, params: { value: 15 } },
                { id: 'jp3', type: CommandType.CHANGE_VAR, params: { varName: 'jumps', value: 1 } },
                { id: 'jp4', type: CommandType.PLAY_SOUND, params: { text: 'jump' } },
                { id: 'jp5', type: CommandType.END_IF, params: {} },
                { id: 'cr1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🚗' } },
                { id: 'cr2', type: CommandType.CHANGE_VAR, params: { varName: 'crushed', value: 1 } },
                { id: 'cr3', type: CommandType.CHANGE_VAR, params: { varName: 'score', value: 10 } },
                { id: 'cr4', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'cr5', type: CommandType.SPAWN_PARTICLES, params: { value: 10 } },
                { id: 'cr6', type: CommandType.SAY, params: { text: '💥 CRUSHED!' } },
                { id: 'cr7', type: CommandType.END_IF, params: {} },
                { id: 'wc1', type: CommandType.IF, params: { condition: 'GREATER' } },
                { id: 'wc2', type: CommandType.WIN_GAME, params: {} },
                { id: 'wc3', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
                { id: 'wc4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_racing_rally',
            mode: AppMode.GAME,
            name: 'Rally Racing',
            description: 'Off-road rally through forests and mountains!',
            icon: Zap,
            color: 'bg-gradient-to-r from-green-500 to-emerald-600',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'forest' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🏎️' } },
                { id: 's3', type: CommandType.SET_WEATHER, params: { text: 'rain' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'speed', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'checkpoint', value: 0 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'damage', value: 0 } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '🚩' } },
                { id: 'p2', type: CommandType.SPAWN_ITEM, params: { text: '🚩' } },
                { id: 'p3', type: CommandType.SPAWN_ITEM, params: { text: '🚩' } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '🌳' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '🪨' } },
                { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'race' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } },
                { id: 'mv2', type: CommandType.MOVE_Y, params: { value: -10 } },
                { id: 'mv3', type: CommandType.CHANGE_VAR, params: { varName: 'speed', value: 2 } },
                { id: 'mv4', type: CommandType.END_IF, params: {} },
                { id: 'mv5', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv6', type: CommandType.MOVE_X, params: { value: -8 } },
                { id: 'mv7', type: CommandType.END_IF, params: {} },
                { id: 'mv8', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv9', type: CommandType.MOVE_X, params: { value: 8 } },
                { id: 'mv10', type: CommandType.END_IF, params: {} },
                { id: 'ed1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🌳' } },
                { id: 'ed2', type: CommandType.CHANGE_VAR, params: { varName: 'damage', value: 10 } },
                { id: 'ed3', type: CommandType.PLAY_SOUND, params: { text: 'hurt' } },
                { id: 'ed4', type: CommandType.END_IF, params: {} },
                { id: 'cp1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🚩' } },
                { id: 'cp2', type: CommandType.CHANGE_VAR, params: { varName: 'checkpoint', value: 1 } },
                { id: 'cp3', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: 'cp4', type: CommandType.SAY, params: { text: '🚩 Checkpoint!' } },
                { id: 'cp5', type: CommandType.END_IF, params: {} },
                { id: 'wc1', type: CommandType.IF, params: { condition: 'GREATER', varName: 'checkpoint', value: 2 } },
                { id: 'wc2', type: CommandType.WIN_GAME, params: {} },
                { id: 'wc3', type: CommandType.PLAY_SOUND, params: { text: 'victory' } },
                { id: 'wc4', type: CommandType.END_IF, params: {} },
                { id: 'go1', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'damage', value: 100 } },
                { id: 'go2', type: CommandType.GAME_OVER, params: {} },
                { id: 'go3', type: CommandType.PLAY_SOUND, params: { text: 'death' } },
                { id: 'go4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        {
            id: 'tpl_racing_endless',
            mode: AppMode.GAME,
            name: 'Endless Highway',
            description: 'Dodge traffic forever! How far can you go?',
            icon: Zap,
            color: 'bg-gradient-to-r from-slate-500 to-slate-700',
            commands: [
                { id: 's1', type: CommandType.SET_SCENE, params: { text: 'grid' } },
                { id: 's2', type: CommandType.SET_EMOJI, params: { text: '🚗' } },
                { id: 's3', type: CommandType.SET_WEATHER, params: { text: 'none' } },
                { id: 'v1', type: CommandType.SET_VAR, params: { varName: 'distance', value: 0 } },
                { id: 'v2', type: CommandType.SET_VAR, params: { varName: 'speed', value: 5 } },
                { id: 'v3', type: CommandType.SET_VAR, params: { varName: 'high_score', value: 0 } },
                { id: 'e1', type: CommandType.SPAWN_ENEMY, params: { text: '🚗' } },
                { id: 'e2', type: CommandType.SPAWN_ENEMY, params: { text: '🚙' } },
                { id: 'e3', type: CommandType.SPAWN_ENEMY, params: { text: '🚕' } },
                { id: 'p1', type: CommandType.SPAWN_ITEM, params: { text: '⚡' } },
                { id: 'm1', type: CommandType.SET_BACKGROUND_MUSIC, params: { text: 'race' } },
                { id: 'f1', type: CommandType.FOREVER, params: {} },
                { id: 'mv1', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } },
                { id: 'mv2', type: CommandType.MOVE_X, params: { value: -10 } },
                { id: 'mv3', type: CommandType.END_IF, params: {} },
                { id: 'mv4', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } },
                { id: 'mv5', type: CommandType.MOVE_X, params: { value: 10 } },
                { id: 'mv6', type: CommandType.END_IF, params: {} },
                { id: 'mv7', type: CommandType.MOVE_Y, params: { value: -3 } },
                { id: 'mv8', type: CommandType.CHANGE_VAR, params: { varName: 'distance', value: 1 } },
                { id: 'ed1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🚗' } },
                { id: 'ed2', type: CommandType.CHANGE_VAR, params: { varName: 'speed', value: 20 } },
                { id: 'ed3', type: CommandType.PLAY_SOUND, params: { text: 'explosion' } },
                { id: 'ed4', type: CommandType.SPAWN_PARTICLES, params: { value: 10 } },
                { id: 'ed5', type: CommandType.END_IF, params: {} },
                { id: 'sp1', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '⚡' } },
                { id: 'sp2', type: CommandType.CHANGE_VAR, params: { varName: 'speed', value: -5 } },
                { id: 'sp3', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'sp4', type: CommandType.SAY, params: { text: '⚡ SLOW MO!' } },
                { id: 'sp5', type: CommandType.END_IF, params: {} },
                { id: 'go1', type: CommandType.IF, params: { condition: 'GREATER', varName: 'speed', value: 25 } },
                { id: 'go2', type: CommandType.GAME_OVER, params: {} },
                { id: 'go3', type: CommandType.PLAY_SOUND, params: { text: 'death' } },
                { id: 'go4', type: CommandType.END_IF, params: {} },
                { id: 'f2', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        { id: 'tpl_racing_kart_new', mode: AppMode.GAME, name: 'Kart Racing', description: 'Fun kart racing with boost pads and items!', icon: Zap, color: 'bg-gradient-to-r from-red-500 to-yellow-500', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'race_road' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🏎️' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'laps', value: 0 } }, { id: 'c4', type: CommandType.SET_VAR, params: { varName: 'speed', value: 0 } }, { id: 'c5', type: CommandType.START_RACE, params: { value: 3 } }, { id: 'c6', type: CommandType.FOREVER, params: {} }, { id: 'c7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } }, { id: 'c8', type: CommandType.MOVE_X, params: { value: 6 } }, { id: 'c9', type: CommandType.CHANGE_VAR, params: { varName: 'speed', value: 1 } }, { id: 'c10', type: CommandType.END_IF, params: {} }, { id: 'c11', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } }, { id: 'c12', type: CommandType.DRIFT, params: { value: 5 } }, { id: 'c13', type: CommandType.PLAY_SOUND, params: { text: 'dash' } }, { id: 'c14', type: CommandType.END_IF, params: {} }, { id: 'c15', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c16', type: CommandType.BOOST, params: { value: 15 } }, { id: 'c17', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } }, { id: 'c18', type: CommandType.END_IF, params: {} }, { id: 'c19', type: CommandType.IF, params: { condition: 'IS_TOUCHING', text: '🏁' } }, { id: 'c20', type: CommandType.LAP_COMPLETE, params: {} }, { id: 'c21', type: CommandType.SAY, params: { text: 'Lap Complete!' } }, { id: 'c22', type: CommandType.END_IF, params: {} }, { id: 'c23', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_racing_formula_new', mode: AppMode.GAME, name: 'Formula 1', description: 'High-speed F1 racing with pit stops!', icon: Zap, color: 'bg-gradient-to-r from-red-600 to-red-800', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'race_road' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🏎️' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'laps', value: 0 } }, { id: 'c4', type: CommandType.SET_VAR, params: { varName: 'tire_wear', value: 100 } }, { id: 'c5', type: CommandType.START_RACE, params: { value: 5 } }, { id: 'c6', type: CommandType.FOREVER, params: {} }, { id: 'c7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } }, { id: 'c8', type: CommandType.MOVE_X, params: { value: 8 } }, { id: 'c9', type: CommandType.CHANGE_VAR, params: { varName: 'tire_wear', value: -1 } }, { id: 'c10', type: CommandType.END_IF, params: {} }, { id: 'c11', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } }, { id: 'c12', type: CommandType.PIT_STOP, params: {} }, { id: 'c13', type: CommandType.SAY, params: { text: 'Pit Stop!' } }, { id: 'c14', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } }, { id: 'c15', type: CommandType.END_IF, params: {} }, { id: 'c16', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c17', type: CommandType.BOOST, params: { value: 20 } }, { id: 'c18', type: CommandType.END_IF, params: {} }, { id: 'c19', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_racing_drift_new', mode: AppMode.GAME, name: 'Drift King', description: 'Master the art of drifting!', icon: RotateCcw, color: 'bg-gradient-to-r from-purple-500 to-pink-600', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'race_road' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🚗' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'drift_score', value: 0 } }, { id: 'c4', type: CommandType.SET_VAR, params: { varName: 'combo', value: 0 } }, { id: 'c5', type: CommandType.FOREVER, params: {} }, { id: 'c6', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } }, { id: 'c7', type: CommandType.MOVE_X, params: { value: 5 } }, { id: 'c8', type: CommandType.END_IF, params: {} }, { id: 'c9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } }, { id: 'c10', type: CommandType.DRIFT, params: { value: 8 } }, { id: 'c11', type: CommandType.CHANGE_VAR, params: { varName: 'drift_score', value: 100 } }, { id: 'c12', type: CommandType.CHANGE_VAR, params: { varName: 'combo', value: 1 } }, { id: 'c13', type: CommandType.PLAY_SOUND, params: { text: 'dash' } }, { id: 'c14', type: CommandType.END_IF, params: {} }, { id: 'c15', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_racing_offroad', mode: AppMode.GAME, name: 'Off-Road Rally', description: 'Race through rough terrain!', icon: Zap, color: 'bg-gradient-to-r from-amber-600 to-green-600', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'race_grass' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🚙' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'distance', value: 0 } }, { id: 'c4', type: CommandType.FOREVER, params: {} }, { id: 'c5', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } }, { id: 'c6', type: CommandType.MOVE_X, params: { value: 5 } }, { id: 'c7', type: CommandType.CHANGE_VAR, params: { varName: 'distance', value: 5 } }, { id: 'c8', type: CommandType.END_IF, params: {} }, { id: 'c9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c10', type: CommandType.BOOST, params: { value: 10 } }, { id: 'c11', type: CommandType.END_IF, params: {} }, { id: 'c12', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_racing_moto', mode: AppMode.GAME, name: 'Moto Racing', description: 'High-speed motorcycle racing!', icon: Zap, color: 'bg-gradient-to-r from-blue-500 to-blue-700', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'race_road' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🏍️' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'speed', value: 0 } }, { id: 'c4', type: CommandType.SET_GRAVITY, params: { condition: 'true' } }, { id: 'c5', type: CommandType.FOREVER, params: {} }, { id: 'c6', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } }, { id: 'c7', type: CommandType.MOVE_X, params: { value: 7 } }, { id: 'c8', type: CommandType.CHANGE_VAR, params: { varName: 'speed', value: 1 } }, { id: 'c9', type: CommandType.END_IF, params: {} }, { id: 'c10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } }, { id: 'c11', type: CommandType.JUMP, params: { value: 10 } }, { id: 'c12', type: CommandType.END_IF, params: {} }, { id: 'c13', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c14', type: CommandType.BOOST, params: { value: 15 } }, { id: 'c15', type: CommandType.END_IF, params: {} }, { id: 'c16', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_racing_boat_new', mode: AppMode.GAME, name: 'Boat Race', description: 'Race boats across the water!', icon: Zap, color: 'bg-gradient-to-r from-blue-400 to-cyan-500', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'water' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '⛵' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'laps', value: 0 } }, { id: 'c4', type: CommandType.FOREVER, params: {} }, { id: 'c5', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } }, { id: 'c6', type: CommandType.MOVE_X, params: { value: 5 } }, { id: 'c7', type: CommandType.END_IF, params: {} }, { id: 'c8', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } }, { id: 'c9', type: CommandType.DRIFT, params: { value: 3 } }, { id: 'c10', type: CommandType.END_IF, params: {} }, { id: 'c11', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c12', type: CommandType.BOOST, params: { value: 10 } }, { id: 'c13', type: CommandType.END_IF, params: {} }, { id: 'c14', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_racing_monster_truck', mode: AppMode.GAME, name: 'Monster Truck', description: 'Crush cars with a monster truck!', icon: Zap, color: 'bg-gradient-to-r from-red-600 to-orange-700', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'race_grass' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🚛' } }, { id: 'c3', type: CommandType.SET_SIZE, params: { value: 150 } }, { id: 'c4', type: CommandType.SET_GRAVITY, params: { condition: 'true' } }, { id: 'c5', type: CommandType.FOREVER, params: {} }, { id: 'c6', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } }, { id: 'c7', type: CommandType.MOVE_X, params: { value: 4 } }, { id: 'c8', type: CommandType.END_IF, params: {} }, { id: 'c9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c10', type: CommandType.JUMP, params: { value: 15 } }, { id: 'c11', type: CommandType.PLAY_SOUND, params: { text: 'jump' } }, { id: 'c12', type: CommandType.END_IF, params: {} }, { id: 'c13', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_racing_snowmobile', mode: AppMode.GAME, name: 'Snow Race', description: 'Race across frozen terrain!', icon: Zap, color: 'bg-gradient-to-r from-blue-200 to-white', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'snow' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🛷' } }, { id: 'c3', type: CommandType.SET_WEATHER, params: { text: 'snow' } }, { id: 'c4', type: CommandType.SET_VAR, params: { varName: 'distance', value: 0 } }, { id: 'c5', type: CommandType.FOREVER, params: {} }, { id: 'c6', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } }, { id: 'c7', type: CommandType.MOVE_X, params: { value: 6 } }, { id: 'c8', type: CommandType.CHANGE_VAR, params: { varName: 'distance', value: 5 } }, { id: 'c9', type: CommandType.END_IF, params: {} }, { id: 'c10', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } }, { id: 'c11', type: CommandType.BOOST, params: { value: 12 } }, { id: 'c12', type: CommandType.END_IF, params: {} }, { id: 'c13', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_racing_hover', mode: AppMode.GAME, name: 'Hover Racing', description: 'Anti-gravity hover car racing!', icon: Zap, color: 'bg-gradient-to-r from-cyan-400 to-fuchsia-500', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'space' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🛸' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'speed', value: 0 } }, { id: 'c4', type: CommandType.FOREVER, params: {} }, { id: 'c5', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } }, { id: 'c6', type: CommandType.MOVE_X, params: { value: 8 } }, { id: 'c7', type: CommandType.CHANGE_VAR, params: { varName: 'speed', value: 1 } }, { id: 'c8', type: CommandType.END_IF, params: {} }, { id: 'c9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } }, { id: 'c10', type: CommandType.MOVE_Y, params: { value: -3 } }, { id: 'c11', type: CommandType.END_IF, params: {} }, { id: 'c12', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 40 } }, { id: 'c13', type: CommandType.MOVE_Y, params: { value: 3 } }, { id: 'c14', type: CommandType.END_IF, params: {} }, { id: 'c15', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c16', type: CommandType.BOOST, params: { value: 20 } }, { id: 'c17', type: CommandType.END_IF, params: {} }, { id: 'c18', type: CommandType.END_FOREVER, params: {} }
        ]},
];
