import { AppMode, CommandType, CircuitComponent, CommandBlock } from '../../types';
import { LucideIcon, User, Box, Boxes, Flame, Droplets } from 'lucide-react';

export const survivalTemplates: {
    id: string,
    mode: AppMode,
    name: string,
    description: string,
    icon: LucideIcon,
    color: string,
    commands: CommandBlock[],
    circuitComponents?: CircuitComponent[]
}[] = [
        {
            id: 'tpl_game_pet',
            mode: AppMode.GAME,
            name: 'Virtual Pet',
            description: 'Take care of your own pet!',
            icon: User,
            color: 'bg-pink-600',
            commands: [
                { id: '1', type: CommandType.SET_TITLE, params: { text: 'My Pet' } },
                { id: '2', type: CommandType.SET_EMOJI, params: { text: '🐱' } },
                { id: '3', type: CommandType.SET_VAR, params: { varName: 'hunger', value: 50 } },
                { id: '4', type: CommandType.SET_VAR, params: { varName: 'happiness', value: 50 } },
                { id: '5', type: CommandType.FOREVER, params: {} },
                { id: '6', type: CommandType.CHANGE_VAR, params: { varName: 'hunger', value: 1 } },
                { id: '7', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } },
                { id: '8', type: CommandType.CHANGE_VAR, params: { varName: 'hunger', value: -10 } },
                { id: '9', type: CommandType.PLAY_SOUND, params: { text: 'coin' } },
                { id: '10', type: CommandType.END_IF, params: {} },
                { id: '11', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 33 } },
                { id: '12', type: CommandType.CHANGE_VAR, params: { varName: 'happiness', value: 10 } },
                { id: '13', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: '14', type: CommandType.END_IF, params: {} },
                { id: '15', type: CommandType.SAY, params: { text: 'Feed me!' } },
                { id: 'win_pet', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'happiness', value: 100 } },
                { id: 'win_pet2', type: CommandType.WIN_GAME, params: {} },
                { id: 'win_pet3', type: CommandType.PLAY_SOUND, params: { text: 'powerup' } },
                { id: 'win_pet4', type: CommandType.END_IF, params: {} },
                { id: 'lose_pet', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'hunger', value: 100 } },
                { id: 'lose_pet2', type: CommandType.GAME_OVER, params: {} },
                { id: 'lose_pet3', type: CommandType.SAY, params: { text: 'I am starving!' } },
                { id: 'lose_pet4', type: CommandType.END_IF, params: {} },
                { id: '16', type: CommandType.END_FOREVER, params: {} }
            ]
        },
        { id: 'tpl_survival_crafting', mode: AppMode.GAME, name: 'Crafting Survival', description: 'Gather resources, craft tools, build shelter!', icon: Boxes, color: 'bg-gradient-to-r from-amber-600 to-orange-700', commands: [
            { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'grass' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🧑‍🔧' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'wood', value: 0 } }, { id: 'c4', type: CommandType.SET_VAR, params: { varName: 'stone', value: 0 } }, { id: 'c5', type: CommandType.SET_VAR, params: { varName: 'food', value: 50 } }, { id: 'c6', type: CommandType.SET_VAR, params: { varName: 'hunger', value: 100 } }, { id: 'c7', type: CommandType.FOREVER, params: {} }, { id: 'c8', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 37 } }, { id: 'c9', type: CommandType.MOVE_X, params: { value: -4 } }, { id: 'c10', type: CommandType.END_IF, params: {} }, { id: 'c11', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 39 } }, { id: 'c12', type: CommandType.MOVE_X, params: { value: 4 } }, { id: 'c13', type: CommandType.END_IF, params: {} }, { id: 'c14', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c15', type: CommandType.GATHER, params: { text: 'wood', value: 1 } }, { id: 'c16', type: CommandType.PLAY_SOUND, params: { text: 'hit' } }, { id: 'c17', type: CommandType.END_IF, params: {} }, { id: 'c18', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 33 } }, { id: 'c19', type: CommandType.CRAFT, params: { text: 'axe', value: 2 } }, { id: 'c20', type: CommandType.END_IF, params: {} }, { id: 'c21', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } }, { id: 'c22', type: CommandType.EAT, params: { value: 10 } }, { id: 'c23', type: CommandType.END_IF, params: {} }, { id: 'c24', type: CommandType.CHANGE_VAR, params: { varName: 'hunger', value: -1 } }, { id: 'lose_crafting', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'hunger', value: 0 } }, { id: 'lose_crafting2', type: CommandType.GAME_OVER, params: {} }, { id: 'lose_crafting3', type: CommandType.SAY, params: { text: 'You starved!' } }, { id: 'lose_crafting4', type: CommandType.END_IF, params: {} }, { id: 'c25', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_survival_zombie', mode: AppMode.GAME, name: 'Zombie Survival', description: 'Build, fortify, and survive the zombie horde!', icon: Boxes, color: 'bg-gradient-to-r from-green-700 to-green-900', commands: [
            { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'grass' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🛡️' } }, { id: 'c3', type: CommandType.SET_WEATHER, params: { text: 'rain' } }, { id: 'c4', type: CommandType.SET_VAR, params: { varName: 'health', value: 100 } }, { id: 'c5', type: CommandType.SET_VAR, params: { varName: 'wood', value: 10 } }, { id: 'c6', type: CommandType.SPAWN_ENEMY, params: { text: '🧟' } }, { id: 'c7', type: CommandType.FOREVER, params: {} }, { id: 'c8', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c9', type: CommandType.SHOOT, params: { text: '🔫' } }, { id: 'c10', type: CommandType.END_IF, params: {} }, { id: 'c11', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 33 } }, { id: 'c12', type: CommandType.BUILD, params: { text: 'wall', value: 3 } }, { id: 'c13', type: CommandType.END_IF, params: {} }, { id: 'c14', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } }, { id: 'c15', type: CommandType.PLACE_TORCH, params: {} }, { id: 'c16', type: CommandType.END_IF, params: {} }, { id: 'lose_zombie', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'health', value: 0 } }, { id: 'lose_zombie2', type: CommandType.GAME_OVER, params: {} }, { id: 'lose_zombie3', type: CommandType.END_IF, params: {} }, { id: 'c17', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_survival_island', mode: AppMode.GAME, name: 'Island Survival', description: 'Stranded on an island — build and survive!', icon: Boxes, color: 'bg-gradient-to-r from-blue-400 to-cyan-500', commands: [
            { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'grass' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🏝️' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'water_level', value: 50 } }, { id: 'c4', type: CommandType.SET_VAR, params: { varName: 'food', value: 30 } }, { id: 'c5', type: CommandType.FOREVER, params: {} }, { id: 'c6', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c7', type: CommandType.GATHER, params: { text: 'coconut', value: 1 } }, { id: 'c8', type: CommandType.END_IF, params: {} }, { id: 'c9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 33 } }, { id: 'c10', type: CommandType.DRINK, params: { value: 10 } }, { id: 'c11', type: CommandType.END_IF, params: {} }, { id: 'c12', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } }, { id: 'c13', type: CommandType.BUILD, params: { text: 'raft', value: 5 } }, { id: 'c14', type: CommandType.END_IF, params: {} }, { id: 'lose_island', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'water_level', value: 0 } }, { id: 'lose_island2', type: CommandType.GAME_OVER, params: {} }, { id: 'lose_island3', type: CommandType.SAY, params: { text: 'No water!' } }, { id: 'lose_island4', type: CommandType.END_IF, params: {} }, { id: 'c15', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_survival_space', mode: AppMode.GAME, name: 'Space Survival', description: 'Survive in the void of space!', icon: Boxes, color: 'bg-gradient-to-r from-indigo-600 to-purple-700', commands: [
            { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'space' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🧑‍🚀' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'oxygen', value: 100 } }, { id: 'c4', type: CommandType.SET_VAR, params: { varName: 'fuel', value: 50 } }, { id: 'c5', type: CommandType.FOREVER, params: {} }, { id: 'c6', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c7', type: CommandType.SHOOT, params: { text: '⚡' } }, { id: 'c8', type: CommandType.CHANGE_VAR, params: { varName: 'fuel', value: -2 } }, { id: 'c9', type: CommandType.END_IF, params: {} }, { id: 'c10', type: CommandType.CHANGE_VAR, params: { varName: 'oxygen', value: -1 } }, { id: 'lose_space', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'oxygen', value: 0 } }, { id: 'lose_space2', type: CommandType.GAME_OVER, params: {} }, { id: 'lose_space3', type: CommandType.SAY, params: { text: 'No oxygen!' } }, { id: 'lose_space4', type: CommandType.END_IF, params: {} }, { id: 'warn_space', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'fuel', value: 0 } }, { id: 'warn_space2', type: CommandType.SAY, params: { text: 'Out of fuel!' } }, { id: 'warn_space3', type: CommandType.END_IF, params: {} }, { id: 'c11', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_survival_arctic', mode: AppMode.GAME, name: 'Arctic Survival', description: 'Survive the freezing cold!', icon: Boxes, color: 'bg-gradient-to-r from-blue-200 to-blue-400', commands: [
            { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'snow' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🥶' } }, { id: 'c3', type: CommandType.SET_WEATHER, params: { text: 'snow' } }, { id: 'c4', type: CommandType.SET_VAR, params: { varName: 'body_temp', value: 37 } }, { id: 'c5', type: CommandType.FOREVER, params: {} }, { id: 'c6', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c7', type: CommandType.GATHER, params: { text: 'wood', value: 1 } }, { id: 'c8', type: CommandType.END_IF, params: {} }, { id: 'c9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 33 } }, { id: 'c10', type: CommandType.PLACE_TORCH, params: {} }, { id: 'c11', type: CommandType.END_IF, params: {} }, { id: 'c12', type: CommandType.CHANGE_VAR, params: { varName: 'body_temp', value: -1 } }, { id: 'lose_arctic', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'body_temp', value: 20 } }, { id: 'lose_arctic2', type: CommandType.GAME_OVER, params: {} }, { id: 'lose_arctic3', type: CommandType.SAY, params: { text: 'Hypothermia!' } }, { id: 'lose_arctic4', type: CommandType.END_IF, params: {} }, { id: 'c13', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_survival_desert', mode: AppMode.GAME, name: 'Desert Survival', description: 'Find water before you dehydrate!', icon: Boxes, color: 'bg-gradient-to-r from-yellow-500 to-orange-600', commands: [
            { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'dirt' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🏜️' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'hydration', value: 100 } }, { id: 'c4', type: CommandType.SET_VAR, params: { varName: 'food', value: 50 } }, { id: 'c5', type: CommandType.FOREVER, params: {} }, { id: 'c6', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c7', type: CommandType.GATHER, params: { text: 'cactus', value: 1 } }, { id: 'c8', type: CommandType.END_IF, params: {} }, { id: 'c9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 33 } }, { id: 'c10', type: CommandType.DRINK, params: { value: 20 } }, { id: 'c11', type: CommandType.END_IF, params: {} }, { id: 'c12', type: CommandType.CHANGE_VAR, params: { varName: 'hydration', value: -2 } }, { id: 'lose_desert', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'hydration', value: 0 } }, { id: 'lose_desert2', type: CommandType.GAME_OVER, params: {} }, { id: 'lose_desert3', type: CommandType.SAY, params: { text: 'Dehydrated!' } }, { id: 'lose_desert4', type: CommandType.END_IF, params: {} }, { id: 'c13', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_survival_ocean', mode: AppMode.GAME, name: 'Ocean Survival', description: 'Survive on a raft in the open ocean!', icon: Boxes, color: 'bg-gradient-to-r from-blue-500 to-blue-700', commands: [
            { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'water' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🚣' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'food', value: 30 } }, { id: 'c4', type: CommandType.SET_VAR, params: { varName: 'fresh_water', value: 20 } }, { id: 'c5', type: CommandType.FOREVER, params: {} }, { id: 'c6', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c7', type: CommandType.GATHER, params: { text: 'fish', value: 1 } }, { id: 'c8', type: CommandType.END_IF, params: {} }, { id: 'c9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 33 } }, { id: 'c10', type: CommandType.DRINK, params: { value: 10 } }, { id: 'c11', type: CommandType.END_IF, params: {} }, { id: 'c12', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 34 } }, { id: 'c13', type: CommandType.BUILD, params: { text: 'sail', value: 3 } }, { id: 'c14', type: CommandType.END_IF, params: {} }, { id: 'lose_ocean', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'food', value: 0 } }, { id: 'lose_ocean2', type: CommandType.GAME_OVER, params: {} }, { id: 'lose_ocean3', type: CommandType.END_IF, params: {} },             { id: 'c15', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_survival_underwater', mode: AppMode.GAME, name: 'Underwater Survival', description: 'Survive the deep ocean!', icon: Droplets, color: 'bg-gradient-to-r from-blue-600 to-cyan-700', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'water' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🤿' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'oxygen', value: 100 } }, { id: 'c4', type: CommandType.FOREVER, params: {} }, { id: 'c5', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c6', type: CommandType.GATHER, params: { text: 'pearl', value: 1 } }, { id: 'c7', type: CommandType.END_IF, params: {} }, { id: 'c8', type: CommandType.CHANGE_VAR, params: { varName: 'oxygen', value: -2 } }, { id: 'lose_underwater', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'oxygen', value: 0 } }, { id: 'lose_underwater2', type: CommandType.GAME_OVER, params: {} }, { id: 'lose_underwater3', type: CommandType.SAY, params: { text: 'Out of air!' } }, { id: 'lose_underwater4', type: CommandType.END_IF, params: {} }, { id: 'c9', type: CommandType.END_FOREVER, params: {} }
        ]},
        { id: 'tpl_survival_volcano', mode: AppMode.GAME, name: 'Volcano Escape', description: 'Escape the erupting volcano!', icon: Flame, color: 'bg-gradient-to-r from-red-600 to-orange-700', commands: [
          { id: 'c1', type: CommandType.SET_SCENE, params: { text: 'lava_pool' } }, { id: 'c2', type: CommandType.SET_EMOJI, params: { text: '🏃' } }, { id: 'c3', type: CommandType.SET_VAR, params: { varName: 'distance', value: 0 } }, { id: 'c4', type: CommandType.FOREVER, params: {} }, { id: 'c5', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 38 } }, { id: 'c6', type: CommandType.MOVE_X, params: { value: 8 } }, { id: 'c7', type: CommandType.CHANGE_VAR, params: { varName: 'distance', value: 5 } }, { id: 'c8', type: CommandType.END_IF, params: {} }, { id: 'c9', type: CommandType.IF, params: { condition: 'IS_PRESSED', pin: 32 } }, { id: 'c10', type: CommandType.JUMP, params: { value: 15 } }, { id: 'c11', type: CommandType.END_IF, params: {} }, { id: 'c12', type: CommandType.SCREEN_SHAKE, params: { value: 0.3 } }, { id: 'win_volcano', type: CommandType.IF, params: { condition: 'EQUALS', varName: 'distance', value: 500 } }, { id: 'win_volcano2', type: CommandType.WIN_GAME, params: {} }, { id: 'win_volcano3', type: CommandType.SAY, params: { text: 'You escaped!' } }, { id: 'win_volcano4', type: CommandType.PLAY_SOUND, params: { text: 'victory' } }, { id: 'win_volcano5', type: CommandType.END_IF, params: {} }, { id: 'c13', type: CommandType.END_FOREVER, params: {} }
        ]},
];
