import { CommandBlock, CommandType, AppMode } from '../types';

export const exportToPython = (commands: CommandBlock[], mode: AppMode): string => {
  let code = "# Generated by KidCode Studio\n";
  code += "import kidcode\n\n";

  if (mode === AppMode.GAME) {
    code += "game = kidcode.Game()\n";
    code += "player = game.player\n\n";
  } else if (mode === AppMode.HARDWARE) {
    code += "board = kidcode.Hardware()\n\n";
  } else if (mode === AppMode.APP) {
    code += "app = kidcode.App()\n\n";
  }

  let indent = "";

  commands.forEach(cmd => {
    switch (cmd.type) {
      // === GAME COMMANDS ===
      case CommandType.MOVE_X:
        code += `${indent}player.move_x(${cmd.params.value || 10})\n`;
        break;
      case CommandType.MOVE_Y:
        code += `${indent}player.move_y(${cmd.params.value || 10})\n`;
        break;
      case CommandType.JUMP:
        code += `${indent}player.jump(${cmd.params.value || 10})\n`;
        break;
      case CommandType.SET_GRAVITY:
        code += `${indent}player.gravity = ${cmd.params.condition === 'true'}\n`;
        break;
      case CommandType.SHOOT:
        code += `${indent}player.shoot("${cmd.params.text || 'bullet'}")\n`;
        break;
      case CommandType.SET_SCENE:
        code += `${indent}game.set_scene("${cmd.params.text || 'default'}")\n`;
        break;
      case CommandType.SET_SCORE:
        code += `${indent}game.score = ${cmd.params.value || 0}\n`;
        break;
      case CommandType.CHANGE_SCORE:
        code += `${indent}game.score += ${cmd.params.value || 1}\n`;
        break;
      case CommandType.GAME_OVER:
        code += `${indent}game.game_over()\n`;
        break;
      case CommandType.WIN_GAME:
        code += `${indent}game.win()\n`;
        break;

      // === APP COMMANDS ===
      case CommandType.SET_TITLE:
        code += `${indent}app.set_title("${cmd.params.text || 'My App'}")\n`;
        break;
      case CommandType.ADD_BUTTON:
        code += `${indent}app.add_button("${cmd.params.text || 'Button'}", lambda: print("${cmd.params.message || 'clicked'}"))\n`;
        break;
      case CommandType.ADD_INPUT:
        code += `${indent}app.add_input("${cmd.params.text || 'Enter text'}", "${cmd.params.varName || 'var1'}")\n`;
        break;
      case CommandType.ADD_TEXT_BLOCK:
        code += `${indent}app.add_text("${cmd.params.text || 'Hello'}")\n`;
        break;
      case CommandType.SHOW_ALERT:
        code += `${indent}app.show_alert("${cmd.params.text || 'Alert!'}")\n`;
        break;
      case CommandType.NAVIGATE:
        code += `${indent}app.navigate_to("${cmd.params.text || 'main'}")\n`;
        break;

      // === HARDWARE COMMANDS ===
      case CommandType.LED_ON:
        code += `${indent}board.pin(${cmd.params.pin || 13}).on()\n`;
        break;
      case CommandType.LED_OFF:
        code += `${indent}board.pin(${cmd.params.pin || 13}).off()\n`;
        break;
      case CommandType.LED_TOGGLE:
        code += `${indent}board.pin(${cmd.params.pin || 13}).toggle()\n`;
        break;
      case CommandType.SET_SERVO:
        code += `${indent}board.servo(${cmd.params.pin || 9}).write(${cmd.params.angle || 90})\n`;
        break;
      case CommandType.SET_FAN:
        code += `${indent}board.fan(${cmd.params.pin || 9}).set_speed(${cmd.params.speed || 50})\n`;
        break;
      case CommandType.READ_DIGITAL:
        code += `${indent}${cmd.params.varName || 'value'} = board.pin(${cmd.params.pin || 4}).read()\n`;
        break;
      case CommandType.READ_ANALOG:
        code += `${indent}${cmd.params.varName || 'value'} = board.pin(${cmd.params.pin || 97}).read_analog()\n`;
        break;

      // === CONTROL FLOW ===
      case CommandType.WAIT:
        code += `${indent}kidcode.wait(${cmd.params.value || 1})\n`;
        break;
      case CommandType.FOREVER:
        code += `${indent}while True:\n`;
        indent += "    ";
        break;
      case CommandType.END_FOREVER:
        indent = indent.slice(0, -4);
        break;
      case CommandType.REPEAT:
        code += `${indent}for i in range(${cmd.params.value || 1}):\n`;
        indent += "    ";
        break;
      case CommandType.END_REPEAT:
        indent = indent.slice(0, -4);
        break;
      case CommandType.IF:
        code += `${indent}if ${cmd.params.condition || 'True'}:\n`;
        indent += "    ";
        break;
      case CommandType.ELSE:
        indent = indent.slice(0, -4);
        code += `${indent}else:\n`;
        indent += "    ";
        break;
      case CommandType.END_IF:
        indent = indent.slice(0, -4);
        break;

      // === VARIABLES & MATH ===
      case CommandType.SET_VAR:
        const strVal = typeof cmd.params.value === 'string' ? `'${cmd.params.value}'` : cmd.params.value;
        code += `${indent}${cmd.params.varName || 'var'} = ${strVal}\n`;
        break;
      case CommandType.CHANGE_VAR:
        code += `${indent}${cmd.params.varName || 'var'} += ${cmd.params.value || 1}\n`;
        break;
      case CommandType.CALC_ADD:
        code += `${indent}${cmd.params.varName || 'result'} = ${cmd.params.value || 0} + ${cmd.params.value2 || 0}\n`;
        break;
      case CommandType.CALC_SUB:
        code += `${indent}${cmd.params.varName || 'result'} = ${cmd.params.value || 0} - ${cmd.params.value2 || 0}\n`;
        break;
      case CommandType.CALC_MUL:
        code += `${indent}${cmd.params.varName || 'result'} = ${cmd.params.value || 0} * ${cmd.params.value2 || 0}\n`;
        break;
      case CommandType.CALC_DIV:
        code += `${indent}${cmd.params.varName || 'result'} = ${cmd.params.value || 0} / ${cmd.params.value2 || 0}\n`;
        break;
      case CommandType.CALC_RANDOM:
        code += `${indent}${cmd.params.varName || 'rand'} = random.randint(${cmd.params.value || 1}, ${cmd.params.value2 || 10})\n`;
        break;

      // === SOUND ===
      case CommandType.PLAY_TONE:
        code += `${indent}kidcode.play_tone(${cmd.params.duration || 0.5})\n`;
        break;
      case CommandType.PLAY_SOUND:
        code += `${indent}kidcode.play_sound("${cmd.params.text || 'beep'}")\n`;
        break;

      // === DEFAULT ===
      default:
        code += `${indent}# Block: ${cmd.type} (not yet supported in Python export)\n`;
    }
  });

  return code;
};

export const exportToJavaScript = (commands: CommandBlock[], mode: AppMode): string => {
  let code = "// Generated by KidCode Studio\n";
  code += "// Run this in a browser with the KidCode runtime\n\n";

  if (mode === AppMode.GAME) {
    code += "const game = new KidCode.Game();\n";
    code += "const player = game.player;\n\n";
  } else if (mode === AppMode.APP) {
    code += "const app = new KidCode.App();\n\n";
  } else if (mode === AppMode.HARDWARE) {
    code += "const board = new KidCode.Hardware();\n\n";
  }

  let indent = "";

  commands.forEach(cmd => {
    switch (cmd.type) {
      // === GAME COMMANDS ===
      case CommandType.MOVE_X:
        code += `${indent}player.moveX(${cmd.params.value || 10});\n`;
        break;
      case CommandType.MOVE_Y:
        code += `${indent}player.moveY(${cmd.params.value || 10});\n`;
        break;
      case CommandType.JUMP:
        code += `${indent}player.jump(${cmd.params.value || 10});\n`;
        break;
      case CommandType.SET_GRAVITY:
        code += `${indent}player.gravity = ${cmd.params.condition === 'true'};\n`;
        break;
      case CommandType.SHOOT:
        code += `${indent}player.shoot("${cmd.params.text || 'bullet'}");\n`;
        break;
      case CommandType.SET_SCENE:
        code += `${indent}game.setScene("${cmd.params.text || 'default'}");\n`;
        break;
      case CommandType.CHANGE_SCORE:
        code += `${indent}game.score += ${cmd.params.value || 1};\n`;
        break;
      case CommandType.GAME_OVER:
        code += `${indent}game.gameOver();\n`;
        break;
      case CommandType.WIN_GAME:
        code += `${indent}game.win();\n`;
        break;

      // === APP COMMANDS ===
      case CommandType.SET_TITLE:
        code += `${indent}app.setTitle("${cmd.params.text || 'My App'}");\n`;
        break;
      case CommandType.ADD_BUTTON:
        code += `${indent}app.addButton("${cmd.params.text || 'Button'}", () => console.log("${cmd.params.message || 'clicked'}"));\n`;
        break;
      case CommandType.ADD_INPUT:
        code += `${indent}app.addInput("${cmd.params.text || 'Enter text'}", "${cmd.params.varName || 'var1'}");\n`;
        break;
      case CommandType.ADD_TEXT_BLOCK:
        code += `${indent}app.addText("${cmd.params.text || 'Hello'}");\n`;
        break;
      case CommandType.SHOW_ALERT:
        code += `${indent}app.showAlert("${cmd.params.text || 'Alert!'}");\n`;
        break;
      case CommandType.NAVIGATE:
        code += `${indent}app.navigateTo("${cmd.params.text || 'main'}");\n`;
        break;

      // === HARDWARE COMMANDS ===
      case CommandType.LED_ON:
        code += `${indent}board.pin(${cmd.params.pin || 13}).on();\n`;
        break;
      case CommandType.LED_OFF:
        code += `${indent}board.pin(${cmd.params.pin || 13}).off();\n`;
        break;
      case CommandType.LED_TOGGLE:
        code += `${indent}board.pin(${cmd.params.pin || 13}).toggle();\n`;
        break;
      case CommandType.SET_SERVO:
        code += `${indent}board.servo(${cmd.params.pin || 9}).write(${cmd.params.angle || 90});\n`;
        break;
      case CommandType.SET_FAN:
        code += `${indent}board.fan(${cmd.params.pin || 9}).setSpeed(${cmd.params.speed || 50});\n`;
        break;
      case CommandType.READ_DIGITAL:
        code += `${indent}let ${cmd.params.varName || 'value'} = board.pin(${cmd.params.pin || 4}).read();\n`;
        break;
      case CommandType.READ_ANALOG:
        code += `${indent}let ${cmd.params.varName || 'value'} = board.pin(${cmd.params.pin || 97}).readAnalog();\n`;
        break;

      // === CONTROL FLOW ===
      case CommandType.WAIT:
        code += `${indent}await kidcode.wait(${cmd.params.value || 1});\n`;
        break;
      case CommandType.FOREVER:
        code += `${indent}while (true) {\n`;
        indent += "  ";
        break;
      case CommandType.END_FOREVER:
        indent = indent.slice(0, -2);
        code += `${indent}}\n`;
        break;
      case CommandType.REPEAT:
        code += `${indent}for (let i = 0; i < ${cmd.params.value || 1}; i++) {\n`;
        indent += "  ";
        break;
      case CommandType.END_REPEAT:
        indent = indent.slice(0, -2);
        code += `${indent}}\n`;
        break;
      case CommandType.IF:
        code += `${indent}if (${cmd.params.condition || 'true'}) {\n`;
        indent += "  ";
        break;
      case CommandType.ELSE:
        indent = indent.slice(0, -2);
        code += `${indent}} else {\n`;
        indent += "  ";
        break;
      case CommandType.END_IF:
        indent = indent.slice(0, -2);
        code += `${indent}}\n`;
        break;

      // === VARIABLES & MATH ===
      case CommandType.SET_VAR:
        const jsStrVal = typeof cmd.params.value === 'string' ? `'${cmd.params.value}'` : cmd.params.value;
        code += `${indent}let ${cmd.params.varName || 'var'} = ${jsStrVal};\n`;
        break;
      case CommandType.CHANGE_VAR:
        code += `${indent}${cmd.params.varName || 'var'} += ${cmd.params.value || 1};\n`;
        break;
      case CommandType.CALC_ADD:
        code += `${indent}let ${cmd.params.varName || 'result'} = ${cmd.params.value || 0} + ${cmd.params.value2 || 0};\n`;
        break;
      case CommandType.CALC_SUB:
        code += `${indent}let ${cmd.params.varName || 'result'} = ${cmd.params.value || 0} - ${cmd.params.value2 || 0};\n`;
        break;
      case CommandType.CALC_MUL:
        code += `${indent}let ${cmd.params.varName || 'result'} = ${cmd.params.value || 0} * ${cmd.params.value2 || 0};\n`;
        break;
      case CommandType.CALC_DIV:
        code += `${indent}let ${cmd.params.varName || 'result'} = ${cmd.params.value || 0} / ${cmd.params.value2 || 0};\n`;
        break;
      case CommandType.CALC_RANDOM:
        code += `${indent}let ${cmd.params.varName || 'rand'} = Math.floor(Math.random() * (${cmd.params.value2 || 10} - ${cmd.params.value || 1} + 1)) + ${cmd.params.value || 1};\n`;
        break;

      // === SOUND ===
      case CommandType.PLAY_TONE:
        code += `${indent}kidcode.playTone(${cmd.params.duration || 0.5});\n`;
        break;
      case CommandType.PLAY_SOUND:
        code += `${indent}kidcode.playSound("${cmd.params.text || 'beep'}");\n`;
        break;

      // === DEFAULT ===
      default:
        code += `${indent}// Block: ${cmd.type} (not yet supported in JS export)\n`;
    }
  });

  return code;
};

// NEW: Arduino/C++ Export
export const exportToArduino = (commands: CommandBlock[]): string => {
  let code = "/* Generated by KidCode Studio */\n";
  code += "// Arduino Sketch - Upload to your board using Arduino IDE\n\n";

  // Collect used pins
  const usedPins = new Set<number>();
  commands.forEach(cmd => {
    if (cmd.params.pin !== undefined) usedPins.add(cmd.params.pin);
  });

  // Setup section
  code += "void setup() {\n";
  code += "  Serial.begin(9600);\n";
  usedPins.forEach(pin => {
    code += `  pinMode(${pin}, OUTPUT);\n`;
  });
  code += "}\n\n";

  // Loop section
  code += "void loop() {\n";

  commands.forEach(cmd => {
    switch (cmd.type) {
      case CommandType.LED_ON:
        code += `  digitalWrite(${cmd.params.pin || 13}, HIGH);\n`;
        break;
      case CommandType.LED_OFF:
        code += `  digitalWrite(${cmd.params.pin || 13}, LOW);\n`;
        break;
      case CommandType.LED_TOGGLE:
        code += `  digitalWrite(${cmd.params.pin || 13}, !digitalRead(${cmd.params.pin || 13}));\n`;
        break;
      case CommandType.WAIT:
        code += `  delay(${(cmd.params.value || 1) * 1000});\n`;
        break;
      case CommandType.SET_SERVO:
        code += `  // Servo on pin ${cmd.params.pin || 9}: angle = ${cmd.params.angle || 90}\n`;
        break;
      case CommandType.READ_DIGITAL:
        code += `  int ${cmd.params.varName || 'value'} = digitalRead(${cmd.params.pin || 4});\n`;
        break;
      case CommandType.READ_ANALOG:
        code += `  int ${cmd.params.varName || 'value'} = analogRead(${cmd.params.pin || 97});\n`;
        break;
      case CommandType.PLAY_TONE:
        code += `  tone(8, 440, ${(cmd.params.duration || 0.5) * 1000});\n`;
        break;
      default:
        code += `  // ${cmd.type} - not supported in Arduino\n`;
    }
  });

  code += "\n  delay(100); // Small delay to prevent runaway\n";
  code += "}\n";

  return code;
};

// NEW: HTML5 Export (Standalone Web Game)
export const exportToHTML5 = (commands: CommandBlock[], mode: AppMode): string => {
  const jsCode = exportToJavaScript(commands, mode);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>KidCode Studio Export</title>
  <style>
    body { margin: 0; display: flex; justify-content: center; align-items: center; min-height: 100vh; background: #1a1a2e; }
    #gameCanvas { border: 4px solid #fff; border-radius: 8px; }
  </style>
</head>
<body>
  <canvas id="gameCanvas" width="400" height="400"></canvas>
  <script>
    // KidCode Runtime (Simplified)
    const KidCode = {
      Game: class {
        constructor() {
          this.canvas = document.getElementById('gameCanvas');
          this.ctx = this.canvas.getContext('2d');
          this.player = { x: 200, y: 200, moveX: (v) => this.player.x += v, moveY: (v) => this.player.y += v, jump: () => this.player.y -= 10 };
          this.score = 0;
          this.scene = 'default';
          this.setScene = (s) => { this.scene = s; this.ctx.fillStyle = s === 'space' ? '#000' : s === 'forest' ? '#228B22' : '#fff'; this.ctx.fillRect(0, 0, 400, 400); };
          this.gameOver = () => alert('Game Over!');
          this.win = () => alert('You Win!');
        }
      },
      App: class {
        constructor() {
          this.title = 'App';
          this.setTitle = (t) => { document.title = t; this.title = t; };
          this.addButton = (text, callback) => { const btn = document.createElement('button'); btn.textContent = text; btn.onclick = callback; document.body.appendChild(btn); };
          this.addInput = (text, varName) => { const inp = document.createElement('input'); inp.placeholder = text; inp.id = varName; document.body.appendChild(inp); };
          this.addText = (t) => { const p = document.createElement('p'); p.textContent = t; document.body.appendChild(p); };
          this.showAlert = (msg) => alert(msg);
          this.navigateTo = (screen) => console.log('Navigate to:', screen);
        }
      },
      Hardware: class {
        pin(n) { return { on: () => console.log('Pin', n, 'ON'), off: () => console.log('Pin', n, 'OFF'), toggle: () => console.log('Pin', n, 'TOGGLE'), read: () => false, readAnalog: () => 0 }; }
        servo(n) { return { write: (a) => console.log('Servo', n, '->', a); }; }
        fan(n) { return { setSpeed: (s) => console.log('Fan', n, 'speed:', s); }; }
      },
      wait: (s) => new Promise(r => setTimeout(r, s * 1000)),
      playTone: (d) => console.log('Tone:', d),
      playSound: (s) => console.log('Sound:', s)
    };

    // Your Code
    (async () => {
${jsCode.split('\n').map(l => '      ' + l).join('\n')}
    })();
  </script>
</body>
</html>`;
};
