/**
 * Godot Exporter — Generates GDScript from IR nodes.
 * 
 * This exporter proves the IR can target multiple backends.
 * The same IR nodes that produce TypeScript also produce GDScript.
 * 
 * Architecture:
 *   IRNode[] → generateGDScript() → GDScript string
 * 
 * The exporter handles:
 * - Basic movement and physics commands
 * - Game state commands
 * - Control flow (IF/ELSE, REPEAT, FOREVER)
 * - Variable operations
 * - Sound effects
 */

import { IRNode } from '../types';
import { CommandBlock, CommandType } from '../../../types';
import { commandBlockToIR } from '../types';

export interface GodotExportResult {
  script: string;
  scenes: string[];
  errors: string[];
}

/**
 * Generate a complete Godot project from command blocks.
 * Uses the IR pipeline: blocks → IR → GDScript.
 */
export function exportToGodot(
  commands: CommandBlock[],
  projectName: string = 'KidCodeGame'
): GodotExportResult {
  const errors: string[] = [];
  const scenes: string[] = [];

  // Convert blocks to IR
  const irNodes: IRNode[] = [];
  for (const cmd of commands) {
    const node = commandBlockToIR(cmd);
    if (node) {
      irNodes.push(node);
    } else {
      // Fallback: generate GDScript directly for unhandled commands
      const fallback = generateFallbackGDScript(cmd);
      if (fallback) irNodes.push(fallback);
    }
  }

  // Generate GDScript
  const script = generateGDScriptFromIR(irNodes, projectName);

  return { script, scenes, errors };
}

/**
 * Generate GDScript from IR nodes.
 */
export function generateGDScriptFromIR(
  nodes: IRNode[],
  projectName: string = 'KidCodeGame'
): string {
  const lines: string[] = [];

  // Header
  lines.push(`extends CharacterBody2D`);
  lines.push(`# Generated by KidCode Studio — Godot Exporter`);
  lines.push(`# Project: ${projectName}`);
  lines.push(``);
  lines.push(`var speed = 200.0`);
  lines.push(`var gravity = 980.0`);
  lines.push(`var jump_force = 400.0`);
  lines.push(`var velocity = Vector2.ZERO`);
  lines.push(``);

  // Process IR nodes
  for (const node of nodes) {
    const gdscript = generateGDScriptFromNode(node);
    if (gdscript) {
      lines.push(gdscript);
    }
  }

  // Physics process
  lines.push(``);
  lines.push(`func _physics_process(delta):`);
  lines.push(`    if is_on_floor():`);
  lines.push(`        velocity.y = 0`);
  lines.push(`    velocity.y += gravity * delta`);
  lines.push(`    move_and_slide()`);
  lines.push(``);

  // Input handling
  lines.push(`func _unhandled_input(event):`);
  lines.push(`    if event.is_action_pressed("ui_up"):`);
  lines.push(`        if is_on_floor():`);
  lines.push(`            velocity.y = -jump_force`);
  lines.push(`    if event.is_action_pressed("ui_left"):`);
  lines.push(`        velocity.x = -speed`);
  lines.push(`    elif event.is_action_pressed("ui_right"):`);
  lines.push(`        velocity.x = speed`);
  lines.push(`    else:`);
  lines.push(`        velocity.x = 0`);

  return lines.join('\n');
}

/**
 * Generate GDScript for a single IR node.
 */
function generateGDScriptFromNode(node: IRNode): string | null {
  switch (node.kind) {
    case 'move_x':
      return `    position.x += ${node.dx}`;
    case 'move_y':
      return `    position.y -= ${node.dy}`;
    case 'set_velocity_x':
      return `    velocity.x = ${node.vx}`;
    case 'set_velocity_y':
      return `    velocity.y = ${node.vy}`;
    case 'set_gravity':
      return node.enabled ? `    gravity = 980.0` : `    gravity = 0.0`;
    case 'set_friction':
      return `    # friction = ${node.value}`;
    case 'set_bounciness':
      return `    # bounciness = ${node.value}`;
    case 'jump':
      return `    if is_on_floor():\n        velocity.y = -${node.force}`;
    case 'set_emoji':
      return `    # sprite = ${node.emoji}`;
    case 'set_size':
      return `    scale = Vector2(${node.scale}, ${node.scale})`;
    case 'set_opacity':
      return `    modulate.a = ${node.opacity / 100}`;
    case 'say':
      return `    # say: "${node.text}"`;
    case 'play_sound':
      return `    # play_sound: ${node.sound}`;
    case 'change_score':
      return `    score += ${node.delta}`;
    case 'set_score':
      return `    score = ${node.value}`;
    case 'change_health':
      return `    health += ${node.delta}`;
    case 'game_over':
      return `    get_tree().reload_current_scene()`;
    case 'win_game':
      return `    # win_game\n    get_tree().change_scene_to_file("res://win_scene.tscn")`;
    case 'spawn_enemy':
      return `    # spawn_enemy: ${node.emoji}`;
    case 'spawn_item':
      return `    # spawn_item: ${node.emoji}`;
    case 'shake_screen':
      return `    # shake_screen: intensity=${node.intensity}`;
    case 'set_camera':
      return node.follow ? `    $Camera2D.make_current()` : `    $Camera2D.clear_current()`;
    default:
      return null;
  }
}

/**
 * Generate fallback GDScript for unhandled CommandBlocks.
 */
function generateFallbackGDScript(cmd: CommandBlock): IRNode | null {
  // Not all commands map to IR nodes yet
  return null;
}

/**
 * Generate a complete Godot project structure.
 */
export function generateGodotProject(
  commands: CommandBlock[],
  projectName: string
): { projectFile: string; scriptFile: string; sceneFile: string } {
  const projectFile = `[gd_resource type="ProjectSettings" format=3]

[application]
config/name="${projectName}"
run/main_scene="res://main.tscn"
config/features=PackedStringArray("4.0")

[display]
window/size/viewport_width=800
window/size/viewport_height=600

[input]
ui_up={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":4194320,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)]
}
ui_left={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":4194319,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)]
}
ui_right={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":4194321,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)]
}`;

  const scriptFile = generateGDScriptFromIR(
    (() => {
      const { commandBlockToIR } = require('./ir');
      const nodes = [];
      for (const cmd of commands) {
        const node = commandBlockToIR(cmd);
        if (node) nodes.push(node);
      }
      return nodes;
    })(),
    'KidCodeGame'
  );

  const sceneFile = `[gd_scene format=3 uid="uid://kidcode"]

[ext_resource type="Script" path="res://player.gd" id="1"]

[node name="Player" type="CharacterBody2D"]
script = ExtResource("1")

[node name="Sprite" type="Sprite2D" parent="."]
position = Vector2(0, -16)

[node name="CollisionShape" type="CollisionShape2D" parent="."]

[node name="Camera" type="Camera2D" parent="."]
zoom = Vector2(1, 1)`;

  return { projectFile, scriptFile, sceneFile };
}
