import { AppMode } from '../types';

export interface DailyChallenge {
  id: string;
  title: string;
  description: string;
  mode: AppMode;
  difficulty: 'easy' | 'medium' | 'hard';
  timeLimit: number;
  requiredBlocks: string[];
  targetScore: number;
  template: any;
  rewards: { xp: number; coins: number; badge?: string };
  expiresAt: number;
}

export const DAILY_CHALLENGES: DailyChallenge[] = [
  {
    id: 'ch_e01',
    title: 'Move the Character',
    description: 'Make the character move right when the green flag is clicked',
    mode: AppMode.GAME,
    difficulty: 'easy',
    timeLimit: 120,
    requiredBlocks: ['EVENT_GREEN_FLAG', 'MOTION_MOVE_RIGHT'],
    targetScore: 1,
    template: { commands: [] },
    rewards: { xp: 20, coins: 10 },
    expiresAt: 0,
  },
  {
    id: 'ch_e02',
    title: 'Change the Background',
    description: 'Set the background to a color of your choice',
    mode: AppMode.GAME,
    difficulty: 'easy',
    timeLimit: 120,
    requiredBlocks: ['LOOKS_SET_BACKGROUND'],
    targetScore: 1,
    template: { commands: [] },
    rewards: { xp: 20, coins: 10 },
    expiresAt: 0,
  },
  {
    id: 'ch_e03',
    title: 'Blink the LED',
    description: 'Make an LED blink on and off repeatedly',
    mode: AppMode.HARDWARE,
    difficulty: 'easy',
    timeLimit: 120,
    requiredBlocks: ['OUTPUT_DIGITAL_WRITE', 'CONTROL_WAIT'],
    targetScore: 1,
    template: { commands: [], circuitComponents: [{ type: 'led', x: 200, y: 200, id: 'led1' }] },
    rewards: { xp: 20, coins: 10 },
    expiresAt: 0,
  },
  {
    id: 'ch_e04',
    title: 'Draw a Square',
    description: 'Use the pen to draw a square on the screen',
    mode: AppMode.GAME,
    difficulty: 'easy',
    timeLimit: 180,
    requiredBlocks: ['PEN_DOWN', 'MOTION_TURN_RIGHT'],
    targetScore: 1,
    template: { commands: [] },
    rewards: { xp: 20, coins: 10 },
    expiresAt: 0,
  },
  {
    id: 'ch_e05',
    title: 'Play a Sound',
    description: 'Play a sound when the game starts',
    mode: AppMode.GAME,
    difficulty: 'easy',
    timeLimit: 120,
    requiredBlocks: ['EVENT_GREEN_FLAG', 'SOUND_PLAY'],
    targetScore: 1,
    template: { commands: [] },
    rewards: { xp: 20, coins: 10 },
    expiresAt: 0,
  },
  {
    id: 'ch_e06',
    title: 'Add a Score',
    description: 'Add a score counter that increases when you click',
    mode: AppMode.GAME,
    difficulty: 'easy',
    timeLimit: 180,
    requiredBlocks: ['DATA_SET_VARIABLE', 'EVENT_WHEN_CLICKED'],
    targetScore: 1,
    template: { commands: [] },
    rewards: { xp: 20, coins: 10 },
    expiresAt: 0,
  },
  {
    id: 'ch_e07',
    title: 'Make a Button',
    description: 'Create a clickable button in the app builder',
    mode: AppMode.APP,
    difficulty: 'easy',
    timeLimit: 180,
    requiredBlocks: ['WIDGET_BUTTON'],
    targetScore: 1,
    template: { commands: [] },
    rewards: { xp: 20, coins: 10 },
    expiresAt: 0,
  },
  {
    id: 'ch_e08',
    title: 'Set a Timer',
    description: 'Display a countdown timer on screen',
    mode: AppMode.GAME,
    difficulty: 'easy',
    timeLimit: 180,
    requiredBlocks: ['DATA_SET_VARIABLE', 'CONTROL_REPEAT'],
    targetScore: 1,
    template: { commands: [] },
    rewards: { xp: 20, coins: 10 },
    expiresAt: 0,
  },
  {
    id: 'ch_e09',
    title: 'Change Size',
    description: 'Make the character grow and shrink',
    mode: AppMode.GAME,
    difficulty: 'easy',
    timeLimit: 120,
    requiredBlocks: ['LOOKS_SET_SIZE'],
    targetScore: 1,
    template: { commands: [] },
    rewards: { xp: 20, coins: 10 },
    expiresAt: 0,
  },
  {
    id: 'ch_e10',
    title: 'Bounce Off Walls',
    description: 'Make the character bounce off screen edges',
    mode: AppMode.GAME,
    difficulty: 'easy',
    timeLimit: 180,
    requiredBlocks: ['MOTION_IF_ON_EDGE_BOUNCE'],
    targetScore: 1,
    template: { commands: [] },
    rewards: { xp: 20, coins: 10 },
    expiresAt: 0,
  },
  {
    id: 'ch_m01',
    title: 'Platformer Jump',
    description: 'Add gravity and jumping to a character',
    mode: AppMode.GAME,
    difficulty: 'medium',
    timeLimit: 300,
    requiredBlocks: ['PHYSICS_SET_GRAVITY', 'EVENT_WHEN_KEY_PRESSED'],
    targetScore: 3,
    template: { commands: [] },
    rewards: { xp: 50, coins: 25 },
    expiresAt: 0,
  },
  {
    id: 'ch_m02',
    title: 'Collect Coins',
    description: 'Make coins disappear when touched and add to score',
    mode: AppMode.GAME,
    difficulty: 'medium',
    timeLimit: 300,
    requiredBlocks: ['EVENT_WHEN_TOUCHING', 'DATA_CHANGE_VARIABLE', 'LOOKS_HIDE'],
    targetScore: 3,
    template: { commands: [] },
    rewards: { xp: 50, coins: 25 },
    expiresAt: 0,
  },
  {
    id: 'ch_m03',
    title: 'Enemy Patrol',
    description: 'Make an enemy move back and forth',
    mode: AppMode.GAME,
    difficulty: 'medium',
    timeLimit: 300,
    requiredBlocks: ['CONTROL_REPEAT', 'MOTION_MOVE_RIGHT'],
    targetScore: 3,
    template: { commands: [] },
    rewards: { xp: 50, coins: 25 },
    expiresAt: 0,
  },
  {
    id: 'ch_m04',
    title: 'Weather Effect',
    description: 'Add rain or snow to the scene',
    mode: AppMode.GAME,
    difficulty: 'medium',
    timeLimit: 300,
    requiredBlocks: ['CONTROL_REPEAT', 'MOTION_GO_TO_RANDOM'],
    targetScore: 3,
    template: { commands: [] },
    rewards: { xp: 50, coins: 25 },
    expiresAt: 0,
  },
  {
    id: 'ch_m05',
    title: 'Day/Night Cycle',
    description: 'Create a day/night cycle with lighting changes',
    mode: AppMode.GAME,
    difficulty: 'medium',
    timeLimit: 300,
    requiredBlocks: ['CONTROL_REPEAT', 'LOOKS_SET_BACKGROUND', 'CONTROL_WAIT'],
    targetScore: 3,
    template: { commands: [] },
    rewards: { xp: 50, coins: 25 },
    expiresAt: 0,
  },
  {
    id: 'ch_m06',
    title: 'Music Loop',
    description: 'Create a repeating music pattern',
    mode: AppMode.GAME,
    difficulty: 'medium',
    timeLimit: 300,
    requiredBlocks: ['CONTROL_REPEAT', 'SOUND_PLAY'],
    targetScore: 3,
    template: { commands: [] },
    rewards: { xp: 50, coins: 25 },
    expiresAt: 0,
  },
  {
    id: 'ch_m07',
    title: 'Calculator',
    description: 'Build a working calculator app',
    mode: AppMode.APP,
    difficulty: 'medium',
    timeLimit: 600,
    requiredBlocks: ['DATA_SET_VARIABLE', 'MATH_OPERATOR', 'WIDGET_BUTTON'],
    targetScore: 3,
    template: { commands: [] },
    rewards: { xp: 50, coins: 25 },
    expiresAt: 0,
  },
  {
    id: 'ch_m08',
    title: 'Quiz Game',
    description: 'Create a 3-question quiz game',
    mode: AppMode.GAME,
    difficulty: 'medium',
    timeLimit: 600,
    requiredBlocks: ['DATA_SET_VARIABLE', 'CONTROL_IF_ELSE', 'SOUND_PLAY'],
    targetScore: 3,
    template: { commands: [] },
    rewards: { xp: 50, coins: 25 },
    expiresAt: 0,
  },
  {
    id: 'ch_m09',
    title: 'LED Brightness',
    description: 'Control LED brightness with a potentiometer',
    mode: AppMode.HARDWARE,
    difficulty: 'medium',
    timeLimit: 300,
    requiredBlocks: ['OUTPUT_ANALOG_WRITE', 'INPUT_ANALOG_READ'],
    targetScore: 3,
    template: { commands: [], circuitComponents: [{ type: 'led', x: 200, y: 200, id: 'led1' }, { type: 'potentiometer', x: 300, y: 200, id: 'pot1' }] },
    rewards: { xp: 50, coins: 25 },
    expiresAt: 0,
  },
  {
    id: 'ch_m10',
    title: 'Pixel Art',
    description: 'Draw a character using the pixel editor',
    mode: AppMode.GAME,
    difficulty: 'medium',
    timeLimit: 300,
    requiredBlocks: ['LOOKS_SET_COSTUME'],
    targetScore: 3,
    template: { commands: [] },
    rewards: { xp: 50, coins: 25 },
    expiresAt: 0,
  },
  {
    id: 'ch_h01',
    title: 'Complete Platformer',
    description: 'Build a full platformer with enemies, coins, and a goal',
    mode: AppMode.GAME,
    difficulty: 'hard',
    timeLimit: 600,
    requiredBlocks: ['PHYSICS_SET_GRAVITY', 'EVENT_WHEN_KEY_PRESSED', 'EVENT_WHEN_TOUCHING', 'DATA_CHANGE_VARIABLE'],
    targetScore: 5,
    template: { commands: [] },
    rewards: { xp: 100, coins: 50, badge: 'platformer_pro' },
    expiresAt: 0,
  },
  {
    id: 'ch_h02',
    title: 'RPG Battle',
    description: 'Create a turn-based battle system with health and attacks',
    mode: AppMode.GAME,
    difficulty: 'hard',
    timeLimit: 600,
    requiredBlocks: ['DATA_SET_VARIABLE', 'CONTROL_IF_ELSE', 'SOUND_PLAY', 'EVENT_WHEN_CLICKED'],
    targetScore: 5,
    template: { commands: [] },
    rewards: { xp: 100, coins: 50, badge: 'rpg_master' },
    expiresAt: 0,
  },
  {
    id: 'ch_h03',
    title: 'Racing Game',
    description: 'Build a top-down racing game with a track and obstacles',
    mode: AppMode.GAME,
    difficulty: 'hard',
    timeLimit: 600,
    requiredBlocks: ['MOTION_MOVE_RIGHT', 'EVENT_WHEN_KEY_PRESSED', 'EVENT_WHEN_TOUCHING', 'PHYSICS_SET_GRAVITY'],
    targetScore: 5,
    template: { commands: [] },
    rewards: { xp: 100, coins: 50, badge: 'speed_demon' },
    expiresAt: 0,
  },
  {
    id: 'ch_h04',
    title: 'Tower Defense',
    description: 'Place towers to defend against waves of enemies',
    mode: AppMode.GAME,
    difficulty: 'hard',
    timeLimit: 600,
    requiredBlocks: ['EVENT_WHEN_CLICKED', 'CONTROL_REPEAT', 'DATA_CHANGE_VARIABLE', 'EVENT_WHEN_TOUCHING'],
    targetScore: 5,
    template: { commands: [] },
    rewards: { xp: 100, coins: 50, badge: 'tower_master' },
    expiresAt: 0,
  },
  {
    id: 'ch_h05',
    title: 'Music Synthesizer',
    description: 'Create a playable keyboard with different sounds',
    mode: AppMode.APP,
    difficulty: 'hard',
    timeLimit: 600,
    requiredBlocks: ['SOUND_PLAY', 'EVENT_WHEN_KEY_PRESSED', 'DATA_SET_VARIABLE'],
    targetScore: 5,
    template: { commands: [] },
    rewards: { xp: 100, coins: 50, badge: 'synth_wizard' },
    expiresAt: 0,
  },
  {
    id: 'ch_h06',
    title: 'Smart Home',
    description: 'Control lights, temperature, and locks with a dashboard',
    mode: AppMode.HARDWARE,
    difficulty: 'hard',
    timeLimit: 600,
    requiredBlocks: ['OUTPUT_DIGITAL_WRITE', 'INPUT_ANALOG_READ', 'WIDGET_BUTTON', 'DATA_SET_VARIABLE'],
    targetScore: 5,
    template: { commands: [], circuitComponents: [{ type: 'led', x: 200, y: 150, id: 'led1' }, { type: 'led', x: 250, y: 150, id: 'led2' }, { type: 'potentiometer', x: 300, y: 200, id: 'pot1' }] },
    rewards: { xp: 100, coins: 50, badge: 'smart_home_pro' },
    expiresAt: 0,
  },
  {
    id: 'ch_h07',
    title: '3D Maze',
    description: 'Navigate a 3D maze to find the exit',
    mode: AppMode.GAME,
    difficulty: 'hard',
    timeLimit: 600,
    requiredBlocks: ['MOTION_MOVE_RIGHT', 'MOTION_TURN_RIGHT', 'EVENT_WHEN_KEY_PRESSED', 'PHYSICS_SET_GRAVITY'],
    targetScore: 5,
    template: { commands: [] },
    rewards: { xp: 100, coins: 50, badge: 'maze_runner' },
    expiresAt: 0,
  },
  {
    id: 'ch_h08',
    title: 'Robot Arm',
    description: 'Control a robotic arm with servo commands',
    mode: AppMode.HARDWARE,
    difficulty: 'hard',
    timeLimit: 600,
    requiredBlocks: ['OUTPUT_SERVO_WRITE', 'INPUT_ANALOG_READ', 'CONTROL_WAIT'],
    targetScore: 5,
    template: { commands: [], circuitComponents: [{ type: 'servo', x: 200, y: 200, id: 'servo1' }, { type: 'potentiometer', x: 300, y: 200, id: 'pot1' }] },
    rewards: { xp: 100, coins: 50, badge: 'robotics_pro' },
    expiresAt: 0,
  },
  {
    id: 'ch_h09',
    title: 'CAD Phone Case',
    description: 'Design a phone case with measurements in CAD',
    mode: AppMode.CAD,
    difficulty: 'hard',
    timeLimit: 600,
    requiredBlocks: ['CAD_BOX', 'CAD_CYLINDER', 'CAD_SUBTRACT'],
    targetScore: 5,
    template: { commands: [] },
    rewards: { xp: 100, coins: 50, badge: 'cad_designer' },
    expiresAt: 0,
  },
  {
    id: 'ch_h10',
    title: '3D Character',
    description: 'Model a character using CAD primitives',
    mode: AppMode.CAD,
    difficulty: 'hard',
    timeLimit: 600,
    requiredBlocks: ['CAD_SPHERE', 'CAD_CYLINDER', 'CAD_BOX', 'CAD_UNION'],
    targetScore: 5,
    template: { commands: [] },
    rewards: { xp: 100, coins: 50, badge: 'character_builder' },
    expiresAt: 0,
  },
];
