import { GalleryProject } from '../types/gallery';
import { AppMode } from '../types/enums';
import { CommandType, CommandBlock } from '../types';

const uid = () => crypto.randomUUID();

const makeCmd = (type: CommandType, params: Record<string, any> = {}): CommandBlock => ({
  id: uid(),
  type,
  params,
});

const makeGameCommands = (blocks: CommandBlock[]): CommandBlock[] => [
  makeCmd(CommandType.SET_SCENE, { text: 'forest' }),
  makeCmd(CommandType.SET_EMOJI, { text: '🧙' }),
  makeCmd(CommandType.SET_VAR, { varName: 'score', value: 0 }),
  ...blocks,
];

const sampleProjects: GalleryProject[] = [
  {
    id: uid(),
    name: 'Platform Adventure',
    description: 'Jump over obstacles, collect coins, and reach the flag! A classic platformer with gravity and physics.',
    mode: AppMode.GAME,
    author: 'CodyKid',
    authorAvatar: '🦊',
    likes: 245,
    views: 1830,
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now() - 86400000 * 2,
    tags: ['platformer', 'adventure', 'coins', 'gravity'],
    isRemix: false,
    projectData: {
      commands: makeGameCommands([
        makeCmd(CommandType.SET_GRAVITY, { condition: 'true' }),
        makeCmd(CommandType.FOREVER, {}),
        makeCmd(CommandType.IF, { condition: 'IS_PRESSED', pin: 38 }),
        makeCmd(CommandType.JUMP, { value: 15 }),
        makeCmd(CommandType.END_IF, {}),
        makeCmd(CommandType.IF, { condition: 'IS_PRESSED', pin: 39 }),
        makeCmd(CommandType.MOVE_X, { value: 5 }),
        makeCmd(CommandType.END_IF, {}),
        makeCmd(CommandType.IF, { condition: 'IS_PRESSED', pin: 37 }),
        makeCmd(CommandType.MOVE_X, { value: -5 }),
        makeCmd(CommandType.END_IF, {}),
        makeCmd(CommandType.CHANGE_SCORE, { value: 1 }),
        makeCmd(CommandType.END_FOREVER, {}),
      ]),
      hardwareState: {} as any,
      spriteState: {} as any,
      appState: {} as any,
      circuitComponents: [],
      pcbColor: '#059669',
    },
  },
  {
    id: uid(),
    name: 'Space Shooter',
    description: 'Defend Earth from alien invaders! Dodge asteroids and shoot enemies in this fast-paced space game.',
    mode: AppMode.GAME,
    author: 'GameWizard',
    authorAvatar: '🦁',
    likes: 312,
    views: 2450,
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now() - 86400000 * 1,
    tags: ['shooter', 'space', 'aliens', 'action'],
    isRemix: false,
    projectData: {
      commands: makeGameCommands([
        makeCmd(CommandType.SET_SCENE, { text: 'space' }),
        makeCmd(CommandType.SET_EMOJI, { text: '🚀' }),
        makeCmd(CommandType.SET_VAR, { varName: 'lives', value: 3 }),
        makeCmd(CommandType.FOREVER, {}),
        makeCmd(CommandType.IF, { condition: 'IS_PRESSED', pin: 39 }),
        makeCmd(CommandType.MOVE_X, { value: 8 }),
        makeCmd(CommandType.END_IF, {}),
        makeCmd(CommandType.IF, { condition: 'IS_PRESSED', pin: 37 }),
        makeCmd(CommandType.MOVE_X, { value: -8 }),
        makeCmd(CommandType.END_IF, {}),
        makeCmd(CommandType.IF, { condition: 'IS_PRESSED', pin: 32 }),
        makeCmd(CommandType.SPAWN_PARTICLES, { text: 'sparkle', color: '#fbbf24' }),
        makeCmd(CommandType.END_IF, {}),
        makeCmd(CommandType.CHANGE_SCORE, { value: 2 }),
        makeCmd(CommandType.END_FOREVER, {}),
      ]),
      hardwareState: {} as any,
      spriteState: {} as any,
      appState: {} as any,
      circuitComponents: [],
      pcbColor: '#059669',
    },
  },
  {
    id: uid(),
    name: 'Calculator App',
    description: 'A fully functional calculator with addition, subtraction, multiplication, and division.',
    mode: AppMode.APP,
    author: 'JuniorDev',
    authorAvatar: '🐻',
    likes: 178,
    views: 1320,
    createdAt: Date.now() - 86400000 * 7,
    updatedAt: Date.now() - 86400000 * 4,
    tags: ['calculator', 'math', 'utility', 'tools'],
    isRemix: false,
    projectData: {
      commands: [
        makeCmd(CommandType.SET_TITLE, { text: 'Calculator Pro' }),
        makeCmd(CommandType.SET_BACKGROUND, { color: '#f8fafc' }),
        makeCmd(CommandType.ADD_TEXT_BLOCK, { text: 'First Number:', textSize: 'lg' }),
        makeCmd(CommandType.ADD_INPUT, { varName: 'num1', text: 'Enter number' }),
        makeCmd(CommandType.ADD_TEXT_BLOCK, { text: 'Second Number:', textSize: 'lg' }),
        makeCmd(CommandType.ADD_INPUT, { varName: 'num2', text: 'Enter number' }),
        makeCmd(CommandType.ADD_SPACER, { value: 12 }),
        makeCmd(CommandType.ADD_BUTTON, { text: 'Add +', message: 'add' }),
        makeCmd(CommandType.ADD_BUTTON, { text: 'Subtract -', message: 'sub' }),
        makeCmd(CommandType.ADD_BUTTON, { text: 'Multiply ×', message: 'mul' }),
        makeCmd(CommandType.ADD_BUTTON, { text: 'Divide ÷', message: 'div' }),
        makeCmd(CommandType.ADD_SPACER, { value: 16 }),
        makeCmd(CommandType.ADD_TEXT_BLOCK, { text: 'Result will appear here!', textSize: 'md' }),
      ],
      hardwareState: {} as any,
      spriteState: {} as any,
      appState: {} as any,
      circuitComponents: [],
      pcbColor: '#059669',
    },
  },
  {
    id: uid(),
    name: 'Pixel Artist',
    description: 'Draw pixel art on a grid canvas! Choose colors, zoom in and out, and create masterpieces.',
    mode: AppMode.APP,
    author: 'PixelPro',
    authorAvatar: '🐱',
    likes: 423,
    views: 3100,
    createdAt: Date.now() - 86400000 * 10,
    updatedAt: Date.now() - 86400000 * 1,
    tags: ['drawing', 'art', 'creative', 'pixel'],
    isRemix: false,
    projectData: {
      commands: [
        makeCmd(CommandType.SET_TITLE, { text: 'Pixel Art Studio' }),
        makeCmd(CommandType.SET_BACKGROUND, { color: '#1e293b' }),
        makeCmd(CommandType.ADD_TEXT_BLOCK, { text: 'Choose a color:', textSize: 'lg' }),
        makeCmd(CommandType.ADD_COLOR_PICKER, { varName: 'drawColor' }),
        makeCmd(CommandType.ADD_DRAWING_CANVAS, {}),
        makeCmd(CommandType.ADD_SPACER, { value: 12 }),
        makeCmd(CommandType.ADD_BUTTON, { text: 'Clear Canvas', message: 'clear' }),
        makeCmd(CommandType.ADD_BUTTON, { text: 'Save Art', message: 'save' }),
      ],
      hardwareState: {} as any,
      spriteState: {} as any,
      appState: {} as any,
      circuitComponents: [],
      pcbColor: '#059669',
    },
  },
  {
    id: uid(),
    name: 'Music Maker',
    description: 'Create beats and melodies with a simple step sequencer. Mix drums, bass, and synth sounds!',
    mode: AppMode.APP,
    author: 'SoundWave',
    authorAvatar: '🐸',
    likes: 287,
    views: 2080,
    createdAt: Date.now() - 86400000 * 4,
    updatedAt: Date.now() - 86400000 * 2,
    tags: ['music', 'audio', 'beats', 'sequencer'],
    isRemix: false,
    projectData: {
      commands: [
        makeCmd(CommandType.SET_TITLE, { text: 'Music Maker' }),
        makeCmd(CommandType.SET_BACKGROUND, { color: '#0f172a' }),
        makeCmd(CommandType.ADD_TEXT_BLOCK, { text: '🎵 Tap to add beats!', textSize: 'lg' }),
        makeCmd(CommandType.ADD_SPACER, { value: 8 }),
        makeCmd(CommandType.ADD_BUTTON, { text: 'Drums', message: 'drums' }),
        makeCmd(CommandType.ADD_BUTTON, { text: 'Bass', message: 'bass' }),
        makeCmd(CommandType.ADD_BUTTON, { text: 'Synth', message: 'synth' }),
        makeCmd(CommandType.ADD_SLIDER, { text: 'Tempo', varName: 'tempo' }),
        makeCmd(CommandType.ADD_SPACER, { value: 16 }),
        makeCmd(CommandType.ADD_BUTTON, { text: '▶ Play', message: 'play' }),
        makeCmd(CommandType.ADD_BUTTON, { text: '⏹ Stop', message: 'stop' }),
      ],
      hardwareState: {} as any,
      spriteState: {} as any,
      appState: {} as any,
      circuitComponents: [],
      pcbColor: '#059669',
    },
  },
  {
    id: uid(),
    name: 'Circuit Lab',
    description: 'Build a blinking LED circuit! Learn how resistors, LEDs, and microcontrollers work together.',
    mode: AppMode.HARDWARE,
    author: 'MakerMax',
    authorAvatar: '🐯',
    likes: 198,
    views: 1560,
    createdAt: Date.now() - 86400000 * 6,
    updatedAt: Date.now() - 86400000 * 3,
    tags: ['circuit', 'LED', 'hardware', 'arduino'],
    isRemix: false,
    projectData: {
      commands: [
        makeCmd(CommandType.FOREVER, {}),
        makeCmd(CommandType.LED_ON, { pin: 0 }),
        makeCmd(CommandType.PLAY_TONE, { duration: 0.5 }),
        makeCmd(CommandType.LED_OFF, { pin: 0 }),
        makeCmd(CommandType.PLAY_TONE, { duration: 0.5 }),
        makeCmd(CommandType.END_FOREVER, {}),
      ],
      hardwareState: {} as any,
      spriteState: {} as any,
      appState: {} as any,
      circuitComponents: [
        { id: 'c1', type: 'LED_RED', x: 120, y: 120, pin: 0 },
        { id: 'c2', type: 'RESISTOR', x: 200, y: 120, pin: 0 },
        { id: 'c3', type: 'BATTERY', x: 280, y: 200, pin: 0 },
      ],
      pcbColor: '#059669',
    },
  },
  {
    id: uid(),
    name: 'Minecraft Village',
    description: 'Build a cozy village with houses, farms, and a blacksmith! Uses custom blocks and terrain.',
    mode: AppMode.MINECRAFT,
    author: 'BrainyBot',
    authorAvatar: '🐼',
    likes: 534,
    views: 4200,
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now() - 86400000 * 1,
    tags: ['minecraft', 'building', 'village', 'creative'],
    isRemix: false,
    projectData: {
      commands: [
        makeCmd(CommandType.SET_VAR, { varName: 'village_size', value: 32 }),
        makeCmd(CommandType.REPEAT, { count: 4 }),
        makeCmd(CommandType.SET_VAR, { varName: 'house_type', value: 'oak' }),
        makeCmd(CommandType.END_REPEAT, {}),
        makeCmd(CommandType.SET_VAR, { varName: 'has_farm', value: 1 }),
      ],
      hardwareState: {} as any,
      spriteState: {} as any,
      appState: {} as any,
      circuitComponents: [],
      pcbColor: '#059669',
    },
  },
  {
    id: uid(),
    name: 'Quiz Game',
    description: 'Test your knowledge with fun trivia questions! Features score tracking and multiple categories.',
    mode: AppMode.GAME,
    author: 'TechTiger',
    authorAvatar: '🐰',
    likes: 156,
    views: 1120,
    createdAt: Date.now() - 86400000 * 8,
    updatedAt: Date.now() - 86400000 * 5,
    tags: ['quiz', 'trivia', 'education', 'fun'],
    isRemix: false,
    projectData: {
      commands: makeGameCommands([
        makeCmd(CommandType.SET_VAR, { varName: 'question_num', value: 1 }),
        makeCmd(CommandType.SET_VAR, { varName: 'correct', value: 0 }),
        makeCmd(CommandType.SET_VAR, { varName: 'total', value: 10 }),
        makeCmd(CommandType.FOREVER, {}),
        makeCmd(CommandType.IF, { condition: 'IS_PRESSED', pin: 32 }),
        makeCmd(CommandType.CHANGE_SCORE, { value: 10 }),
        makeCmd(CommandType.CHANGE_VAR, { varName: 'correct', value: 1 }),
        makeCmd(CommandType.SPAWN_PARTICLES, { text: 'sparkle', color: '#22c55e' }),
        makeCmd(CommandType.END_IF, {}),
        makeCmd(CommandType.END_FOREVER, {}),
      ]),
      hardwareState: {} as any,
      spriteState: {} as any,
      appState: {} as any,
      circuitComponents: [],
      pcbColor: '#059669',
    },
  },
];

export const getSampleProjects = (): GalleryProject[] => sampleProjects;
