
export enum CommandType {
  // --- COMMON FLOW ---
  WAIT = 'WAIT',
  SAVE_GAME = 'SAVE_GAME',
  LOAD_GAME = 'LOAD_GAME',
  REPEAT = 'REPEAT',
  END_REPEAT = 'END_REPEAT',
  FOREVER = 'FOREVER',
  END_FOREVER = 'END_FOREVER',
  BREAK = 'BREAK',
  COMMENT = 'COMMENT',

  // --- 3D COMMANDS ---
  MOVE_Z = 'MOVE_Z',
  ROTATE_X = 'ROTATE_X',
  ROTATE_Y = 'ROTATE_Y',
  ROTATE_Z = 'ROTATE_Z',
  SET_VIEW_3D = 'SET_VIEW_3D',
  SPAWN_3D_OBJECT = 'SPAWN_3D_OBJECT',
  SET_LIGHTING = 'SET_LIGHTING',
  SET_CAMERA_CONSTRAINT = 'SET_CAMERA_CONSTRAINT',
  GENERATE_ENVIRONMENT = 'GENERATE_ENVIRONMENT',

  // --- EVENTS & MESSAGING ---
  ON_COLLIDE = 'ON_COLLIDE',
  ON_CLICK = 'ON_CLICK',
  BROADCAST = 'BROADCAST',
  WHEN_I_RECEIVE = 'WHEN_I_RECEIVE',
  END_EVENT = 'END_EVENT',

  // --- LOGIC & CONDITIONS ---
  IF = 'IF',
  ELSE = 'ELSE',
  END_IF = 'END_IF',
  WAIT_FOR_PRESS = 'WAIT_FOR_PRESS',
  LISTEN_FOR = 'LISTEN_FOR', // Voice command

  // --- VARIABLES & DATA ---
  SET_VAR = 'SET_VAR',
  CHANGE_VAR = 'CHANGE_VAR',
  CALC_RANDOM = 'CALC_RANDOM', // Set var to random(min, max)

  // --- MATH & CALCULATION (Stored in Variable) ---
  CALC_ADD = 'CALC_ADD', // var = val1 + val2
  CALC_SUB = 'CALC_SUB',
  CALC_MUL = 'CALC_MUL',
  CALC_DIV = 'CALC_DIV',
  CALC_MOD = 'CALC_MOD',
  CALC_ROUND = 'CALC_ROUND',
  CALC_ABS = 'CALC_ABS',
  CALC_SIN = 'CALC_SIN',
  CALC_COS = 'CALC_COS',

  // --- STRING OPERATIONS ---
  STR_JOIN = 'STR_JOIN', // var = str1 + str2
  STR_LENGTH = 'STR_LENGTH',
  STR_UPPER = 'STR_UPPER',
  STR_LOWER = 'STR_LOWER',

  // --- LISTS / ARRAYS ---
  LIST_ADD = 'LIST_ADD',
  LIST_REMOVE = 'LIST_REMOVE',
  LIST_INSERT = 'LIST_INSERT',
  LIST_REPLACE = 'LIST_REPLACE',
  LIST_GET = 'LIST_GET',
  LIST_CLEAR = 'LIST_CLEAR',
  LIST_CONTAINS = 'LIST_CONTAINS',

  // --- APP MAKER: UI ---
  CREATE_SCREEN = 'CREATE_SCREEN',
  NAVIGATE = 'NAVIGATE',
  SET_TITLE = 'SET_TITLE',
  SET_BACKGROUND = 'SET_BACKGROUND',
  SET_THEME = 'SET_THEME',

  // UI Elements
  ADD_BUTTON = 'ADD_BUTTON',
  ADD_TEXT_BLOCK = 'ADD_TEXT_BLOCK',
  ADD_INPUT = 'ADD_INPUT',
  ADD_PASSWORD = 'ADD_PASSWORD',
  ADD_TEXTAREA = 'ADD_TEXTAREA',
  ADD_IMAGE = 'ADD_IMAGE',
  ADD_VIDEO = 'ADD_VIDEO',
  ADD_CAMERA = 'ADD_CAMERA',
  ADD_DRAWING_CANVAS = 'ADD_DRAWING_CANVAS',
  ADD_LIST_VIEW = 'ADD_LIST_VIEW',
  ADD_AUDIO_PLAYER = 'ADD_AUDIO_PLAYER',
  ADD_AUDIO_RECORDER = 'ADD_AUDIO_RECORDER', // New
  ADD_SWITCH = 'ADD_SWITCH',
  ADD_SLIDER = 'ADD_SLIDER',
  ADD_CHECKBOX = 'ADD_CHECKBOX',
  ADD_RADIO = 'ADD_RADIO',
  ADD_DROPDOWN = 'ADD_DROPDOWN',
  ADD_DATE_PICKER = 'ADD_DATE_PICKER',
  ADD_TIME_PICKER = 'ADD_TIME_PICKER',
  ADD_COLOR_PICKER = 'ADD_COLOR_PICKER',
  ADD_PROGRESS = 'ADD_PROGRESS',
  ADD_NEWS_FEED = 'ADD_NEWS_FEED',
  ADD_CHAT_MESSAGE = 'ADD_CHAT_MESSAGE',
  ADD_MAP = 'ADD_MAP',
  ADD_CHART = 'ADD_CHART',
  ADD_QR_CODE = 'ADD_QR_CODE',
  ADD_RATING = 'ADD_RATING',
  ADD_DIVIDER = 'ADD_DIVIDER',
  ADD_SPACER = 'ADD_SPACER',
  ADD_ICON = 'ADD_ICON',
  DEFINE_PLUGIN = 'DEFINE_PLUGIN',
  USE_PLUGIN = 'USE_PLUGIN',

  // UI Actions
  SPEAK = 'SPEAK',
  VIBRATE_DEVICE = 'VIBRATE_DEVICE',
  SHOW_ALERT = 'SHOW_ALERT',
  SHOW_TOAST = 'SHOW_TOAST',
  OPEN_URL = 'OPEN_URL',
  SHARE_TEXT = 'SHARE_TEXT',
  CLEAR_UI = 'CLEAR_UI',
  CLOUD_SAVE = 'CLOUD_SAVE',
  CLOUD_LOAD = 'CLOUD_LOAD',

  // --- GAME MAKER: MOVEMENT ---
  MOVE_X = 'MOVE_X',
  MOVE_Y = 'MOVE_Y',
  GO_TO_XY = 'GO_TO_XY',
  GLIDE_TO_XY = 'GLIDE_TO_XY',
  POINT_DIR = 'POINT_DIR',
  POINT_TOWARDS = 'POINT_TOWARDS',
  TURN_RIGHT = 'TURN_RIGHT',
  TURN_LEFT = 'TURN_LEFT',
  SET_ROTATION_STYLE = 'SET_ROTATION_STYLE',
  BOUNCE_ON_EDGE = 'BOUNCE_ON_EDGE',

  // Physics
  JUMP = 'JUMP',
  SET_GRAVITY = 'SET_GRAVITY',
  SET_VELOCITY_X = 'SET_VELOCITY_X',
  SET_VELOCITY_Y = 'SET_VELOCITY_Y',
  SET_MASS = 'SET_MASS',
  SET_FRICTION = 'SET_FRICTION',
  SET_BOUNCINESS = 'SET_BOUNCINESS',

  // --- PHYSICS 2.0 (Matter.js) ---
  SET_PHYSICS_TYPE = 'SET_PHYSICS_TYPE', // Static, Dynamic, Bouncy
  CREATE_JOINT = 'CREATE_JOINT', // Connect two bodies
  APPLY_FORCE = 'APPLY_FORCE', // Push object

  // Looks
  SAY = 'SAY',
  THINK = 'THINK',
  SET_EMOJI = 'SET_EMOJI',
  SET_SIZE = 'SET_SIZE',
  CHANGE_SIZE = 'CHANGE_SIZE',
  SHOW = 'SHOW',
  HIDE = 'HIDE',
  SET_OPACITY = 'SET_OPACITY',
  CHANGE_EFFECT = 'CHANGE_EFFECT', // Color, Ghost, etc.
  PLAY_ANIMATION = 'PLAY_ANIMATION',
  GO_TO_FRONT = 'GO_TO_FRONT',
  GO_TO_BACK = 'GO_TO_BACK',

  // World
  SET_SCENE = 'SET_SCENE',
  SET_WEATHER = 'SET_WEATHER',
  SET_CAMERA = 'SET_CAMERA',
  SHAKE_CAMERA = 'SHAKE_CAMERA',

  // Game Objects
  SHOOT = 'SHOOT',
  SPAWN_ENEMY = 'SPAWN_ENEMY',
  SPAWN_ITEM = 'SPAWN_ITEM',
  SPAWN_PARTICLES = 'SPAWN_PARTICLES',
  NPC_TALK = 'NPC_TALK',
  CREATE_DIALOGUE = 'CREATE_DIALOGUE',
  END_DIALOGUE = 'END_DIALOGUE',
  ADD_PLATFORM = 'ADD_PLATFORM',
  CREATE_CLONE = 'CREATE_CLONE',
  DELETE_CLONE = 'DELETE_CLONE',
  SET_TILE = 'SET_TILE',

  // === 3D GAME COMMANDS ===
  CREATE_3D_OBJECT = 'CREATE_3D_OBJECT',
  SPAWN_3D_MODEL = 'SPAWN_3D_MODEL',
  SET_3D_POSITION = 'SET_3D_POSITION',
  SET_3D_ROTATION = 'SET_3D_ROTATION',
  ROTATE_3D_MODEL = 'ROTATE_3D_MODEL',
  SCALE_3D_MODEL = 'SCALE_3D_MODEL',
  SET_3D_MATERIAL = 'SET_3D_MATERIAL',
  ADD_3D_LIGHT = 'ADD_3D_LIGHT',
  PLAY_3D_ANIMATION = 'PLAY_3D_ANIMATION',
  SET_3D_CAMERA = 'SET_3D_CAMERA',
  SET_3D_LIGHTING = 'SET_3D_LIGHTING',
  ENABLE_PHYSICS_3D = 'ENABLE_PHYSICS_3D',
  SWITCH_TO_3D_MODE = 'SWITCH_TO_3D_MODE',
  SWITCH_TO_2D_MODE = 'SWITCH_TO_2D_MODE',

  // Inventory & Items
  ADD_TO_INVENTORY = 'ADD_TO_INVENTORY',
  REMOVE_FROM_INVENTORY = 'REMOVE_FROM_INVENTORY',
  USE_ITEM = 'USE_ITEM',
  SHOW_INVENTORY = 'SHOW_INVENTORY',
  CRAFT_ITEM = 'CRAFT_ITEM',

  // Audio & Music
  SET_BACKGROUND_MUSIC = 'SET_BACKGROUND_MUSIC',
  PLAY_MUSIC = 'PLAY_MUSIC',
  STOP_MUSIC = 'STOP_MUSIC',
  SET_MUSIC_VOLUME = 'SET_MUSIC_VOLUME',
  PLAY_AMBIENT = 'PLAY_AMBIENT',

  // Cutscenes & Events
  TRIGGER_CUTSCENE = 'TRIGGER_CUTSCENE',
  FADE_IN = 'FADE_IN',
  FADE_OUT = 'FADE_OUT',
  SHAKE_SCREEN = 'SHAKE_SCREEN',
  SLOW_MOTION = 'SLOW_MOTION',
  FREEZE_FRAME = 'FREEZE_FRAME',

  // Boss Battles
  SPAWN_BOSS = 'SPAWN_BOSS',
  SET_BOSS_HEALTH = 'SET_BOSS_HEALTH',
  BOSS_ATTACK = 'BOSS_ATTACK',
  BOSS_PHASE = 'BOSS_PHASE',

  // Advanced Movement
  DASH = 'DASH',
  WALL_JUMP = 'WALL_JUMP',
  DOUBLE_JUMP = 'DOUBLE_JUMP',
  GRAPPLE = 'GRAPPLE',

  // Checkpoints & Saves
  CREATE_CHECKPOINT = 'CREATE_CHECKPOINT',
  LOAD_CHECKPOINT = 'LOAD_CHECKPOINT',
  AUTO_SAVE = 'AUTO_SAVE',

  // Game Data
  CHANGE_SCORE = 'CHANGE_SCORE',
  SET_SCORE = 'SET_SCORE',
  SET_HEALTH = 'SET_HEALTH',
  CHANGE_HEALTH = 'CHANGE_HEALTH',
  GAME_OVER = 'GAME_OVER',
  WIN_GAME = 'WIN_GAME',

  // --- SPORTS GAME ---
  KICK_BALL = 'KICK_BALL',
  PASS_BALL = 'PASS_BALL',
  DRIBBLE = 'DRIBBLE',
  SHOOT_BALL = 'SHOOT_BALL',
  SET_TIMER = 'SET_TIMER',
  TICK_TIMER = 'TICK_TIMER',
  STOP_TIMER = 'STOP_TIMER',
  SCORE_GOAL = 'SCORE_GOAL',
  ADD_PERIOD = 'ADD_PERIOD',
  END_PERIOD = 'END_PERIOD',
  SPAWN_BALL = 'SPAWN_BALL',
  SPAWN_TEAMMATE = 'SPAWN_TEAMMATE',
  SPAWN_OPPONENT = 'SPAWN_OPPONENT',
  SWITCH_CONTROL = 'SWITCH_CONTROL',
  SET_FORMATION = 'SET_FORMATION',
  FOUL = 'FOUL',
  YELLOW_CARD = 'YELLOW_CARD',
  RED_CARD = 'RED_CARD',

  // --- ACTION GAME ---
  SWING_WEAPON = 'SWING_WEAPON',
  COMBO_ATTACK = 'COMBO_ATTACK',
  DODGE_ROLL = 'DODGE_ROLL',
  SCREEN_SHAKE = 'SCREEN_SHAKE',
  BLOCK_ATTACK = 'BLOCK_ATTACK',
  SPECIAL_MOVE = 'SPECIAL_MOVE',
  SWITCH_WEAPON = 'SWITCH_WEAPON',
  CHARGE_ATTACK = 'CHARGE_ATTACK',

  // --- ADVENTURE GAME ---
  EXAMINE = 'EXAMINE',
  COMBINE_ITEMS = 'COMBINE_ITEMS',
  TALK_TO = 'TALK_TO',
  ADD_QUEST = 'ADD_QUEST',
  COMPLETE_QUEST = 'COMPLETE_QUEST',
  DISCOVER = 'DISCOVER',
  TRIGGER_PUZZLE = 'TRIGGER_PUZZLE',

  // --- SHOOTER GAME ---
  RELOAD = 'RELOAD',
  THROW_GRENADE = 'THROW_GRENADE',
  TAKE_COVER = 'TAKE_COVER',
  AIM = 'AIM',
  SWAP_WEAPON = 'SWAP_WEAPON',
  DROP_WEAPON = 'DROP_WEAPON',
  PICKUP_WEAPON = 'PICKUP_WEAPON',

  // --- SURVIVAL GAME ---
  GATHER = 'GATHER',
  CRAFT = 'CRAFT',
  EAT = 'EAT',
  DRINK = 'DRINK',
  BUILD = 'BUILD',
  PLACE_TORCH = 'PLACE_TORCH',
  SHELTER = 'SHELTER',

  // --- ADVANCED SPORTS ---
  CRY_FOUL = 'CRY_FOUL',
  CELEBRATE_GOAL = 'CELEBRATE_GOAL',
  SUBSTITUTION = 'SUBSTITUTION',
  EXTRA_TIME = 'EXTRA_TIME',
  PENALTY_KICK = 'PENALTY_KICK',
  CORNER_KICK = 'CORNER_KICK',
  FREE_KICK = 'FREE_KICK',
  INJURY_TIME = 'INJURY_TIME',
  WATER_BREAK = 'WATER_BREAK',
  TEAM_TALK = 'TEAM_TALK',
  SET_PIECE = 'SET_PIECE',
  MAN_MARK = 'MAN_MARK',

  // --- ADVANCED PLATFORMER ---
  WALL_JUMP_ENABLED = 'WALL_JUMP_ENABLED',
  CEILING_CLING = 'CEILING_CLING',
  AIR_DASH = 'AIR_DASH',
  GROUND_SLAM = 'GROUND_SLAM',
  CLIMB_VINE = 'CLIMB_VINE',
  SWING_ROPE = 'SWING_ROPE',
  RIDE_PLATFORM = 'RIDE_PLATFORM',
  ACTIVATE_SWITCH = 'ACTIVATE_SWITCH',
  MOVE_PLATFORM = 'MOVE_PLATFORM',
  DEACTIVATE_TRAP = 'DEACTIVATE_TRAP',
  COLLECT_STAR = 'COLLECT_STAR',
  ENTER_PORTAL = 'ENTER_PORTAL',

  // --- PUZZLE GAME ---
  SWAP_TILES = 'SWAP_TILES',
  ROTATE_BLOCK = 'ROTATE_BLOCK',
  SLIDE_PUZZLE = 'SLIDE_PUZZLE',
  FILL_COLOR = 'FILL_COLOR',
  CONNECT_DOTS = 'CONNECT_DOTS',
  SORT_ITEMS = 'SORT_ITEMS',
  UNLOCK_PATTERN = 'UNLOCK_PATTERN',
  MIRROR_PUZZLE = 'MIRROR_PUZZLE',
  FLIP_CARD = 'FLIP_CARD',
  CHECK_MATCH = 'CHECK_MATCH',

  // --- RACING GAME ---
  BOOST = 'BOOST',
  DRIFT = 'DRIFT',
  LAP_COMPLETE = 'LAP_COMPLETE',
  START_RACE = 'START_RACE',
  SET_CHECKPOINT = 'SET_CHECKPOINT',
  UPGRADE_CAR = 'UPGRADE_CAR',
  PIT_STOP = 'PIT_STOP',
  USE_BOOST_PAD = 'USE_BOOST_PAD',

  // --- HARDWARE: OUTPUTS ---
  LED_ON = 'LED_ON',
  LED_OFF = 'LED_OFF',
  LED_TOGGLE = 'LED_TOGGLE',
  SET_RGB = 'SET_RGB',
  SET_RGB_BRIGHTNESS = 'SET_RGB_BRIGHTNESS',

  PLAY_TONE = 'PLAY_TONE',
  PLAY_NOTE = 'PLAY_NOTE',
  PLAY_SOUND = 'PLAY_SOUND',
  STOP_SOUND = 'STOP_SOUND',

  SET_FAN = 'SET_FAN',
  SET_SERVO = 'SET_SERVO',
  SET_MOTOR_SPEED = 'SET_MOTOR_SPEED',
  SET_MOTOR_DIR = 'SET_MOTOR_DIR',
  SET_STEPPER = 'SET_STEPPER',

  SET_RELAY = 'SET_RELAY',
  SET_SOLENOID = 'SET_SOLENOID',
  SET_LASER = 'SET_LASER',

  // Displays
  SET_LCD = 'SET_LCD',
  CLEAR_LCD = 'CLEAR_LCD',
  SCROLL_LCD = 'SCROLL_LCD',
  SET_OLED_TEXT = 'SET_OLED_TEXT',
  DRAW_OLED_SHAPE = 'DRAW_OLED_SHAPE',
  SET_SEGMENT = 'SET_SEGMENT',
  SET_MATRIX_ROW = 'SET_MATRIX_ROW',
  CLEAR_MATRIX = 'CLEAR_MATRIX',

  // --- HARDWARE: SENSORS / INPUT ---
  READ_DIGITAL = 'READ_DIGITAL',
  READ_ANALOG = 'READ_ANALOG',
  READ_TEMPERATURE = 'READ_TEMPERATURE',
  READ_HUMIDITY = 'READ_HUMIDITY',
  READ_DISTANCE = 'READ_DISTANCE',
  READ_GAS_LEVEL = 'READ_GAS_LEVEL',
  READ_FLAME = 'READ_FLAME',
  READ_RAIN = 'READ_RAIN',
  READ_SOIL = 'READ_SOIL',
  READ_HEARTBEAT = 'READ_HEARTBEAT',
  READ_COMPASS = 'READ_COMPASS',
  READ_GYRO = 'READ_GYRO',
  READ_GPS = 'READ_GPS',
  READ_COLOR = 'READ_COLOR',
  READ_PRESSURE = 'READ_PRESSURE',
  READ_FLEX = 'READ_FLEX',
  READ_MAGNETIC = 'READ_MAGNETIC',
  SET_VIBRATION = 'SET_VIBRATION',

  // === RPG SYSTEM COMMANDS (New in Cycle 2) ===
  // XP & Leveling
  ADD_XP = 'ADD_XP',
  LEVEL_UP = 'LEVEL_UP',
  SET_STAT = 'SET_STAT', // STR, DEF, SPD, etc.
  
  // Status Effects
  APPLY_STATUS = 'APPLY_STATUS', // Apply poison/burn/freeze/etc
  REMOVE_STATUS = 'REMOVE_STATUS',
  HAS_STATUS = 'HAS_STATUS', // Check if has status
  
  // Combat
  CALCULATE_DAMAGE = 'CALCULATE_DAMAGE', // With defense
  CRITICAL_HIT = 'CRITICAL_HIT',
  ATTACK_ENEMY = 'ATTACK_ENEMY',
  
  // Waves & Spawning
  START_WAVE = 'START_WAVE',
  SPAWN_WAVE_ENEMIES = 'SPAWN_WAVE_ENEMIES',
  NEXT_WAVE = 'NEXT_WAVE',
  
  // Loot
  DROP_LOOT = 'DROP_LOOT',
  ROLL_LOOT = 'ROLL_LOOT',
  ADD_TO_LOOT_TABLE = 'ADD_TO_LOOT_TABLE',
  
  // Quests
  ACCEPT_QUEST = 'ACCEPT_QUEST',
  UPDATE_QUEST = 'UPDATE_QUEST',
  SHOW_QUEST_LOG = 'SHOW_QUEST_LOG',
  
  // Shop
  OPEN_SHOP = 'OPEN_SHOP',
  BUY_ITEM = 'BUY_ITEM',
  SELL_ITEM = 'SELL_ITEM',
  
  // Minimap
  TOGGLE_MINIMAP = 'TOGGLE_MINIMAP',
  SET_MINIMAP_CONFIG = 'SET_MINIMAP_CONFIG',
  
  // Areas & Transitions
  TRANSITION_TO_AREA = 'TRANSITION_TO_AREA',
  SET_AREA = 'SET_AREA',
  
  // Boss Phases
  SET_BOSS_PHASE_CONFIG = 'SET_BOSS_PHASE_CONFIG',
  TRIGGER_BOSS_PHASE = 'TRIGGER_BOSS_PHASE',
  
  // Difficulty
  SET_DIFFICULTY = 'SET_DIFFICULTY',
  
  // --- LOCAL DATABASE ---
  DB_CREATE = 'DB_CREATE',
  DB_INSERT = 'DB_INSERT',
  DB_QUERY = 'DB_QUERY',
  DB_UPDATE = 'DB_UPDATE',
  DB_DELETE = 'DB_DELETE',
  DB_SELECT = 'DB_SELECT',
  DB_COUNT = 'DB_COUNT',
  DB_CLEAR = 'DB_CLEAR',

  // --- FORM VALIDATION ---
  VALIDATE_EMAIL = 'VALIDATE_EMAIL',
  VALIDATE_NUMBER = 'VALIDATE_NUMBER',
  VALIDATE_PASSWORD = 'VALIDATE_PASSWORD',
  VALIDATE_REQUIRED = 'VALIDATE_REQUIRED',
  VALIDATE_LENGTH = 'VALIDATE_LENGTH',

  // --- DEVICE SENSORS ---
  READ_ACCELEROMETER = 'READ_ACCELEROMETER',
  READ_GYROSCOPE = 'READ_GYROSCOPE',
  READ_DEVICE_COMPASS = 'READ_DEVICE_COMPASS',

  // --- PUSH NOTIFICATIONS ---
  PUSH_NOTIFICATION = 'PUSH_NOTIFICATION',

  // --- CUSTOM FONTS ---
  SET_FONT = 'SET_FONT',

  // --- CHART ---
  SET_CHART_DATA = 'SET_CHART_DATA',

  // --- SYSTEM ---
  SLEEP = 'SLEEP',
  LOG_DATA = 'LOG_DATA',
  RESET_BOARD = 'RESET_BOARD',
  CONNECT_WIFI = 'CONNECT_WIFI',
  SEND_HTTP = 'SEND_HTTP',

  // --- HARDWARE: LOGIC ---
  LOGIC_AND = 'LOGIC_AND',
  LOGIC_OR = 'LOGIC_OR',
  LOGIC_NOT = 'LOGIC_NOT',

  // --- MINECRAFT ---
  MC_SET_BLOCK = 'MC_SET_BLOCK',
  MC_REMOVE_BLOCK = 'MC_REMOVE_BLOCK',
  MC_FILL_AREA = 'MC_FILL_AREA',
  MC_SPAWN_ENTITY = 'MC_SPAWN_ENTITY',
  MC_SET_WEATHER = 'MC_SET_WEATHER',
  MC_SET_TIME = 'MC_SET_TIME',
  MC_TELEPORT = 'MC_TELEPORT',
  MC_GIVE_ITEM = 'MC_GIVE_ITEM',
  MC_PLAY_SOUND = 'MC_PLAY_SOUND',
  MC_SHOW_MESSAGE = 'MC_SHOW_MESSAGE',
  MC_CREATE_STRUCTURE = 'MC_CREATE_STRUCTURE',

  READ_FILE = 'READ_FILE',
  READ_I2C = 'READ_I2C',
  WRITE_I2C = 'WRITE_I2C',
  READ_SPI = 'READ_SPI',
  WRITE_SPI = 'WRITE_SPI',
  WRITE_FILE = 'WRITE_FILE',

  // --- COMPONENT OBJECT METHODS ---
  COMP_METHOD = 'COMP_METHOD',
  COMP_GET_PROP = 'COMP_GET_PROP',
  COMP_SET_PROP = 'COMP_SET_PROP',
  COMP_WAIT_EVENT = 'COMP_WAIT_EVENT',
  COMP_IS_READY = 'COMP_IS_READY',

  // --- NEW SENSING ---
  DISTANCE_TO = 'DISTANCE_TO',
  TOUCHING_COLOR = 'TOUCHING_COLOR',
  ASK_AND_WAIT = 'ASK_AND_WAIT',
  ANSWER = 'ANSWER',

  // --- NEW OPERATORS ---
  MATH_OP = 'MATH_OP',
  RANDOM_BETWEEN = 'RANDOM_BETWEEN',
  STRING_CONTAINS = 'STRING_CONTAINS',

  // --- NEW CONTROL ---
  WAIT_UNTIL = 'WAIT_UNTIL',
  WHEN_CLONE_STARTS = 'WHEN_CLONE_STARTS',
  DELETE_THIS_CLONE = 'DELETE_THIS_CLONE',

  // --- NEW GAMEPLAY ---
  SET_GRAVITY_STRENGTH = 'SET_GRAVITY_STRENGTH',
  SET_CAMERA_TARGET = 'SET_CAMERA_TARGET',

  // --- NEW SPRITE FEATURES ---
  SWITCH_COSTUME = 'SWITCH_COSTUME',
  PEN_DOWN = 'PEN_DOWN',
  PEN_UP = 'PEN_UP',
  PEN_CLEAR = 'PEN_CLEAR',
  PEN_COLOR = 'PEN_COLOR',
  SAY_THINK = 'SAY_THINK',
  GHOST_EFFECT = 'GHOST_EFFECT',
  COLOR_EFFECT = 'COLOR_EFFECT',
  SIZE_EFFECT = 'SIZE_EFFECT',

  // --- CAD ---
  CREATE_BOX = 'CREATE_BOX',
  CREATE_CYLINDER = 'CREATE_CYLINDER',
  CREATE_SPHERE = 'CREATE_SPHERE',
  EXTRUDE = 'EXTRUDE',
  REVOLVE = 'REVOLVE',
  SWEEP = 'SWEEP',
  LOFT = 'LOFT',
  BOOLEAN_UNION = 'BOOLEAN_UNION',
  BOOLEAN_SUBTRACT = 'BOOLEAN_SUBTRACT',
  BOOLEAN_INTERSECT = 'BOOLEAN_INTERSECT',
  EXPORT_STL = 'EXPORT_STL',
  CAD_SET_PARAM = 'CAD_SET_PARAM',
}
