import { ComponentSchemaMap } from './types';

export const DISPLAY_COMPONENTS: ComponentSchemaMap = {
  LCD: {
    properties: [
      { name: 'line1', type: 'string', default: '', description: 'Row 0 text (16 chars)' },
      { name: 'line2', type: 'string', default: '', description: 'Row 1 text (16 chars)' },
      { name: 'backlight', type: 'boolean', default: true, description: 'Backlight on/off' },
      { name: 'displayOn', type: 'boolean', default: true, description: 'Display on/off' },
      { name: 'cursorRow', type: 'number', default: 0, min: 0, max: 3, description: 'Cursor row' },
      { name: 'cursorCol', type: 'number', default: 0, min: 0, max: 19, description: 'Cursor column' },
      { name: 'cursorVisible', type: 'boolean', default: true, description: 'Cursor visible' },
      { name: 'cursorBlink', type: 'boolean', default: false, description: 'Cursor blinking' },
      { name: 'autoScroll', type: 'boolean', default: false, description: 'Auto-scroll on write' },
      { name: 'entryMode', type: 'string', default: 'right', description: 'Text direction (left/right)' },
      { name: 'contrast', type: 'number', default: 255, min: 0, max: 255, description: 'LCD contrast' },
    ],
    methods: [
      { name: 'print', description: 'Print text at cursor', params: [{ name: 'text', type: 'string' }] },
      { name: 'printAt', description: 'Print at row,col', params: [{ name: 'row', type: 'number' }, { name: 'col', type: 'number' }, { name: 'text', type: 'string' }] },
      { name: 'printNumber', description: 'Print number', params: [{ name: 'value', type: 'number' }, { name: 'decimals', type: 'number' }] },
      { name: 'printFloat', description: 'Print float', params: [{ name: 'value', type: 'number' }, { name: 'decimals', type: 'number' }] },
      { name: 'printHex', description: 'Print as hex', params: [{ name: 'value', type: 'number' }, { name: 'digits', type: 'number' }] },
      { name: 'printBinary', description: 'Print as binary', params: [{ name: 'value', type: 'number' }, { name: 'digits', type: 'number' }] },
      { name: 'setCursor', description: 'Move cursor', params: [{ name: 'row', type: 'number' }, { name: 'col', type: 'number' }] },
      { name: 'home', description: 'Cursor to 0,0', params: [] },
      { name: 'clear', description: 'Clear display', params: [] },
      { name: 'cursorOn', description: 'Show cursor', params: [] },
      { name: 'cursorOff', description: 'Hide cursor', params: [] },
      { name: 'blinkOn', description: 'Enable blink', params: [] },
      { name: 'blinkOff', description: 'Disable blink', params: [] },
      { name: 'displayOn', description: 'Turn on', params: [] },
      { name: 'displayOff', description: 'Turn off', params: [] },
      { name: 'backlightOn', description: 'Backlight on', params: [] },
      { name: 'backlightOff', description: 'Backlight off', params: [] },
      { name: 'setContrast', description: 'Set contrast', params: [{ name: 'value', type: 'number' }] },
      { name: 'scrollLeft', description: 'Scroll left', params: [] },
      { name: 'scrollRight', description: 'Scroll right', params: [] },
      { name: 'autoScrollOn', description: 'Enable auto-scroll', params: [] },
      { name: 'autoScrollOff', description: 'Disable auto-scroll', params: [] },
      { name: 'leftToRight', description: 'Set LTR', params: [] },
      { name: 'rightToLeft', description: 'Set RTL', params: [] },
      { name: 'createChar', description: 'Define custom char', params: [{ name: 'id', type: 'number' }, { name: 'pattern', type: 'string' }] },
      { name: 'writeCustomChar', description: 'Write custom char', params: [{ name: 'id', type: 'number' }] },
      { name: 'center', description: 'Center text', params: [{ name: 'text', type: 'string' }, { name: 'row', type: 'number' }] },
      { name: 'rightAlign', description: 'Right-align text', params: [{ name: 'text', type: 'string' }, { name: 'row', type: 'number' }] },
      { name: 'progressBar', description: 'Draw progress bar', params: [{ name: 'row', type: 'number' }, { name: 'percent', type: 'number' }, { name: 'width', type: 'number' }] },
      { name: 'marquee', description: 'Scrolling text', params: [{ name: 'text', type: 'string' }, { name: 'row', type: 'number' }, { name: 'offset', type: 'number' }] },
      { name: 'box', description: 'Draw text box', params: [{ name: 'row', type: 'number' }, { name: 'text', type: 'string' }] },
      { name: 'getText', description: 'Get all text', params: [] },
      { name: 'getLine', description: 'Get line text', params: [{ name: 'row', type: 'number' }] },
      { name: 'getCursorPos', description: 'Get cursor position', params: [] },
      { name: 'isBusy', description: 'Check if busy', params: [] },
      { name: 'formatTime', description: 'Format time HH:MM:SS', params: [{ name: 'seconds', type: 'number' }] },
      { name: 'formatTemp', description: 'Format temp °C', params: [{ name: 'celsius', type: 'number' }] },
      { name: 'formatVoltage', description: 'Format voltage V', params: [{ name: 'volts', type: 'number' }] },
      { name: 'formatPercent', description: 'Format percent %', params: [{ name: 'value', type: 'number' }] },
    ],
    events: ['update', 'scroll', 'clear'],
  },
  LCD_2004: {
    properties: [
      { name: 'line1', type: 'string', default: '', description: 'Row 0 text (20 chars)' },
      { name: 'line2', type: 'string', default: '', description: 'Row 1 text (20 chars)' },
      { name: 'line3', type: 'string', default: '', description: 'Row 2 text (20 chars)' },
      { name: 'line4', type: 'string', default: '', description: 'Row 3 text (20 chars)' },
      { name: 'backlight', type: 'boolean', default: true, description: 'Backlight on/off' },
      { name: 'displayOn', type: 'boolean', default: true, description: 'Display on/off' },
      { name: 'cursorRow', type: 'number', default: 0, min: 0, max: 3, description: 'Cursor row' },
      { name: 'cursorCol', type: 'number', default: 0, min: 0, max: 19, description: 'Cursor column' },
      { name: 'cursorVisible', type: 'boolean', default: true, description: 'Cursor visible' },
      { name: 'cursorBlink', type: 'boolean', default: false, description: 'Cursor blinking' },
      { name: 'contrast', type: 'number', default: 255, min: 0, max: 255, description: 'LCD contrast' },
    ],
    methods: [
      { name: 'print', description: 'Print text at cursor', params: [{ name: 'text', type: 'string' }] },
      { name: 'printAt', description: 'Print at row,col', params: [{ name: 'row', type: 'number' }, { name: 'col', type: 'number' }, { name: 'text', type: 'string' }] },
      { name: 'printNumber', description: 'Print number', params: [{ name: 'value', type: 'number' }, { name: 'decimals', type: 'number' }] },
      { name: 'printHex', description: 'Print as hex', params: [{ name: 'value', type: 'number' }] },
      { name: 'setCursor', description: 'Move cursor', params: [{ name: 'row', type: 'number' }, { name: 'col', type: 'number' }] },
      { name: 'home', description: 'Cursor to 0,0', params: [] },
      { name: 'clear', description: 'Clear display', params: [] },
      { name: 'cursorOn', description: 'Show cursor', params: [] },
      { name: 'cursorOff', description: 'Hide cursor', params: [] },
      { name: 'blinkOn', description: 'Enable blink', params: [] },
      { name: 'displayOn', description: 'Turn on', params: [] },
      { name: 'displayOff', description: 'Turn off', params: [] },
      { name: 'backlightOn', description: 'Backlight on', params: [] },
      { name: 'backlightOff', description: 'Backlight off', params: [] },
      { name: 'scrollLeft', description: 'Scroll left', params: [] },
      { name: 'scrollRight', description: 'Scroll right', params: [] },
      { name: 'center', description: 'Center text', params: [{ name: 'text', type: 'string' }, { name: 'row', type: 'number' }] },
      { name: 'progressBar', description: 'Draw progress bar', params: [{ name: 'row', type: 'number' }, { name: 'percent', type: 'number' }] },
      { name: 'formatTime', description: 'Format time HH:MM:SS', params: [{ name: 'seconds', type: 'number' }] },
      { name: 'formatTemp', description: 'Format temp °C', params: [{ name: 'celsius', type: 'number' }] },
      { name: 'getText', description: 'Get all text', params: [] },
      { name: 'getLine', description: 'Get line text', params: [{ name: 'row', type: 'number' }] },
    ],
    events: ['update', 'clear'],
  },
  LCD_12864: {
    properties: [
      { name: 'width', type: 'number', default: 128, description: 'Display width' },
      { name: 'height', type: 'number', default: 64, description: 'Display height' },
      { name: 'backlight', type: 'boolean', default: true, description: 'Backlight on/off' },
      { name: 'displayOn', type: 'boolean', default: true, description: 'Display on/off' },
    ],
    methods: [
      { name: 'clear', description: 'Clear display', params: [] },
      { name: 'print', description: 'Print text', params: [{ name: 'text', type: 'string' }, { name: 'x', type: 'number' }, { name: 'y', type: 'number' }] },
      { name: 'drawLine', description: 'Draw line', params: [{ name: 'x1', type: 'number' }, { name: 'y1', type: 'number' }, { name: 'x2', type: 'number' }, { name: 'y2', type: 'number' }] },
      { name: 'drawRect', description: 'Draw rectangle', params: [{ name: 'x', type: 'number' }, { name: 'y', type: 'number' }, { name: 'w', type: 'number' }, { name: 'h', type: 'number' }] },
      { name: 'drawCircle', description: 'Draw circle', params: [{ name: 'x', type: 'number' }, { name: 'y', type: 'number' }, { name: 'r', type: 'number' }] },
      { name: 'drawPixel', description: 'Draw pixel', params: [{ name: 'x', type: 'number' }, { name: 'y', type: 'number' }] },
      { name: 'fillRect', description: 'Fill rectangle', params: [{ name: 'x', type: 'number' }, { name: 'y', type: 'number' }, { name: 'w', type: 'number' }, { name: 'h', type: 'number' }] },
      { name: 'drawBitmap', description: 'Draw bitmap', params: [{ name: 'x', type: 'number' }, { name: 'y', type: 'number' }, { name: 'data', type: 'string' }] },
      { name: 'setContrast', description: 'Set contrast', params: [{ name: 'value', type: 'number' }] },
      { name: 'backlightOn', description: 'Backlight on', params: [] },
      { name: 'backlightOff', description: 'Backlight off', params: [] },
    ],
    events: ['update'],
  },

  OLED: {
    properties: [
      { name: 'width', type: 'number', default: 128, description: 'Display width' },
      { name: 'height', type: 'number', default: 64, description: 'Display height' },
      { name: 'backlight', type: 'boolean', default: true, description: 'Backlight on/off' },
      { name: 'displayOn', type: 'boolean', default: true, description: 'Display on/off' },
    ],
    methods: [
      { name: 'clear', description: 'Clear display', params: [] },
      { name: 'print', description: 'Print text', params: [{ name: 'text', type: 'string' }, { name: 'x', type: 'number' }, { name: 'y', type: 'number' }] },
      { name: 'drawLine', description: 'Draw line', params: [{ name: 'x1', type: 'number' }, { name: 'y1', type: 'number' }, { name: 'x2', type: 'number' }, { name: 'y2', type: 'number' }] },
      { name: 'drawRect', description: 'Draw rectangle', params: [{ name: 'x', type: 'number' }, { name: 'y', type: 'number' }, { name: 'w', type: 'number' }, { name: 'h', type: 'number' }] },
      { name: 'drawCircle', description: 'Draw circle', params: [{ name: 'x', type: 'number' }, { name: 'y', type: 'number' }, { name: 'r', type: 'number' }] },
      { name: 'drawBitmap', description: 'Draw bitmap', params: [{ name: 'x', type: 'number' }, { name: 'y', type: 'number' }, { name: 'data', type: 'string' }] },
    ],
    events: ['update'],
  },

  SEVEN_SEGMENT: {
    properties: [{ name: 'value', type: 'number', default: 0, min: 0, max: 9, description: 'Display digit' }],
    methods: [{ name: 'display', description: 'Show digit', params: [{ name: 'digit', type: 'number' }] }, { name: 'clear', description: 'Clear display', params: [] }, { name: 'countUp', description: 'Count up from current', params: [{ name: 'to', type: 'number' }, { name: 'delay', type: 'number' }] }],
    events: ['change'],
  },

  MATRIX: {
    properties: [{ name: 'pattern', type: 'string', default: '0000000000000000', description: '16-char binary pattern' }],
    methods: [{ name: 'setRow', description: 'Set row pattern', params: [{ name: 'row', type: 'number' }, { name: 'pattern', type: 'string' }] }, { name: 'clear', description: 'Clear matrix', params: [] }, { name: 'drawPattern', description: 'Set full pattern', params: [{ name: 'pattern', type: 'string' }] }, { name: 'scrollText', description: 'Scroll text', params: [{ name: 'text', type: 'string' }, { name: 'speed', type: 'number' }] }],
    events: ['update'],
  },
};
