import { ComponentSchemaMap } from './types';

export const EXTRA_COMPONENTS: ComponentSchemaMap = {
  // --- MICROCONTROLLERS ---
  ARDUINO_UNO: {
    properties: [
      { name: 'digitalPins', type: 'number', default: 14, description: 'Digital I/O pins' },
      { name: 'analogPins', type: 'number', default: 6, description: 'Analog input pins' },
      { name: 'pwmPins', type: 'number', default: 6, description: 'PWM capable pins' },
      { name: 'voltage', type: 'number', default: 5, unit: 'V', description: 'Operating voltage' },
      { name: 'clockSpeed', type: 'number', default: 16, unit: 'MHz', description: 'Clock speed' },
    ],
    methods: [
      { name: 'digitalWrite', description: 'Write HIGH/LOW to pin', params: [{ name: 'pin', type: 'number' }, { name: 'value', type: 'boolean' }] },
      { name: 'digitalRead', description: 'Read digital pin', params: [{ name: 'pin', type: 'number' }] },
      { name: 'analogRead', description: 'Read analog pin (0-1023)', params: [{ name: 'pin', type: 'number' }] },
      { name: 'analogWrite', description: 'Write PWM (0-255)', params: [{ name: 'pin', type: 'number' }, { name: 'value', type: 'number' }] },
      { name: 'pinMode', description: 'Set pin mode (INPUT/OUTPUT)', params: [{ name: 'pin', type: 'number' }, { name: 'mode', type: 'string' }] },
      { name: 'delay', description: 'Delay in milliseconds', params: [{ name: 'ms', type: 'number' }] },
      { name: 'millis', description: 'Get milliseconds since start', params: [] },
      { name: 'serialPrint', description: 'Print to serial monitor', params: [{ name: 'text', type: 'string' }] },
      { name: 'serialRead', description: 'Read from serial', params: [] },
      { name: 'tone', description: 'Play tone on pin', params: [{ name: 'pin', type: 'number' }, { name: 'frequency', type: 'number' }, { name: 'duration', type: 'number' }] },
      { name: 'noTone', description: 'Stop tone on pin', params: [{ name: 'pin', type: 'number' }] },
      { name: 'attachInterrupt', description: 'Attach interrupt to pin', params: [{ name: 'pin', type: 'number' }, { name: 'mode', type: 'string' }] },
      { name: 'detachInterrupt', description: 'Detach interrupt', params: [{ name: 'pin', type: 'number' }] },
      { name: 'reset', description: 'Reset the board', params: [] },
    ],
    events: ['boot', 'reset', 'interrupt'],
  },
  ARDUINO_NANO: {
    properties: [
      { name: 'digitalPins', type: 'number', default: 14, description: 'Digital I/O pins' },
      { name: 'analogPins', type: 'number', default: 8, description: 'Analog input pins' },
      { name: 'voltage', type: 'number', default: 5, unit: 'V', description: 'Operating voltage' },
    ],
    methods: [
      { name: 'digitalWrite', description: 'Write HIGH/LOW', params: [{ name: 'pin', type: 'number' }, { name: 'value', type: 'boolean' }] },
      { name: 'digitalRead', description: 'Read digital pin', params: [{ name: 'pin', type: 'number' }] },
      { name: 'analogRead', description: 'Read analog pin', params: [{ name: 'pin', type: 'number' }] },
      { name: 'analogWrite', description: 'Write PWM', params: [{ name: 'pin', type: 'number' }, { name: 'value', type: 'number' }] },
      { name: 'delay', description: 'Delay ms', params: [{ name: 'ms', type: 'number' }] },
      { name: 'millis', description: 'Get ms since start', params: [] },
      { name: 'serialPrint', description: 'Print to serial', params: [{ name: 'text', type: 'string' }] },
      { name: 'tone', description: 'Play tone', params: [{ name: 'pin', type: 'number' }, { name: 'frequency', type: 'number' }] },
      { name: 'reset', description: 'Reset board', params: [] },
    ],
    events: ['boot', 'reset'],
  },
  ARDUINO_MEGA: {
    properties: [
      { name: 'digitalPins', type: 'number', default: 54, description: 'Digital I/O pins' },
      { name: 'analogPins', type: 'number', default: 16, description: 'Analog input pins' },
      { name: 'voltage', type: 'number', default: 5, unit: 'V', description: 'Operating voltage' },
      { name: 'flash', type: 'number', default: 256, unit: 'KB', description: 'Flash memory' },
    ],
    methods: [
      { name: 'digitalWrite', description: 'Write HIGH/LOW', params: [{ name: 'pin', type: 'number' }, { name: 'value', type: 'boolean' }] },
      { name: 'digitalRead', description: 'Read digital pin', params: [{ name: 'pin', type: 'number' }] },
      { name: 'analogRead', description: 'Read analog pin', params: [{ name: 'pin', type: 'number' }] },
      { name: 'analogWrite', description: 'Write PWM', params: [{ name: 'pin', type: 'number' }, { name: 'value', type: 'number' }] },
      { name: 'serialPrint', description: 'Print to serial', params: [{ name: 'text', type: 'string' }] },
      { name: 'tone', description: 'Play tone', params: [{ name: 'pin', type: 'number' }, { name: 'frequency', type: 'number' }] },
      { name: 'reset', description: 'Reset board', params: [] },
    ],
    events: ['boot', 'reset'],
  },
  ESP32_DEVKIT: {
    properties: [
      { name: 'digitalPins', type: 'number', default: 34, description: 'GPIO pins' },
      { name: 'analogPins', type: 'number', default: 18, description: 'ADC pins' },
      { name: 'wifi', type: 'boolean', default: false, description: 'WiFi enabled' },
      { name: 'bluetooth', type: 'boolean', default: false, description: 'Bluetooth enabled' },
      { name: 'voltage', type: 'number', default: 3.3, unit: 'V', description: 'Operating voltage' },
      { name: 'cpuSpeed', type: 'number', default: 240, unit: 'MHz', description: 'CPU speed' },
    ],
    methods: [
      { name: 'digitalWrite', description: 'Write HIGH/LOW', params: [{ name: 'pin', type: 'number' }, { name: 'value', type: 'boolean' }] },
      { name: 'digitalRead', description: 'Read digital pin', params: [{ name: 'pin', type: 'number' }] },
      { name: 'analogRead', description: 'Read analog pin', params: [{ name: 'pin', type: 'number' }] },
      { name: 'analogWrite', description: 'Write PWM (0-255)', params: [{ name: 'pin', type: 'number' }, { name: 'value', type: 'number' }] },
      { name: 'touchRead', description: 'Read capacitive touch', params: [{ name: 'pin', type: 'number' }] },
      { name: 'ledcSetup', description: 'Setup LEDC channel', params: [{ name: 'channel', type: 'number' }, { name: 'freq', type: 'number' }, { name: 'resolution', type: 'number' }] },
      { name: 'ledcAttachPin', description: 'Attach pin to LEDC', params: [{ name: 'pin', type: 'number' }, { name: 'channel', type: 'number' }] },
      { name: 'ledcWrite', description: 'Write to LEDC channel', params: [{ name: 'channel', type: 'number' }, { name: 'value', type: 'number' }] },
      { name: 'wifiConnect', description: 'Connect to WiFi', params: [{ name: 'ssid', type: 'string' }, { name: 'password', type: 'string' }] },
      { name: 'bluetoothStart', description: 'Start Bluetooth', params: [{ name: 'name', type: 'string' }] },
      { name: 'serialPrint', description: 'Print to serial', params: [{ name: 'text', type: 'string' }] },
      { name: 'delay', description: 'Delay ms', params: [{ name: 'ms', type: 'number' }] },
      { name: 'deepSleep', description: 'Enter deep sleep', params: [{ name: 'us', type: 'number' }] },
      { name: 'restart', description: 'Restart ESP32', params: [] },
      { name: 'getCpuTemp', description: 'Read CPU temperature', params: [] },
      { name: 'getFreeHeap', description: 'Get free heap memory', params: [] },
    ],
    events: ['boot', 'wifiConnected', 'bluetoothConnected', 'touch'],
  },
  ESP32_CAM: {
    properties: [
      { name: 'resolution', type: 'string', default: 'VGA', description: 'Camera resolution' },
      { name: 'framesize', type: 'number', default: 10, description: 'Frame size enum' },
      { name: 'quality', type: 'number', default: 10, min: 0, max: 63, description: 'JPEG quality' },
    ],
    methods: [
      { name: 'capture', description: 'Capture photo', params: [] },
      { name: 'setResolution', description: 'Set resolution', params: [{ name: 'res', type: 'string' }] },
      { name: 'setQuality', description: 'Set JPEG quality', params: [{ name: 'quality', type: 'number' }] },
      { name: 'streamStart', description: 'Start video stream', params: [] },
      { name: 'streamStop', description: 'Stop video stream', params: [] },
      { name: 'flashOn', description: 'Turn on flash LED', params: [] },
      { name: 'flashOff', description: 'Turn off flash LED', params: [] },
      { name: 'getFrameCount', description: 'Get frames captured', params: [] },
    ],
    events: ['capture', 'stream'],
  },
  ESP8266: {
    properties: [
      { name: 'wifi', type: 'boolean', default: false, description: 'WiFi connected' },
      { name: 'ip', type: 'string', default: '', description: 'IP address' },
      { name: 'voltage', type: 'number', default: 3.3, unit: 'V', description: 'Operating voltage' },
    ],
    methods: [
      { name: 'digitalWrite', description: 'Write HIGH/LOW', params: [{ name: 'pin', type: 'number' }, { name: 'value', type: 'boolean' }] },
      { name: 'digitalRead', description: 'Read digital pin', params: [{ name: 'pin', type: 'number' }] },
      { name: 'analogRead', description: 'Read analog pin', params: [{ name: 'pin', type: 'number' }] },
      { name: 'wifiConnect', description: 'Connect to WiFi', params: [{ name: 'ssid', type: 'string' }, { name: 'password', type: 'string' }] },
      { name: 'httpGet', description: 'HTTP GET request', params: [{ name: 'url', type: 'string' }] },
      { name: 'httpPost', description: 'HTTP POST request', params: [{ name: 'url', type: 'string' }, { name: 'data', type: 'string' }] },
      { name: 'mqttConnect', description: 'Connect to MQTT broker', params: [{ name: 'broker', type: 'string' }, { name: 'port', type: 'number' }] },
      { name: 'mqttPublish', description: 'Publish to MQTT topic', params: [{ name: 'topic', type: 'string' }, { name: 'message', type: 'string' }] },
      { name: 'serialPrint', description: 'Print to serial', params: [{ name: 'text', type: 'string' }] },
      { name: 'reset', description: 'Reset ESP8266', params: [] },
    ],
    events: ['wifiConnected', 'mqttMessage'],
  },
  NODEMCU: {
    properties: [
      { name: 'wifi', type: 'boolean', default: false },
      { name: 'ip', type: 'string', default: '' },
      { name: 'voltage', type: 'number', default: 3.3, unit: 'V' },
    ],
    methods: [
      { name: 'digitalWrite', description: 'Write HIGH/LOW', params: [{ name: 'pin', type: 'number' }, { name: 'value', type: 'boolean' }] },
      { name: 'digitalRead', description: 'Read digital pin', params: [{ name: 'pin', type: 'number' }] },
      { name: 'analogRead', description: 'Read analog pin', params: [{ name: 'pin', type: 'number' }] },
      { name: 'wifiConnect', description: 'Connect WiFi', params: [{ name: 'ssid', type: 'string' }, { name: 'password', type: 'string' }] },
      { name: 'serialPrint', description: 'Print to serial', params: [{ name: 'text', type: 'string' }] },
      { name: 'reset', description: 'Reset', params: [] },
    ],
    events: ['wifiConnected'],
  },
  MICROBIT: {
    properties: [
      { name: 'buttons', type: 'number', default: 2, description: 'Button A and B' },
      { name: 'leds', type: 'number', default: 25, description: '5x5 LED matrix' },
      { name: 'voltage', type: 'number', default: 3, unit: 'V', description: 'Operating voltage' },
    ],
    methods: [
      { name: 'digitalWrite', description: 'Write to pin', params: [{ name: 'pin', type: 'number' }, { name: 'value', type: 'boolean' }] },
      { name: 'digitalRead', description: 'Read from pin', params: [{ name: 'pin', type: 'number' }] },
      { name: 'analogRead', description: 'Read analog', params: [{ name: 'pin', type: 'number' }] },
      { name: 'showString', description: 'Scroll text on LEDs', params: [{ name: 'text', type: 'string' }] },
      { name: 'showIcon', description: 'Show icon on LED matrix', params: [{ name: 'icon', type: 'string' }] },
      { name: 'showLed', description: 'Set single LED', params: [{ name: 'x', type: 'number' }, { name: 'y', type: 'number' }, { name: 'on', type: 'boolean' }] },
      { name: 'clearDisplay', description: 'Clear LED matrix', params: [] },
      { name: 'plot', description: 'Plot on accelerometer', params: [{ name: 'x', type: 'number' }, { name: 'y', type: 'number' }] },
      { name: 'unplot', description: 'Unplot on accelerometer', params: [{ name: 'x', type: 'number' }, { name: 'y', type: 'number' }] },
      { name: 'buttonA', description: 'Is button A pressed?', params: [] },
      { name: 'buttonB', description: 'Is button B pressed?', params: [] },
      { name: 'compassHeading', description: 'Get compass heading', params: [] },
      { name: 'temperature', description: 'Get temperature', params: [] },
      { name: 'accelerometer', description: 'Get accelerometer (x,y,z)', params: [] },
      { name: 'say', description: 'Display text', params: [{ name: 'text', type: 'string' }] },
    ],
    events: ['buttonA', 'buttonB', 'shake', 'tilt'],
  },
  RASPBERRY_PI_4: {
    properties: [
      { name: 'gpioPins', type: 'number', default: 40, description: 'GPIO header pins' },
      { name: 'voltage', type: 'number', default: 3.3, unit: 'V', description: 'GPIO voltage' },
      { name: 'wifi', type: 'boolean', default: false, description: 'WiFi enabled' },
      { name: 'bluetooth', type: 'boolean', default: false, description: 'Bluetooth enabled' },
      { name: 'cpuCores', type: 'number', default: 4, description: 'CPU cores' },
      { name: 'ram', type: 'number', default: 4, unit: 'GB', description: 'RAM' },
    ],
    methods: [
      { name: 'digitalWrite', description: 'Write to GPIO', params: [{ name: 'pin', type: 'number' }, { name: 'value', type: 'boolean' }] },
      { name: 'digitalRead', description: 'Read GPIO', params: [{ name: 'pin', type: 'number' }] },
      { name: 'pwmWrite', description: 'Write PWM', params: [{ name: 'pin', type: 'number' }, { name: 'value', type: 'number' }] },
      { name: 'i2cRead', description: 'Read I2C', params: [{ name: 'address', type: 'number' }, { name: 'register', type: 'number' }] },
      { name: 'i2cWrite', description: 'Write I2C', params: [{ name: 'address', type: 'number' }, { name: 'value', type: 'number' }] },
      { name: 'spiRead', description: 'Read SPI', params: [{ name: 'csPin', type: 'number' }] },
      { name: 'runPython', description: 'Run Python script', params: [{ name: 'script', type: 'string' }] },
      { name: 'shellCommand', description: 'Execute shell command', params: [{ name: 'cmd', type: 'string' }] },
      { name: 'wifiConnect', description: 'Connect WiFi', params: [{ name: 'ssid', type: 'string' }, { name: 'password', type: 'string' }] },
      { name: 'bluetoothStart', description: 'Start Bluetooth', params: [{ name: 'name', type: 'string' }] },
      { name: 'getCpuTemp', description: 'Get CPU temperature', params: [] },
      { name: 'getMemUsage', description: 'Get memory usage', params: [] },
      { name: 'getGpuMem', description: 'Get GPU memory', params: [] },
    ],
    events: ['boot', 'wifiConnected', 'bluetoothConnected'],
  },
  RASPBERRY_PI_ZERO: {
    properties: [
      { name: 'gpioPins', type: 'number', default: 40 },
      { name: 'voltage', type: 'number', default: 3.3, unit: 'V' },
      { name: 'wifi', type: 'boolean', default: false },
    ],
    methods: [
      { name: 'digitalWrite', description: 'Write GPIO', params: [{ name: 'pin', type: 'number' }, { name: 'value', type: 'boolean' }] },
      { name: 'digitalRead', description: 'Read GPIO', params: [{ name: 'pin', type: 'number' }] },
      { name: 'pwmWrite', description: 'Write PWM', params: [{ name: 'pin', type: 'number' }, { name: 'value', type: 'number' }] },
      { name: 'runPython', description: 'Run Python script', params: [{ name: 'script', type: 'string' }] },
      { name: 'wifiConnect', description: 'Connect WiFi', params: [{ name: 'ssid', type: 'string' }, { name: 'password', type: 'string' }] },
    ],
    events: ['boot'],
  },

  // --- PASSIVE COMPONENTS ---
  CAPACITOR_ELEC: {
    properties: [
      { name: 'capacitance', type: 'number', default: 0.0001, unit: 'F', description: 'Capacitance in farads' },
      { name: 'voltage', type: 'number', default: 0, unit: 'V', description: 'Voltage across capacitor' },
      { name: 'charge', type: 'number', default: 0, unit: 'C', description: 'Charge in coulombs' },
      { name: 'isCharged', type: 'boolean', default: false, description: 'Fully charged' },
    ],
    methods: [
      { name: 'charge', description: 'Charge capacitor', params: [{ name: 'voltage', type: 'number' }, { name: 'timeConstant', type: 'number' }] },
      { name: 'discharge', description: 'Discharge capacitor', params: [{ name: 'timeConstant', type: 'number' }] },
      { name: 'getVoltage', description: 'Get current voltage', params: [] },
      { name: 'getTimeConstant', description: 'Get RC time constant', params: [{ name: 'resistance', type: 'number' }] },
      { name: 'getEnergy', description: 'Get stored energy (Joules)', params: [] },
      { name: 'getCharge', description: 'Get charge (Coulombs)', params: [] },
      { name: 'isFullyCharged', description: 'Is charged to 63%?', params: [] },
      { name: 'setCapacitance', description: 'Set capacitance value', params: [{ name: 'farads', type: 'number' }] },
    ],
    events: ['charge', 'discharge'],
  },
  CAPACITOR_CERAMIC: {
    properties: [
      { name: 'capacitance', type: 'number', default: 0.0000001, unit: 'F', description: 'Capacitance' },
      { name: 'voltage', type: 'number', default: 0, unit: 'V', description: 'Voltage across' },
    ],
    methods: [
      { name: 'charge', description: 'Charge', params: [{ name: 'voltage', type: 'number' }, { name: 'timeConstant', type: 'number' }] },
      { name: 'discharge', description: 'Discharge', params: [{ name: 'timeConstant', type: 'number' }] },
      { name: 'getVoltage', description: 'Get voltage', params: [] },
      { name: 'getTimeConstant', description: 'Get RC constant', params: [{ name: 'resistance', type: 'number' }] },
      { name: 'getEnergy', description: 'Get energy (J)', params: [] },
    ],
    events: ['charge', 'discharge'],
  },
  CAPACITOR_TANTALUM: {
    properties: [
      { name: 'capacitance', type: 'number', default: 0.00001, unit: 'F', description: 'Capacitance' },
      { name: 'voltage', type: 'number', default: 0, unit: 'V', description: 'Voltage across' },
      { name: 'esr', type: 'number', default: 0.08, unit: 'Ω', description: 'Equivalent series resistance' },
    ],
    methods: [
      { name: 'charge', description: 'Charge', params: [{ name: 'voltage', type: 'number' }, { name: 'timeConstant', type: 'number' }] },
      { name: 'discharge', description: 'Discharge', params: [{ name: 'timeConstant', type: 'number' }] },
      { name: 'getVoltage', description: 'Get voltage', params: [] },
      { name: 'getESR', description: 'Get ESR', params: [] },
      { name: 'getEnergy', description: 'Get energy (J)', params: [] },
    ],
    events: ['charge', 'discharge'],
  },

  // --- DIODES ---
  DIODE: {
    properties: [
      { name: 'forwardVoltage', type: 'number', default: 0.7, unit: 'V', description: 'Forward voltage drop' },
      { name: 'isForwardBiased', type: 'boolean', default: false, description: 'Conducting current' },
      { name: 'current', type: 'number', default: 0, unit: 'A', description: 'Current through diode' },
    ],
    methods: [
      { name: 'isForward', description: 'Is forward biased?', params: [] },
      { name: 'isReverse', description: 'Is reverse biased?', params: [] },
      { name: 'getForwardVoltage', description: 'Get Vf', params: [] },
      { name: 'getCurrent', description: 'Get current', params: [] },
      { name: 'getPower', description: 'Get power dissipation', params: [] },
      { name: 'setForwardVoltage', description: 'Set Vf', params: [{ name: 'volts', type: 'number' }] },
    ],
    events: ['forward', 'reverse'],
  },
  DIODE_SCHOTTKY: {
    properties: [
      { name: 'forwardVoltage', type: 'number', default: 0.3, unit: 'V', description: 'Low forward voltage' },
      { name: 'isForwardBiased', type: 'boolean', default: false },
      { name: 'current', type: 'number', default: 0, unit: 'A' },
    ],
    methods: [
      { name: 'isForward', description: 'Is forward biased?', params: [] },
      { name: 'isReverse', description: 'Is reverse biased?', params: [] },
      { name: 'getForwardVoltage', description: 'Get Vf (0.3V typical)', params: [] },
      { name: 'getCurrent', description: 'Get current', params: [] },
      { name: 'getRecoveryTime', description: 'Get reverse recovery time', params: [] },
    ],
    events: ['forward', 'reverse'],
  },
  DIODE_ZENER: {
    properties: [
      { name: 'zenerVoltage', type: 'number', default: 5.1, unit: 'V', description: 'Zener breakdown voltage' },
      { name: 'forwardVoltage', type: 'number', default: 0.7, unit: 'V', description: 'Forward voltage' },
      { name: 'isRegulating', type: 'boolean', default: false, description: 'Regulating voltage' },
      { name: 'current', type: 'number', default: 0, unit: 'A' },
    ],
    methods: [
      { name: 'isForward', description: 'Is forward biased?', params: [] },
      { name: 'isReverse', description: 'Is reverse biased?', params: [] },
      { name: 'isRegulating', description: 'Is zener regulating?', params: [] },
      { name: 'getZenerVoltage', description: 'Get breakdown voltage', params: [] },
      { name: 'getCurrent', description: 'Get current', params: [] },
      { name: 'setZenerVoltage', description: 'Set zener voltage', params: [{ name: 'volts', type: 'number' }] },
    ],
    events: ['forward', 'reverse', 'breakdown'],
  },

  // --- TRANSISTORS ---
  TRANSISTOR_NPN: {
    properties: [
      { name: 'baseCurrent', type: 'number', default: 0, unit: 'mA', description: 'Base current' },
      { name: 'collectorCurrent', type: 'number', default: 0, unit: 'mA', description: 'Collector current' },
      { name: 'isSaturated', type: 'boolean', default: false, description: 'Fully on' },
      { name: 'gain', type: 'number', default: 200, description: 'Current gain (hFE)' },
      { name: 'baseVoltage', type: 'number', default: 0, unit: 'V', description: 'Base-emitter voltage' },
    ],
    methods: [
      { name: 'switchOn', description: 'Turn transistor ON', params: [{ name: 'baseCurrent', type: 'number' }] },
      { name: 'switchOff', description: 'Turn transistor OFF', params: [] },
      { name: 'isOn', description: 'Is transistor conducting?', params: [] },
      { name: 'isSaturated', description: 'Is fully saturated?', params: [] },
      { name: 'getCollectorCurrent', description: 'Get Ic', params: [] },
      { name: 'getGain', description: 'Get hFE', params: [] },
      { name: 'getPower', description: 'Get power dissipation', params: [] },
      { name: 'setGain', description: 'Set hFE value', params: [{ name: 'hfe', type: 'number' }] },
    ],
    events: ['on', 'off'],
  },
  TRANSISTOR_PNP: {
    properties: [
      { name: 'baseCurrent', type: 'number', default: 0, unit: 'mA' },
      { name: 'collectorCurrent', type: 'number', default: 0, unit: 'mA' },
      { name: 'isSaturated', type: 'boolean', default: false },
      { name: 'gain', type: 'number', default: 200 },
    ],
    methods: [
      { name: 'switchOn', description: 'Turn ON (base LOW)', params: [{ name: 'baseCurrent', type: 'number' }] },
      { name: 'switchOff', description: 'Turn OFF', params: [] },
      { name: 'isOn', description: 'Is conducting?', params: [] },
      { name: 'getCollectorCurrent', description: 'Get Ic', params: [] },
      { name: 'getGain', description: 'Get hFE', params: [] },
    ],
    events: ['on', 'off'],
  },
  MOSFET_N: {
    properties: [
      { name: 'gateVoltage', type: 'number', default: 0, unit: 'V', description: 'Gate-source voltage' },
      { name: 'drainCurrent', type: 'number', default: 0, unit: 'A', description: 'Drain current' },
      { name: 'isOn', type: 'boolean', default: false, description: 'Channel conducting' },
      { name: 'thresholdVoltage', type: 'number', default: 2, unit: 'V', description: 'Vgs threshold' },
      { name: 'rdsOn', type: 'number', default: 0.1, unit: 'Ω', description: 'On-resistance' },
    ],
    methods: [
      { name: 'switchOn', description: 'Turn ON (Vgs > threshold)', params: [{ name: 'gateVoltage', type: 'number' }] },
      { name: 'switchOff', description: 'Turn OFF', params: [] },
      { name: 'isOn', description: 'Is channel conducting?', params: [] },
      { name: 'getDrainCurrent', description: 'Get Id', params: [] },
      { name: 'getPower', description: 'Get power dissipation', params: [] },
      { name: 'setThreshold', description: 'Set threshold voltage', params: [{ name: 'volts', type: 'number' }] },
    ],
    events: ['on', 'off'],
  },
  MOSFET_P: {
    properties: [
      { name: 'gateVoltage', type: 'number', default: 0, unit: 'V' },
      { name: 'drainCurrent', type: 'number', default: 0, unit: 'A' },
      { name: 'isOn', type: 'boolean', default: false },
      { name: 'thresholdVoltage', type: 'number', default: -2, unit: 'V' },
    ],
    methods: [
      { name: 'switchOn', description: 'Turn ON (Vgs < threshold)', params: [{ name: 'gateVoltage', type: 'number' }] },
      { name: 'switchOff', description: 'Turn OFF', params: [] },
      { name: 'isOn', description: 'Is conducting?', params: [] },
      { name: 'getDrainCurrent', description: 'Get Id', params: [] },
    ],
    events: ['on', 'off'],
  },

  // --- VOLTAGE REGULATORS ---
  VREG_7805: {
    properties: [
      { name: 'inputVoltage', type: 'number', default: 9, unit: 'V', description: 'Input voltage' },
      { name: 'outputVoltage', type: 'number', default: 5, unit: 'V', description: 'Regulated output' },
      { name: 'dropoutVoltage', type: 'number', default: 2, unit: 'V', description: 'Minimum input-output difference' },
      { name: 'outputCurrent', type: 'number', default: 0, unit: 'A', description: 'Output current' },
      { name: 'thermalShutdown', type: 'boolean', default: false, description: 'Thermal protection active' },
    ],
    methods: [
      { name: 'getOutputVoltage', description: 'Get regulated 5V output', params: [] },
      { name: 'getInputVoltage', description: 'Get input voltage', params: [] },
      { name: 'getOutputCurrent', description: 'Get output current', params: [] },
      { name: 'getPowerDissipation', description: 'Get power wasted as heat', params: [] },
      { name: 'getEfficiency', description: 'Get efficiency %', params: [] },
      { name: 'isThermalShutdown', description: 'Is thermal protection on?', params: [] },
      { name: 'isInputValid', description: 'Is input >= 7V?', params: [] },
      { name: 'getTemperature', description: 'Get junction temperature', params: [] },
    ],
    events: ['thermalShutdown'],
  },
  VREG_317: {
    properties: [
      { name: 'outputVoltage', type: 'number', default: 3.3, unit: 'V', description: 'Adjusted output voltage' },
      { name: 'adjResistor', type: 'number', default: 1000, unit: 'Ω', description: 'R1 resistor value' },
      { name: 'setResistor', type: 'number', default: 2000, unit: 'Ω', description: 'R2 resistor value' },
    ],
    methods: [
      { name: 'getOutputVoltage', description: 'Get output: 1.25 × (1 + R2/R1)', params: [] },
      { name: 'setOutputVoltage', description: 'Set desired output voltage', params: [{ name: 'volts', type: 'number' }] },
      { name: 'calculateResistors', description: 'Calculate R1/R2 for target voltage', params: [{ name: 'targetV', type: 'number' }] },
      { name: 'getOutputCurrent', description: 'Get output current', params: [] },
      { name: 'getEfficiency', description: 'Get efficiency %', params: [] },
    ],
    events: ['voltageChange'],
  },
  VREG_LDO: {
    properties: [
      { name: 'inputVoltage', type: 'number', default: 5, unit: 'V', description: 'Input voltage' },
      { name: 'outputVoltage', type: 'number', default: 3.3, unit: 'V', description: 'Output voltage' },
      { name: 'dropoutVoltage', type: 'number', default: 0.3, unit: 'V', description: 'Low dropout voltage' },
      { name: 'quiescentCurrent', type: 'number', default: 0.00005, unit: 'A', description: 'Standby current' },
    ],
    methods: [
      { name: 'getOutputVoltage', description: 'Get regulated output', params: [] },
      { name: 'getDropoutVoltage', description: 'Get dropout voltage', params: [] },
      { name: 'isInputValid', description: 'Is input >= output + dropout?', params: [] },
      { name: 'getEfficiency', description: 'Get efficiency %', params: [] },
      { name: 'getQuiescentCurrent', description: 'Get standby current', params: [] },
    ],
    events: ['voltageChange'],
  },

  // --- OP-AMPS ---
  OPAMP_358: {
    properties: [
      { name: 'positiveInput', type: 'number', default: 0, unit: 'V', description: 'Non-inverting input' },
      { name: 'negativeInput', type: 'number', default: 0, unit: 'V', description: 'Inverting input' },
      { name: 'output', type: 'number', default: 0, unit: 'V', description: 'Output voltage' },
      { name: 'gain', type: 'number', default: 100000, description: 'Open-loop gain' },
      { name: 'supplyVoltage', type: 'number', default: 5, unit: 'V', description: 'Supply voltage' },
    ],
    methods: [
      { name: 'amplify', description: 'Non-inverting amplifier', params: [{ name: 'input', type: 'number' }, { name: 'gain', type: 'number' }] },
      { name: 'invertingAmplify', description: 'Inverting amplifier', params: [{ name: 'input', type: 'number' }, { name: 'gain', type: 'number' }] },
      { name: 'voltageFollower', description: 'Buffer (gain=1)', params: [{ name: 'input', type: 'number' }] },
      { name: 'comparator', description: 'Compare two voltages', params: [{ name: 'positive', type: 'number' }, { name: 'negative', type: 'number' }] },
      { name: 'summingAmplifier', description: 'Sum multiple inputs', params: [{ name: 'inputs', type: 'string' }, { name: 'gain', type: 'number' }] },
      { name: 'getOutput', description: 'Get output voltage', params: [] },
      { name: 'setGain', description: 'Set closed-loop gain', params: [{ name: 'gain', type: 'number' }] },
    ],
    events: ['outputChange'],
  },
  OPAMP_072: {
    properties: [
      { name: 'positiveInput', type: 'number', default: 0, unit: 'V' },
      { name: 'negativeInput', type: 'number', default: 0, unit: 'V' },
      { name: 'output', type: 'number', default: 0, unit: 'V' },
      { name: 'gain', type: 'number', default: 200000, description: 'Open-loop gain' },
      { name: 'inputImpedance', type: 'number', default: 1000000000, unit: 'Ω', description: 'Very high input impedance' },
    ],
    methods: [
      { name: 'amplify', description: 'Non-inverting amplifier', params: [{ name: 'input', type: 'number' }, { name: 'gain', type: 'number' }] },
      { name: 'invertingAmplify', description: 'Inverting amplifier', params: [{ name: 'input', type: 'number' }, { name: 'gain', type: 'number' }] },
      { name: 'voltageFollower', description: 'Buffer', params: [{ name: 'input', type: 'number' }] },
      { name: 'comparator', description: 'Compare voltages', params: [{ name: 'positive', type: 'number' }, { name: 'negative', type: 'number' }] },
      { name: 'getOutput', description: 'Get output', params: [] },
      { name: 'getInputImpedance', description: 'Get input impedance', params: [] },
      { name: 'getNoiseLevel', description: 'Get noise level', params: [] },
    ],
    events: ['outputChange'],
  },

  // --- 555 TIMER (extended) ---
  '555_TIMER_EXT': {
    properties: [
      { name: 'frequency', type: 'number', default: 1, unit: 'Hz', description: 'Oscillation frequency' },
      { name: 'dutyCycle', type: 'number', default: 50, unit: '%', description: 'Duty cycle' },
      { name: 'output', type: 'boolean', default: false, description: 'Timer output state' },
      { name: 'mode', type: 'string', default: 'astable', description: 'Monostable/Astable/Bistable' },
      { name: 'period', type: 'number', default: 1, unit: 's', description: 'Period in seconds' },
    ],
    methods: [
      { name: 'start', description: 'Start oscillator', params: [] },
      { name: 'stop', description: 'Stop oscillator', params: [] },
      { name: 'setFrequency', description: 'Set frequency', params: [{ name: 'hz', type: 'number' }] },
      { name: 'setDutyCycle', description: 'Set duty cycle', params: [{ name: 'percent', type: 'number' }] },
      { name: 'setMode', description: 'Set mode (astable/monostable/bistable)', params: [{ name: 'mode', type: 'string' }] },
      { name: 'pulse', description: 'Send single pulse', params: [{ name: 'duration', type: 'number' }] },
      { name: 'getOutput', description: 'Get output state', params: [] },
      { name: 'getFrequency', description: 'Get frequency', params: [] },
      { name: 'getPeriod', description: 'Get period', params: [] },
      { name: 'calculateRC', description: 'Calculate R and C for frequency', params: [{ name: 'hz', type: 'number' }] },
    ],
    events: ['tick', 'pulse'],
  },

  // --- MORE DISPLAYS ---
  EINK: {
    properties: [
      { name: 'width', type: 'number', default: 296, description: 'Display width' },
      { name: 'height', type: 'number', default: 128, description: 'Display height' },
      { name: 'isUpdating', type: 'boolean', default: false, description: 'Screen refreshing' },
      { name: 'refreshTime', type: 'number', default: 2000, unit: 'ms', description: 'Refresh time' },
    ],
    methods: [
      { name: 'clear', description: 'Clear display', params: [] },
      { name: 'display', description: 'Refresh display', params: [] },
      { name: 'print', description: 'Print text', params: [{ name: 'text', type: 'string' }, { name: 'x', type: 'number' }, { name: 'y', type: 'number' }] },
      { name: 'drawLine', description: 'Draw line', params: [{ name: 'x1', type: 'number' }, { name: 'y1', type: 'number' }, { name: 'x2', type: 'number' }, { name: 'y2', type: 'number' }] },
      { name: 'drawRect', description: 'Draw rectangle', params: [{ name: 'x', type: 'number' }, { name: 'y', type: 'number' }, { name: 'w', type: 'number' }, { name: 'h', type: 'number' }] },
      { name: 'drawBitmap', description: 'Draw bitmap', params: [{ name: 'x', type: 'number' }, { name: 'y', type: 'number' }, { name: 'data', type: 'string' }] },
      { name: 'setRotation', description: 'Set display rotation', params: [{ name: 'degrees', type: 'number' }] },
      { name: 'partialRefresh', description: 'Fast partial refresh', params: [] },
      { name: 'fullRefresh', description: 'Full screen refresh', params: [] },
      { name: 'sleep', description: 'Enter deep sleep', params: [] },
      { name: 'wake', description: 'Wake from sleep', params: [] },
    ],
    events: ['refresh', 'sleep', 'wake'],
  },
  NEOPIXEL_RING: {
    properties: [
      { name: 'numLeds', type: 'number', default: 12, description: 'Number of LEDs' },
      { name: 'brightness', type: 'number', default: 50, min: 0, max: 255, description: 'Global brightness' },
      { name: 'color', type: 'color', default: '#FF0000', description: 'All LEDs color' },
    ],
    methods: [
      { name: 'setColor', description: 'Set all LEDs to color', params: [{ name: 'color', type: 'string' }] },
      { name: 'setLed', description: 'Set individual LED', params: [{ name: 'led', type: 'number' }, { name: 'color', type: 'string' }] },
      { name: 'setBrightness', description: 'Set brightness', params: [{ name: 'level', type: 'number' }] },
      { name: 'rainbow', description: 'Show rainbow', params: [{ name: 'speed', type: 'number' }] },
      { name: 'chase', description: 'Chase animation', params: [{ name: 'color', type: 'string' }, { name: 'speed', type: 'number' }] },
      { name: 'pulse', description: 'Pulse brightness', params: [{ name: 'color', type: 'string' }, { name: 'speed', type: 'number' }] },
      { name: 'clear', description: 'Turn off all LEDs', params: [] },
      { name: 'show', description: 'Update display', params: [] },
      { name: 'fade', description: 'Fade between colors', params: [{ name: 'from', type: 'string' }, { name: 'to', type: 'string' }, { name: 'duration', type: 'number' }] },
    ],
    events: ['colorChange'],
  },
  TM1637: {
    properties: [
      { name: 'digit1', type: 'number', default: 0, min: 0, max: 9, description: 'Digit 1' },
      { name: 'digit2', type: 'number', default: 0, min: 0, max: 9, description: 'Digit 2' },
      { name: 'digit3', type: 'number', default: 0, min: 0, max: 9, description: 'Digit 3' },
      { name: 'digit4', type: 'number', default: 0, min: 0, max: 9, description: 'Digit 4' },
      { name: 'colon', type: 'boolean', default: false, description: 'Colon on/off' },
      { name: 'brightness', type: 'number', default: 7, min: 0, max: 7, description: 'Display brightness' },
    ],
    methods: [
      { name: 'display', description: 'Display number', params: [{ name: 'number', type: 'number' }] },
      { name: 'displayColon', description: 'Display with colon', params: [{ name: 'hours', type: 'number' }, { name: 'minutes', type: 'number' }] },
      { name: 'setBrightness', description: 'Set brightness (0-7)', params: [{ name: 'level', type: 'number' }] },
      { name: 'clear', description: 'Clear display', params: [] },
      { name: 'showDigit', description: 'Show single digit at position', params: [{ name: 'pos', type: 'number' }, { name: 'digit', type: 'number' }] },
      { name: 'scrollText', description: 'Scroll text across display', params: [{ name: 'text', type: 'string' }, { name: 'speed', type: 'number' }] },
      { name: 'countUp', description: 'Count up animation', params: [{ name: 'from', type: 'number' }, { name: 'to', type: 'number' }, { name: 'delay', type: 'number' }] },
      { name: 'blinkColon', description: 'Blink colon', params: [{ name: 'times', type: 'number' }] },
    ],
    events: ['update'],
  },
  MAX7219: {
    properties: [
      { name: 'brightness', type: 'number', default: 8, min: 0, max: 15, description: 'Display brightness' },
      { name: 'scanLimit', type: 'number', default: 7, min: 0, max: 7, description: 'Number of digits' },
      { name: 'pattern', type: 'string', default: '0000000000000000', description: '8x8 LED pattern' },
    ],
    methods: [
      { name: 'setLed', description: 'Set single LED', params: [{ name: 'row', type: 'number' }, { name: 'col', type: 'number' }, { name: 'on', type: 'boolean' }] },
      { name: 'setRow', description: 'Set row pattern', params: [{ name: 'row', type: 'number' }, { name: 'pattern', type: 'string' }] },
      { name: 'setColumn', description: 'Set column pattern', params: [{ name: 'col', type: 'number' }, { name: 'pattern', type: 'string' }] },
      { name: 'clear', description: 'Clear display', params: [] },
      { name: 'setBrightness', description: 'Set brightness', params: [{ name: 'level', type: 'number' }] },
      { name: 'setScanLimit', description: 'Set scan limit', params: [{ name: 'limit', type: 'number' }] },
      { name: 'drawBitmap', description: 'Draw 8x8 bitmap', params: [{ name: 'data', type: 'string' }] },
      { name: 'scrollText', description: 'Scroll text', params: [{ name: 'text', type: 'string' }, { name: 'speed', type: 'number' }] },
      { name: 'invert', description: 'Invert display', params: [] },
    ],
    events: ['update'],
  },
  RGB_STRIP: {
    properties: [
      { name: 'numLeds', type: 'number', default: 8, description: 'Number of LEDs' },
      { name: 'brightness', type: 'number', default: 50, min: 0, max: 255 },
      { name: 'color', type: 'color', default: '#FF0000' },
    ],
    methods: [
      { name: 'setColor', description: 'Set all to color', params: [{ name: 'color', type: 'string' }] },
      { name: 'setLed', description: 'Set individual LED', params: [{ name: 'led', type: 'number' }, { name: 'color', type: 'string' }] },
      { name: 'setBrightness', description: 'Set brightness', params: [{ name: 'level', type: 'number' }] },
      { name: 'rainbow', description: 'Show rainbow', params: [{ name: 'speed', type: 'number' }] },
      { name: 'chase', description: 'Chase pattern', params: [{ name: 'color', type: 'string' }, { name: 'speed', type: 'number' }] },
      { name: 'clear', description: 'Turn off all', params: [] },
    ],
    events: ['colorChange'],
  },

  // --- TOOLS ---
  MULTIMETER: {
    properties: [
      { name: 'mode', type: 'string', default: 'voltage', description: 'Measurement mode' },
      { name: 'voltage', type: 'number', default: 0, unit: 'V', description: 'Voltage reading' },
      { name: 'current', type: 'number', default: 0, unit: 'mA', description: 'Current reading' },
      { name: 'resistance', type: 'number', default: 0, unit: 'Ω', description: 'Resistance reading' },
      { name: 'continuity', type: 'boolean', default: false, description: 'Continuity test' },
    ],
    methods: [
      { name: 'measureVoltage', description: 'Measure voltage', params: [{ name: 'pointA', type: 'number' }, { name: 'pointB', type: 'number' }] },
      { name: 'measureCurrent', description: 'Measure current in series', params: [{ name: 'pointA', type: 'number' }, { name: 'pointB', type: 'number' }] },
      { name: 'measureResistance', description: 'Measure resistance', params: [{ name: 'pointA', type: 'number' }, { name: 'pointB', type: 'number' }] },
      { name: 'testContinuity', description: 'Test continuity', params: [{ name: 'pointA', type: 'number' }, { name: 'pointB', type: 'number' }] },
      { name: 'setMode', description: 'Set measurement mode', params: [{ name: 'mode', type: 'string' }] },
      { name: 'getReading', description: 'Get current reading', params: [] },
      { name: 'getMode', description: 'Get current mode', params: [] },
    ],
    events: ['reading'],
  },
  OSCILLOSCOPE: {
    properties: [
      { name: 'timebase', type: 'number', default: 1, unit: 'ms/div', description: 'Time per division' },
      { name: 'voltageScale', type: 'number', default: 1, unit: 'V/div', description: 'Voltage per division' },
      { name: 'triggerLevel', type: 'number', default: 2.5, unit: 'V', description: 'Trigger voltage' },
      { name: 'channel', type: 'number', default: 1, description: 'Active channel' },
    ],
    methods: [
      { name: 'setTimebase', description: 'Set timebase', params: [{ name: 'msPerDiv', type: 'number' }] },
      { name: 'setVoltageScale', description: 'Set voltage scale', params: [{ name: 'voltsPerDiv', type: 'number' }] },
      { name: 'setTrigger', description: 'Set trigger level', params: [{ name: 'volts', type: 'number' }] },
      { name: 'setChannel', description: 'Select channel', params: [{ name: 'ch', type: 'number' }] },
      { name: 'capture', description: 'Capture waveform', params: [{ name: 'pin', type: 'number' }] },
      { name: 'measureFrequency', description: 'Measure frequency', params: [{ name: 'pin', type: 'number' }] },
      { name: 'measureDutyCycle', description: 'Measure duty cycle', params: [{ name: 'pin', type: 'number' }] },
      { name: 'measureVpp', description: 'Measure peak-to-peak voltage', params: [{ name: 'pin', type: 'number' }] },
      { name: 'measureVrms', description: 'Measure RMS voltage', params: [{ name: 'pin', type: 'number' }] },
    ],
    events: ['capture', 'trigger'],
  },

  // --- MISC ---
  LED_INFRARED: {
    properties: [
      { name: 'on', type: 'boolean', default: false },
      { name: 'wavelength', type: 'number', default: 940, unit: 'nm', description: 'IR wavelength' },
      { name: 'forwardVoltage', type: 'number', default: 1.3, unit: 'V' },
    ],
    methods: [
      { name: 'turnOn', description: 'Turn on IR LED', params: [] },
      { name: 'turnOff', description: 'Turn off IR LED', params: [] },
      { name: 'pulse', description: 'Send IR pulse', params: [{ name: 'protocol', type: 'string' }, { name: 'code', type: 'number' }] },
      { name: 'sendNEC', description: 'Send NEC protocol code', params: [{ name: 'code', type: 'number' }] },
      { name: 'getWavelength', description: 'Get wavelength', params: [] },
    ],
    events: ['on', 'off', 'pulse'],
  },
  LASER_DIODE: {
    properties: [
      { name: 'on', type: 'boolean', default: false },
      { name: 'power', type: 'number', default: 5, unit: 'mW', description: 'Laser power' },
      { name: 'wavelength', type: 'number', default: 650, unit: 'nm', description: 'Wavelength (red)' },
      { name: 'class', type: 'string', default: '3R', description: 'Laser safety class' },
    ],
    methods: [
      { name: 'turnOn', description: 'Turn on laser', params: [] },
      { name: 'turnOff', description: 'Turn off laser', params: [] },
      { name: 'pulse', description: 'Pulse laser', params: [{ name: 'duration', type: 'number' }] },
      { name: 'setPower', description: 'Set power level', params: [{ name: 'mw', type: 'number' }] },
      { name: 'getWavelength', description: 'Get wavelength', params: [] },
    ],
    events: ['on', 'off'],
  },
  SERVO_CONTINUOUS: {
    properties: [
      { name: 'speed', type: 'number', default: 0, min: -100, max: 100, unit: '%', description: 'Rotation speed (-100=CCW, 0=stop, 100=CW)' },
      { name: 'isRunning', type: 'boolean', default: false, description: 'Motor running' },
      { name: 'direction', type: 'string', default: 'stop', description: 'cw/ccw/stop' },
    ],
    methods: [
      { name: 'setSpeed', description: 'Set rotation speed', params: [{ name: 'speed', type: 'number' }] },
      { name: 'forward', description: 'Run clockwise', params: [{ name: 'speed', type: 'number' }] },
      { name: 'reverse', description: 'Run counter-clockwise', params: [{ name: 'speed', type: 'number' }] },
      { name: 'stop', description: 'Stop rotation', params: [] },
      { name: 'getSpeed', description: 'Get current speed', params: [] },
    ],
    events: ['speedChange', 'start', 'stop'],
  },
  SWITCH_ROTARY: {
    properties: [
      { name: 'position', type: 'number', default: 0, min: 0, max: 7, description: 'Current position (0-7)' },
      { name: 'totalPositions', type: 'number', default: 8, description: 'Number of positions' },
    ],
    methods: [
      { name: 'getPosition', description: 'Get current position', params: [] },
      { name: 'setPosition', description: 'Set position', params: [{ name: 'pos', type: 'number' }] },
      { name: 'next', description: 'Move to next position', params: [] },
      { name: 'previous', description: 'Move to previous position', params: [] },
      { name: 'getTotalPositions', description: 'Get total positions', params: [] },
    ],
    events: ['positionChange'],
  },
  WIRE_SPOOL: {
    properties: [
      { name: 'length', type: 'number', default: 1, unit: 'm', description: 'Wire length' },
      { name: 'gauge', type: 'number', default: 22, description: 'AWG wire gauge' },
      { name: 'color', type: 'color', default: '#ef4444', description: 'Wire color' },
      { name: 'resistance', type: 'number', default: 0.05, unit: 'Ω/m', description: 'Resistance per meter' },
    ],
    methods: [
      { name: 'getColor', description: 'Get wire color', params: [] },
      { name: 'setColor', description: 'Set wire color', params: [{ name: 'color', type: 'string' }] },
      { name: 'getResistance', description: 'Get resistance', params: [] },
      { name: 'getVoltageDrop', description: 'Calculate voltage drop', params: [{ name: 'current', type: 'number' }] },
      { name: 'getMaxCurrent', description: 'Get max safe current', params: [] },
      { name: 'getLength', description: 'Get length', params: [] },
    ],
    events: [],
  },
  MOTOR_SOL: {
    properties: [
      { name: 'active', type: 'boolean', default: false },
      { name: 'force', type: 'number', default: 5, unit: 'N', description: 'Pull force' },
    ],
    methods: [
      { name: 'activate', description: 'Extend solenoid', params: [] },
      { name: 'deactivate', description: 'Retract solenoid', params: [] },
      { name: 'pulse', description: 'Quick pulse', params: [{ name: 'duration', type: 'number' }] },
      { name: 'getForce', description: 'Get pull force', params: [] },
    ],
    events: ['activate', 'deactivate'],
  },
  MOTOR_STEPPER: {
    properties: [
      { name: 'position', type: 'number', default: 0, unit: 'steps', description: 'Current position' },
      { name: 'speed', type: 'number', default: 100, unit: 'RPM', description: 'Rotation speed' },
      { name: 'stepAngle', type: 'number', default: 1.8, unit: '°', description: 'Step angle' },
    ],
    methods: [
      { name: 'step', description: 'Move N steps', params: [{ name: 'steps', type: 'number' }] },
      { name: 'rotate', description: 'Rotate N degrees', params: [{ name: 'degrees', type: 'number' }] },
      { name: 'home', description: 'Return home', params: [] },
      { name: 'setSpeed', description: 'Set RPM', params: [{ name: 'rpm', type: 'number' }] },
      { name: 'getPosition', description: 'Get position', params: [] },
      { name: 'getSpeed', description: 'Get speed', params: [] },
    ],
    events: ['move', 'home'],
  },

  KEYPAD_MATRIX: {
    properties: [
      { name: 'lastKey', type: 'string', default: '', description: 'Last key pressed' },
      { name: 'keyPressed', type: 'boolean', default: false, description: 'Key currently pressed' },
      { name: 'matrix', type: 'string', default: '4x4', description: 'Matrix size' },
    ],
    methods: [
      { name: 'getKey', description: 'Read key press (returns key label)', params: [] },
      { name: 'waitKey', description: 'Wait for any key press', params: [] },
      { name: 'readMatrix', description: 'Read entire matrix state', params: [] },
      { name: 'isKeyPressed', description: 'Is specific key pressed?', params: [{ name: 'key', type: 'string' }] },
      { name: 'getDebounced', description: 'Get debounced key press', params: [] },
      { name: 'setMatrix', description: 'Set matrix size (3x4/4x4)', params: [{ name: 'size', type: 'string' }] },
    ],
    events: ['keypress', 'release'],
  },

  RTC: {
    properties: [
      { name: 'seconds', type: 'number', default: 0, min: 0, max: 59, description: 'Seconds' },
      { name: 'minutes', type: 'number', default: 0, min: 0, max: 59, description: 'Minutes' },
      { name: 'hours', type: 'number', default: 0, min: 0, max: 23, description: 'Hours (24h)' },
      { name: 'day', type: 'number', default: 1, min: 1, max: 31, description: 'Day of month' },
      { name: 'month', type: 'number', default: 1, min: 1, max: 12, description: 'Month' },
      { name: 'year', type: 'number', default: 2026, description: 'Year' },
      { name: 'dayOfWeek', type: 'number', default: 0, min: 0, max: 6, description: 'Day of week (0=Sun)' },
      { name: 'unixTimestamp', type: 'number', default: 0, description: 'Unix timestamp' },
      { name: 'batteryLevel', type: 'number', default: 100, min: 0, max: 100, unit: '%', description: 'Backup battery level' },
    ],
    methods: [
      { name: 'getTime', description: 'Get current time as HH:MM:SS', params: [] },
      { name: 'getDate', description: 'Get date as YYYY-MM-DD', params: [] },
      { name: 'getDateTime', description: 'Get full datetime', params: [] },
      { name: 'setTime', description: 'Set time', params: [{ name: 'hours', type: 'number' }, { name: 'minutes', type: 'number' }, { name: 'seconds', type: 'number' }] },
      { name: 'setDate', description: 'Set date', params: [{ name: 'day', type: 'number' }, { name: 'month', type: 'number' }, { name: 'year', type: 'number' }] },
      { name: 'getUnix', description: 'Get unix timestamp', params: [] },
      { name: 'fromUnix', description: 'Set from unix timestamp', params: [{ name: 'timestamp', type: 'number' }] },
      { name: 'getDayName', description: 'Get day name', params: [] },
      { name: 'getMonthName', description: 'Get month name', params: [] },
      { name: 'getBattery', description: 'Get backup battery level', params: [] },
      { name: 'isExpired', description: 'Is battery expired?', params: [] },
      { name: 'formatAlarm', description: 'Format as alarm time', params: [{ name: 'hours', type: 'number' }, { name: 'minutes', type: 'number' }] },
    ],
    events: ['alarm', 'batteryLow'],
  },
};
