
import { vi } from 'vitest';
import { CommandBlock, SpriteState, AppState, HardwareState } from '../../../types';

export const createMockSpriteState = (overrides: Partial<SpriteState> = {}): SpriteState => ({
  x: 100, y: 100, z: 0,
  rotation: 0,
  scaleX: 1, scaleY: 1,
  rotationX: 0, rotationY: 0, rotationZ: 0,
  emoji: '😊',
  texture: null,
  frames: [],
  animations: {},
  currentAnimation: null,
  animationSpeed: 1,
  speech: null,
  weather: 'none',
  score: 0,
  keys: 0,
  health: 100,
  maxHealth: 100,
  variables: {},
  is3D: false,
  cameraMode: 'top_down',
  powerups: {},
  vx: 0, vy: 0, vz: 0,
  opacity: 1,
  scale: 1,
  gravity: false,
  gravityForce: 0.5,
  jumpForce: 12,
  isJumping: false,
  canDoubleJump: false,
  canDash: true,
  dashCooldown: 0,
  projectiles: [],
  enemies: [],
  items: [],
  platforms: [],
  clones: [],
  cameraFollow: false,
  particles: [],
  floatingTexts: [],
  tilemap: [],
  objects3d: [],
  inventory: [],
  maxInventorySize: 20,
  dialogueHistory: [],
  isDialogueActive: false,
  musicVolume: 1,
  checkpoints: [],
  isCutsceneActive: false,
  screenShake: 0,
  screenFreeze: 0,
  timeScale: 1,
  fadeAlpha: 1,
  bossHealth: 0,
  bossMaxHealth: 0,
  bossPhase: 0,
  ...overrides,
});

// @ts-expect-error HandlerContext not yet exported from types
export const createMockContext = (overrides: Partial<HandlerContext> = {}): HandlerContext => ({
  cmd: { id: '1', type: 'WAIT' as any, params: {} },
  mode: 'GAME',
  spriteStateRef: { current: createMockSpriteState() } as any,
  appStateRef: { current: { title: '', backgroundColor: '#fff', activeScreen: 'main', screens: {}, score: 0, variables: {} } } as any,
  hardwareStateRef: { current: { pins: [], buzzerActive: false, fanSpeed: 0, temperature: 0, servoAngle: 0, lcdLines: [], cursorRow: 0, cursorCol: 0, potentiometerValue: 0, speakerVolume: 0, rgbColor: '#000000', sevenSegmentValue: null, distance: 0, motionDetected: false, vibrationActive: false, keypadValue: null, joystick: { x: 0, y: 0 } } } as any,
  setNpcChat: vi.fn(),
  playSound: vi.fn(),
  setConsoleLogs: vi.fn(),
  stopExecution: { current: false },
  wait: vi.fn().mockResolvedValue(undefined),
  appState: { title: '', backgroundColor: '#fff', activeScreen: 'main', screens: {}, score: 0, variables: {} },
  setAppState: vi.fn(),
  setSpriteState: vi.fn(),
  setHardwareState: vi.fn(),
  hardwareState: { pins: [], buzzerActive: false, fanSpeed: 0, temperature: 0, servoAngle: 0, lcdLines: [], cursorRow: 0, cursorCol: 0, potentiometerValue: 0, speakerVolume: 0, rgbColor: '#000000', sevenSegmentValue: null, distance: 0, motionDetected: false, vibrationActive: false, keypadValue: null, joystick: { x: 0, y: 0 } },
  isPlaying: true,
  isBoardConnected: false,
  showConsole: false,
  setShowConsole: vi.fn(),
  plugins: {},
  addPlugin: vi.fn(),
  renderingScreen: { current: '' },
  particleSettings: {},
  circuitComponents: [],
  setGameState: vi.fn(),
  addAppElement: vi.fn(),
  eventBus: { on: vi.fn(), off: vi.fn(), emit: vi.fn() },
  ...overrides,
});
